### ISSUE TITLE
hello world example doesn't seek to work?

### ISSUE THREAD

**Issue by Insomnia88** [ratchetphp/Ratchet#1007]
I am new to this project and started with the hello world example in the docs. I followed every step but when I try to run the server (php bin/server.php) there is no response and no connection seems to established. I checked everything multiple times.

Has anyone a solution for this?

**Comment by hayden-t** [comment]
are you running on localhost or remote server ?

**Comment by Insomnia88** [comment]
I recently solved the problem. There were 2 factors causing this "error". 
1) I had to put an echo inside inside the Chat.php class construct in order to show something after the server started.
2) My IDE seems to use the same ports as shown in the example which blocked the connection via js. When I closed my IDE it worked as intended.

**Comment by hayden-t** [comment]
great, maybe close issue ?
