### ISSUE TITLE
Multiple Thread

### ISSUE THREAD

**Issue by abrahamb** [ratchetphp/Ratchet#101]
Hi, if I implement pthreads on my php project then it would be possible to have a multithreaded server socket. 
What do you think about this idea?

I need a multithread process because when I receive a message from the WebSocket client then I make at least 3 http requests, so the whole process stops and not new connections could be accepted until the request of the client has been completed.

Is there any way to solve this problem without use multithreading?

Thanks

**Comment by pthreat** [comment]
If a client performs a blocking socket operation such as reading a rather large data set from a database, all other connected clients will be blocked waiting until said process has finished.

Why was this closed?

**Comment by mbonneau** [comment]
@pthreat The concepts relating to blocking i/o and integrating them into react projects is not unique to Ratchet. There is some discussion of this here: https://github.com/reactphp/react/wiki/FAQ#how-can-i-use-blocking-functions

If you are looking specifically for non-blocking database access, there are a few databases that have non-blocking react support:
https://github.com/friends-of-reactphp/mysql
https://github.com/clue/reactphp-sqlite
https://github.com/voryx/PgAsync

**Comment by pthreat** [comment]
I'm looking specifically for a way to fork or do whatever is needed to have separate non blocking processes so there are no wait delays for the rest of my connected clients, for example, streaming a large file to a connected client. If you could guide me on how to handle forking correctly I will appreciate it! Thanks for the previous links.

**Comment by mbonneau** [comment]
Check out https://github.com/reactphp/child-process

Article:
https://clue.engineering/2019/introducing-reactphp-child-process
