### ISSUE TITLE
socket URL changed?

### ISSUE THREAD

**Issue by carliedu** [ratchetphp/Ratchet#1015]
All links here are pointing to socket.me but apparently the correct is socket.io.

**Comment by SimonFrings** [comment]
Thanks for reporting this @carliedu :+1:

Important to note here is that the name of the site is actually `socketo.me` and not `socket.me` (but I can totally understand the confusion ^^).  You're right that a website with the name `socket.io` exists and works, but it isn't related to Ratchet.

I opened up a new ticket in the https://github.com/ratchetphp/socketo.me (the website repository) so we have a record of this issue in the right place. I'll go ahead and close this ticket.
