### ISSUE TITLE
What is the benefit of having the X-Powered-By header?

### ISSUE THREAD

**Issue by quakemmo** [ratchetphp/Ratchet#1021]
Users has been asking for an option to remove this for literally years, with nothing but condescendence from the maintainers in return.

What is the exact use of this header? If you are the server owner, you already know the version of the software you are running, and if you're not the server owner, why would anyone legit want to know it?

I can see why an attacker would like to know it in order to maybe find an attack surface, but other than that, what is the point?

I can't convince myself it is intentionally left in Ratchet to benefit the attackers.

Honest question!

Thanks for any hints.

**Comment by quakemmo** [comment]
And yes, it is trivial to strip on the proxy / WAF and that's exactly what I do and what everyone should be doing. I'm just wondering why are the maintainers intentionally leaving a headache for the users.

**Comment by SimonFrings** [comment]
@quakemmo We're aware of this, one of the reasons why @clue opened a ticket a while ago in order to discuss this and find the right solution : #999

We're happy about constructive input :+1:
