### ISSUE TITLE
Creation of dynamic property React\Socket\Connection::$decor is deprecated

### ISSUE THREAD

**Issue by imranertaza** [ratchetphp/Ratchet#1032]
Hi
I have found this error when I set my server to php 8.1

"Creation of dynamic property React\Socket\Connection::$decor is deprecated Creation of dynamic property React\Socket\Connection::$decor is deprecated"

**Comment by SimonFrings** [comment]
@imranertaza This is already being discussed in #988, #1002, #1003 and others, so I'll close this as a duplicate.
