### ISSUE TITLE
Deprecated: Creation of dynamic property Ratchet\Server\IoConnection::$WebSocket is deprecated

### ISSUE THREAD

**Issue by wilianmaique** [ratchetphp/Ratchet#1033]
Deprecated: Creation of dynamic property Ratchet\Server\IoConnection::$WebSocket is deprecated in vendor\cboden\ratchet\src\Ratchet\WebSocket\WsServer.php on line 114

PHP 8.2
"cboden/ratchet": "^0.4.4"

-> https://prnt.sc/kchjnHJal6FO

**Comment by SimonFrings** [comment]
Hey @wilianmaique, this is already being discussed in #988, #1002, #1003 and others, so I'll close this as a duplicate.
