### ISSUE TITLE
Support symfony/http-foundation ^v7

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [ratchetphp/Ratchet#1067]
I'm trying to install Ratchet on Laravel 11. According to the Laravel dependency graph `symfony/http-foundation@^7.0` is required and fixed.
So, if we can support `v7`, we can install Ratchet on Laravel 11.

**Comment by clue** [comment]
Closing as duplicate of #1045. Please take the time to review open tickets before posting any new tickets and consider supporting this project by becoming a sponsor (#1054) ❤️

**Comment by ebootingdev** [comment]
Please i need the version for Symfony 7 D:
