### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by yktd26** [ratchetphp/Ratchet#125]
Is it possible to be the server of WebRTC clients?

**Comment by abrahamjsb** [comment]
You could solve the problem? Is it ratchet capable to stablish a WebRTC connection?

**Comment by lsanczyk** [comment]
> 
> 
> You could solve the problem? Is it ratchet capable to stablish a WebRTC connection?

Seems [this article](https://medium.com/@amirsanni/building-a-text-audio-and-video-chat-web-app-using-webrtc-and-ratchet-45863446e79a) explains how to do it.
