### ISSUE TITLE
ws to wss

### ISSUE THREAD

**Issue by t3chn0r** [ratchetphp/Ratchet#161]
I need some help as I've been trying to do this for the last couple of days without luck. I recently switched my application to https, everything is working fine except for websockets. If I still try to connect to my server using the address ws://ws.myserver.com:8888/ I get the following error now:

```
SecurityError: The operation is insecure.
```

I guess this error makes sense as I'm trying to establish an unsecured connection from a secured site. So, I changed the connection string to wss://ws.myserver.com:8888/, and I know Ratchet doesn't support SSL as it will be too slow for PHP to handle. 

Because I'm using Nginx I'm trying to do some kind of redirect from wss to ws to no avail. My Ratchet server is running in port 8888, I went ahead and changed the connection string to wss://ws.myserver.com:18888/ and then put these lines (based on documentation I found) in nginx but it still doesn't work...

```
server {
    listen 18888;
    server_name *.myserver.com;

    ssl on;
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    ssl_session_timeout 5m;
    ssl_protocols SSLv2 SSLv3 TLSv1;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://192.168.1.100:8888;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }
}
```

Now, I get the following error, I guess something is still not quite right but at this point I'm lost...

```
Firefox can't establish a connection to the server at wss://ws.myserver.com:18888/.
```

Any ideas what I'm missing?

Appreciate any help...

**Comment by makhulhet** [comment]
Hi t3chn0r!

Recently, I started using ratchet for my project using web socket. And now I am trying to use wss: for secured connection. My question is, how did you  managed to use stunnel for ratchet. I saw your comment last Jan 24, 2014 that you ended up using stunnel. Did it worked? How? Can you help me out? 

Thanks!

**Comment by bobvandevijver** [comment]
@makhulhet I also use the secure websockets with stunnel, which is easy to setup. I just run stunnel and specify the config location als argument, which has the following content:

```
sslVersion = all
foreground = no
debug = 1
; Disable support for insecure SSLv2 protocol
options = NO_SSLv2
[websockets]
accept  = 8080
connect = 8081
TIMEOUTclose = 0
cert = /etc/apache2/ssl/mycert.cert
key = /etc/apache2/ssl/mykey.key
```

That's all! Notice that I run the websocket server on port 8081 on the local machine, and that stunnel enables clients to connect to port 8080 with the wss protocol.

**Comment by t3chn0r** [comment]
Hi @makhulhet, using pretty much same values as @bobvandevijver:

```
key = /etc/nginx/ssl/domain.com.key
cert =  /etc/nginx/ssl/domain.com.unified.crt
CApath = /etc/ssl/certs

socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

setuid = stunnel4
setgid = stunnel4
pid = /var/run/stunnel4/websocket.pid

debug = 6
output = /var/log/stunnel4/websocket.log

[websocket]
accept = 4443
connect = domain.com:8888
```

Just replace domain.com with your domain.

Regards

**Comment by makhulhet** [comment]
@bobvandevijver, thanks dude... I'll try that config... by the way... i forgot to mention that I am currently running under apache web server.. will it work? 

@t3chn0r, I already used that configuration and it seems it doesn't work on mine.. maybe there's something else you did.. :D

**Comment by makhulhet** [comment]
Hi @bobvandevijver, i tried the your configuration... but how am I going to run my server it seems they'll be having port conflict... 

`
PHP Fatal error:  Uncaught exception 'React\Socket\ConnectionException' with message 'Could not bind to tcp://0.0.0.0:8080: Address already in use' in ../vendor/react/socket/src/Server.php:29
Stack trace:
#0 ../bin/push-server.php(22): React\Socket\Server->listen(8080, '0.0.0.0')
#1 {main} thrown in ../vendor/react/socket/src/Server.php on line 29
`

**Comment by t3chn0r** [comment]
Ho @makhulhet, I just double checked my server and remembered that I ended up using haproxy instead as I was already using it and decided to not run and maintain the stunnel service when haproxy could also take care of that... 

If you need the haproxy setup that I'm using just let me know.

**Comment by makhulhet** [comment]
Hi @t3chn0r, if im going to use haproxy instead of stunnel. Will it work with apache web server?

**Comment by bobvandevijver** [comment]
@makhulhet Just change the port used in you websocket script to 8081, or interchange the ports in the stunnel config. 

I use Apache, works perfect.

**Comment by makhulhet** [comment]
Awesome! It worked! 

I just need to create separate vhost for my webserver and add some ssl configuration to my vhost. 

Thanks!

**Comment by kergdgreat** [comment]
@bobvandevijver i used your code but its not working.
sslVersion = all
foreground = no
debug = 1
; Disable support for insecure SSLv2 protocol
options = NO_SSLv2
[websockets]
accept  = 8080
connect = 8081
TIMEOUTclose = 0
cert = /etc/apache2/ssl/mycert.cert
key = /etc/apache2/ssl/mykey.key

 i got apache 2.2 version in my server.
