### ISSUE TITLE
nginx and HAProxy

### ISSUE THREAD

**Issue by speix** [ratchetphp/Ratchet#170]
I have just started implementing Ratchet library on one of my projects.
I am using nginx as rev proxy on my server and reading through the deployment articles it is recommended to use HAProxy.

Is nginx unable to work with Ratchet ?

**Comment by galihsan3** [comment]
> 
> 
> When I switched from ws:// to wss:// I tried to use Nginx to perform the SSL handling and it was impossible, I had to use stunnel or HAProxy and ended up deciding for HAProxy...

hellow friend I need haproxy config to switch ws to wss, I hope you can help me
