### ISSUE TITLE
how too access $loop inside of a app

### ISSUE THREAD

**Issue by alanquigley** [ratchetphp/Ratchet#171]
I'd like to use ratchet for a app, I need to trigger events that will be broadcast to all clients at intervals, my first though is to use $loop->periodicTimer() object. Looking at the Chat() app example:  a) is this a valid approach and b) how best would you reference $loop inside the Chat() app. Thanks

**Comment by MarcGodard** [comment]
Do I need to add React to composer to use this?

Ratchet doesn't have an eventloop?

**Comment by webdev2018** [comment]
I tried with addPeriodicTimer() with this code:
[        $dataPacket = array(
            'type' => 'ping',
            'data' => array(
                'roomId' => $roomId,
                'from' => 'System',
                'message' => 'You are pinged.'
            )
        );


        $clients = $this->getAllClients();

        $loop = Factory::create();
        $loop->addPeriodicTimer(5, function () use ($clients, $dataPacket){
            echo 'periodic timer ';
            $this->sendDataToClients($clients, $dataPacket);
        });

        $loop->run();](url)

sendDataToClients() is:
```
 public function sendDataToClients($clients, $message)
    {
        foreach ($clients as $client) {
            $this->sendData($client, $message);
        }
    }

```
sendData() is:
[   protected function sendData(ConnectedClientInterface $conn, $data)
    {
        $conn->getConnection()->send(json_encode($data));
    }
]

But sending message to all clients doesn't work. Please help..
