### ISSUE TITLE
Binary support

### ISSUE THREAD

**Issue by cboden** [ratchetphp/Ratchet#18]
Part of #13 is including binary message support for the WS protocol. 

I'm thinking this will expand on the WebSocketComponent interface addax an _onFile_ method. Try to further incorporate SF2 HttpFoundation by passing a _File_ object to the method.

**Comment by nazar-pc** [comment]
@vincentdieltiens, are you going to send PR for this feature?
I need to receive binary messages as well, so what it implementation state right now?

**Comment by dizard** [comment]
https://github.com/dizard/Ratchet added binary support

**Comment by khalilst** [comment]
@dizard I've a problem in installing your package via composer in my Laravel application. 
`composer require dizard/ratchet`
But it's not working. Composer shows this error message:

> Could not find package dizard/ratchet at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

I'm totally confused!
What was wrong with this package?

**Comment by dizard** [comment]
You are need add to composer.json
"repositories": [
        {
            "type":"git",
            "url":"https://github.com/dizard/Ratchet"
        }
]

**Comment by khalilst** [comment]
@dizard thank you for your help. I think, I need more to learn about composer.

**Comment by mengnalin90** [comment]
@dizard 
Hi I am confused why it is like this when I run composer require dizard/ratchet. 
Thanks!
  Problem 1
    - Installation request for dizard/ratchet ^0.3.3 -> satisfiable by dizard/ratchet[v0.3.3].
    - Conclusion: remove symfony/http-foundation v3.2.8
    - Conclusion: don't install symfony/http-foundation v3.2.8

**Comment by ryancwalsh** [comment]
Does Ratchet definitely support sending binary data? IBM Watson Speech-to-text requires it: https://console.bluemix.net/docs/services/speech-to-text/websockets.html#WSaudio

> The client must send the audio as binary data. The client can stream a maximum of 100 MB of audio data with a single utterance (per send request). It must send at least 100 bytes of audio for any request. The client can send multiple utterances over a single WebSocket connection.
> 
> The WebSocket interface imposes a maximum frame size of 4 MB. The client can set the maximum frame size to less than 4 MB. If it is not practical to set the frame size, the client can set the maximum message size to less than 4 MB and send the audio data as a sequence of messages.

Looking at http://socketo.me/docs/hello-world and other docs, I've been unclear on how to use Ratchet to do something super basic like this (but with support for binary): https://github.com/Textalk/websocket-php/blob/master/examples/send.php

**Comment by ryancwalsh** [comment]
I found https://github.com/ratchetphp/Ratchet/issues/393#issuecomment-329532173 and https://github.com/ratchetphp/Ratchet/issues/627#issue-304813937 and am just as confused as @SilverDeath32.

I'm wondering how to put an audio file into:

```
$binaryMsg = new \Ratchet\RFC6455\Messaging\Message();
$conn->send($binaryMsg);
```

I will ask on his issue. Thanks for this library, which looks promising.

**Comment by programarivm** [comment]
Hi there, 

This one is working for me.

https://github.com/chesslablab/chess-server/blob/main/src/Socket/Ratchet/BinaryWebSocket.php

I hope it helps.
