### ISSUE TITLE
Hixie76 disabled by default

### ISSUE THREAD

**Issue by cboden** [ratchetphp/Ratchet#201]
RFC6455 is now widely supported, no need to enable Hixie unless absolutely required

**Comment by cboden** [comment]
Now strongly considering only supporting RFC6455...comments welcome.

**Comment by danijeld** [comment]
I think you should keep all the old Version implementations and mark them deprecated. Worst case, remove them, they are marked obsolete but at least keep the VersionManager, VersionInterface classes for future when RFC6455 gets updated or superseded by another spec. For now, default to RFC6455. I know this may be a long way down the road but you never know. It just seems like it would be a shame to throw out the "versioning" code.
