### ISSUE TITLE
No access to Cookies or Session using Nginx

### ISSUE THREAD

**Issue by Raxvis** [ratchetphp/Ratchet#204]
I am using Ratchet behind Nginx (a simple chat application) and for some reason, I can not get sessions or cookies.  Right now, I don't have a domain so I have been using the IP and it works with other PHP scripts, but not Ratchet.

Is there something I have to do differently to get access to $_COOKIE or $_SESSION variables?

Here is my websocket nginx config to help 

```
    map $http_upgrade $connection_upgrade {
            default                                 upgrade;
            ''                                      close;
    }

    upstream websocket {
        server 127.0.0.1:8080;
    }

    server{
            ...
            location /ws/ {
                    proxy_pass                      http://websocket;
                    proxy_http_version              1.1;
                    proxy_set_header                Upgrade $http_upgrade;
                    proxy_set_header                Connection "Upgrade";
                    proxy_read_timeout              999999999;
            }
    }
```

**Comment by acidjazz** [comment]
Is there a way to get these cookies decoded? I have to manually rawurldecode() each one

**Comment by cboden** [comment]
I haven't seen that before. Perhaps your sync stack or client library is encoding them?

**Comment by acidjazz** [comment]
I don't think so, I'm just using getCookies which I believe is guzzle? they come w/ % codes unless I do something in onOpen or onMessage like

```php

      foreach ($conn->WebSocket->request->getCookies() as $key=>$value) {
        $_COOKIE[$key] = rawurldecode($value);
      }

```

**Comment by cboden** [comment]
Yeah, maybe try the guzzle mailing list? My apologies, I've never seen that before. Ratchet uses Guzzle to parse the raw HTTP headers and it turns that into the Guzzle objects used in the source code seen in this issue, so I'm not too familiar with the inner workings of it or why you would need to decode the cookie value...
