### ISSUE TITLE
Use php multi-threading in a web socket server

### ISSUE THREAD

**Issue by NightFox7** [ratchetphp/Ratchet#214]
Is it possible to make asynchronous calls from within the web socket server by using php multi-threading or any other way that you suggest?
The reason why I need asynchronous calls is that my web socket servers is blocked for several minutes while waiting for a response from a web service. 
This is of course unacceptable as it completely make the server inaccessible for the other clients.

**Comment by huyanping** [comment]
I have wrote a package which can add multi-process support to react\event-loop, and it is really simple.
src:https://github.com/huyanping/react-multi-process

**Comment by andreybolonin** [comment]
https://github.com/andreybolonin/RatchetMultiInstance

**Comment by mbonneau** [comment]
Closed due to inactivity.

**Comment by asim709** [comment]
> Is it possible to make asynchronous calls from within the web socket server by using php multi-threading or any other way that you suggest?
> The reason why I need asynchronous calls is that my web socket servers is blocked for several minutes while waiting for a response from a web service.
> This is of course unacceptable as it completely make the server inaccessible for the other clients.

Check out this project: https://github.com/asim709/php-multithreaded-websocket-and-json-rest-server

It might be the solution in your case as it is fully non-blocking. Each websocket message is spawned to a new thread while keeping the communication thread alive to receive and serve more requests.
