### ISSUE TITLE
Firefox Can't Connect to Server

### ISSUE THREAD

**Issue by ybanwait** [ratchetphp/Ratchet#219]
Hi Chris,
I have been trying to make ratchet work on a live website. The web socket server runs ok but the client can't connect to the server on chrome or firefox. Even through telnet no message is sent to other window. I will greatly appreciate your help, sir.

**Comment by webappmaster** [comment]
Hello @ybanwait, I am having the same issue. Please let me know what was that security setting?

**Comment by mikealmond** [comment]
@webappmaster Do you have your own app, or are you using the bootstraped `Ratchet\App`? If you have your own, you need to make sure you wrap it with the proper component layers to get web sockets to work.

```php
$server = IoServer::factory(
        new HttpServer(
            new WsServer(
                new Chat()
            )
        ),
        8080, '0.0.0.0'
    );
```

**Comment by webappmaster** [comment]
Hello Mike, I already implemented above code. Thank you for your prompt reply.
