### ISSUE TITLE
Event class

### ISSUE THREAD

**Issue by valeryq** [ratchetphp/Ratchet#223]
Hello. I have some error:
PHP Fatal error:  Undefined class constant 'READ' in /www/HOST/vendor/react/event-loop/ExtEventLoop.php on line 50
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Undefined class constant 'READ'","file":"\/www\/HOST\/vendor\/react\/event-loop\/ExtEventLoop.php","line":50}}
I use Laravel framework. What I should to do to fix problem?
Thank you :)

**Comment by Vinceveve** [comment]
in app/config/app.php, aliases, change this : 
`'Event' => 'Illuminate\Support\Facades\Event',`
To that
`'EventFacade' => 'Illuminate\Support\Facades\Event',`
