### ISSUE TITLE
Perf gain in masking

### ISSUE THREAD

**Issue by cboden** [ratchetphp/Ratchet#226]
From @rdlowrey via IRC:

Using str_pad instead of looping over the payload to mask/de-mask should yield a performance gain:

``` php
$payload = $payload ^ str_pad('', $length, $mask, STR_PAD_RIGHT);
```

**Comment by Xaraknid** [comment]
You should try str_repeat I made some benchmark spec with various method and it's happen to be the fastest. The samplesize I use is 1000000.

$effectiveMask = str_repeat($this->mask , ($samplesize/4)+1 );
$over=$samplesize-strlen($effectiveMask);
$effectiveMask=substr($effectiveMask,0,$samplesize);
