### ISSUE TITLE
Hello World! tutorial can't find class MyApp/Chat

### ISSUE THREAD

**Issue by Lugia101101** [ratchetphp/Ratchet#243]
Heyo,
I have followed every step of the Hello World! tutorial, but can't get past Instantiation. I run it through the command prompt and the following error appears:

> php bin\chat-server.php
> Fatal error: Class 'MyApp\Chat' not found in C:\path\to\install\beta\bin\chat-server.php on line 8

File tree and composer.json can be found here: http://pastebin.com/xEDwVBg0
Just wondering if I missed something or interpreted something wrong. Thank you~

**Comment by zqhong** [comment]
Thansk a lot. I have the same problem. When I execute "php composer.phar update", I fixed it.


My folder tree:
➜  ws  tree -L 3
.
├── bin
│   └── chat-server.php
├── composer.json
├── composer.lock
├── composer.phar
├── MyApp.php
├── src
│   └── MyApp
│       └── Chat.php
└── vendor
    ├── autoload.php
    ├── cboden
    │   └── ratchet
    ├── composer
    │   ├── autoload_classmap.php
    │   ├── autoload_namespaces.php
    │   ├── autoload_psr4.php
    │   ├── autoload_real.php
    │   ├── ClassLoader.php
    │   └── installed.json
    ├── evenement
    │   └── evenement
    ├── guzzle
    │   ├── common
    │   ├── http
    │   ├── parser
    │   └── stream
    ├── react
    │   ├── event-loop
    │   ├── socket
    │   └── stream
    └── symfony
        ├── event-dispatcher
        ├── http-foundation
        └── routing

22 directories, 13 files
