### ISSUE TITLE
Problem managing libraries with composer.json

### ISSUE THREAD

**Issue by kdzekov** [ratchetphp/Ratchet#260]
Hello,

I started to learn and use Ratchet recently and I have some issue in managing some libraries with composer.json. So, i started a project and installed composer. The content looks like this:
```json
{
    "autoload": 
     {
        "psr-0": 
        {
            "MyApp": "src"
        }
    },
    "require": {
        "cboden/ratchet": "0.3.*",
        "react/zmq": "0.2.*|0.3.*"
    }
}
```
It seems that the ratchet libraries are well managed since i have no problem to include them in my php scripts (ex. use Ratchet\Server\IoServer, etc) but for the rest of the libraries i have a problem.

For the first case, when i try to include my application in a php script with:
use MyApp\TheClassName 

it  throws an error: "Class 'MyApp\PDG' not found in /srv/www/htdocs/pdg_realtime/bin/PDG_server.php on line 13"

 so i have to add: 

require dirname(__DIR__) . '/src/MyApp/PDG.php'; 
on the top of the document in order to work properly.

As for the second case, I have installed ZeroMQ. I have put the zmq library in vendor/react folder, unpacked it and installed it from there. The folder name is zmq as it is initialized on the composer.json file. However when i try to include a library from zmq like:

use React\ZMQ\Context; (the pusher example on the Ratchet portal )

it gives:

PHP Fatal error:  Class 'React\ZMQ\Context' not found in /srv/www/htdocs/pdg_realtime/bin/PDG_server.php on line 16

on the line 16 i have: "$context = new React\zmq\Context($loop);"

it seems that composer.jason library does not manage zmq libraries well.

Any suggestions about these issues?

P.S The second case is much more important to me at the moment.

**Comment by kdzekov** [comment]
I realized the problem. Instead of localhost it should stay 127.0.0.1

**Comment by kdzekov** [comment]
So , the ZeroMQ connection works now but another problem appeared. When i try to connect to the server via regular socket connection the server breaks down with the following error:

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message '$request can not be null' in /srv/www/htdocs/pdg_realtime/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php:76
Stack trace:
#0 /srv/www/htdocs/pdg_realtime/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(99): Ratchet\WebSocket\WsServer->onOpen(Object(Ratchet\Server\IoConnection))
#1 [internal function]: Ratchet\Server\IoServer->handleConnect(Object(React\Socket\Connection))


The server script is:

require dirname(__DIR__) . '/vendor/autoload.php';  

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Chat;

use React\EventLoop\Factory;
use React\Socket\Server as Reactor;
use React\ZMQ\Context;

$loop   = React\EventLoop\Factory::create();
$chat   = new Chat();

$context    = new React\ZMQ\Context($loop);
$pull       = $context->getSocket(ZMQ::SOCKET_PULL);
$pull->bind('tcp://127.0.0.1:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself
$pull->on('message', array($chat, 'ZMQHandle'));

$sock = new React\Socket\Server($loop);
$sock->listen(8080, '127.0.0.1');

$webServer  = new Ratchet\Server\IoServer(
        new Ratchet\WebSocket\WsServer(
                new Ratchet\Wamp\WampServer(
                        $chat
                        )
                ),
                $sock
        );
$loop->run();

In a situation in which ZeroMQ messaging is enabled the regular socket connection breaks down the server. 

How can I enable in parallel WebSocket and ZeroMQ communication?

**Comment by cboden** [comment]
You forgot to put a `HttpServer` between the `IoServer` and `WsServer`.

**Comment by kdzekov** [comment]
Ok, i put HttpServer instantiation and it works until i try to send message. When I send message through a socket connection the client that sends the message is disconnected automatically.

When I get back to:

$server = IoServer::factory(
        new HttpServer(
            new WsServer(
                new Chat()
            )
        ),
        8080        
    );
$server->run();

it works normally but without ZeroMQ messaging.

**Comment by kdzekov** [comment]
Ok, Chris.
I found what was the problem. I just commented instantiation of WampServer and now works perfectly well. Thank you very much for your help and patience!

I think i have my bases for the real-time application i'm planning to built.
