### ISSUE TITLE
Ping and keepAlive in Ratchet

### ISSUE THREAD

**Issue by SaphirAngel** [ratchetphp/Ratchet#263]
For those who want to ping or be sure that a client is present (internet lost, mobile network). We have implemented the following functions:
Ping and keepAlive
The only requirement is to have an instance of the loop event.
The commit is here :  6da3b04e2d
Repo : https://github.com/bjtpartners/Ratchet/tree/ping-dev

There are no problem found at this time for  and it's very reactive. 
I will not make pull request because i use the Promise and Event Loop in Ratchet directly but i share the solution :).

If you are opinions or remarks, you're welcome :).

Just a quick question : Is there a way to get the loop event from the instance of a connection ? I have not found but you never know.

Bye :)

**Comment by filipecoelho** [comment]
Hello everyone, I'm having connection problems that get active and this ping / pong solution would help a lot.
I tried to download version 0.4 but it seems that it is still not stable.
Any forecast for official release?

**Comment by cboden** [comment]
> it is still not stable

Have you experienced a bug in the 0.4 branch?

**Comment by filipecoelho** [comment]
pessoal, resolvi aqui e consegui usar a versão 0.4.
porém, estou tendo problemas com o memory_limit do PHP.
