### ISSUE TITLE
This is not your Grandfather's Internet. 

### ISSUE THREAD

**Issue by codeyash** [ratchetphp/Ratchet#270]
Not like issue but may not feel good about this line 

Instead you say

Grandfather will love this (new/magnificent / black/voodo ) magic or may be other positive line which actually convey your meaning. that's its new age technology.

Again you can close if you don't agree.

**Comment by codeyash** [comment]
And I'm young so I have no problem :)

**Comment by cboden** [comment]
The headline is meant to be tongue-in-cheek. No complains yet ;)
