### ISSUE TITLE
HAProxy with memcache

### ISSUE THREAD

**Issue by PgPedroGabriel** [ratchetphp/Ratchet#271]
I have a HAProxy...

This " route " my application to use same port (CBoden recommendation in documentation)

I have a WebServer (apache) that saves a object in Sesssion (symfony, memcache)

When i access my WebSocketServer in html like this :

var conn = new WebSocket("ws://localhost:5000");

i can access my object saved in webServer through $conn->Session, its Ok!

in my HAProxy has a condition if is_websocket go to localhost:5000...

if i access my WebSocketServer in html like this:

var conn = new WebSocket("ws://localhost");

i can get session also;

but if i created a subdomain eg: ws.localhost

i access my websocketserver but i cant access my Session...

I see the package network, when i access through of a subdomain the HAproxy dont send Cookie to my WebServerSocket...

Why this occurs?
is there anything I need to put in HAproxy config, what??
Is possible subdomain share cookies in ratchet?
Has any alternative to i do this?

**Comment by cboden** [comment]
Closing this issue, the same question was asked and answered on the mailing list.
