### ISSUE TITLE
Reliable way to get total number of open connections?

### ISSUE THREAD

**Issue by Brade** [ratchetphp/Ratchet#273]
Right now it seems the way to get the total number of open connections is to keep track of them in our own object array, and trust that the attach/detach methods in onOpen and onClose are firing correctly. Is that right Or is there a more reliable count somewhere that doesn't rely on us keeping track of it ourselves?

**Comment by cboden** [comment]
Counting via `onOpen` and `onClose` is the best way. Those underlying events are how lower levels keep their own count as well. Keeping your own count also has the advantage of keeping the number open at your application level. 

For example a component between `IoServer` and `WsServer` might keep its own count and that could be different than your count; a socket connection could be established but not upgraded yet so the "connected" counts would vary.

**Comment by Brade** [comment]
Gotcha, thanks
