### ISSUE TITLE
Logging via supervisord randomly stops

### ISSUE THREAD

**Issue by Brade** [ratchetphp/Ratchet#274]
I know this might be more of a supervisord issue than Ratchet, but I've set up supervisord as described in the deployment section, and it logs the output from my app (in info.log) fine for a while. But at some point it randomly stops logging, even though the app continues to run as expected. I think it's the same issue with output buffering described here: http://stackoverflow.com/questions/13934801/supervisord-logs-dont-show-my-ouput

But how do I correct this w/ PHP? I've tried ob_flush() and flush() everywhere that I'm echoing. But that hasn't worked. Any ideas?

**Comment by Brade** [comment]
Now using the syslog method from supervisord instead, and things appear to be going better. Will go ahead and close this.

**Comment by cboden** [comment]
:+1:
