### ISSUE TITLE
Missing documentation on Hello World

### ISSUE THREAD

**Issue by Gn13l** [ratchetphp/Ratchet#276]
I'm just getting started in trying Ratchet for the first time.  On the page: http://socketo.me/docs/install  part of the instructions are:
"Once you have composer.phar on your system (for this documentation, we're going to assume it's in your home directory) create a file called composer.json in your project folder. Inside that file copy and paste the JSON from the top of this page."

As far as I can tell there is no JSON at the top of the page to copy and paste.

**Comment by cboden** [comment]
Check out my comment on #272 for the solution. I'll correct the documentation this weekend. Sorry for the inconvenience.

**Comment by Gn13l** [comment]
Thank you for the speedy response.

**Comment by Gn13l** [comment]
Also, I had to run `php composer.phar update` before I could run `php bin/chat-server.php`.

I found this solution on Issue #243.
