### ISSUE TITLE
Less dependencies

### ISSUE THREAD

**Issue by nazar-pc** [ratchetphp/Ratchet#277]
I see in dependencies `Symfony/*` and `guzzle/http` (they are 66% of Pawl dependencies).
Especially Symfony dependencies with all tests and docs are far from lightweight.
> I'm not using Symfony components, not using sessions or routing provided by Ratchet, but I do use Pawl (usage is the same as example in repo).
Any suggestions what can I safely remove without loosing everything else?

In fact it would be great to move sessions and routing into separate component for those who do not need them.

P.S. I know, there are people who just run `composer install` and do not care about what is inside, but I do care, and want to have the smallest possible set of dependencies.

**Comment by cboden** [comment]
I'm currently working on separating out the RFC6455 parts into its own repo. This repo will only depend on Guzzle\Http to do the HTTP parsing. I don't foresee this dependency requirement changing. When I first started Ratchet I looked into HTTP parsing; it's not easy and Guzzle does a great job of it. 

Once the RFC6455 repo has been refactored Pawl will rely on that and no longer have a dependency on Ratchet itself, which means Pawl will no longer pull in either Symfony library. 

After that refactor is done I plan on re-visiting the Session component. Its API will change and it will be moved to its own repository as it is not a requirement, but a feature add-on. In addition to moving it to its own repo part of the design change is not to tie it to Symfony Sessions but have adapters for multiple frameworks (including Symfony). This will remove the HttpFoundation from the main Ratchet repo. 

Finally, Symfony Routing will stay as a requirement in the main repository. URI path and query routing is specified in RFC6455. This was also a much requested feature for v0.3. While I understand you *can* create a server without needing routes, many people do require different endpoints and I do not want to ship regressing a feature defined in the specification.

**Comment by nazar-pc** [comment]
Thanks for quick response!
Do you use somewhere internally Symfony components except routing and session? I can bundle custom version into my app without them, just curious will it break something or not.
Here is how I use it: [server](https://github.com/nazar-pc/CleverStyle-CMS/blob/41d60aae9af6d57c0cae8df89b40ee450ea65a48/components/modules/WebSockets/Server.php#L81) and [Pawl](https://github.com/nazar-pc/CleverStyle-CMS/blob/41d60aae9af6d57c0cae8df89b40ee450ea65a48/components/modules/WebSockets/Server.php#L283)

**Comment by cboden** [comment]
Nope, that's it. `SessionProvider` uses `HttpFoundation` for the Session classes and `Router` uses `Router`. `App` uses the `Router`.

**Comment by nazar-pc** [comment]
Awesome, thanks!
