### ISSUE TITLE
Publish based on Access Control Lists

### ISSUE THREAD

**Issue by Rvanlaak** [ratchetphp/Ratchet#278]
We're using Symfony for the application specific logic, and will implement Ratchet for notification messages. `React/ZMQ` will be used to implement [server-push integration](http://socketo.me/docs/push), but I'd like to combine it with the [Symfony ACL](http://symfony.com/doc/current/cookbook/security/acl.html) without the client having to do an AJAX call whether or not it should eventually show the message.

I think it has something to do with the [SessionProvider](http://socketo.me/docs/sessions), but can't figure it out exactly. Where does my ACL logic has to come?

**Comment by cboden** [comment]
Unfortunately I have no experience with Symfony ACL so I'm unable to comment. 

I'm closing this issue as there hasn't been any activity in over 3 months. If you're still looking for a solution you could try posting your question on our [Mailing List](https://groups.google.com/forum/#!forum/ratchet-php)
