### ISSUE TITLE
Arraybuffer support?

### ISSUE THREAD

**Issue by pwnsdx** [ratchetphp/Ratchet#279]
Hi there,

I'm actually using ngWebsocket (Angular plugin) to establish an Websocket connection. I also use msgpack (binary-JSON) to encode/decode datas but it looks like I can't transfert anything to Ratchet: the connection is closed as soon as I send the encoded message.

Here is the js code I am using:
```javascript
                 // Instance of ngWebsocket, handled by $websocket service
                Adelaide.interfaces.Websocket.$transit = $websocket.$new({
                    url: 'ws://10.211.55.5/',
                    //lazy: true,
                    //enqueue: true,
                    reconnect: false,
                    reconnectInterval: 10000,
                });
                Adelaide.interfaces.Websocket.$transit.$on('$open', function() {
                    
                    // Use only ArrayBuffer data
                    Adelaide.interfaces.Websocket.$transit.$$ws.binaryType = 'arraybuffer';

                    console.log('websocket: open');
                    Adelaide.interfaces.Websocket.$transit.$emit('ping', 482938239); // send a message to the websocket server
                    Adelaide.interfaces.Websocket.$transit.$emit('ping', 4235241); // send a message to the websocket server
                });
                Adelaide.interfaces.Websocket.$transit.$on('$close', function () {
                    console.log('websocket: closed');
                });
```

This is what I get when I send the message:
![screen shot 2015-02-04 at 10 02 01](https://cloud.githubusercontent.com/assets/2057765/6037547/102ff060-ac55-11e4-956e-1ffd49f785e9.png)

Is Ratchet do not support ArrayBuffer yet or it is me?

Thanks for your help.

**Comment by cboden** [comment]
Not yet. The protocol handler had code to support it but the API does not. I'll be tackling this in a couple weeks. 

refs #18

**Comment by Marc-Tibout** [comment]
To support binary-only messages without any code source change, I did the following:
- To send binary messages: send a Frame instead of a string: 
    $conn->send(new Frame($msg, true, Frame::OP_BINARY));
- To prevent UTF-8 parsing errors on message arrival, I disabled validation:
    $wsServer->setEncodingChecks(false);

It seems to work quite well this way.
