### ISSUE TITLE
Multiple ratchet server instances behind HAProxy

### ISSUE THREAD

**Issue by drodil** [ratchetphp/Ratchet#280]
Hi,

I have multiple servers running both websocket service (on top of Ratchet) and also the actual website. Currently user connects to the same ratchet instance with the actual website (with HAProxy cookie set). Now I have a problem when two users are connected to different servers the websocket messages are only sent through the same ratchet instance as the user is connected to. 

Is there any way these ratchet servers can communicate with each other and publish the same messages on all nodes (ZeroMQ configuration perhaps?)? Or do I have to publish the same message to each and every instance individually?

Thanks for all the answers!

**Comment by cboden** [comment]
Sorry for the slow response @drodil 

You're guess is correct. One way to connect the two running WebSocket servers is via ZeroMQ. If a message is to be delivered over a WebSocket the script that is initiating it would also broadcast that via ZMQ to the other WebSocket servers who would then relay the message to the intended clients. 

A more advanced way of doing this is having a centralized message broker; but a similar concept.
