### ISSUE TITLE
can't use  $_SESSION global variable in the Pusher class.

### ISSUE THREAD

**Issue by islamdarwish** [ratchetphp/Ratchet#283]
i'm going to make a private chat so for example i have usr1 and usr2 to chat with each other.
In function onSubscribe() i set $subscribedTopics array key to be "usrid1,userid2" to broadcast to them any message sent to this topic.
So in the onSubscribe() function when user1 subscribes the array key will be set using userid2 concatenated to $_SESSION variable (which contains user1 id).
but problem is that $_SESSION variable is empty when i use it in the Pusher class.

there is other issue : i want to change the id of Topic object because if i set the topic as "usrid1,usrid2" in usr1 client script then this topic must set exactly the same and in the same order in the usr2 client script so it can't be "usrid2,userid1".

**Comment by cboden** [comment]
All global $_ variables can not be used in a Ratchet application. Those variables are typically filled via FCGI on a per-user bases but Ratchet applications house more than one user session; the scope of global variables is that of the application not of an individual user.
