### ISSUE TITLE
Composer dependencies problem

### ISSUE THREAD

**Issue by vyants** [ratchetphp/Ratchet#285]
Hello.

Composer showing errors on update:

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by cboden** [comment]
Ratchet uses Guzzle 3's HTTP Parser library to handle incoming WebSocket requests. Guzzle3 is now officially no longer maintained but the library still works. I will look in to upgrading and testing Guzzle 5's parser in the near future. In the mean time everything should still work, this is composer issuing a warning, not an error.

**Comment by karser** [comment]
+1

**Comment by naroga** [comment]
+1

This is conflicting with other dependencies in my project (such as Goutte).
