### ISSUE TITLE
WAMP1 + SessionProvider?

### ISSUE THREAD

**Issue by izemize** [ratchetphp/Ratchet#286]
Hi.

I have this config:

```php
$session = new SessionProvider(
		new Chat,
		new Handler\PdoSessionHandler($pdo,array(
			'db_table'=>'sessions',
			'db_id_col'=>'id',
			'db_data_col'=>'data',
		))
);
$app = new App('xxx.xxx.xxx','10081','0.0.0.0');
$app->route('/chat',$session);
$app->run();
```

When i start this script i get:

PHP Catchable fatal error:  Argument 1 passed to Ratchet\Session\SessionProvider::__construct() must implement interface Ratchet\MessageComponentInterface, instance of MyApp\Chat given, called in server/bin/new.php on line 20 and defined in /vendor/cboden/ratchet/src/Ratchet/Session/SessionProvider.php on line 47

My base app class fully same as [Chatroom example script](https://github.com/ratchetphp/socketo.me/blob/master/src/Ratchet/Website/Chat/ChatRoom.php), and it works fine with implements WampServerInterface.

SessionProvider requires MessageComponentInterface.

When i change WampServerInterface to MessageComponentInterface in Chat application, i can't connect to server.

I don't understand how to do this.. :-/ Please somebody help me.

**Comment by ProPheT777** [comment]
May be

```php
$session = new SessionProvider(
        new WampServer(new Chat),
        new Handler\PdoSessionHandler($pdo,array(
            'db_table'=>'sessions',
            'db_id_col'=>'id',
            'db_data_col'=>'data',
        ))
);
$app = new App('xxx.xxx.xxx','10081','0.0.0.0');
$app->route('/chat',$session);
$app->run();
```

**Comment by izemize** [comment]
Thanks, it works.

I have a new problem. My session is NULL.

ws URL is ws://deejay.sytes.net:port/chat

session runs on ".sytes.net" domain.

```php
	public function onOpen(Conn $conn)
	{
		var_export($conn->Session->get('chatData'));[...]
```
