### ISSUE TITLE
Guzzle out of date?

### ISSUE THREAD

**Issue by absalomedia** [ratchetphp/Ratchet#288]
Writing a new app with Ratchet & Composer is complaining that the Guzzle reference is out of date / abandoned.

Any chance you can use "guzzlehttp/guzzle": "5.0.*@dev" instead?

**Comment by bobvandevijver** [comment]
See #285, it will be updated in the near future.

**Comment by hrach** [comment]
It would be quite usefull, until then my IDE suggest me both libraries when I write a code, but of couse, I wanna just guzzlehttp.

**Comment by cboden** [comment]
I started replacing it with Guzzle 5 yesterday. Unfortunately quite a bit has changed so it's not just a quick upgrade. 

In the mean time, composer is just issuing a warning. Guzzle 3 is stable and still works.

**Comment by hrach** [comment]
@cboden thanks for a feedback, ouf course, it's not so big deal :-)

**Comment by andig** [comment]
+1 for "guzzlehttp/guzzle", current version is 6.0.1. which has PSR7 support. Might make sense- if you consider upgrading- to go for PSR7?

**Comment by cboden** [comment]
Ratchet v0.4 will be PSR-7. See the `0.4-wip/*` branches.

**Comment by RynnHeldeD** [comment]
Question : Is it safe to add "guzzle/guzzle" to composer.json as Composer recommends to use it instead ?
Because I tried to add this line and when updating, it deleted all guzzle/<something> to install guzzle/guzzle.

My app seems to keep running but I do not know if it will be less stable or not. What is the recommend things to do for now ? To keep "guzzle/guzzle" or to delete this line and let composer reinstall "guzzle/<http-and-else>" ?

Thanks !

**Comment by cboden** [comment]
@RynnHeldeD `guzzle/http`, `guzzle/parser`, and the other `guzzle/` packages are git subtree splits from `guzzle/guzzle`. The author of Guzzle just stopped splitting the sub repositories from the main repo. You're safe doing what you're doing. The only reason Ratchet doesn't do this is because `guzzle/guzzle` requires `ext/curl` which is not needed by Ratchet and would introduce a BC break.

**Comment by lucascherifi** [comment]
👍

**Comment by Phyks** [comment]
Any news on this? Thanks!

**Comment by Pierstoval** [comment]
News on this?

**Comment by victorvassilev** [comment]
Still, for production delivery having deprecated messages on composer update is not really nice, do you have any ETA when this could be resolved?

**Comment by cboden** [comment]
The 0.4 branch is ready for testing to be merged into master. Feel free to test it out and open any issues that come as a result. Documentation will then have to be updated to tag it. 

Deprecated messages don't mean anything; it means the package is no longer maintained, not that it doesn't work. Ratchet's use of Guzzle is take an HTTP string, parse, and return an object.

**Comment by tacman** [comment]
+1  Trying to clean up our code now that PHP 7.1 and Symfony 3.2 is out.  I know it's just a warning, but it's the last one in our list of dependencies.

**Comment by max-kovpak** [comment]
August 29 2017... Any news?

**Comment by saydulk** [comment]
what should i do?

![screenshot from 2017-10-05 04 00 05](https://user-images.githubusercontent.com/1058663/31201790-c7b30ac0-a981-11e7-8398-7a001ff43f78.png)


Using version ^6.3 for guzzlehttp/guzzle                                            
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                   
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0].
    - Conclusion: remove guzzlehttp/psr7 1.3.1
    - Conclusion: don't install guzzlehttp/psr7 1.3.1
    - guzzlehttp/guzzle 6.3.0 requires guzzlehttp/psr7 ^1.4 -> satisfiable by guzzlehttp/psr7[1.4.0, 1.4.1, 1.4.2].
    - Can only install one of: guzzlehttp/psr7[1.4.0, 1.3.1].
    - Can only install one of: guzzlehttp/psr7[1.4.1, 1.3.1].
    - Can only install one of: guzzlehttp/psr7[1.4.2, 1.3.1].
    - Installation request for guzzlehttp/psr7 (locked at 1.3.1) -> satisfiable by guzzlehttp/psr7[1.3.1].


Installation failed, reverting ./composer.json to its original content.
![screenshot from 2017-10-05 04 00 05](https://user-images.githubusercontent.com/1058663/31201768-b891b01e-a981-11e7-8666-5ebb33fe6c90.png)

**Comment by cboden** [comment]
@saydulk Try doing a `composer upgrade guzzlehttp/psr7` before you add guzzlehttp/guzzle.

**Comment by andig** [comment]
... or upgrade both at the same time, see https://stackoverflow.com/questions/46510542/howto-upgrade-selected-package-when-composer-lock-is-present?noredirect=1#comment79983904_46510542

**Comment by saydulk** [comment]
![screenshot from 2017-10-05 16 07 42](https://user-images.githubusercontent.com/1058663/31222002-5e150788-a9e7-11e7-8b17-b4ea95a8256c.png)
![screenshot from 2017-10-05 16 07 52](https://user-images.githubusercontent.com/1058663/31221995-5da4633e-a9e7-11e7-96af-bb3c931f99d6.png)

I am trying to setup this - https://www.rosehosting.com/blog/install-mautic-on-an-ubuntu-14-04-vps/

**Comment by cboden** [comment]
@saydulk What's the output of `composer show`?
