### ISSUE TITLE
Server response.

### ISSUE THREAD

**Issue by jignesh87** [ratchetphp/Ratchet#291]
Hello ,cboden
I am trying to get server response as a audio/video file, so that all clients can see the video or listen audio
How it can be done?
Thanks,
Jignesh

**Comment by kinncj** [comment]
You can send the URL trough the message.

If you are looking to send the binary, you will probably need an array buffer (or just send the blob as part of the message, which can be huge).

Please take a look at https://github.com/ratchetphp/Ratchet/issues/279

**Comment by cboden** [comment]
I haven't done audio/video before but as @kinncj said if you were to do it over WebSocket it would be with binary messages.

I also have no experience with it, but I think this is what WebRTC is meant for.

**Comment by jignesh87** [comment]
Thnaks ,
kinncj and cboden.
