### ISSUE TITLE
Stream bufferSize

### ISSUE THREAD

**Issue by casmeiron** [ratchetphp/Ratchet#292]
Hi, I'm using Ratchet to create a server socket that receives messages from a client.
The problem occurs when I try to send a message thats longer than 4096 bytes. The only way that I could make it work was changing (I don't like that) manually the bufferSize in Stream.php class. Is that a way to do that but calling some method acessors? Couldn't find out.

Thanks in advance.

**Comment by casmeiron** [comment]
Just to give more insights, my server implements MessageComponentInterface and my onMessage its receiving only the first 4096 bytes of my message.

**Comment by kinncj** [comment]
This should be post to [react](https://github.com/reactphp/react)

**Comment by casmeiron** [comment]
Thanks.

**Comment by kinncj** [comment]
And btw, the `Connection::bufferSize` is public.
