### ISSUE TITLE
PSR-0 deprecated; use PSR-4 instead? 

### ISSUE THREAD

**Issue by shivanraptor** [ratchetphp/Ratchet#295]
Reading the [Hello World tutorial](http://socketo.me/docs/hello-world), I found that the tutorial mentions using PSR-0.

I wonder if Ratchet will use [PSR-4](http://www.php-fig.org/psr/psr-4/) standards rather than [PSR-0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md), as the standard is marked as deprecated on 2014-10-21.

**Comment by cboden** [comment]
Good catch. I just created an issue for this in the [website repo](https://github.com/ratchetphp/socketo.me/issues/24). Opening a pull request against this before I get to it is always welcome. :)
