### ISSUE TITLE
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

### ISSUE THREAD

**Issue by Sshuichi** [ratchetphp/Ratchet#305]
I think you should use the version 5 instead of 3.6

The full error message:
`Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.`

**Comment by cboden** [comment]
I just started a new job this week so I won't have much free time in the next couple weeks while I'm on-boarding. The Guzzle 5 API has some differences between 3 so it wasn't a quick fix for me to do. Feel free to open a PR against the 0.4 branch with this replacement.
