### ISSUE TITLE
Client authentication on subscribe to topic

### ISSUE THREAD

**Issue by islamdarwish** [ratchetphp/Ratchet#306]
i am not using Symfony so that it is so hard to change the application session to be Symfony session provider, so what is the solution !!!.

**Comment by cboden** [comment]
Currently Symfony sessions are the only supported option. There are plans to change how session management works to have adapters for any library that uses non-native session handlers. 

Alternatively you could always write your own `ComponentInterface` adapter to handle connection sessions in the mean time.
