### ISSUE TITLE
Deploy chat application in live server

### ISSUE THREAD

**Issue by Mrrific** [ratchetphp/Ratchet#311]
I'm getting a hard time to implement my chat application and following the instructions from the website.

Everything is working in localhost. Now I want to implement it to live server.
I'am using framework which is CODEIGNITER.

Thanks for you help..

**Comment by cboden** [comment]
Please check the [troubleshooting guide](http://socketo.me/docs/troubleshooting) first. If that has not resolved your issue please post a gist with your code so I am able to reproduce your problem.

**Comment by Mrrific** [comment]
Here is my function that I created. I think the only problem here is the websocket URL. How can I resolve this? https://gist.github.com/Mrrific/5568db674ea48bce8582

**Comment by cboden** [comment]
I attempted to connect to your website given the URL in that gist. Apache is handling the request and responding with a 200 status code when the client is attempting to make a WebSocket request. Apache is not understanding the upgrade request and is responding with the index page as a typical HTTP negotiation. 

You either need to expose Ratchet to a different port other than 80 and connect to that or reverse proxy  to your WebSocket server.

**Comment by revic1993** [comment]
I have implemented ratchet using Laravel 5 which works perfectly on my local machine. When I run the command for the ratchet on live server it is listening to port 8080. But when I try to connect via javascript it gives me connection timeout error.

**Comment by cboden** [comment]
@revic1993 Odds are either port 8080 is being blocked by your hosts firewall or you're binding to loopback. I would recommend using a reverse proxy such as Nginx so your browsers connect through port 80. If that's not an option make sure to set the third parameter of `App` constructor or `IoServer::factory` to `'0.0.0.0'`.

**Comment by revic1993** [comment]
Ok so I read the deployment part on the documentation. As i am not much familiar with ubuntu system and whole proxy thing I didnt try it. I also inspected code of IoServer::factory method which takes 0.0.0.0 as default address and I also tried that but didn't work. 
If i give the address of subdomain in IoServer::factory on port 80 with the subdomain directory empty will that work?

**Comment by cboden** [comment]
Please provide a gist with both your server and client side source code.

**Comment by revic1993** [comment]
https://gist.github.com/revic1993/9cbfcef8927c45dfc65a

The error is Connection time out when trying to open a socket connection in javascript.

**Comment by cboden** [comment]
Your code shows your server running on port 80 and your client attempting to connect on port 7777.

**Comment by revic1993** [comment]
Oh.. sorry I attached my local file. But its port 80 on my server.

**Comment by cboden** [comment]
127.0.0.1 is your local machine. If you deploy on production you need to use it's hostname or IP address.

**Comment by revic1993** [comment]
Ya as i said i uploaded the local file by mistake.. I assure you I have made the necessary changes on the server side script.

**Comment by cboden** [comment]
@revic1993 Given the data provided I don't have enough to troubleshoot with. 

* Make sure your script is running, check your process list on your server
* Make sure your script is bound to the port: turn on all error logging, check the output. From your production server verify you can connect to the given port
* Externally make sure you can connect to the port (no WS, just TCP)
* Send an invalid handshake HTTP request to see the error response

**Comment by revic1993** [comment]
Ok.. thank you for your response.

**Comment by revic1993** [comment]
Hello Chris,
I have tried haproxy on my shared hosting server. But apparently the providers deny to grant me the compiler permission. Do you know if I can run ratchet on the forge servers?

**Comment by cboden** [comment]
I'm not sure about forge but yes to digital ocean. You have root access to your VPS' there. Alternatively to HAProxy you could try Nginx.

**Comment by revic1993** [comment]
Thank you.

**Comment by Rupashdas** [comment]
Hi cboden, Are you there I need help with the same issue.
