### ISSUE TITLE
Has Ratchet stopped develop?

### ISSUE THREAD

**Issue by argb** [ratchetphp/Ratchet#312]
Why Ratchet there is no updates,old packages dependencies,such as guzzle,and don't implement WAMP v2.

**Comment by argb** [comment]
I found a WAMP v2 implementation of php,Thruway(https://github.com/voryx/Thruway) ,but it's only a pure WAMP v2 implementation,not like Ratchet a websocket library,I like Ratchet more,Ratchet can do more things,more flexible ,but the only problem of Ratchet is don't implement WAMP v2.
Is there any plan to update?

**Comment by argb** [comment]
This list there is no Ratchet
http://wamp.ws/implementations/

**Comment by cboden** [comment]
guzzle/http still works it's just deprecated. All that means is that library is no longer being maintained. It's still a fully functional HTTP parser. 

Ratchet will not support WAMPv2, see [this comment](https://github.com/ratchetphp/Ratchet/issues/168#issuecomment-55339203). 

Ratchet is still being developed, just more slowly now as I don't have as much free time on my hands as I used to have.

**Comment by argb** [comment]
Got it ,Thanks!

**Comment by argb** [comment]
But Thruway just a WAMP v2 implementation,not like Ratchet,more like Ratchet.

**Comment by cboden** [comment]
Thruway uses Ratchet internally as its WebSocket transport. You should be able to use any features Ratchet provides within Thruway.

**Comment by argb** [comment]
@cboden Thank you ,maybe because Thruway there is no any document.
