### ISSUE TITLE
IDLE or any loop function for game physics calcucations processing?

### ISSUE THREAD

**Issue by alexmatveev** [ratchetphp/Ratchet#315]
Hello! Please, give us an advice: within Hello World example (http://socketo.me/docs/hello-world), any best practices to create calculations loop? For game physics server-side calculations: players moving, in-game events, etc?
Thanks!

**Comment by andig** [comment]
See https://github.com/reactphp/react/issues/254

**Comment by cboden** [comment]
Closing in favour of question asked in [mailing list](https://groups.google.com/forum/#!topic/ratchet-php/TwjlU9aVTMQ)
