### ISSUE TITLE
How to check if client is still connected?

### ISSUE THREAD

**Issue by shirofuji** [ratchetphp/Ratchet#316]
How do i check if the client is still connected to the Ratchet server? I tried opening multiple instance of my client using browser tabs and closed them using taskkill, unfortunately the onclose function of my server did not trigger. My server is fully based on the push integration sample on http://socketo.me

**Comment by cboden** [comment]
See #70 on why this happens. You can resolve this in one of two ways: use a reverse proxy for your WebSocket server (nginx) and have a TCP timeout on it. Another option would be to implement your own heartbeat, see #263 for an example of someone doing this.
