### ISSUE TITLE
Authentication in Ratchet Webocket server

### ISSUE THREAD

**Issue by travisspears0** [ratchetphp/Ratchet#320]
Hi! I want to do an authentication on Ratchet Webocket server. I've came to the idea to pass username and password in url(when connecting via js websocket client) and then perform standard login uing PDO. I would like to do an authentication and then send a mesage to user whether it was successful, and if not, close the connection. I'm not sure how to do thi as there are no such issues on the web and in the documentation either. I tried to do this in the SocketServer class(copied from tutorial and modified by me, implements Ratchet\MessageComponentInterface) but I can't figure out how to force closing connection there. So theres quetion number one how to do such thing? I also tried to do this in Guzzle\Http\Message\Request as there's a method named setAuth but I have no clue how to use it. Please help.

**Comment by cboden** [comment]
I think you're on the right path on how to do this. Read up on "HTTP Baisc Authentication". You can parse the `Authorization` from the Guzzle Request object. 

I would create a class that implements [HttpServerInterface](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Http/HttpServerInterface.php) that handles the authentication. You can close the connection with a 401 response. This class would sit between Ratchet's `HttpServer` and `WsServer` components.
