### ISSUE TITLE
Newbie guidance please...

### ISSUE THREAD

**Issue by pjam** [ratchetphp/Ratchet#322]
Hi.

I'm developing an app that needs some real time operations, so I got to Ratchet from my searching. In the past I used the nginx push stream module to have real time messages in a website, and in php I would just make a curl call to a specific address to send a message.

Now with websockets and ratchet, I'm not getting how to send messages from php. I'm using Symfony2 and would like to send messages from a controller or a service. I got the chat tutorial to work without problems, but this part I can't figure out.

Is it possible to do this with the chat tutorial? And it would be something simple, or I have to go for something more complex like the other tutorial? A tiny example on just how to send a message would be great ;)

I know these are newbie questions, but I'm not having the capability to abstract myself and fully understand this.

Thanks. Regards

**Comment by cboden** [comment]
Ratchet is built on an asynchronous stack which has to run independently from your FCGI website. You need some kind of network messaging to communicate between the two different running processes. 

See the [Push Integration tutorial](http://socketo.me/docs/push) on how to do this using ZeroMQ.
