### ISSUE TITLE
Ratchet in Symfony 

### ISSUE THREAD

**Issue by kimlongngin** [ratchetphp/Ratchet#326]
Hi, i try to set follow up Ratchet "hello world" example in Symfony 2. But i can't get result.
How can i work on Symfony ?

**Comment by ProPheT777** [comment]
Hi, I have create a bundle for that :D 

https://github.com/GeniusesOfSymfony/WebSocketBundle but you can also plug ratchet out of box within symfony by yourself.

**Comment by kimlongngin** [comment]
Dear Johann Saunier
    Thank you for your bundle, now it's work a better.
For your bundle it's support for chat, So if i want to make real time
server for transaction data. Does it's work ?
Or if you have any bundle for real time server for data transaction. please
help to advice me.

Best regards
Kimlong

**Comment by ProPheT777** [comment]
This bundle is just a symfony integration of ratchet, so the bundle is not specific to create a chat application, you can create any apps with that. 

So yes you can make a real time data transaction server.

**Comment by kimlongngin** [comment]
Dear Johann Saunier

     Oh, so great for you bundle. Thank you so much i will suggest my
friend to use it.
Best regards
Kimlong

**Comment by kimlongngin** [comment]
Hi Sir,
   How can i create a Chanel for for your project for publish message or other data ?

regards 
Kimlong

**Comment by ProPheT777** [comment]
You can read this docs : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md

and pratical usage in the demo application : https://github.com/GeniusesOfSymfony/WebsocketAppDemo and here the topic (channel handler) : https://github.com/GeniusesOfSymfony/WebsocketAppDemo/blob/master/src/AppBundle/Topic/AcmeTopic.php
