### ISSUE TITLE
Does it make sense to encapsulate broadcast() in nextTick()?

### ISSUE THREAD

**Issue by andig** [ratchetphp/Ratchet#329]
I have an HTTP server (single threaded) that broadcasts to WAMP topics when HTTP requests are received. Does it make sense to wrap the `$topic->broadcast()` in a `$loop->nextTick()` to send the HTTP response as early as possible?

```php
	public function handleRequest($json) {

		$result = $this->doSomethingWithJson();

		$this->loop->nextTick(function() use ($result) {
			$this->broadcast($result);
		});

		$response = $this->doSomethingWithResult();

		return $response;
	}
```
Hope this is not too off-topic, answer much appreciated, thank you!

**Comment by cboden** [comment]
I'm pretty sure that won't make a difference. Off the top of my head calling broadcast without wrapping it in nextTick will fill the write buffer of each connection that has subscribed to the topic. Once a message is in a connection's write buffer it's up to the event loop implementation to send the message which will happen "when it's ready".

**Comment by andig** [comment]
Excellent, much appreciated!
