### ISSUE TITLE
Loop in Onopen

### ISSUE THREAD

**Issue by QuinLena15** [ratchetphp/Ratchet#331]
Hello!
If I do this :
```php
 public function onOpen(ConnectionInterface $conn) {
    $loops = \React\EventLoop\Factory::create();
  
    $loops->addPeriodicTimer(2, function() {
        print_r('hello');
    });
    $this->repository->addClient($conn);
}
```
this does not work.

**Comment by cboden** [comment]
You can only have 1 event loop running per app. Pass your already existing `$loop` into your `__construct` function, store it in your class and then use `addPeriodicTimer` on that loop.

**Comment by QuinLena15** [comment]
I try like this:
$loop = \React\EventLoop\Factory::create();
$server = IoServer::factory(new HttpServer(new WsServer(new Chat($loop))), 8990);

$server->loop->addPeriodicTimer(60, function () {
	//code
});
$server->run();


class Chat implements MessageComponentInterface {
	private $loop;
	
    public function __construct(\React\EventLoop\LoopInterface $loop) {
       
		$this->loop=$loop;

	}
	
    public function onOpen(ConnectionInterface $conn) {
		
	 $this->loop->addPeriodicTimer(2, function() {
        print_r('sadds');
    });
    }

Don't work. whether somewhere to see an example?

**Comment by QuinLena15** [comment]
Help me, please....

**Comment by mbonneau** [comment]
The factory static method creates it's own loop, so if you want to share a loop, you need to use the regular constructor.

Try:

```php
$loop = LoopFactory::create();
$socket = new Reactor($loop);
$socket->listen(8990);

$server = new IoServer(new HttpServer(new WsServer(new Chat($loop))), $socket, $loop);
```

Let me know if that works for you.

**Comment by QuinLena15** [comment]
WebSocket connection to 'ws://address:8990/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by mbonneau** [comment]
By default, this only binds to 127.0.0.1. If you would like to connect from a machine other than local - change the listen line to:

```php
$socket->listen(8990, '0.0.0.0');
```

Not 100% sure this is your issue because there isn't much detail in the last comment.

Let me know if this helps.

**Comment by QuinLena15** [comment]
Thank you!!!!!! It works for me!!!!
