### ISSUE TITLE
ZMQ not transmitting data to websocket

### ISSUE THREAD

**Issue by johannes-z** [ratchetphp/Ratchet#333]
I followed the steps on http://socketo.me/docs/push but couldn't reproduce the functionality. I tried a very basic example, but the Websocket function is not called - I want to echo the received data, but the function is never called. 

First I implemented the **Pusher**: 

```php
namespace App\WebSocket;
class Pusher implements WampServerInterface {
    // empty functions for the interface

    // call this, when ZMQ sends data.
    public function onEvent($data) {
        echo $data . "\n";
    }
}
```
This is the **post action handler**.
```php
// $data is a json encoded database record.
$context = new \ZMQContext();
$socket  = $context->getSocket(\ZMQ::SOCKET_PUSH, 'websocket');
$socket->connect('tcp://127.0.0.1:5555');

echo $data . "\n";
$socket->send($data);
```
And this is what I do to initialise the **websocket**.
```php
// WebSocket/ZMQ startup
$loop   = Factory::create();
$pusher = new \App\WebSocket\Pusher;

$context = new Context($loop);
$pull    = $context->getSocket(\ZMQ::SOCKET_PULL);
$pull->bind('tcp://127.0.0.1:5555');
$pull->on('message', [$pusher, 'onEvent']);

$websocket = new Server($loop);
$websocket->listen(8080, '0.0.0.0');

$webServer = new IoServer(
	new HttpServer(
		new WsServer(
			new WampServer(
				$pusher
			)
		)
	),
	$websocket
);

$loop->run();
```

The websocket is running, the server event works too...

**Comment by Doncode** [comment]
//My implementation 
class Pusher implements WampServerInterface {
    protected $topicAll;

    public function __construct()
    {
        echo '__construct' , PHP_EOL;
        $this->topicAll = new Topic('all');
    }

    public function onOpen(ConnectionInterface $conn) {
        echo 'onOpen' . PHP_EOL;
        $this->topicAll->add($conn)
    }

    public function onZMQ($str) {
        $data = json_decode($str, true);
        print_r($data);

        $this->topicAll->broadcast($data);
    }
}

you should use broadcast
