### ISSUE TITLE
Session dont get data (only the ID)

### ISSUE THREAD

**Issue by cirovargas** [ratchetphp/Ratchet#336]
Hi,

Im trying to share session data beetwen the socket server and Symfony using handlers (File) but he get only the session id:

My socket file:
```php
        $loop   = \React\EventLoop\Factory::create();
        $pusher = new \Comunicacao\ComunicadorBundle\Topic\WampChatTopic();

        // Listen for the web server to make a ZeroMQ push after an ajax request
        $context = new \React\ZMQ\Context($loop);
        $pull = $context->getSocket(\ZMQ::SOCKET_PULL);
        $pull->bind('tcp://127.0.0.1:5555'); 
        $pull->on('message', array($pusher, 'onChatMessage'));

        $webSock = new \React\Socket\Server($loop);
        $webSock->listen(8080, '0.0.0.0'); 

        $session = new SessionProvider(
            new \Ratchet\Wamp\WampServer($pusher)
          , new Handler\NativeFileSessionHandler()
        );
        
        $webServer = new \Ratchet\Server\IoServer(
            new \Ratchet\Http\HttpServer(
                new \Ratchet\WebSocket\WsServer(
                    $session
                )
            ),
            $webSock
        );

        $loop->run();
```

On the topic implementation have:
```php
        public function onOpen(ConnectionInterface $conn) {
            print_r($conn->WebSocket->request->getCookies());
        }
```
i get de session id (are the same on browser) but the data? nothing...

**Comment by ProPheT777** [comment]
Here an example : https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Client/Auth/WebsocketAuthenticationProvider.php#L61

**Comment by cirovargas** [comment]
Hi, nothing with:

        if (false !== $serializedToken = $conn->Session->get('_security_' . 'default', false)) {
                    $token = unserialize($serializedToken);
                    print_r($token);
        }

No data to get

Nice bundle

**Comment by ProPheT777** [comment]
your user is connected and the firewall is named 'default' ?

**Comment by cirovargas** [comment]
Yes, the firewall is 'default' the sessid is the same on socket and on browser.

Maybe have issue with the nativefilesessionhandler?

with the NativeSessionHandler throws 'Cannot call default session handler'

**Comment by ProPheT777** [comment]
Try with PDOSessionHandler

**Comment by cirovargas** [comment]
hostname is the same, the diference is the port 80 and 8080 

:'(

with the nativefilesessionhandler on $conn->Session->all() get null, with memcached returns a empty array

**Comment by cirovargas** [comment]
I need to configure php.ini session.cookie_domain  directive?

when i set the domain, symfony dont login anymore

**Comment by cboden** [comment]
@cirovargas Are you doing this locally? Browsers only send cookies to same domain names. Your website and WebSocket server need to have matching domain or parent domain name.

**Comment by cirovargas** [comment]
Are locally. the same domain on the websocket and site

The domain are configured on the hosts file to the VM

**Comment by cboden** [comment]
I also seem to recall some browsers don't send cookies to localhost. Can you confirm you're getting the cookie data from the HTTP request in your PHP script?

**Comment by cirovargas** [comment]
I'm getting the cookie on the page and in the socket (IDs are the same). But i cant get the session data

**Comment by cboden** [comment]
I just noticed you're using `NativeFileSessionHandler`...from the docs:

> The *SessionProvider* **will not work** with any of the Native* session handlers.

**Comment by cirovargas** [comment]
Yes, but tryed with MemcacheSessionHandler, MemcachedSessionHandler and MongoDbSessionHandler and got the same result.

**Comment by cboden** [comment]
Can you confirm the value of a connection's id:
```php
echo $conn->WebSocket->request->getCookie(ini_get('session.name'));
```

Also try this before trying to access the session data:
```php
$conn->Session->start();
```

**Comment by bizley** [comment]
I've got the same problem with session. Can get session cookie but no session data. Using `start()` doesn't help. Same cookie domain.

I'm using `PdoSessionHandler`. Is there anything I'm missing in configuration?

**Comment by yousifalraheem** [comment]
@cboden .. Same issue here. When I use:
`$conn->Session->start();`
I get this response in the terminal:
`Error! Details:
 Undefined property: Ratchet\Server\IoConnection::$Session`

**Comment by cboden** [comment]
@yousifalraheem Please provide more of your code to assist in troubleshooting.

**Comment by yousifalraheem** [comment]
@cboden .. My code used to work perfectly fine, I remember running `composer update` and then it stopped working. Here is my code:
This is my server (Protected port 8080 and IP 127.0.0.1):
```
$server = IoServer::factory(
  new HttpServer(
    new WsServer(
      new Messenger()
    )
  ),
  $this->port,
  $this->ip
);
$server->run();
```

In the Messenger class I have a constructor:
```
function __construct() {
  $this->clients = new \SplObjectStorage;
  $this->index = array();
  $capsule = new Capsule;
  $config = config::get('database');
  $capsule->addConnection($config['connections'][$config['default']]);
  $capsule->setEventDispatcher(new Dispatcher(new Container));
  $capsule->setAsGlobal();
  $capsule->bootEloquent();
  echo "Server is running...".PHP_EOL;
}
```
And this is where the code stops working (onOpen Function):
```
public function onOpen(ConnectionInterface $conn) {
  echo "New connection".PHP_EOL;
  $this->clients->attach($conn);
  $session = (new SessionManager(App::getInstance()))->driver();
  $cookies = $conn->WebSocket->request->getCookies();
  $laravelCookie = Crypt::decrypt(urldecode($cookies[Config::get('session.cookie')]));
  $session->setId($laravelCookie);
  $conn->session = $session;
}
```
As I traced the issue, for some reason `$conn->WebSocket->request->getCookies()` returns an empty array. Therefore, an error is thrown at the next line since `$cookies` has no index called `laravel_session` because the array is empty.

**Comment by yousifalraheem** [comment]
I just updated Ratchet to version 0.4, Now I'm getting something else. The code stops at `onOpen` function running this line `$cookies = $conn->WebSocket->request->getCookies();`. The error is:
```
Error! Details:Undefined property: stdClass::$request
```
I tried running `print_r($conn->WebSocket);`. And this is what I get:
```
stdClass Object
(
    [closing] => 
)
```

**Comment by cboden** [comment]
@yousifalraheem 0.4 introduced a BC break with HTTP. See http://socketo.me/docs/migration-3

**Comment by yousifalraheem** [comment]
@cboden  .. Now I'm back to the same issue as before: 
```
$conn->httpRequest->getHeader('cookie');
```
returns an empty array. Any idea why is this happening?

**Comment by cboden** [comment]
Are your ~LAMP stack and your Ratchet app running on the same domain?

**Comment by yousifalraheem** [comment]
`php artisan serve` is served to
<http://127.0.0.1:8000>
And my websocket server is served to:
<http://127.0.0.1:8080>
in JavaScript I have this line:
`this.conn = new WebSocket('ws://localhost:8080');`

**Comment by cboden** [comment]
Cookies can't be shared across different ports. I'm not 100% sure but I think you also need a domain name for this to work (non IP addresses). See http://socketo.me/docs/sessions for more info.

**Comment by yousifalraheem** [comment]
I think I fixed it thanks to you pointing at the probable cause. In JavaScript I wrote **localhost** and in PHP I wrote **127.0.0.1**. I changed **localhost** to **127.0.0.1** in JavaScript and it worked. I'm sorry if I bothered you, it's a silly fix. 😅
