### ISSUE TITLE
http://socketo.me/docs/install gives wrong install instructions.

### ISSUE THREAD

**Issue by SvenRtbg** [ratchetphp/Ratchet#338]
The instruction says in the paragraph of the second headline:

> create a file called composer.json in your project folder. Inside that file copy and paste the JSON from the top of this page.    

There is no json at the top of that page, only this code:

> php ~/composer.phar require cboden/ratchet

The result is confusion for new users of Composer, like this: http://stackoverflow.com/questions/31502930/php-composer-cant-parse-composer-json-file-for-my-project

**Comment by heaversm** [comment]
+1

**Comment by cboden** [comment]
I have a backlog of email and PRs to review before I'll get to this. In the mean time feel free to open a PR for this at https://github.com/ratchetphp/socketo.me

**Comment by cboden** [comment]
docs updated
