### ISSUE TITLE
Problem with installation Invalid version string "^0.3"

### ISSUE THREAD

**Issue by miholeus** [ratchetphp/Ratchet#339]
Hi, I have a problem with installation.
composer require cboden/ratchet
gives me the following error
[RuntimeException]
  Could not load package cboden/ratchet in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^0.3: Invalid version string "^0.3"

What happened?

**Comment by cboden** [comment]
I just ran the command `composer require cboden/ratchet:^0.3` and it worked as expected. Make sure your composer is update to date by running `composer self-update` and try again.

**Comment by miholeus** [comment]
Yeah, right! self-update fixed the issue, the problem was with composer. Thank you!
