### ISSUE TITLE
Type hinting for "resourceId"

### ISSUE THREAD

**Issue by jacobson** [ratchetphp/Ratchet#340]
Neither IOConnection nor ConnectionInterface include "resourceId".

I recommend to add resourceId to one of the Ratchet classes or interfaces.

``` php
        public function handleConnect($conn) {
            $conn->decor = new IoConnection($conn);

            $conn->decor->resourceId    = (int)$conn->stream;
```

**Comment by cboden** [comment]
please see explanation in the above pull request
