### ISSUE TITLE
Ratchet Truck Factor

### ISSUE THREAD

**Issue by gavelino** [ratchetphp/Ratchet#341]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Ratchet** and obtained a value of **1**.

The developer responsible for this TF is:

Chris Boden - author of 100% of the files 

To validate our results, we would like to ask **Ratchet** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Ratchet**?

(b) Do you agree that **Ratchet** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Ratchet** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by cboden** [comment]
(a) yes
(b) no
(c) yes

I agree the truck factor of Ratchet would look like a 1 based on the commit history. However I'm incredibly confident there are a few developers who could take over the project should I leave it. This is based on conversations I've had with developers outside the GitHub ecosystem regarding architecture, project direction, and implementation details.

**Comment by gavelino** [comment]
Hi, thank you for your answer. 

Just a small argumentation about the answer for the question b.  Even believing that the project would continue without you, how great would be the impact? How much time do you believe the remainder team will need to really dominate the entire project source?

**Comment by mbonneau** [comment]
I think the truck factor is much more difficult to determine in open-source systems.

It could be valid to say that the truck factor of any closed source system is always 1. My argument is this: [Satya Nadella](https://en.wikipedia.org/wiki/Satya_Nadella) could unilaterally decide to halt development and sales of any of Microsoft's products at any time. As it has done with [Windows RT](http://www.windowscentral.com/microsoft-halts-production-surface-2) and other products. This would make maintenance and bug fixes impossible. One person is in complete control.

In open source software, this is not really an option. In this project, @cboden could decide he wants to kill Ratchet completely. The likelihood of him being successful is very small. Not only is the source code already on thousands of systems, but many developers have been deeply into the source code and are contributors back to the project already. They would likely continue to make and share these development efforts.

**Comment by cboden** [comment]
@gavelino I think @mbonneau should answer b for you. He's put a significant amount of work into the next major release. I think if I got hit by a bus he'd have no problem taking over the project. 

Another reason I don't think the project would suffer a great deal is that it suits its job; it implements RFC6455 as a WebSocket server while being loosely coupled. Most of the upcoming features I have planned will be done as separate packages.

**Comment by mbonneau** [comment]
Hi @gavelino ,

To answer the original questions:

(a) Yes
(b) No - In the event that @cboden "won the lottery", I would not be concerned about Ratchet's future. While @cboden has done a great job and contributed most of the code, there are people like myself and others who have a pretty good understanding of the system (especially the decorator pattern). In my company's specific circumstance, we would need Ratchet to continue to function (get bug fixes when needed and keep up with new developments in technology in this area). As has happened with previous bug fixes, myself or others would take on the task of fixing them because we have projects that rely on Ratchet. I know in my case, I would find a way to contribute this work back in hopes that the rest of the Ratchet community would also. And as @cboden has mentioned, I am also involved with continued development.
(c) Yes

**Comment by gavelino** [comment]
Thank you! I really appreciate your answers.
