### ISSUE TITLE
Help in handling Error 413

### ISSUE THREAD

**Issue by shirofuji** [ratchetphp/Ratchet#343]
Hello guys, I have a server running ratchetphp. I followed the tutorial on socketo.me on how to implement push integration. recently I have encountered an error with the code 413, I have successfully fixed this by clearing browser's cache. I found out the error by looking at the developer tools in chrome. How can I make the client know about this error? also is there a way to reproduce this error? because I am encountering this error at random times.

**Comment by cboden** [comment]
The 413 HTTP status code is "Payload Too Large". By default Ratchet fails upgrade requests if they're larger than 4KB. Given clearing your cache fixes this I'm guessing you're sending a lot of cookie data.

**Comment by shirofuji** [comment]
I had this fixed temporarily by increasing the limit to 8kb. Do you think that much increase may have security issues? Also our session cookies have large amount of data which may be one reason this error is occuring

**Comment by cboden** [comment]
No, I wouldn't be concerned about a security issue; especially if your'e expecting headers that large.
