### ISSUE TITLE
Sending Object through websocket

### ISSUE THREAD

**Issue by Isty001** [ratchetphp/Ratchet#348]
It's not an issue, but a question, I can't ask elsewhere. I can't figure out how to send objects (StdClasses from Twitter api) to the client through a websocket. Is it even possible? I tried  json_encode(), but I receive it as a string. How can I do this?

**Comment by cboden** [comment]
You can only transmit data (strings) through WebSockets.

**Comment by daltones** [comment]
Native PHP ```serialize()``` and ```unserialize()```?

**Comment by Isty001** [comment]
Ahh, I think I had some problem with my browser, or don't know, because it couldn't parse the encoded JSON, now it works fine, no idea what was it. Thank you anyway!
