### ISSUE TITLE
Same responses even when code changes

### ISSUE THREAD

**Issue by hussan-choudhry** [ratchetphp/Ratchet#352]
I am using ratchet with zmq to connect to a WAMP Autobahn v0.8 front-end.

Everything works perfectly however when I change the topic code, the responses do not change!

i am running this in docker, when I restart the containers the updated responses get updated but then if I change this again nothing changes!

It is as if the responses are being cached, but I don't know where or why

**Comment by cboden** [comment]
Did you restart the application after the code change? If so, please post code so others are able to reproduce the issue.
