### ISSUE TITLE
Is there any way for setting request size limit?

### ISSUE THREAD

**Issue by NightShifter42** [ratchetphp/Ratchet#355]
Hi everyone!

Is there any way for setting request size limit? I mean, what if some client, will try to send 10Gb request. Need to restrict it to 1mb (per request) maximum.

Best regards!

**Comment by cboden** [comment]
If you mean in the initial HTTP handshake request it's currently limited to 4kb but is adjustable. If you mean an individual message size or client in general check out #26. There's a couple links to source code where this kind of work was started. You could copy that and implement a component in your source.
