### ISSUE TITLE
Constantly running server

### ISSUE THREAD

**Issue by QuinLena15** [ratchetphp/Ratchet#360]
Good afternoon! I do not know where to write, so I write here. How to make the script was running constantly? Through crone fails.
```php
$loop = LoopFactory: create();
$socket = new Reactor($loop);
$socket->listen(8990, 'ip');

$server = new IoServer(new HttpServer(new WsServer(new Chat($loop))), $socket, $loop);
$server->run();
```

**Comment by cboden** [comment]
Cron files execute a script to run. Ratchet is intended to be an indefinitely running script. Execute the above file with the `php` command. You can use something like `nohup` to keep it alive after your session closes or supervisor to monitor and launch it.
