### ISSUE TITLE
Is it possible to create a cluster of WS ? 

### ISSUE THREAD

**Issue by ProPheT777** [ratchetphp/Ratchet#363]
Hey, 

Currently i'm trying to create a cluster of WS but I make face to a problem, ratchet store internally all connection (and callback for webosocket) and contain also stream. 

I have made a try here https://github.com/GeniusesOfSymfony/WebSocketBundle/pull/56

Code is not really readable because I do it in MVP mode to test some cool toys :D That work, but client are insulated in server wich have been connected and I can't find a way to export all connections in a distributed pool. 

Have you an idea or maybe another way to do that ?

**Comment by nazar-pc** [comment]
I have implemented WS cluster by having one master instance (basically instance which was started first) and then all other instances connecting to it using https://github.com/ratchetphp/Pawl.
If master fails - everyone is reconnected to second instance which becomes first (you have to keep record of all running instances).
Then requests that are coming to each instance are re-sent to master and master re-sends requests to all other instances.
This way I can have chat app with multiple users on multiple servers and they are virtually in the same chat no matter which server they are connected to.

This question have nothing to do with Ratchet itself, this is purely architectural connectivity thing.
