### ISSUE TITLE
Streaming voice through websockets

### ISSUE THREAD

**Issue by Isty001** [ratchetphp/Ratchet#364]
I tried to look for an implementation for an example which uses PHP (first of all Ratchet) to stream voice over websocket, but I couldn't find anything useful. Could you let me know if it's possible, and if yes give me some ideas how to do it?

Thanks!

**Comment by cboden** [comment]
You *might* be able to do it with Binary message types in WebSockets but I think this kind of application might be more suited to WebRTC.
