### ISSUE TITLE
Receive callResult/callError from client

### ISSUE THREAD

**Issue by DHNCarlos** [ratchetphp/Ratchet#365]
Hello,

I have an implementation where the Client sends CALL requests to the Server and the Server replies with either CALL_RESULT or CALL_ERROR. But a large part of the implementation is where the Server sends a request to the Client (e.g. CALL) and expects to get a response from the Client back to the Server (e.g. CALL_RESULT or CALL_ERROR).

Currently I'm sending requests to the Client using the regular `MessageComponentInterface` but I'm not getting any response back to Server with either `onCall` nor `onMessage`.

Note: I have no control over the Client code as it is an encased charge box so the solution has to be server-side only.

In Ratchet, am I able to receive such responses from the Client?

**Comment by cboden** [comment]
Can you post some code examples please? The given information is not enough to troubleshoot. It sounds like you're using WAMP? In that case you should be implementing `WampServerInterface` instead of `MessageComponentInterface`.
