### ISSUE TITLE
connection with MySQL, query, insert ..

### ISSUE THREAD

**Issue by thebestclass** [ratchetphp/Ratchet#370]
I do not see anything on the internet that mentions the ratchet and mysql to do inserts, updates, or get rows.

How can I do this without disturbing the structure? there is something ready?

**Comment by Isty001** [comment]
If you don't use anything external (for example in Symfony you can inject the EntityManager easily) just simply write a method taking care of the inserts. http://www.phpeveryday.com/articles/PDO-Insert-and-Update-Statement-Use-Prepared-Statement-P552.html

**Comment by cboden** [comment]
MySQL drivers block, currently the recommended method is to use the [React Child Process](https://github.com/reactphp/child-process/) library tied in with the EventLoop used for your Ratchet process to offload blocking processes.

**Comment by thebestclass** [comment]
@cboden this will cause it does not block? You have examples of that .. I'm kind lay on that new platform.

**Comment by cboden** [comment]
When using React's Child Process lib the I/O between the child and parent is async. Any blocking I/O done in the child does not affect the parent. Check out [this blog post](http://blog.wyrihaximus.net/2015/03/reactphp-child-processes/) by @WyriHaximus

**Comment by daltones** [comment]
Actually there is a MySQL driver we can consider async: [mysqlnd (MySQL Native Driver)](http://php.net/manual/en/book.mysqlnd.php).

`mysqli::query()` has a `MYSQLI_ASYNC` option so you can `mysqli::poll()` the connection with periodic timer (just like Child Process does). But you won't be able to execute prepared queries with `mysqli_stmt` and some other helper methods. Even the connection can't be async. :(
Even so, I'm using mysqlnd right now in a React-based project and it's working very well! (sync connection isn't a problem in this case)
 
I've made a lib to use it on React, very based on [AsyncMysql](https://github.com/kaja47/async-mysql). I want to open it sometime. :)

**Comment by thebestclass** [comment]
@daltones  please share, I need stuff like that.

Regards

**Comment by fedyfausto** [comment]
so if i run some queries (like after a Message by user A) if User B need to exec a query this wait the UserA ?

**Comment by daltones** [comment]
@fedyfausto No, because (AsyncMysql)[https://github.com/kaja47/async-mysql] uses a connection pool (default limited by 100). So you could have 100 queries at the same moment for 100 Users.

But one connection from the pool by query would be a problem if you realy need multiple queries from the same connection. That's why I did my own lib, to be able to work with *transactions*.

@thebestclass Yeah, I'm working on that… I didn't write any automated tests yet. =/

**Comment by thebestclass** [comment]
@daltones Percebi que você é brasileiro, estamos a cá! Espero que não se importe se eu fugir um pouco do inglês para poder me expressar melhor...

O nosso colega alí de cima me recomendou o uso de React Child Process para não bloquear a execução, isso seria algo equivalente ao AsynMysql ou ao sua biblioteca em desenvolvimento? Pois preciso usar MySQL para tudo em meu servidor WebSockets e queria encontrar um meio melhor de fazê-lo sem travar a execução assíncrona.

**Comment by thebestclass** [comment]
@daltones  Our colleague over there from above recommended me using React Child Process not to block the execution, that would be something equivalent to AsynMysql or your library in development? Because I need to use MySQL for everything in my WebSockets server and wanted to find a better way to do it without halting asynchronous execution.

**Comment by thebestclass** [comment]
@cboden 

It's been a while and there are no answers.

Well, I read and re-read the article you gave me, though I can not understand how I apply MySQL with the React Child Process, you could me explain a little more or show me some sample code so I can find my way around?

**Comment by thebestclass** [comment]
@cboden  Its something like this?


$loop = React\EventLoop\Factory::create();
$process = new React\ChildProcess\Process(false);

$loop->addTimer(0.001, function($timer) use ($process) {
    $loop = $timer->getLoop();

    $process->on('exit', function($output) use ($loop) {
        $loop->stop();
    });

    $process->start($loop);

    $process->stdout->on('data', function($output) {
       echo $output->num_rows;
    });

        $process->stdin->write($db->query('SELECT * FROM `users`'));

});
$loop->run();

**Comment by kinncj** [comment]
https://github.com/bixuehujin/reactphp-mysql/blob/master/examples/query-with-callback.php
