### ISSUE TITLE
Infinite loop function for updates

### ISSUE THREAD

**Issue by thebestclass** [ratchetphp/Ratchet#371]
is there any way to run code within the server to function as the javascript SetInterval.

so the server can perform functions automatically...

**Comment by Isty001** [comment]
If you use the construct of the IoServer instead of the factory, you can pass anything to your server, including the React loop, and you can use it's timer. 
http://blog.wyrihaximus.net/2015/01/reactphp-timers/

**Comment by thebestclass** [comment]
@Isty001  Using React Timers, it could work as same the setInterval of javascript?
