### ISSUE TITLE
php 5.4 required

### ISSUE THREAD

**Issue by beardedgeek** [ratchetphp/Ratchet#375]
Hi.

Am I right in thinking the minimum PHP version needs to be upped to 5.4 due to react/event-loop/StreamSelectLoop.php defining array's using the new shorthand method of square brackets. It might be in other places too, but this is the first insance of the error I've seen so far so should already be enough to require upping it.

    private $readStreams = [];
    private $readListeners = [];
    private $writeStreams = [];
    private $writeListeners = [];

**Comment by cboden** [comment]
The current version of most React libs (0.4.*) require 5.4. However the API hasn't changed much from 0.3 so [this line](https://github.com/ratchetphp/Ratchet/blob/master/composer.json#L27) will figure out which version is needed based on the installed PHP version. This [Travis build](https://travis-ci.org/ratchetphp/Ratchet/jobs/80591437) also shows Ratchet running on 5.3
