### ISSUE TITLE
ERR_CONNECTION_REFUSED with reactTimers

### ISSUE THREAD

**Issue by thebestclass** [ratchetphp/Ratchet#378]
I put this code in the __construct of the class that handles connections and now I can not connect to my server, returns **ERR_CONNECTION_REFUSED**

    use React\EventLoop\Factory; 
    ....
    protected $loop;

    public function __construct() {
        $this->loop = Factory::create();

        $this->loop->addPeriodicTimer(600, function() {
            return $this->functionLoop();
        });

        $this->loop->run();
    }

why?

**Comment by cboden** [comment]
Your application can only have 1 event loop running. Pass the existing event loop in your constructor instead of creating a new one.

**Comment by thebestclass** [comment]
@cboden and where I put it? Where is this existing loop? You can exemplify me?

**Comment by thebestclass** [comment]
@cboden  

but it is already inside the constructor...

You can exemplify me?

My code:

$server = IoServer::factory(
        new HttpServer(
            new OriginCheck (
                new WsServer(
                   $classc
                ), 
                array('127.0.0.1')
            )
        ),
    8080,
);

**Comment by thebestclass** [comment]
@cboden thanks, i changed the constructor and all is worked
