### ISSUE TITLE
Set Realtime WebSocket Buffer

### ISSUE THREAD

**Issue by dansari88** [ratchetphp/Ratchet#379]
I am working on a realtime multiplayer game which was built using Ratchet 0.3.3, Laravel 5 and PHP 5.5.9, The server OS is Ubuntu. The server sends approximately 500 bytes of data in each cycle to every user via WebSocket (hundreds of users).
It looks like WebSocket is buffering the requests and sends 5 to 6 requests at once (500 bytes each). 
We have 30 millisecond cycles.  Is there a way to manually set the WebSocket buffer settings so I can send each request in every cycle?

**Comment by mbonneau** [comment]
Hi @dansari88 ,

I have not had a chance to really look at the issue too hard - but thought you may be able to try:
```php
socket_set_option(socket_import_stream($stream->stream), SOL_TCP, TCP_NODELAY, true);
```

**Comment by cboden** [comment]
This buffering is happening at the TCP level, not the WebSocket level and is therefore outside the scope of Ratchet. @mbonneau is correct on the correct function use on the socket however. :)  These kind of issues are more targeted towards React.
