### ISSUE TITLE
Insertion of ResourceID does not occur 

### ISSUE THREAD

**Issue by thebestclass** [ratchetphp/Ratchet#380]
I'm trying to insert the $conn->ResourceID through another class but can not in any way, however giving echo operate normally, why?

Example

    public function onOpen(ConnectionInterface $conn) {
        $this->MyOtherClassDefinedInConstructor->save($conn);
   }

in the other class:

      public function save($conn) {
        echo $conn->ResourceID; // works
          $this->db->query("INSERT INTO `x` (`socket`) VALUES ('". $conn->resourceID."');"); // dont works

why??

**Comment by cboden** [comment]
Should be `resourceId`

**Comment by thebestclass** [comment]
@cboden the original code is as resourceID .. this problem does not make sense ...

**Comment by cboden** [comment]
https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Server/IoServer.php#L96

**Comment by thebestclass** [comment]
@cboden The resource ID does not work for me, I do not know if it's because I use a ReactLoop on the server or why instantiate a class through the constructor ... I'm frustrated.

Is there any problem if I reset the resourceID for each connection? using my criteria to specify the number (such as first-come ...)

**Comment by cboden** [comment]
The "d" in `resourceId` should be lower case.

**Comment by thebestclass** [comment]
pretend i didn't create this topic please
