### ISSUE TITLE
How to handle events that may block

### ISSUE THREAD

**Issue by elaine342** [ratchetphp/Ratchet#381]
I am using Ratchet order to create an asynchronous server for PHP, however there are many functions that block, how can I do to use these functions to occur without these locks?

Is there any library that do this and get callback function or something? I completely lost

Please show me examples, you speak in a complicated way that makes me crazy ..

**Comment by thebestclass** [comment]
good question, anyone?

**Comment by mbonneau** [comment]
Can you give a specific example of something that you are trying to do that is blocking?

**Comment by elaine342** [comment]
@mbonneau  yes, mysql, cURL, aes encrypt, rsa encrypt etc..

**Comment by cboden** [comment]
I would recommend using the [React ChildProcess](https://github.com/reactphp/child-process) library to offload any processes that are blocking. The parent application would control any children. I/O between is async but the sync tasks in the child do not block the parent.
