### ISSUE TITLE
Possible spec compatible way to allow out of spec tweaks to protocol for approving subscriptions

### ISSUE THREAD

**Issue by BrettTrotter** [ratchetphp/Ratchet#384]
I'm new to WebSockets and Ratchet. I created an issue yesterday to ask about ways of approving/denying subscriptions rather than just adding them. I closed the ticket once I understood why you didn't pursue this originally.

I found that things didn't work well and that there wasn't enough exposed members to do what I wanted to do using it with a modified version of autobahn. 

Rather than creating a pull request, I'll just post a link to the commit in my fork as an example. Long story short, it would be a breaking change in that people would need to create a method and rename another, but it would still work normally with WAMPv1 while allowing for out of spec modifications.

The conversion to stay in spec would be to rename your onSubscribe to onSubscribeApprove, create an onSubscribeRequest that just returns true, and create an onSubscribeDecline that does nothing.

Anyway, I hate to fork things but I don't want to be the "gimme stuff for free" sort of guy either. So, I'm just putting this here in case you might consider it. I saw some comments that you'd tried the same thing and not pursued it since Autobahn was already out.

If you're interested, great, and if not, I completely understand.

So here goes:
https://github.com/BrettTrotter/Ratchet/commit/5f3182324e7b99c13ba429f97330d989532b1769

**Comment by cboden** [comment]
Thanks for sharing this! A better place to post would be the message boards as I like to keep the GitHub issues curated only leaving un-resolved problems open. 

I do believe your code could be made into a component and standalone library that could work with Ratchet instead of forking and altering the project.
