### ISSUE TITLE
Is there a way to start the rachet server without having to keep an open console window?

### ISSUE THREAD

**Issue by KTrentLR** [ratchetphp/Ratchet#386]
Is there a way to start the rachet server without having to keep an open console window?

I am not the server admin for my server,  I am only the developer. The admins do not want to have to keep or manage an open window on the server to keep the ratchet server running.  Is there a way to to start my ratchet server without having to open or keep a console window open?

**Comment by kinncj** [comment]
I guess the admins have knowledge to daemonize it or at least use `nohup` ?

Try Googling for `daemonizing process` or `nohup` as it would give you a bunch of cool info.

**Comment by mikealmond** [comment]
The docs recommend using Supervisor to monitor the process. You can read about that here http://socketo.me/docs/deploy#supervisor
