### ISSUE TITLE
SSH port listening issue

### ISSUE THREAD

**Issue by rc135791** [ratchetphp/Ratchet#391]
Hello Guys,

I am using example from "http://socketo.me/docs/hello-world". After installing everything and copying all files in folders. When executing "php bin/chat-server.php" in SHELL commandline it doesn't displays message regarding listening of port. And after sometime I need to exit via "CTRL+Z".

How can I make the port listening? All files are properly copied and installed as earlier I was getting error regarding "MyApp/Chat" missing but fixed by copying it to "src" directly.

Any help will be highly appreciated. Thank you!

**Comment by philippfrenzel** [comment]
i think somewhere it says ssh is not supported yet, you need to use an stunnel proxy e.g.

**Comment by rc135791** [comment]
Thank you Philipp for your reply! Do I need to ask hosting to create stunnel proxy?

**Comment by philippfrenzel** [comment]
I don't know how your host works, but you need a network professional to setup a ssl tunnel to your websocket port. On managed hosts this sometimes can be "difficult" - but hope you'll make it;)

**Comment by rc135791** [comment]
Thank you for your help! There is one more query please if you have successfully made connection in past via Rachet.

"On a test.php page I have added following code:
var conn = new WebSocket('wss://mysite.com:8080');
conn.onopen = function(e) {
    console.log("Connection established!");
};

conn.onmessage = function(e) {
    console.log(e.data);
};

In console log I am getting error (Firefox can't establish a connection to the server at wss://mysite.com:3000/)
"

Thank you for your help Phillip. :)

**Comment by cboden** [comment]
Your code shows you're trying to connect to port 8080 but the error message says port 3000. Have you setup your STunnel proxy? Which port is it listening on and have you ensured it's connecting to the Ratchet instance accordingly?

**Comment by rc135791** [comment]
Thanks Cboden for your reply! 

Sorry port number was written wrong above. It is "wss://mysite.com:3000" instead of "wss://mysite.com:8080".

I have asked hosting provide to check if any firewall is there on port 3000 and they have removed firewalls from port 3000. But error is still there "Firefox can't establish a connection to the server at wss://mysite.com:3000/"

**Comment by rc135791** [comment]
Got it fixed. It was firewall issue. Working fine. 

Thank you Cboden, Phillip for looking into matter. :) <3
