### ISSUE TITLE
No remote connection to Ratchet/Websocket possible

### ISSUE THREAD

**Issue by Damokles84** [ratchetphp/Ratchet#394]
Hi there,

currently I'm working on an application which is supposed to push tickets to a JavaScript-Client/Browser.  If browser and WebSocket-Service reside on the same machine, all works well!

But if I deploy the Service onto a remote Server (running on Fedora with Apache/httpd), my Browser can't connect to the Websocket. I configured the firewall to open up port 8080 and no other process is listening on this port!

The relevant code section looks like this:

`$ratchetApp = new Ratchet\App('koda-cs-vm-dw', 8080, '192.168.230.116', $loop);
$ratchetApp->route('/koda-webSocketServer', $KoDAWSS_Ratchet, ["*"]);`

"koda-cs-vm-dw" is the host, where the Websocket-Service resides.
192.168.230.116 is the current IP-address of the server.
"/koda-webSocketServer" is the endpoint, where the browser should connect to.

I also tried setting the third parameter of App() to "0.0.0.0" but without any success. 

Any advice is greatly appreciated!

Regards,
Dominik

EDIT: When I try to access the Websocket with Chrome, the debug-console shows:

`WebSocket connection to 'ws://koda-cs-vm-dw.xbreuer.local:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

**Comment by cboden** [comment]
The third parameter should be `0.0.0.0` if you're not behind a proxy such as Nginx. 

The first step in troubleshooting is attempt to connect at the TCP level with something such as `telnet domain-name.com 8080`. The domain you're attempting to connect to doesn't look like a FQDN.

**Comment by Damokles84** [comment]
Hi,

I tried to connect to my server with putty, the connection timed out. I also tried to change the first parameter of Ratchet\App() to a FQDN and then to the corresponding ip-address, with the same result: the connection times out!

**Comment by cboden** [comment]
This sounds like a firewall issue. Try setting up this simple echo server:
```
mkfifo
cat fifo | nc -k -l domain-name.com 8080 -v | cat > fifo
```

The connecting to it via telnet:
`telnet domain-name.com 8080
Hello World!
```

You should connect and get an echo back of what you sent...if not you have something in your network blocking connections.

**Comment by Damokles84** [comment]
Same result as before, the connection times out :(

**Comment by cboden** [comment]
You have a firewall or some security policy blocking

**Comment by Damokles84** [comment]
I also tried it with the firewall on both systems down.

**Comment by cboden** [comment]
Is your server setup to accept the domain name you're trying to connect to it as?

**Comment by Damokles84** [comment]
Any advice on how to do that? Since I use Windows most of the time.

**Comment by cboden** [comment]
I wouldn't know where to start...depends on your OS, its configuration, your host (i.e. AWS has security groups and blocks ports by default), etc.

**Comment by Damokles84** [comment]
Since the server runs in a local VM, I guess changing /etc/hostname could do the trick?

**Comment by cboden** [comment]
Maybe? I'm not sure given I don't know how/what you've set up. In my env I use VirtualBox so there's some NAT config needed, but I let Vagrant handle that kind of stuff for me.

**Comment by grey-dev-0** [comment]
I've just faced this issue today, and as @cboden has mentioned it's a firewall issue but not on destination side - where ratchet is running - but, on source side - where nginx proxy is passing the request.
I didn't find this myself though, it took me a couple of hours and an extra hand to find it, so make sure that the ports you're using to connect to websocket on nginx side are open in both directions - outbound and inbound.
