### ISSUE TITLE
How to pass data securely?

### ISSUE THREAD

**Issue by TheMiller2015** [ratchetphp/Ratchet#395]
Hello, I need some help. I want to achieve, that a user creates a socket connection and the ws-server knows its user-id. Then the ws-server subscribes the "user" to all channels he has access to (all his groups and friends). I want to avoid, that the user sends all the ids over js to ws-server while connecting. This data can be manipulated. So my architecure looks like this now:

Client(https) -> HAProxy -> php | ratchtet | redis (for storing session data)

I know that redis can't read php session data. I'm using cakephp. What are my options to let the ws-server securly know some user-identifing-data. All data sent via js can be manipulated, can't be?

Thanks in adavce!

**Comment by cboden** [comment]
When a connection is made if the domain from your sync stack as your WebSocket server it will pass the cookies, including the session ID. You can access this cookie via the HTTP headers passed `$conn->WebSocket->request->getCookies()`. 

From there you can use [predis-async](https://github.com/nrk/predis-async) or [php-redis-react](https://github.com/clue/php-redis-react) to asynchronously access Redis querying with the session id from the users cookies.

**Comment by TheMiller2015** [comment]
Hey! Sorry, I didn't recognize your answer. Thanks for that. This is exactly how I implemented my stack. Great work and great help. Thanks@all

**Comment by junaidkhan89** [comment]
Hi!
is there any way to run socket wamp server with 4 ports 2 is secure and 2 is non-secure
