### ISSUE TITLE
need to update dependency for guzzle

### ISSUE THREAD

**Issue by zoomcrypt** [ratchetphp/Ratchet#396]
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by davidwdan** [comment]
This is a duplicate.  See https://github.com/ratchetphp/Ratchet/issues/373
