### ISSUE TITLE
Minimal Example on Windows failing

### ISSUE THREAD

**Issue by johannes-z** [ratchetphp/Ratchet#398]
Just tried the minimal chat example from the homepage on a Windows 10 x64 with PHP 5.6.13.
Upon execution of the WS server I get:
```
PHP Warning:  stream_select(): unable to select [2]: No such file or directory (max_fd=272) in C:\Users\<DIR>\vendor\react\event-loop\StreamSelectLoop.php on line 255

Warning: stream_select(): unable to select [2]: No such file or directory (max_fd=272) in C:\Users\<DIR>\vendor\react\event-loop\StreamSelectLoop.php on line 255
```
It works fine on linux though. I did use the exact same code on Windows 8 some time ago though and back then it worked just fine. Is there some requirement or configuration I'm missing?
I did a quick search on the matter, but they lack an answer:
#327 and https://groups.google.com/forum/#!topic/ratchet-php/KyWvtK-JIVY

**Comment by cboden** [comment]
Looks like your script has reached the maximum open file descriptor limit. Each connection opens a new file descriptor. You either need to make sure clients are properly disconnecting, and probably increase your limit as 272 is incredibly tiny for a server.

**Comment by johannes-z** [comment]
Those warnings are immediately thrown when executing the script (and also each time a client is connecting). So based on what you're saying I'm assuming the maximum of file descriptors is already reached when I start the server. 
I'm not sure on how to change the fd limit on windows... seems like MS changed it from Windows 8 to Windows 10 - or I'm missing something obvious here. If no further comments are added I'm going to close this, since it doesn't seem to be an issue with Ratchet.
