### ISSUE TITLE
Long tasks in onMessage

### ISSUE THREAD

**Issue by dragonnn** [ratchetphp/Ratchet#399]
Hi!
I have a question - I am running some long tasks in onMessage with can take up to ~5s and I am not sure if this tasks will lock the server for this time to respond to other messages.
As far I know Ratchet is event based, so that schould be not a problem, I am right?

**Comment by cboden** [comment]
While Ratchet is evented and its I/O is async anything you do to consume the CPU will block the events from happening as they share the same thread.

**Comment by RogerWaters** [comment]
Hi,
at this point you can ether wait or use any threading component to keep the server responsive. Depending on the number of users this can be a problem or not. If you have 10 messages on the loop each 5 seconds running. The server is not responding for 50 seconds.

**Comment by dragonnn** [comment]
Ok, I understand. Will default Threads from PHP works fine? I need to send a msg back to the client when this task finishes from that thread, passing to the thread the from object will work?

**Comment by RogerWaters** [comment]
I don't known what you mean with default threads. I setup an experimental thread component here https://github.com/RogerWaters/react-thread-pool its work in progress and has for sure some bugs but is designed to work with react. You can create a thread and get a callback left if work is done. Then you can send the message left to the client. See example 3.

Pthreads ( https://github.com/krakjoe/pthreads ) can also be a solution but I didn't get it to work stable with loop.

**Comment by dragonnn** [comment]
Yes, I have by thinking about pthreads, what do you mean not stable loop? Did you run PHP7 or PHP5?

**Comment by RogerWaters** [comment]
Tried with PHP5.5 and 5.6 using libevent. Every handler registered to the loop in the thread is executed in the main process as there is the loop->run(). Also pthreads has removed condition and mutex so the interaction between threads is limited. The new monitor function is implemented in the base library but currently not in the php wrapper. Also we use some more libraries like inotify that results in segfault in some cases. Another propblem is that pthread convert every array exchanged into Threaded so you have to copy and convert between array and Threaded multiple times depending on your environment.

If it fits your needs its for sure the best solution but for me it's not as flexible and stable as required.
