### ISSUE TITLE
WAMP 2.0 no supported

### ISSUE THREAD

**Issue by saidmoya12** [ratchetphp/Ratchet#402]
The wamp socket 2.0 no is supported so the example no work.

Some idea to fix this problem

Thanks

**Comment by cboden** [comment]
Ratchet supports v1 of the WAMP protocol which is compatible with Autobahn.js version 0.8.*. If you want to use WAMPv2 check out [Thruway](https://github.com/voryx/Thruway)

**Comment by TheMiller2015** [comment]
Hello @cboden ! Thanks for this hint. Just read about it. One question. Thruway is "just" a client and router. Does this mean, the websocket-server is set up with ratchet and only the connection to it is done via thruway? If not, which websocket-server has to be used with thruway? (Sorry I don't wanted to post this question on both repos. But while I'm using ratchet right now and also posted here in the past, I decided to ask this question here.)

Thanks

**Comment by mbonneau** [comment]
Hi @TheMiller2015 ,

A websocket server is not necessarily called a router. "Router" is a term that the WAMP2 protocol uses. The Thruway router does have a websocket server built into it (which is Ratchet) that is used to talk WAMP2.

WAMP2 systems are built with a router that allows the clients to offer services (through RPC) and the ability to publish and subscribe. The application logic resides mostly in the clients themselves - whether it is a browser that is calling RPCs or backend client that is providing an RPC.

Different WAMP2 components can be used together (Thruway, crossbar, autobahn, etc.) to build distributed systems out of application components which are loosely coupled and communicate in (soft) real-time.

**Comment by TheMiller2015** [comment]
hey. Thanks for your great answer. I read the docs of crossbar and your answer. Things became clearer now. And I also do have my first ws-connection (within the new setup). 

Thanks.
