### ISSUE TITLE
Connection to the database

### ISSUE THREAD

**Issue by QuinLena15** [ratchetphp/Ratchet#405]
Hello! There is a problem. Terminates connection to the database over time. What could be the reason?

File server.php

```php
<?php
require __DIR__ . '/../vendor/autoload.php';
use Chat\Chat;
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use React\EventLoop\LoopInterface;
use React\EventLoop\Factory as LoopFactory;
 use React\Socket\Server as Reactor;
$loop = LoopFactory::create();
$socket = new Reactor($loop);
$socket->listen(8991,'****');

$server = new IoServer(new HttpServer(new WsServer(new Chat($loop))), $socket, $loop);
$server->run();
?>
```

**Comment by cboden** [comment]
I'm not quite sure what you're asking. I don't see a database connection here.

**Comment by WyriHaximus** [comment]
Database connections timeout after some time of inactivity. Also my guess if you use a regular blocking connection.

There are a few ways to solve this:
* Use redis as database with [predis async](https://github.com/nrk/predis-async) or [Async Redis client](https://github.com/clue/php-redis-react)
* Use an async SQL client [MySQL ](https://github.com/bixuehujin/reactphp-mysql) or [PostGres](https://github.com/voryx/PgAsync)
* Use [child processes](https://github.com/reactphp/child-process), to wrap the connecting in on, either direct or take a look at my [pooling package](https://github.com/wyrihaximus/reactphp-child-process-pool/)

**Comment by jurasm2** [comment]
You can check, if your connection is active. If not, create a new connection.
E.g. in doctrine you can write:
```php
<?php
$conn = $this->em->getConnection();
if ($conn->ping() === false) {
    $conn->close();
    $conn->connect();
}
```

**Comment by QuinLena15** [comment]
In Chat.php do:

**Comment by QuinLena15** [comment]
After some time, the connection is broken. Can the $ this-> loop-> addPeriodicTimer (300, function () {}) to check the connection?

**Comment by ProPheT777** [comment]
Yes, I currently use that to prevent server gone.

https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Periodic/PdoPeriodicPing.php

You can also use a permanent connection.
