### ISSUE TITLE
failed to run  the example server_ssl.php 

### ISSUE THREAD

**Issue by samchen123** [ratchetphp/Ratchet#406]
Hi all:
I am trying to run the server_ssl.php in the example dir
but I got the following message.
Fatal error: require(): Failed opening required '/home/demo/Wrench-master/examples/../../vendor/autoload.php' (include_path='.:/opt/php/lib/php') in /home/demo/Wrench-master/examples/server_ssl.php on line 16

Could anyone tell me how the solve the problem.?
where is the autoload.php.......
I really can not find it

Thank you very much...

**Comment by cboden** [comment]
I think you opened this in the wrong project
