### ISSUE TITLE
Ratchet Websocket working on local but not in server

### ISSUE THREAD

**Issue by jitendra456** [ratchetphp/Ratchet#408]
#Hi , I am using Ratchet in my project. It is work completely in my local pc but not in my live server.
I have set ip address of my site and use 8080 port. Can I use 127.0.0.1 instead of my site's ip or host name.
Can some one help me?
Thanks in advance.

**Comment by cboden** [comment]
See Q/A 4 on the [Troubleshooting](http://socketo.me/docs/troubleshooting) page.

**Comment by jitendra456** [comment]
I have already read this but  i can not understand.
  $pull->bind('tcp://127.0.0.1:5555'); 
 $socket->connect("tcp://localhost:5555");
var conn = new ab.Session('ws://localhost:8080');

Should i use my site's ip address instead of 127.0.0.1/localhost?
Thanks

**Comment by geggleto** [comment]
you should be using the IP of your server in your client... otherwise its going to try and connect to itself. Also why are you changing your ports?

**Comment by jitendra456** [comment]
I am using 8080 port for web socket.Can i use  80 port in web socket?

Thanks

**Comment by kadnan** [comment]
@geggleto How can I change default host in this code?

```
$server = IoServer::factory(
    new HttpServer(
        new WsServer(
            new Chat()
        )
    ),
    8080
);
```

**Comment by geggleto** [comment]
@kadnan that is your server. On your client you must specify the hostname or IP address of your server.
ie. myserver.mydomain.com ==> x.x.x.x

Then in your web client.
`
var conn = new WebSocket('ws://x.x.x.x:8080');
//OR
var conn = new WebSocket('ws://myserver.mydomain.com:8080');
`

**Comment by kadnan** [comment]
@geggleto So I don't need to bind IP at server end? whatever I mention at client end, it would work?

**Comment by geggleto** [comment]
@kadnan yep. I am sure there is a way to bind it at the server end but i haven't seen any examples.
