### ISSUE TITLE
Patch for V0.4

### ISSUE THREAD

**Issue by Kurairaito** [ratchetphp/Ratchet#411]
dear,

Here is a patch to fix a crash when a connection is openned and keepAlive is requested

> Notice: Undefined variable: from in C:\xampp\htdocs\x1601\api\vendor\cboden\ratchet\src\Ratchet\WebSocket\WsServer.php on line 214
> 
> Warning: SplObjectStorage::offsetGet() expects parameter 1 to be object, null given in C:\xampp\htdocs\x1601\api\vendor\cboden\ratchet\src\Ratchet\WebSocket\WsServer.php on line 214
> 
> Notice: Trying to get property of non-object in C:\xampp\htdocs\x1601\api\vendor\cboden\ratchet\src\Ratchet\WebSocket\WsServer.php on line 214
> 
> Fatal error: Call to a member function send() on null in C:\xampp\htdocs\x1601\api\vendor\cboden\ratchet\src\Ratchet\WebSocket\WsServer.php on line 216

Patch removed, see pull request : https://github.com/ratchetphp/Ratchet/pull/413

**Comment by Nek-** [comment]
Hello, you should use the pull request systm for your patch :) .

**Comment by Kurairaito** [comment]
Yeah, but I couldn't find a way to do it. I commited in local but then
couldn't push or create a pull request (I think I must push before do that)
, so I just put the patch as text here...  I also put another patch in RFC
dependencie that fix connexion refused from Firefox.

**Comment by philippfrenzel** [comment]
You can change the code online and github will create a pull request for you ;)

**Comment by Nek-** [comment]
@Kurairaito the workflow is to create a fork, make a branch, then a PR to the main project !

**Comment by Kurairaito** [comment]
Done, I hope I did it well. I didn't know this side of github thanks.

**Comment by cboden** [comment]
Merged in RFC6455 library
