### ISSUE TITLE
[0.4] drop support of PHP 5.4 ?

### ISSUE THREAD

**Issue by Nek-** [ratchetphp/Ratchet#412]
Is there any good reason to keep PHP 5.4 ? It's a release with bugfix only while PHP7 is on the rails.

As soon as ratchet 0.4 will be release, it will be deprecated, releasing a tool that allow deprecated usage is not so awesome... Especially when it can bother you because of missing features.

**Comment by cboden** [comment]
Not everyone is on PHP7 yet and that will take time. There are a lot of changes in 0.4 and I don't want to leave many developers stranded just for the sake of pushing 7. I could bump the version to 5.5 or maybe 5.6 but since none of the new language features in those versions are being used I don't see the point.

**Comment by Nek-** [comment]
I understand that support for PHP7 too early. My point is on bumping to 5.5.

This version number is motivated by the Symfony 3.0 php version support. Also as PHP 5.5 is far to not be supported anymore it's legit to me to make this choice.

Of course if it's a problem in any way and 5.6 features are needed, better go directly with 5.6. But well, IMO 5.5 is enough for next release of ratchet.

A bit out of topic. But why ratchet does not follow [semver](http://semver.org/) ?

**Comment by cboden** [comment]
I'll take a look and consider 5.5 as a requirement, but again, as none of the language features are used I don't see the value in forcing someone who might be stuck on 5.4 for what ever reason. 

Ratchet does follow semver, see [this comment](https://github.com/ratchetphp/Ratchet/pull/347#issuecomment-204556690)
