### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by semiromid** [ratchetphp/Ratchet#414]
http://socketo.me/docs/hello-world

I testing (good work):
```
Running It ¶
Complete, let's run it and test it. Open up three terminal windows, typing:

$ php bin/chat-server.php
$ telnet localhost 8080
$ telnet localhost 8080
In each of the telnet windows, type a message ("Hello World!") and see it appear in the other!
```

I try (not working)
```
var conn = new WebSocket('ws://localhost:8080');
conn.onopen = function(e) {
    console.log("Connection established!");
};

conn.onmessage = function(e) {
    console.log(e.data);
};
```

`WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 400`

Why not worked?

**Comment by semiromid** [comment]
http://ru.stackoverflow.com/questions/512116/%D0%9A%D0%B0%D0%BA-%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE-%D0%BE%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%BB%D0%B8%D1%82%D1%8C-%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D1%81%D0%B2%D1%8F%D0%B7%D1%8C-%D1%81-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BE%D0%BC-websocket

**Comment by cboden** [comment]
Did you remember to add `HttpServer` and `WsServer` instances between `IoServer` and your application after testing through telnet?

**Comment by cboden** [comment]
400 is an issue with the initial handshake. All validation is done by [verifyAll](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/Version/RFC6455/HandshakeVerifier.php#L16) which means your client attempting to connect was failing one of those conditions.
