### ISSUE TITLE
Switch to guzzle/guzzle ?

### ISSUE THREAD

**Issue by half2me** [ratchetphp/Ratchet#415]
Is there any reason why the switch has not been made yet?

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by WyriHaximus** [comment]
FYI: https://github.com/ratchetphp/Ratchet/search?q=abandoned&type=Issues&utf8=%E2%9C%93

**Comment by half2me** [comment]
@WyriHaximus should've checked first :) Sorry...

**Comment by WyriHaximus** [comment]
It happens, :+1: for taking the time to report :)
