### ISSUE TITLE
What is the correct way to respond with a 404?

### ISSUE THREAD

**Issue by 0plus1** [ratchetphp/Ratchet#416]
In my onOpen, I want to do some checks and in case something is not right return a 404 or 403.

What is the correct way to achieve this in Ratchet? I see that Exceptions bubble and are caught in the onError method.

Thank you very much

**Comment by cboden** [comment]
404 and 403 are HTTP response codes. I'll make the assumption you're following the tutorial and by the time your app has received the onOpen Ratchet has already done an HTTP response. 

So, one way to achieve this is by creating a new middleware class that implements [HttpServerInterface](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Http/HttpServerInterface.php) that can make the decision to respond to the HTTP request before `WsServer` completes the WebSocket handshake. You can see an example of this in the [Router](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Http/Router.php#L39) class. 

Alternatively, you could follow the example in the README which uses the `App` class to handle routing. I plan on adding documentation to App on the website in the near future.
