### ISSUE TITLE
Websockets apps sending messages to each other

### ISSUE THREAD

**Issue by krekk4** [ratchetphp/Ratchet#418]
Hello, I have two apps running on one websocket server and I want to send one app messages to another. How can I achieve this? I need something like this: there is a game table and lobby, when someone leaves game I want onClose event to send message to lobby that someone left and update lobby. Like there were players 3/4 one left and lobby updated players 2/4. Is it possible or I should integrate it another way? Like having game tables on same app instance as lobby.

**Comment by dustingraham** [comment]
Check out the sister project [Pawl](https://github.com/ratchetphp/Pawl). What you're looking for is a client in addition to a server. The client connects to the server to communicate.

While Websockets are great tools for this, you might also want to check out Pub/Sub architectures. What you are describing sort of fits the entire purpose of that pattern better.

This looks like a pretty good article [using Redis](https://xmeng.wordpress.com/2011/11/14/pubsub-in-redis-using-php/) but search around for message queues and pub/sub.

**Comment by krekk4** [comment]
Thank you very much!!! [https://github.com/ratchetphp/Pawl](url) works nicely, exactly what I needed.
