### ISSUE TITLE
Get header value in "onOpen" function.

### ISSUE THREAD

**Issue by ali-abbas-29** [ratchetphp/Ratchet#422]
Client is sending values in header while handshaking.
I want to receive those value in "onOpen" function of "Chat.php". (as in example) 
Can you please tell me how to do that?
Thanks.

**Comment by johannes-z** [comment]
`public function onOpen(ConnectionInterface $conn)`
you can then access the request object by:
`$conn->WebSocket->request`
from there on you get access to the header, cookies, etc.

**Comment by ali-abbas-29** [comment]
PHP Notice:  Undefined property: Ratchet\Server\IoConnection::$WebSocket in C:\x
ampp\htdocs\NearPeople\socket\NearChat.php on line 18

Notice: Undefined property: Ratchet\Server\IoConnection::$WebSocket in C:\xampp\
htdocs\NearPeople\socket\NearChat.php on line 18
PHP Notice:  Trying to get property of non-object in C:\xampp\htdocs\NearPeople\
socket\NearChat.php on line 18

Notice: Trying to get property of non-object in C:\xampp\htdocs\NearPeople\socke
t\NearChat.php on line 18
NULL<br/>onOpen: 30onMessage: 30 || msg: GET / HTTP/1.1
Host: 192.168.9.156:8080
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 1a5YB/+iy69hqVakoQHqDQ==

PHP Notice:  Trying to get property of non-object in C:\xampp\htdocs\NearPeople\
socket\Parser.php on line 13

Notice: Trying to get property of non-object in C:\xampp\htdocs\NearPeople\socke
t\Parser.php on line 13

Its giving me this error.

**Comment by cboden** [comment]
Can you post some source to assist in troubleshooting please?

**Comment by 2f-concept** [comment]
I looked for a good time the solution, and I ended up finding. If it can help someone, I'll post it here:
```
public function onOpen(ConnectionInterface $conn) {        
        $headers = $conn->httpRequest->getHeaders();
        // ...
}
```

**Comment by Tofandel** [comment]
None of the solutions work for me.. httpRequest and WebSocket are null.. :(

It's behind a nginx proxy, don't know if it has anything to do with it

**Comment by faryar76** [comment]
> I looked for a good time the solution, and I ended up finding. If it can help someone, I'll post it here:
> 
> ```
> public function onOpen(ConnectionInterface $conn) {        
>         $headers = $conn->httpRequest->getHeaders();
>         // ...
> }
> ```

its actually on "Ratchet\WebSocket\WsServer" line 112

**Comment by hayden-t** [comment]
whats the best way to parse the cookies ?
`$cookies = $conn->httpRequest->getHeader('Cookie');`
