### ISSUE TITLE
WebSocket connection to 'ws://localhost:1337/' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1

### ISSUE THREAD

**Issue by consigliere23** [ratchetphp/Ratchet#423]
What about this? 
Everything worked and it suddenly appeared as error?

**Comment by henryoswald** [comment]
Are you on windows?

**Comment by cboden** [comment]
That is a protocol error. It most likely means the client attempting to connect did something it wasn't supposed to be doing.

**Comment by consigliere23** [comment]
Yes I am on Windows. The problem is in Chrome and FF. But on the another win 7 laptop sockets are working normaly. What is the issue here and is there anything to do in order to solve? I also tried with disabling antivirus but it did not help.

@cboden who is doing that and what is not supposed to be done?

**Comment by henryoswald** [comment]
I am not involved in Ratchet at all but we have started seeing some websocket issues on windows in the past couple of days. We use Socket.io on node so very different tech stack.

**Comment by consigliere23** [comment]
Ok, but how did you fix this issue? Is this some general problem with windows or maybe with latests udpates in chrome and FF?

**Comment by consigliere23** [comment]
Can anyone assists me with this? I am using Autobahn|JS, on android everything is working as it should be. What can be the cause? I do not know is the problem on back-end of php ratchet or in JS or maybe something else? I am using push integration.

**Comment by mwsv** [comment]
I'm facing exactly the same problem using Ratchet/Autobahn.js throuth the [,](https://github.com/GeniusesOfSymfony/WebSocketBundle) I tested my project on more than 10 workstations with Windows and the problem occured on three of them, in all of main browsers (Opera, Chrome, FF, IE) in these cases. I don't see the problem on Ubuntu machines too. It's really hard to guess how to fix it, so thanks for any help to resolve this weird issue.

**Comment by dmitriyGarden** [comment]
This error is also in official demo page. [https://monosnap.com/file/GDN0cLOVTjT0EJVDNlBOyP8dPTpk6E](url)

**Comment by consigliere23** [comment]
This URL is broken :(

**Comment by dmitriyGarden** [comment]
Sorry. New screenshot http://take.ms/LaKmJ

**Comment by consigliere23** [comment]
I can see now thanks, but as I can see there is still no patch for this :(

**Comment by dmitriyGarden** [comment]
I'm too have issues with WebSocket last days. And try find resolve

**Comment by dmitriyGarden** [comment]
Another site, another tech, but similar problem http://take.ms/QOVFl

**Comment by dmitriyGarden** [comment]
I have idea. I seen trouble with protocol ws://  but protocol wss:// work correct. For example http://websocketstest.com/

**Comment by mwsv** [comment]
I have the same problem with wss:// protocol too.

**Comment by jeremy-saidani** [comment]
Hi guys !
Same problem for me, but I just find something : 
https://forum.eset.com/topic/8355-protocol-filtering-breaks-websockets-after-update-at-5052016/
Works for me !

**Comment by consigliere23** [comment]
So, all this is due to ESET NOD32 Antivirus recent update?

**Comment by jeremy-saidani** [comment]
If NOD32 is installing on your computer yes. It's works for me.
Is it working for you ?

**Comment by consigliere23** [comment]
Yes, I have NOD32. 
I added IP addresses in exclude list and it works.

**Comment by jeremy-saidani** [comment]
I did the same !
Hope the next update of NOD32 will fixe this ...

**Comment by dmitriyGarden** [comment]
I  resolved  the trouble with WebSockets. Use wss:// instead ws:// and proxy through nginx.
