### ISSUE TITLE
Notice: Undefined property: Ratchet\Server\IoConnection::$XXXX

### ISSUE THREAD

**Issue by kadnan** [ratchetphp/Ratchet#424]
My Code is working fine locally. On remote server when sending data from local browser it generates notice as:

```
Notice: Undefined property: Ratchet\Server\IoConnection::$XXXX in /home/xx/server/xx/Server/vendor/cboden/ratchet/src/Ratchet/AbstractConnectionDecorator.php on line 31
```

**Comment by cboden** [comment]
Can you provide a test URL for me to connect to with a WebSocket client? What OS/version and PHP version are you using on your server?
