### ISSUE TITLE
Sync'd subscriptions

### ISSUE THREAD

**Issue by cboden** [ratchetphp/Ratchet#43]
When `WampServer` receives a subscription from a client it attaches a `Connection` to a `Topic` in two places.  The developer is able to remove a `Connection` from a `Topic` but currently doing so will not remove the reference in the `TopicManager`.

**Comment by harveyslash** [comment]
@cboden , could you please suggest how to avoid it?

**Comment by mbonneau** [comment]
Closed due to inactivity.
