### ISSUE TITLE
WsServer::enableKeepAlive pong handler needs to check that $lastPing is set

### ISSUE THREAD

**Issue by mbonneau** [ratchetphp/Ratchet#430]
https://github.com/ratchetphp/Ratchet/blob/b0e72bb7da661fae9fbaa10895ab8bd556d1b508/src/Ratchet/WebSocket/WsServer.php#L200

Need to check that $lastPing is set before trying to compare the contents:

See: https://tools.ietf.org/html/rfc6455#section-5.5.3

```
   A Pong frame MAY be sent unsolicited.  This serves as a
   unidirectional heartbeat.  A response to an unsolicited Pong frame is
   not expected.
```

**Comment by cboden** [comment]
Nice find. Instead of initiating `$lastPing` as null setting it to a `Frame` should fix any errors.
