### ISSUE TITLE
Async functions and performance

### ISSUE THREAD

**Issue by krekk4** [ratchetphp/Ratchet#432]
I want to code online card game with chat, but these issues ruined my ideas. I don't want to go through node documentations cause I want to master PHP.)) The first issue is that the same loop on node.js (with socket.io) server takes up to 2.5 seconds to execute and on ratchetphp server it takes up to 32 seconds.
```
for ($i = 0; $i <= 1000000000; $i++) {
    if ($i === 1000000000) {
         //....
    }
 }
```
 I knew node is faster than php but such a biiig difference?! I didn't expect.

And another main issue is that functions in my app is blocking and while this loop is running if I or other client sends a chat message to server, chat message function waits for loop to exit.
I'm not much experienced so any advice would be appreciated.
How can I improve performance, may I use hhvm with ratchetphp? and is there any way to make functions non-blocking?? I want it to handle multiple requests at the same time

**Comment by cboden** [comment]
You're mixing two different performance concerns here: Execution speed and I/O. PHP7 and HHVM execution speed are on par with Node. Any singled threaded environment will block I/O when you're doing CPU intensive work such as a for loop a million times.
