### ISSUE TITLE
Check for authentication after connection (MessageComponentInterface)

### ISSUE THREAD

**Issue by harveyslash** [ratchetphp/Ratchet#434]
I have set up a ratchet server with MessageComponentInterface. However, I was told that upon connection by a client to server,  if he doesn't send any message, the connection will stay open forever(and thus blocking resources on my server). 

Is there a way to automatically close a connection if no message is received within N seconds ?

**Comment by cboden** [comment]
You can implement your own heartbeat. See [enableKeepAlive in the 0.4 branch](https://github.com/ratchetphp/Ratchet/blob/0.4/src/Ratchet/WebSocket/WsServer.php#L194) for an idea of how to do something the way you're suggesting.
