### ISSUE TITLE
WebSocket connection to 'ws://localhost:8080/echo' failed: Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by ace411** [ratchetphp/Ratchet#436]
I'm using an Apache server and I get the following message when I attempt to run the $server->run(); script.

WebSocket connection to 'ws://localhost:8080/echo' failed: Error during WebSocket handshake: Unexpected response code: 404.

My application worked two days ago and I was able to send messages to other browsers but it is not working now.

I have tried to edit my http.conf file to allow the sockets to run on port 8080; I've been unsuccessful.

**Comment by cboden** [comment]
Ratchet is not meant to be run from an Apache server. You should be running it from a shell.

**Comment by ace411** [comment]
How can I set up this shell?

**Comment by cboden** [comment]
command line

**Comment by ace411** [comment]
How exactly in the command line?

**Comment by cboden** [comment]
This is documented in the tutorials on the [website](http://socketo.me)

**Comment by mohhamedion** [comment]
i do have the same problem although i run it from CMD

**Comment by wenbinke** [comment]
I have tracked the code. Found that you have to make sure the request host must be the same as the code you used when run with "$app = new Ratchet\App('localhost', 8080);"

the code is in application/vendor/symfony/routing/Matcher/UrlMatcher.php. You can print the `$this->context->getHost()` to see if it is that issue.
`            
            $hostMatches = [];
            if ($compiledRoute->getHostRegex() && !preg_match($compiledRoute->getHostRegex(), $this->context->getHost(), $hostMatches)) {
                continue;
            }`
