### ISSUE TITLE
Send user ID from browser to websocket server while opening connection

### ISSUE THREAD

**Issue by wangran326990** [ratchetphp/Ratchet#438]
I want to change $conn->resourceId to the id in my user database table. are there any method i can use and how.

**Comment by harveyslash** [comment]
You can send parameters that the connection interface has access to like this 

function onOpen( ConnectionInterface $conn ) {
   $querystring = $conn->WebSocket->request->getQuery();
}

**Comment by cboden** [comment]
resourceId is the ID of the socket, you can not change this. You can add your own properties to each connection. As @harveyslash said you can get data from the initial HTTP request.

**Comment by mikealmond** [comment]
You can also fire an message after connecting with a valid [JWT](https://jwt.io/) token that has the information you are trying to set. This would allow you to attach it to the connection for future use.

**Comment by tgbv** [comment]
> 
> 
> You can send parameters that the connection interface has access to like this
> 
> function onOpen( ConnectionInterface $conn ) {
> $querystring = $conn->WebSocket->request->getQuery();
> }

This method no longer works. What are the alternatives?
