### ISSUE TITLE
Ratchet server windows only 254 connections

### ISSUE THREAD

**Issue by 3isoluciones** [ratchetphp/Ratchet#439]
I have ratchet server in a aws ec2 windows 2008 r2 standard machine. The problem is that i only can have 254 conections open, the new conection after 254 stay waiting and only when i restart ratchet receive the others. Any one knows why this happen. i would like help because i already change some tcpip parameters in windows regedit but didnt solve. 

Thanks in advanced.

if someone knows how solve this issue please contact we can  pay for suport.

best regards

**Comment by cboden** [comment]
I'm not a Windows user so I can't give you a definitive answer but Google around for "Windows ulimit" or "Windows file descriptor limit". In *nix based systems there are several security layers for number of open file descriptor (in this case open socket) that a running process and a user can have open. I'm sure Windows has a similar security layer but changing it will be different.
