### ISSUE TITLE
Ratchet Hello world issue 

### ISSUE THREAD

**Issue by daslicht** [ratchetphp/Ratchet#440]
Hi, 
what is wrong with my version of the hello world tutorial , please?

https://github.com/daslicht/ratchet-hello-world/tree/master

**Comment by rafaelnery** [comment]
Try this...
```
composer dump-autoload
```

I think you edited the composer.json without and did not change the autoload 
:smile:

**Comment by daslicht** [comment]
Yeah indeed taht worked, I found the answer here : 
http://stackoverflow.com/questions/24392787/php-composer-autoload-not-loading-class

what is that ```-o``` flag for ?

**Comment by rafaelnery** [comment]
@daslicht ...

This creates a "classmap" mapping each class to its file in a big array. When you use an optimized autoloader, you don't perform any calls to file_exists so your application is faster.

https://getcomposer.org/doc/03-cli.md#dump-autoload
