### ISSUE TITLE
Understanding the ->on() method used to listen to ZMQ::SOCKET_PULL

### ISSUE THREAD

**Issue by cyorobert** [ratchetphp/Ratchet#443]
Chris & Ratchet contributors - thanks so much for the hard work. Your code is beautiful and a pleasure to work with.

I have a question as a follow up to the push integration tutorial http://socketo.me/docs/push. Following the example, I've created a Main.php file as the entry point of my program that looks like this 

``` php
//Creates the React PHP event loop
$loop       = React\EventLoop\Factory::create();

//Creates an instance of our class that implements WampServerInterface
$pusher     = new MyPusherClass();

//Next, listen for our servers to make a ZeroMQ push
$context    = new React\ZMQ\Context($loop);

//Note that the Context class doesn't have a getSocket method
//and instead uses the __call method to dynamically call properties
//On its own private ZMQContext object
$pull       = $context->getSocket(ZMQ::SOCKET_PULL);
//Binding to itself means the client can only connect to itself
$pull->bind(LOCAL_ZMQ_SOCKET);
//On a 'message' event, pass the data to the myMessageHandler method of the MyPusherClass
$pull->on('message', [$pusher, 'myMessageHandler']);

// Set up our WebSocket server for clients wanting real-time updates
$webSock = new React\Socket\Server($loop);
$webSock->listen(8080, WEB_SOCKET_IP);
$webServer = new Ratchet\Server\IoServer(
    new Ratchet\Http\HttpServer(
        new Ratchet\WebSocket\WsServer(
            new Ratchet\Wamp\WampServer(
                $pusher
            )
        )
    ),
    $webSock
);

$loop->run();
```

Next, I push incoming messages via ZMQ

``` php
public function send($json){
       $zmq      = new ZMQContext();
       $socket   = $zmq->getSocket(ZMQ::SOCKET_PUSH, 'push server');
       $socket->connect(ZMQ_SOCKET);

       if(is_string($json){
             $socket->send($json);
       }
       else{
            throw new \InvalidArgumentException("Can only send json_encoded values through zmq");
        }
}

```

My server is working properly most of the time, but when testing with Postman the data is occasionally not passed to my `myMessageHandler` method (same data is being tested every time via postman). 

Is this an issue you've seen before, or could there be any set of circumstances where `myMessageHandler` would not get called only some of the time when sent a message via ZMQ?

I can provide more details if necessary. Thank you very much for your time.

**Comment by cboden** [comment]
Thank you for the kind words, they're always appreciated  :)

What operating system are you running your server on?

**Comment by cyorobert** [comment]
Absolutely I learned a lot from your talks at Ski PHP via youtube as well! I'm currently testing on Mac OSX El Capitan version 10.11.5, but it will ultimately be deployed to CentOS 6.

**Comment by mbonneau** [comment]
Closed due to inactivity.
