### ISSUE TITLE
Is it work on apache?

### ISSUE THREAD

**Issue by hilmanrdn** [ratchetphp/Ratchet#447]
I read on 'deployment' section:
Apache can not handle or even pass-through WebSocket traffic (as of this writing)

is it mean, Ratchet can't work on Apache? so we have to use nginx? or.. ?

**Comment by cboden** [comment]
I'd recommend nginx. You can try the [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) extension for Apache though.

**Comment by hilmanrdn** [comment]
Thanks for the response, i'm not sure why is it working right now on my local machine which im still using apache not nginx, does it mean its work but there is other problem? Or..
amazing library btw!

**Comment by cboden** [comment]
Apache and Ratchet can run on the same machine together. They just have to be bound to different ports. If you want a client to see your website and Ratchet through the same port that's when you need to proxy with that extension (or nginx).

**Comment by hilmanrdn** [comment]
thanks for the explanation!
