### ISSUE TITLE
Working on dev, not working on production..

### ISSUE THREAD

**Issue by vatnoise** [ratchetphp/Ratchet#448]
I've been following [this tutorial](http://socketo.me/docs/push) and it all seems to be working on my local machine but as soon as I try it on a production server, the page where I send the new blog post, as soon as it gets to the `$socket->connect("tcp://localhost:5555");` part it returns a 500/502 error.

With apache2 and PHP working on FastCGI the apache log says:

```
(104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: http://website/_test/send.php
```

And if I switch it to an Apache module the error is following:

```
upstream prematurely closed connection while reading response header from upstream
```

There is nothing in the php error log file, only in the apache log.

**Comment by vatnoise** [comment]
Checked sockets with a script from https://www.websocket.org/echo.html "Creating your own test" section.

It responded with

    CONNECTED

    SENT: WebSocket rocks

    RESPONSE: [0,"166422729657a4668eedc90747239488",1,"Ratchet\/0.3.5"]

    DISCONNECTED

**Comment by vatnoise** [comment]
I'm thinking it might be something with nginx. From the looks of it our production server uses apache on the inside but then uses nginx for the outside connections (I wasn't the one who set it up, hence the guesses).

**Comment by vatnoise** [comment]
Log from proxy_error_log:

    2016/08/05 14:27:22 [error] 19214#0: *155952 upstream prematurely closed connection while reading response header from upstream, client: 217.**.**.***, server: my.domain.name, request: "POST /_socket/send.php HTTP/1.1", upstream: "http://78.***.***.**:7080/_socket/send.php", host: "my.domain.name", referrer: "http://my.domain.name/_test/chat.php"

**Comment by mbonneau** [comment]
Closed due to inactivity.
