### ISSUE TITLE
websocket publish vs PHP socket send

### ISSUE THREAD

**Issue by vatnoise** [ratchetphp/Ratchet#449]
Hi,
I'm slighly curious regarding this tutorial: http://socketo.me/docs/push
I should add that I'm not ~~a big~~ an expert in the subject.

I'm mostly interested in this bit of code:

```
public function onPublish(ConnectionInterface $conn, $topic, $event, array $exclude, array $eligible) {
    // In this application if clients send data it's because the user hacked around in console
    $conn->close();
}
```

Is there an advantage in using PHP and doing `$socket->send(...);` rather than having JavaScript to do a push through the websocket? Because as far as I can see if we publish using the ws:// it will still be handled by PHP and therefore if we would need to, for example, add a blog to the DB we could still do it this way.

**Comment by cboden** [comment]
The advantage of using the push strategy is it's less obtrusive to introduce into an existing system than moving all your existing logic into a Ratchet application. You're adding real-time as a feature instead of building anew.
