### ISSUE TITLE
What about new release?

### ISSUE THREAD

**Issue by nazar-pc** [ratchetphp/Ratchet#452]
I feel like both ReactPHP and Ratchet are stagnating. There are many awesome features already done, but there was no major release for many months.
I've read through issues in corresponding [milestone](https://github.com/ratchetphp/Ratchet/milestone/4) and it seems that they have been already resolved (in 0.4).

So the question is: what is left before new version can be released?

**Comment by cboden** [comment]
Indeed 0.4 is almost done. I've been crazy busy with my job lately so I haven't been able to finish the release off. The major thing that needs to be done is testing and documentation. 

While you could consider Ratchet to be "stagnant" it's job is to allow a developer to serve and work with WebSockets, which it does. There are features I'd like to add (as separate libraries) to give new functionality of things I think people would need, but the core is solid and will probably not change much. 

React on the other hand is very active.

**Comment by nazar-pc** [comment]
Thanks for clarification. I know Ratchet does what it is supposed to, but there are some features like binary messages, that are implemented, but not available in stable version. So I was curious when it might happen (while not trying to hurry you or something like that), just to know what to expect.

**Comment by Smile42RU** [comment]
@cboden Hi. Well... Ratchet repo looks like abandoned, actually. Nobody sends any commit to master branch for many months. It still alive? :)

**Comment by cboden** [comment]
@Smile42RU please see my [previous comment in this thread](https://github.com/ratchetphp/Ratchet/issues/452#issuecomment-245312406). 

If there is a feature missing from Ratchet you need pull requests are welcome.

**Comment by smalot** [comment]
@cboden Hi Chris, I'm very interested by the 0.4 release because it implements the new Guzzle library.
When do you think you'll be able to release it ?
Many thanks

**Comment by gsaqui** [comment]
@cboden any updates on if 0.4 is going to come out soon?  Is there something the community can do to help to get it released?

**Comment by cboden** [comment]
Updating documentation on the website is the last thing to do before releasing 0.4. I'm very sorry for the delay.

**Comment by gsaqui** [comment]
@cboden you maintain an open source library and you have a life - don't apologize, we all respect what you do and are here to help.
