### ISSUE TITLE
Guzzle/HTTP abandoned, switch to guzzle/guzzle?

### ISSUE THREAD

**Issue by christoferd** [ratchetphp/Ratchet#454]
Hi, was looking through packagist to learn about this, and found a message that may help you.

Guzzle/HTTP
This package is abandoned and no longer maintained. The author suggests using the guzzle/guzzle package instead.
https://packagist.org/packages/guzzle/http

**Comment by WyriHaximus** [comment]
FYI https://github.com/ratchetphp/Ratchet/search?q=abandoned&type=Issues&utf8=%E2%9C%93 :smile: , IIRC this will be fixed in 0.4

**Comment by svemir** [comment]
It seems to get even more fun - now you are supposed to be using guzzlehttp/guzzle. In my app composer.json, i added "guzzlehttp/guzzle": "~5.0" to stop composer warnings. Versions 3 and 4 are not maintained anymore, and I did not really have the time to check if 6 brings significant changes. It all seems to work fine (I am using ratchet via voryx/thruway)

**Comment by svemir** [comment]
Yup, guzzle 6 is a big change, but up to 5 it seems not to break ratchet in my limited testing: https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by cboden** [comment]
Guzzle 3 is not maintained. That does not mean it stopped working. Guzzle is only used for its HTTP parsing, not to make any HTTP requests. It still works perfectly fine. 

That being said, see the upcoming 0.4 branch. It replaced Guzzle/3 with Guzzle/psr

**Comment by christoferd** [comment]
Okay, let me know if want me to change title, or my post to help others, and not confuse anyone.
:-)
