### ISSUE TITLE
Handling PONG frames

### ISSUE THREAD

**Issue by voidoverflow** [ratchetphp/Ratchet#455]
I've been looking into using Websocket PING-PONG frames to detect half open connections.  As far as I can see, Ratchet currently handles PING (by replying PONG) but simply ignores PONG frames after parsing them.

Are there plans to add an event or callback for PONG frames?  Is there a way to implement this kind of heartbeat functionality, other than at the application protocol level?

**Comment by cboden** [comment]
There is a [heartbeat feature coming in 0.4](https://github.com/ratchetphp/Ratchet/blob/0.4/src/Ratchet/WebSocket/WsServer.php#L194) you can enable that will periodically send pings and if a pong isn't received in a given amount of time will disconnect the client.

**Comment by sargearmstrong** [comment]
Dears.. love the library. I too would like to listen and perform additional functions for OP_PONG and/or all control frames within the custom MessageComponentInterface class. I tried splicing in various things from the WsServer.php=>onControlFrame() function but to no avail.. perhaps somebody already knows a way to achieve this? Thanks!

**Comment by cboden** [comment]
@sargearmstrong What additional function are you needing to perform?

You were on the right track, probably extend `WsServer` and overload the `onControlFrame` method; just make sure to call the original parent method.

**Comment by sargearmstrong** [comment]
@cboden Thank you kindly, I'll see if I can correlate those terms. Are you on fiverr by chance? :-)

I'm experiementing with various ways to monitor connections and thought it would be fun to track connection status by the onopen, onclose, AND control frames. I had previously achieved this with the applications sending messages back and forth but those show up in the console which other wss services seem to avoid. And, I'm assuming, that control frames are a tiny bit "lighter" to deal with for everything involved. My reasons are probably silly, but seems like low hanging fruit (well, slightly beyond grasp for me.. currently). Thanks friend!
