### ISSUE TITLE
terminated sockets not calling callbacks

### ISSUE THREAD

**Issue by half2me** [ratchetphp/Ratchet#456]
On `Ratchet\WebSocket\WsServer;` when a connected client drops the connection (not in a clean way, i.e.: Unplugs computer), my `onClose` function does not get called. Infact, when I use `$conn->send($msg)` the `onError` function is not called, it treats it as if the client was still connected. How can I know when a client drops the connection uncleanly?

**Comment by cboden** [comment]
Short answer is you can't. This is a problem at the TCP level. The best thing you can do is use a heartbeat protocol. If the peer doesn't respond in a given amount of time close the connection.

**Comment by half2me** [comment]
What I was looking for was `Ratchet\WebSocket\WsServer::enableKeepAlive()` This would be worth mentioning in the documentation. It is something that all websockets would want to implement. I had even started working on my own heartbeat protocol at application layer, but then found the RFC for pings. Maybe its just me, but I couldn't find this option documented anywhere. I would even put it in the tutorial page (Which is great btw).

**Comment by cboden** [comment]
It's not in the documentation (yet) because 0.4 hasn't been released. It will be documented for the release.

**Comment by half2me** [comment]
@cboden ah I see :) Looking forward to that release then :+1:
