### ISSUE TITLE
onMessage not firing always

### ISSUE THREAD

**Issue by mukilana** [ratchetphp/Ratchet#458]
onOpen() event fired always, but onMessage() event not firing always. 
But the chat system will work fine sometimes, but sometimes it can't work

I can't able to find out what is problem behind this.

Server Side Code:
public function onOpen(ConnectionInterface $conn)
    {
        $this->repository->addClient($conn);
    }

```
/**
 * Called when a message is sent through the socket
 *
 * @param ConnectionInterface $conn
 * @param string              $msg
 * @return void
 */
public function onMessage(ConnectionInterface $conn, $msg)
{
    echo $msg;
    // Parse the json
    $data = $this->parseMessage($msg);
    $currClient = $this->repository->getClientByConnection($conn);

    // Distinguish between the actions
    if ($data->action === "setname")
    {
        $currClient->setName($data->username);
    }
    else if ($data->action === "message")
    {
        // We don't want to handle messages if the name isn't set
        if ($currClient->getName() === "")
            return;

        foreach ($this->repository->getClients() as $client)
        {
            // Send the message to the clients if, except for the client who sent the message originally
            if ($currClient->getName() !== $client->getName())
                $client->sendMsg($currClient->getName(), $data->msg);
        }
    }
}
```

Client Side Codes : 

setupConnectionEvents: function() {
            var self = this;

```
        self.socket.onopen = function(evt) { self.connectionOpen(evt); };
        self.socket.onmessage = function(evt) { self.connectionMessage(evt); };
        self.socket.onclose = function(evt) { self.connectionClose(evt); };
    },

    connectionOpen: function(evt) {
        this.open = true;
        this.addSystemMessage("Connected");
        this.updateUsername();
    },

    connectionMessage: function(evt) {
        alert("gi");
        if (!this.open)
            return;

        var data = JSON.parse(evt.data);
        alert(data);
        if (data.action == 'setname') {
            if (data.success)
                this.addSystemMessage("Set username to " + this.username);
            else
                this.addSystemMessage("Username " + this.username + " has been taken.");
        } else if (data.action == 'message') {
            this.addChatMessage(data.username, data.msg);
        }
    },
```

Please give me a solution

**Comment by cboden** [comment]
First step in troubleshooting is make sure the client is sending data. Open your website in Chrome and watch the traffic: View > Developer > Developer Tools > Network > WS > (your WebSocket connection) > Frames

When you attempt to send a message ensure the frame is sent to the server. If you aren't able to solve the problem please post a screen shot of this in your next reply.

**Comment by mukilana** [comment]
Thanks for your reply. I found that the problem only occur when using server and few client in same PC. While accessing the server from other PC will not give the problem.

While seeing the Developer tool, the frame is sent to server. But i think there is some problem in server response.

FYI, sometimes server throw a exception 10053 socket error.

The screenshot for Network Frames of WS (Developer Tools)
![chat error](https://cloud.githubusercontent.com/assets/22561177/19045158/000162f2-89b5-11e6-9d2c-ee6debc9eca3.jpg)

Please guide me on this issue. Thank you @cboden

**Comment by cboden** [comment]
Very strange as this shows the message is being delivered to the server, but no response. What about the console output? Do you see the echo from the first line of your onMessage function?

**Comment by mukilana** [comment]
No echo appear from the onMessage function,  this problem only appear in few system using chrome browser(my system too). But all other browser working fine without any problem.

**Comment by cboden** [comment]
I've seen some strange behaviour like this only on Windows system before. Perhaps some kind of firewall or AV running? I faintly recall some weird TCP buffering going on in Windows too...as in if you send another message the previous one will send.

**Comment by mukilana** [comment]
Thank you and the problem still exist even after turn off the firewall and AV.

WS Timing shows a caution: request is not finished yet. 
Is any problem with this error given below?

![image](https://cloud.githubusercontent.com/assets/22561177/21609264/64e5a50a-d1e7-11e6-8eb9-f6d32bc27c37.png)

**Comment by mbonneau** [comment]
Closed due to inactivity.
