### ISSUE TITLE
Installation Tutorial Confusing

### ISSUE THREAD

**Issue by Ecksters** [ratchetphp/Ratchet#459]
Brother's trying to set this up, showed me that the tutorial site has some really confusing wording, I assume an edit happened that failed to clean up references to something that was removed later.

http://socketo.me/docs/install

"Inside that file copy and paste the JSON from the top of this page."

There is no JSON at the top of that page.

**Comment by MonkeyFreeZone** [comment]
Agreed - this is still an issue. When running the PHP binary and attempting to install ratchet, you receive the following error message:

      [Seld\JsonLint\ParsingException]
      "./composer.json" does not contain valid JSON
      Parse error on line 1:
      php ~/composer.phar
      ^
      Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

**Comment by cboden** [comment]
Sorry, that sentence was left over from the old installation docs. It's been updated. Composer's recommended installation method is with the binary:

    php ~/composer.phar require cboden/ratchet

(assuming your `composer.phar` file you downloaded is in your home directory).

**Comment by cboden** [comment]
The install tutorial has been updated
