### ISSUE TITLE
404 error when using new App()

### ISSUE THREAD

**Issue by joshcrawmer4** [ratchetphp/Ratchet#462]
Hello. When using this:
```php
$server = IoServer::factory(
                    new HttpServer(
                        new WsServer(
                            $this->taskStatusPusher
                        )
                    ),
                    8080
                );

$server->run();
```
Everything works fine using telnet and from the browser. But when using this:
```php
$app = new App('www.stmarys.dev', 8080, '0.0.0.0', $this->taskStatusPusher->getLoop());
        $app->route('/chat', $this->taskStatusPusher);
        $app->run();
```

Everything works fine with telnet but I get this browser error: 

TaskStatus.js:93 WebSocket connection to 'ws://www.stmarys.dev:8080/' failed: Error during WebSocket handshake: Unexpected response code: 404

This is my Javascript code...
```javascript
var conn = new WebSocket('ws://www.stmarys.dev:8080');
      conn.onopen = function (e) {
          LogUtil.log("Connection established!");
      };
conn.onmessage = function (e) {
      LogUtil.log(e.data);
      };
```

I don't see why it would work for the IoServer::Factory but not the new App() constructor.... Could this possibly be a bug? When I run telnet www.stmarys.dev 8080 I get a proper connection on both of them. Why would it work with telnet but not from the browser? Iam using Vagrant and virtual box if this makes a difference.

**Comment by cboden** [comment]
Part of the App class adds routing via the [Router](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Http/Router.php) class. You need to now connect to the endpoint you configured when adding a route:

```javascript
var conn = new WebSocket('ws://www.stmarys.dev:8080/chat');
```

**Comment by joshcrawmer4** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Perfect. Thank you so much!


Sent from Yahoo Mail for iPhone


On Saturday, November 5, 2016, 11:58 AM, Chris Boden <notifications@github.com> wrote:


Part of the App class adds routing via the Router class. You need to now connect to the endpoint you configured when adding a route:
var conn = new WebSocket('ws://www.stmarys.dev:8080/chat');
