### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by dankhrapiyush** [ratchetphp/Ratchet#463]
I'm getting this issue after onClose connection

PHP version = 7.0.8-0ubuntu0.16.04.3
PHP memory limit = 900M
Operating system = Ubuntu 16.04
Libevent version = [2.0.22-stable](http://libevent.org/)
Libevent php = https://github.com/expressif/pecl-event-libevent ([Reference](https://github.com/ratchetphp/Ratchet/issues/357#issuecomment-230186851))

Using libevent consider following log
```
New connection! (123)
New connection! (131)
New connection! (139)
Connection 123 has disconnected
Segmentation fault (core dumped)
```
Here as we can see it's stopping execution onClose and throws "Segmentation fault (core dumped)" message.
If I try without libevent then it's disconnecting clients and execution not stopping after onClose.

Sometime I'm getting following warning on onClose connection
`PHP Warning: Unknown list entry type (0) in /vendor/react/event-loop/src/LibEventLoop.php on line 106`

**Comment by cboden** [comment]
It seems the libevent extension does not support PHP 7 yet. I'd suggest using [event](http://pecl.php.net/package/event) instead as it supports PHP 7.
