### ISSUE TITLE
Docs only mention libevent for better performance

### ISSUE THREAD

**Issue by dzuelke** [ratchetphp/Ratchet#465]
ReactPHP will [also utilize the `ev` or `event` extensions](https://github.com/reactphp/event-loop/blob/626faeb9e2c1dfb17b55658676bf3ff580d43d02/src/Factory.php#L7) if they are present. This should be mentioned [in the docs](http://socketo.me/docs/deploy#libevent).

**Comment by cboden** [comment]
Good point. Would you be interested in opening a pull request in the [website repo](https://github.com/ratchetphp/socketo.me) to update the docs?

**Comment by dzuelke** [comment]
Sure. https://github.com/ratchetphp/socketo.me/pull/30

**Comment by cboden** [comment]
Merged and deployed. Thank you!
