### ISSUE TITLE
Ratchet needs update of guzzle/guzzle requirement

### ISSUE THREAD

**Issue by victorvassilev** [ratchetphp/Ratchet#466]
As per requirement in composer.json:

"require": {
        "php": ">=5.3.9"
      , "react/socket": "^0.3 || ^0.4"
      , "guzzle/http": "^3.6"
      , "symfony/http-foundation": "^2.2|^3.0"
      , "symfony/routing": "^2.2|^3.0"
    }

However, guzzle is now using guzzle/guzzle instead. The requirement needs to be updated.

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by cboden** [comment]
see #288
