### ISSUE TITLE
Socket send data to client slow with 3 - 6 seconds delay

### ISSUE THREAD

**Issue by sebastianvirlan** [ratchetphp/Ratchet#467]
Hi, I am using this library with laravel.

I have some problems when I connect to the socket with 5 - 6 phones (clients) and start exchanging informations client - server. If the data sent from phones are lot, like flooding am getting response from server too slow.

For example each phone send 1 update location / second, there are 6 update locations per second and cumulate with all other interactions the data send to server become much.

The problem is that the response I am receiving is with delay.

Is this an issue or can be fixed with some custom parameters?

Thank you!

**Comment by cboden** [comment]
Make sure you're not doing any other blocking I/O (database queries) or heavy computational processing that could block the event loop. Otherwise please provide more information to help troubleshoot.
