### ISSUE TITLE
Send message immediately.

### ISSUE THREAD

**Issue by thetuyen** [ratchetphp/Ratchet#468]
I have same issues:
> I have to do some complicated computing between sending messages, but first message is sent with second after compulting. How I can send it immediately?

[http://stackoverflow.com/questions/30753763/ratchet-websocket-send-message-immediately#](url)
But, when I update code as your answer (copy your code). It's not still send immediately.
I am sorry for having bothered you.

**Comment by cboden** [comment]
Computational code (including sleep) will actually block the event loop. In the SO example it was a demonstration to ensure two messages were sent in a strict order. 

If you're doing computational heavy processes I'd suggest looking into integration of React's ChildProcess handler to offload CPU intensive (or blocking I/O) tasks.
