### ISSUE TITLE
Got 100% CPU Load on a production server with huge parallel load

### ISSUE THREAD

**Issue by Dantist** [ratchetphp/Ratchet#469]
Hello,

I am getting 100% CPU Load almost instantly (after 10-15 seconds of run) on a production server with a lot of parallel usage (~500 users in parallel opens WebSocket and send some data).

Trying to figure out the bottleneck I have ended up with an absolutely empty code that causes a 100% CPU usage. Xdebug suggests that the issue is in react/event-loop. 
I have tried StreamSelectLoop (the default one) and ExtEventLoop (this one selected automatically when php-pecl-event enabled. I have php-pecl-event 2.2.1 and libevent 2.0.22 installed) - both make 100% CPU Load.

CacheGrind files:
ExtEventLoop: https://www.dropbox.com/s/s5lmg9ey5lyxrf5/cachegrind_ExtEventLoop.zip
StreamSelectLoop: https://www.dropbox.com/s/q61kbzy1y7cpxg3/cachegrind_StreamSelectLoop.zip

Sample code:

```
<?php
  require __DIR__ . '/vendor/autoload.php';
  use Ratchet\ConnectionInterface;

  class EmptyClass implements Ratchet\MessageComponentInterface {
    public function onMessage(ConnectionInterface $from, $msg) {
    }
    public function onOpen(ConnectionInterface $conn) {
    }
    public function onClose(ConnectionInterface $conn) {
    }
    public function onError(ConnectionInterface $conn, \Exception $e) {
    }
  }

  $webServer = Ratchet\Server\IoServer::factory(
          new EmptyClass(),
    8080
  );
  $webServer->run();
?>

```

composer show -i:
```
cboden/ratchet            v0.3.5 PHP WebSocket library
evenement/evenement       v2.0.0 Événement is a very simple event dispatching library for PHP
guzzle/common             v3.9.2 Common libraries used by Guzzle
guzzle/http               v3.9.2 HTTP libraries used by Guzzle
guzzle/parser             v3.9.2 Interchangeable parsers used by Guzzle
guzzle/stream             v3.9.2 Guzzle stream wrapper component
guzzlehttp/psr7           1.3.1  PSR-7 message implementation
psr/http-message          1.0.1  Common interface for HTTP messages
ratchet/pawl              v0.2.2 Asynchronous WebSocket client
ratchet/rfc6455           v0.2.1 RFC6455 WebSocket protocol handler
react/cache               v0.4.1 Async caching.
react/dns                 v0.4.3 Async DNS resolver.
react/event-loop          v0.4.2 Event loop abstraction layer that libraries can use for evented I/O.
react/promise             v2.4.1 A lightweight implementation of CommonJS Promises/A for PHP
react/promise-timer       v1.1.0 Trivial timeout implementation for Promises
react/socket              v0.4.3 Library for building an evented socket server.
react/socket-client       v0.5.1 Async connector to open TCP/IP and SSL/TLS based connections.
react/stream              v0.4.5 Basic readable and writable stream interfaces that support piping.
react/zmq                 v0.3.0 ZeroMQ bindings for React.
symfony/event-dispatcher  v3.1.7 Symfony EventDispatcher Component
symfony/http-foundation   v3.1.7 Symfony HttpFoundation Component
symfony/polyfill-mbstring v1.3.0 Symfony polyfill for the Mbstring extension
symfony/routing           v3.1.7 Symfony Routing Component
```

php -v
```
PHP 7.0.13 (cli) (built: Nov  8 2016 20:28:51) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

Any help is highly appreciated!

**Comment by Dantist** [comment]
Hello again,

Digging further and using a simple strace I see that the infinite loop appears at the state "EMFILE (Too many open files)", so increasing the open fd limit ultimately solves the problem completely. 

This limit was set to 1024 and was used up in a few seconds on a high load. CentOS allows us to set this limit as big as 1048576 for a single user.

On a production server having ~100 persistent opened connections in a single point of time (having a lot of connections being opened and closed before that) I see, that an example code above have ~1200 opened sockets (which indeed counts in file descriptors), which used up a limit. I suspect that some sockets not been closed correctly.

I am not sure is this a bug or not, but from the other side these limits can be tracked like this:

```
<?php 
  $fd_opened_by_this_process = iterator_count(new FilesystemIterator("/proc/self/fd/", FilesystemIterator::SKIP_DOTS));

  $soft_fd_limit = posix_getrlimit()['soft openfiles'];
  $hard_fd_limit = posix_getrlimit()['hard openfiles'];
```

Using this information we can gracefully stop accepting new connections with some user-friendly error instead of going into infinite loop.

You may close this issue when you decide what to do with this ;-)

Off Topic:
I saw such behavior, i.e. in MySQL Server when you just can't increase a maximum connection value without increasing an open files limit (https://codepoets.co.uk/2015/mysql-max_connections-stuck-on-214/)

**Comment by exodus4d** [comment]
I have probably the same problem. I get a 40% CPU load with just 2 clients connected.
I have already installed the `ev` PHP extension (see: http://socketo.me/docs/deploy#evented-io-extensions)
Should I try the `event`?

I have a WebSocket Server that get some data over a ZMQ `push/pull` setup.
#### My Architecture:
![pf1](https://cloud.githubusercontent.com/assets/9299033/22265366/1885ecce-e27c-11e6-8b5f-7fe1d6c2b336.png)

#### WebSocket that holds the TCP Socket and listens for Data

``` PHP
$loop   = React\EventLoop\Factory::create();

$context = new React\ZMQ\Context($loop);

$pull = $context->getSocket(\ZMQ::SOCKET_PULL);
$pull->bind( $this->dns );

// main WebSocket app -> inject socket that will listen for data (TCP)
$mapUpdate = new Main\MapUpdate($pull);
// "onMessage" listener
$pull->on('message', [$mapUpdate, 'receiveData']);

// Set up our WebSocket server for clients wanting real-time updates
$webSock = new React\Socket\Server($loop);
// Binding to 0.0.0.0 means remotes can connect (Web Clients)
$webSock->listen($this->wsListenPort, $this->wsListenHost);
new IoServer(
    new HttpServer(
        new WsServer(
            $mapUpdate
        )
    ),
    $webSock
);

$loop->run();
```

#### TCP Socket that pushes data to the WebSocketServer (see above)
``` PHP
$context = new \ZMQContext();
$socket = $context->getSocket(\ZMQ::SOCKET_PUSH);

$send = [
    'task' => $task,
    'load' => $load
];

$socket->connect($this->socketUri);
$socket->send(json_encode($send));
$socket->disconnect($this->socketUri);
```

Any ideas, what could be wrong with that? Thanks :)

**Comment by mbonneau** [comment]
Closed due to inactivity.
