### ISSUE TITLE
fwrite(): send of 4 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by webocoders** [ratchetphp/Ratchet#477]
Sometimes I have an error in vendor/react/stream/src/Buffer.php (line:86)
fwrite(): send of 4 bytes failed with errno=32 Broken pipe

in this line:
$sent = fwrite($this->stream, $this->data);

What should I do? Thanks.

Info:

PHP version 5.6.26.

composer show -i:

cboden/ratchet            v0.3.5 PHP WebSocket library
evenement/evenement       v2.0.0 ├Йv├йnement is a very simple event dispatching library for PHP
guzzle/common             v3.9.2 Common libraries used by Guzzle
guzzle/http               v3.9.2 HTTP libraries used by Guzzle
guzzle/parser             v3.9.2 Interchangeable parsers used by Guzzle
guzzle/stream             v3.9.2 Guzzle stream wrapper component
monolog/monolog           1.21.0 Sends your logs to files, sockets, inboxes, databases and various web services
psr/log                   1.0.2  Common interface for logging libraries
react/event-loop          v0.4.2 Event loop abstraction layer that libraries can use for evented I/O.
react/socket              v0.4.3 Library for building an evented socket server.
react/stream              v0.4.4 Basic readable and writable stream interfaces that support piping.
react/zmq                 v0.3.0 ZeroMQ bindings for React.
symfony/event-dispatcher  v3.1.6 Symfony EventDispatcher Component
symfony/http-foundation   v3.1.6 Symfony HttpFoundation Component
symfony/polyfill-mbstring v1.2.0 Symfony polyfill for the Mbstring extension
symfony/routing           v3.1.6 Symfony Routing Component

**Comment by cboden** [comment]
Can you provide more of the stack trace? The is an error that shows up in your logs but everything continues to work, correct?

The error message is when a peer attempts to send data over a closed connection. Odds are this is just the result of a race condition that can be ignored. (The client closed the connection just as the server was sending it data).

**Comment by webocoders** [comment]
Stack trace:

#0 [internal function]: React\Stream\Buffer->handleWrite(Resource id #171646, Object(React\EventLoop\StreamSelectLoop))
#1 /var/www/myproject.com/protected/ratchet/vendor/react/event-loop/src/StreamSelectLoop.php(240): call_user_func(Array, Resource id #171646, Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/myproject.com/protected/ratchet/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#3 /var/www/myproject.com/protected/ratchet/bin/push-server.php(33): React\EventLoop\StreamSelectLoop->run()
#4 {main}

> The is an error that shows up in your logs but everything continues to work, correct?

Yes, if an error occurs, the work does not stop.

**Comment by cboden** [comment]
Try updating your dependencies. There was some logic change in the last update reactphp/stream with writing to stream buffers. (https://github.com/reactphp/stream/compare/v0.4.4...v0.4.5).

Also take a look at [this unit test](https://github.com/reactphp/stream/blob/master/tests/BufferTest.php#L364) which is testing the exact error you received. The test is writing to a closed stream and expecting the error you received back. This is what leads me to believe this is an error you can ignore.

**Comment by BenasPaulikas** [comment]
Hello from 2020

This issue is still persists with me.

```
2020-01-02 00:51:34 [-][-][-][error][RuntimeException] ErrorException: fwrite(): send of 4 bytes failed with errno=32 Broken pipe in /home/alua/api/vendor/react/stream/src/WritableResourceStream.php:118
Stack trace:
#0 /home/alua/api/vendor/react/event-loop/src/StreamSelectLoop.php(252): React\Stream\WritableResourceStream->handleWrite(Resource id #671746)
#1 /home/alua/api/vendor/react/event-loop/src/StreamSelectLoop.php(211): React\EventLoop\StreamSelectLoop->waitForStreamActivity(73973)
#2 /home/alua/api/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()```

Happens every few weeks..

    "cboden/ratchet": "^0.4.1",

What should I try ?
