### ISSUE TITLE
websockets are blocking ajax requests

### ISSUE THREAD

**Issue by ankitjain28may** [ratchetphp/Ratchet#478]
When I am trying to access session values by setting the session again from session_Id, my Ajax requests are blocked..!

**Comment by cboden** [comment]
Sessions in Ratchet are read only. You should not be setting the session id.

**Comment by ankitjain28may** [comment]
It is fixed, is there any way to deploy without using supervisor bcs i am getting an error in installing supervisor.

**Comment by cboden** [comment]
supervisor is just a suggestion. You can use any process manager such as the system ones that come on Linux distributions. Alternatively you can just run the script manually.
