### ISSUE TITLE
Failed to execute `send` on `Websocket`: Still in CONNECTING state

### ISSUE THREAD

**Issue by bigtunacan** [ratchetphp/Ratchet#481]
I setup just "quick example" from the GitHub page to test that I had Ratchet going correctly, but when I connect to my test page I'm getting this error message.

`Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at http://php7dev/:5:8
(anonymous) @ (index):5
VM736:35 WebSocket connection to 'ws://localhost:8080/echo' failed: Connection closed before receiving a handshake response
WrappedWebSocket @ VM736:35
(anonymous) @ (index):3`

My client page that is connecting is just the following
    
    <?php
    ?>
    <script type="text/javascript">
      var conn = new WebSocket('ws://localhost:8080/echo');
      conn.onmessage = function(e){ console.log(e.data); };
      conn.send('Hello Me!');
    </script>
    <?

**Comment by cboden** [comment]
The message is being sent before the connection is established. Try this:

```javascript
var conn = new WebSocket('ws://localhost:8080/echo');
conn.onmessage = function(e){ console.log(e.data); };
conn.onopen = () => conn.send('hello');
```
