### ISSUE TITLE
Need help in configuring websocket over SSL

### ISSUE THREAD

**Issue by mukilana** [ratchetphp/Ratchet#482]
Examples on Ratchet Websocket Connection with HTTPS/SSL will help me a lot in configuring Chat connections. 

The coding now used for HTTP is given below

`require __DIR__ . '/../vendor/autoload.php';

use Chat\Chat;

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;

$server = IoServer::factory(new HttpServer(new WsServer(new Chat)), 8080);

$server->run();`

**Comment by cboden** [comment]
Server SSL is not currently supported. Proxy your Ratchet app behind Nginx, HAProxy, or STunnel that are configured with SSL termination.
