### ISSUE TITLE
Warning: strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by ryzhov** [ratchetphp/Ratchet#483]
Have this issue in chromium  => Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 17.3 (64-bit)
php => v7.0.13-0ubuntu0.16.04.1
commit =>   [git] https://github.com/ratchetphp/Ratchet.git 84df35d2a6576985b9e81b564d3c25809f8d647e

message => "Warning: strlen() expects parameter 1 to be string, array given"
file => ".../cboden/ratchet/src/Ratchet/WebSocket/Version/RFC6455/Frame.php\"
line => "76"

**Comment by cboden** [comment]
Please provide source code. If I had to guess you're passing an array on a `$conn->send($arr)` or `$conn->close($arr)` call.

**Comment by ryzhov** [comment]
Thanks a lot!
yes it my mistake,  I send array in `$conn->send($arr)`
