### ISSUE TITLE
Support for igbinary

### ISSUE THREAD

**Issue by bizley** [ratchetphp/Ratchet#486]
Is it possible to add support for `igbinary` serializer?

Right now when using `igbinary` `SessionProvider` throws exception
> Unable to parse session serialize handler

**Comment by cboden** [comment]
You'd have to [write a handler](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Session/SessionProvider.php#L59) for `igbinary`. Currently we support [PHP and PHPBinary](https://github.com/ratchetphp/Ratchet/tree/master/src/Ratchet/Session/Serialize)

**Comment by bizley** [comment]
I should rephrase my question - Could you add support for `igbinary` please?
I'm aware what's needed to make it happen but I understand it's not planned yet.
Anyway thank you.
