### ISSUE TITLE
No SSL/WSS support?

### ISSUE THREAD

**Issue by samuel-allan** [ratchetphp/Ratchet#489]
Greetings! Very happy to be reporting in on an issue here, hope I'm useful.
It appears, as though there was a lack of SSL support (especially for WSS) (in the past and now), due to lack of such support in reactphp/socket, however now there is a way of implementing this (via the `SecureServer` component in react), so I was wondering if there are any plans on implementing this?

One of the main reasons is that there are many scenarios where this library becomes a no-deal because of this bug, for example if you are creating a WebRTC chat client, it is not possible to work with this library, despite the fact that it is the BEST library for PHP which offers this functionality (WebRTC has to be hosted on HTTPS, which can only request WSS, which ratchet does not support). 

I would be glad to fix this myself, but I was wondering: 
**(a)** Is this fixed already but undocumented? and 
**(b)** Are there any reasons why this shouldn't be fixed?

Thanks a lot! Regards :)

**Comment by Daijobou** [comment]
+1

**Comment by ruslan-naryzhnyi** [comment]
Maybe this will help!? I think the same issue!
#161 #100

**Comment by samuel-allan** [comment]
Thanks for the support @Ruslan!
Now that this issue is gaining quite some support, I may actually start
some preliminary work on it.

**Comment by samuel-allan** [comment]
Edit: There is apparently a pull request aiming to achieve just this: #500.

**Comment by cboden** [comment]
This should now be achievable with 0.4. React/SecureServer now supports TLS which can be injected into IoServer constructor. As well, as previously mentioned supporting it via reverse proxy is an option.

**Comment by heidji** [comment]
In the ReactPHP docs you only need to construct the SecureServer mentioned in such manner:
`    $webSock = new React\Socket\Server('0.0.0.0:8443', $loop); // Binding to 0.0.0.0 means remotes can connect
    $webSock = new React\Socket\SecureServer($webSock, $loop, ['local_cert' => '/etc/ssl/key.pem', 'allow_self_signed' => true, 'verify_peer' => false]); // SSL encapsulation`

and then inject into the IoServer as mentioned by cboden above

**Comment by semmel** [comment]
Thanks @heidji !. Just a minor correction regarding the parameters:
```php
$socketServer = new React\Socket\SecureServer(
		$socketServer, 
		$loop, 
		[	'local_cert' => 'cert.pem',
			'local_pk' => 'key.pem',
			'allow_self_signed' => true, 
			'verify_peer' => false
		]
	);
```

**Comment by heidji** [comment]
Thanks for the follow-up @semmel .
Quick follow-up question:
In my project I only included the public key, mainly due to my lack of knowledge in SSL encryption and what really happens ins the background. Could you please tell me if the system behaves differently for only having the public key as a parameter than it would with both keys?
Does this have any impact on how the data is encrypted at all?

**Comment by AntonioDilorenzo** [comment]
hi i've laravel project, I can not make the websocket work since I put the HTTPS on my webapp, with the hhtp working without problems, could you help me specifically what should I do? I'm a newbie :(

**Comment by vanht** [comment]
Create PEM file.

```
openssl rsa -in server.key -text > private.pem
openssl x509 -inform PEM -in server.crt > public.pem
```

```
local_cert' => 'private.pem',
'local_pk' => 'public.pem',
```

https://stackoverflow.com/a/12202346

**Comment by stefblokdijk** [comment]
Incase someone is still stuck, here's an working example based on the Ratchet hello world app:

```php
$app = new \Ratchet\Http\HttpServer(
    new \Ratchet\WebSocket\WsServer(
        new \MyApp\Chat()
    )
);

$loop = \React\EventLoop\Factory::create();

$secure_websockets = new \React\Socket\Server('0.0.0.0:8081', $loop);
$secure_websockets = new \React\Socket\SecureServer($secure_websockets, $loop, [
    'local_cert' => 'path-to/public.pem',
    'local_pk' => 'path-to/private.pem',
    'verify_peer' => false
]);

$secure_websockets_server = new \Ratchet\Server\IoServer($app, $secure_websockets, $loop);
$secure_websockets_server->run();
```

You may want to add `'allow_self_signed' => true,` in the ssl settings array if you're using it locally.

**Comment by nivshah** [comment]
Hi,

I've used the code posted here to set up a secure Ratchet WebSocket server. When I try to connect to the WebSocket server using wscat to test it, I get the following response:

```# wscat --connect 127.0.0.1:8010
error: Error: socket hang up```

I've tested moving off the React SecureServer and I'm able to connect:

```# wscat --connect 127.0.0.1:8010
connected (press CTRL+C to quit)
disconnected```

Anyone run into issues with React SecureServer not accepting incoming connections?

**Comment by nivshah** [comment]
My issue was related to my certs not being set up quite right and not connecting via wss:// when using wscat.

**Comment by LeoGalleguillos** [comment]
I am receiving the following error when attempting to connect via wss in Chrome browser:

    Error in connection establishment: net::ERR_CONNECTION_RESET

In the following line, I have replaced `0.0.0.0` with my server's IP address. Is this correct?

    $secure_websockets = new \React\Socket\Server('0.0.0.0:8081', $loop);

Also, I have used openssl to generate public and private pem files for the array:

    'local_cert' => 'path-to/public.pem',
    'local_pk' => 'path-to/private.pem',

Any idea how to resolve this or go from here? I am able to connect successfully to ws (not secure) both from within the server and via web browser. Thank you.

**Comment by LeoGalleguillos** [comment]
I was receiving the following error when using @stefblokdijk's code above:

    Error in connection establishment: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
(anonymous) @ VM100:1

It turns out that php was unable to read the public and private key files.

So, I ran the `php bin/chat-server.php` command as root (or run as a sudo user), and now I am able to connect via wss.

Now I have to figure out how to make the public and private key files accessible to php when running as a non-root user, but I don't think this will be too hard.

**Comment by nstechns** [comment]
if you are using laravel library cboden/ratchet for socket then go to app/Console/Commands/WebSocketServer.php Replace handle function with these lines of code and use your certification file path 'local_cert' and 'local_pk'
```

public function handle()
{

    $loop   = Factory::create();
    $webSock = new SecureServer(
        new Server('0.0.0.0:8090', $loop),
        $loop,
        array(
            'local_cert'        => '/opt/ssl/chamberstock_com.crt', // path to your cert
            'local_pk'          => '/opt/ssl/server.key', // path to your server private key
            'allow_self_signed' => TRUE, // Allow self signed certs (should be false in production)
            'verify_peer' => FALSE
        )
    );
    // Ratchet magic
    $webServer = new IoServer(
        new HttpServer(
            new WsServer(
                new WebSocketController()
            )
        ),
        $webSock
    );
    $loop->run();

}
```

**Comment by akramg478** [comment]
> Thanks @heidji !. Just a minor correction regarding the parameters:
> 
> ```
> $socketServer = new React\Socket\SecureServer(
> 		$socketServer, 
> 		$loop, 
> 		[	'local_cert' => 'cert.pem',
> 			'local_pk' => 'key.pem',
> 			'allow_self_signed' => true, 
> 			'verify_peer' => false
> 		]
> 	);
> ```

`<?php
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Chat;

    require dirname(__DIR__) . '/vendor/autoload.php';

    $server = IoServer::factory(
        new HttpServer(
            new WsServer(
                new Chat()
            )
        ),
        8080
    );

    $server->run();`

Here is my code how can I do that ?

**Comment by akramg478** [comment]
The thing is I am using php and here is my code:
`<?php
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Chat;

    require dirname(__DIR__) . '/vendor/autoload.php';

    $server = IoServer::factory(
        new HttpServer(
            new WsServer(
                new Chat()
            )
        ),
        8080
    );

    $server->run();`

I am unable to see it working for me by any means ... what changes I have to made kindly some one help me out in this.

Thanks

**Comment by akramg478** [comment]
> This should now be achievable with 0.4. React/SecureServer now supports TLS which can be injected into IoServer constructor. As well, as previously mentioned supporting it via reverse proxy is an option.

Can you please show me how to do it ?

Here is my code I am using this one:

`<?php
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Chat;

    require dirname(__DIR__) . '/vendor/autoload.php';

    $server = IoServer::factory(
        new HttpServer(
            new WsServer(
                new Chat()
            )
        ),
        8080
    );

    $server->run();`

My app is all ready but I am stuck in deployment now ... I am having apache server

**Comment by nikserg** [comment]
> > This should now be achievable with 0.4. React/SecureServer now supports TLS which can be injected into IoServer constructor. As well, as previously mentioned supporting it via reverse proxy is an option.
> 
> Can you please show me how to do it ?
> 
> Here is my code I am using this one:
> 
> `<?php
> use Ratchet\Server\IoServer;
> use Ratchet\Http\HttpServer;
> use Ratchet\WebSocket\WsServer;
> use MyApp\Chat;
> 
> ```
> require dirname(__DIR__) . '/vendor/autoload.php';
> 
> $server = IoServer::factory(
>     new HttpServer(
>         new WsServer(
>             new Chat()
>         )
>     ),
>     8080
> );
> 
> $server->run();`
> ```
> 
> My app is all ready but I am stuck in deployment now ... I am having apache server

Done this via Nginx proxy.

For **Nginx** I've used this manual: https://stackoverflow.com/a/55237668

For **Apache** I believe you can use this manual: https://stackoverflow.com/a/28393526

**Comment by andimi3** [comment]
A little late but do you have to create .pem files or can you just use the .crt and .key files in ssh folder?

**Comment by andimi3** [comment]
> ```
> 0.0.0.0
> ```

hey, is the key and cert files supposed to be a single line and stripped of "------begin" for the proper key and cert to be read or does that matter?

**Comment by andimi3** [comment]
> Incase someone is still stuck, here's an working example based on the Ratchet hello world app:
> 
> ```
> $app = new \Ratchet\Http\HttpServer(
>     new \Ratchet\WebSocket\WsServer(
>         new \MyApp\Chat()
>     )
> );
> 
> $loop = \React\EventLoop\Factory::create();
> 
> $secure_websockets = new \React\Socket\Server('0.0.0.0:8081', $loop);
> $secure_websockets = new \React\Socket\SecureServer($secure_websockets, $loop, [
>     'local_cert' => 'path-to/public.pem',
>     'local_pk' => 'path-to/private.pem',
>     'verify_peer' => false
> ]);
> 
> $secure_websockets_server = new \Ratchet\Server\IoServer($app, $secure_websockets, $loop);
> $secure_websockets_server->run();
> ```
> 
> You may want to add `'allow_self_signed' => true,` in the ssl settings array if you're using it locally.

@stefblokdijk
do the the private key and crt files have to be stripped of any additional text like "-----begin"  and new lines for it to work right? Or can I leave the additional default text there and will everything work fine..

**Comment by FilRav** [comment]
.pem and .crt files don't need to be manually modified. They are ready to be used as obtained by openssl.
