### ISSUE TITLE
guzzle/http  is abandoned

### ISSUE THREAD

**Issue by broneq** [ratchetphp/Ratchet#490]
When I use ratchet i have below warnings in composer:

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle                                                                                                                                                              instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle                                                                                                                                                              instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle                                                                                                                                                              instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle i                                                                                                                                                             nstead.

**Comment by cboden** [comment]
https://github.com/ratchetphp/Ratchet/search?q=abandoned&type=Issues&utf8=✓

**Comment by PrivateHeberg** [comment]
yes but with compoer i have a error ?

**Comment by cboden** [comment]
It's not an error it's just a warning. Everything still works.
