### ISSUE TITLE
Ratchet doesnt work if PCs behind the proxies

### ISSUE THREAD

**Issue by gwyneblaidd** [ratchetphp/Ratchet#491]
Hi guys! It seems that ratchet doesnt work if PCs behind the proxies? Al mobile GSM operators 3G/4G work via proxy. And it seems that on mobiles we cannot use Ratchet?  I am  even now currently trying to run demo on socketme.so from the LAN behind local proxy and it doesnt work. It generates the same error - cannot connect via the proxy. In the attachments - printscreen with the error in the latest Google Chrome browser

![image](https://cloud.githubusercontent.com/assets/6455432/23021792/64690806-f456-11e6-88fc-f1c9bc8c55b3.png)

**Comment by cboden** [comment]
The proxy you are using probably doesn't support or allow WebSockets. There is nothing Ratchet can do if your proxy is blocking my server.  ;)
