### ISSUE TITLE
Allow react/socket 0.5

### ISSUE THREAD

**Issue by andig** [ratchetphp/Ratchet#492]
Today, react has released `http@0.5` which requires `socket@0.5`. This has effectively locked users of ratchet + react/http out of composer installs.

The [changelog](https://github.com/reactphp/socket/blob/master/CHANGELOG.md) has various breaking changes though.

Would it be possible- I cannot judge the impacts- to support `socket@0.5`, too?

**Comment by cboden** [comment]
refs #485 

I'll look into this soon

**Comment by andig** [comment]
Closing in favour of #485. Would really like to see this merged ;)
