### ISSUE TITLE
How to close Server connection 

### ISSUE THREAD

**Issue by shaunshau** [ratchetphp/Ratchet#495]
I have started a server connection to port 7000 in localhost with below code. Now how can I close this connection. 
```php
<?php
use Ratchet\Server\IoServer;
use MyApp\Chat;
    require dirname(__DIR__) . '/vendor/autoload.php';
    require dirname(__DIR__) . '/src/MyApp/Chat.php';

    $server = IoServer::factory(
        new Chat(), 
        7000
    );

    $server->run();
```

**Comment by cboden** [comment]
Do you want to close an individual client that has connected or do you mean to stop the server from running?

**Comment by shaunshau** [comment]
I want to stop server from running. In this scenario I have IP(Hostname) and port with me, So how can I stop that? As I know How to stop individual clients that has connected

**Comment by shaunshau** [comment]
I am trying to use addPeriodicTimer. And I have written condition in onMessage service. According to JSON request, I am saving data in DB and I am giving response. How to fetch only latest message in OnMessage service? Because I am also getting old messages in that Service

**Comment by cboden** [comment]
1. `$server->loop->stop()`
2. Yes, this is the default behaviour of Ratchet. For production I recommend using something like supervisord to ensure your server is always running. 
3. MySQL connections aren't meant to be long lived. You will probably need to re-establish their connections.
