### ISSUE TITLE
websocket lunch on remote host

### ISSUE THREAD

**Issue by mkeyno** [ratchetphp/Ratchet#496]
hi, I'm sorry to open ticket for my question , but actually I'm not pro in php and with your instruction not figure out how to install it in my remote directory host , and really appreciate for couple of hints , in fact I've tried to hook url on my host to the Telegram webhoock call back bot, so at first step new update data inserted to MySQL database then websoket server give the update data to designated live client .
the problem is I bought the domain & host which is has Cpanel and I don't know how to configure my php server to lunch websocket service 
can you tell me which files should be copy in designated host URL and what files should be modified?
Thanks
My Cpanel images
[image](https://cloud.githubusercontent.com/assets/6232001/23093326/57fb941c-f5f5-11e6-82cc-33b0f8bb0195.jpg)

[image](https://cloud.githubusercontent.com/assets/6232001/23093360/e1f67326-f5f5-11e6-8ef8-290754664d77.jpg
)

**Comment by Mecanik** [comment]
Ratchet will not work on shared hosting, unless you have SSH access. You need to "run" the server via command line.
