### ISSUE TITLE
Question about telnet and WsServer

### ISSUE THREAD

**Issue by 3mmarg97** [ratchetphp/Ratchet#502]
Hello , why I can't connect to the server using "telnet" command after  the "[Next Steps](http://socketo.me/docs/hello-world#nextsteps)"  , I am working on a project , And I need to send data from terminal using telnet to the connected web browsers .
thanks :+1:

**Comment by cboden** [comment]
The telnet test part in the tutorial is over a raw stream. Once you add the `Http` and `WsServer` layers the client is then expected to speak the WebSocket protocol, which is an updated HTTP protocol. 

If you want to test via terminal against a WebSocket server I suggest writing a script using [Pawl](https://github.com/ratchetphp/Pawl)

**Comment by 3mmarg97** [comment]
Thanks but I don't want to test from terminal . I have a gps device sending data using tcp protocol . So I want to preview this data on my browser and send other data from browser to my gps device . Is there any way to do that ? (I can't change my gps device code)

**Comment by cboden** [comment]
You can do this using the React EventLoop that power Ratchet. See [this tutorial](http://socketo.me/docs/push). Now, you won't use ZMQ but raw TCP instead. The tutorial is not exactly what you will do but the concept is the same in that you're communicating with different protocols and different servers/clients.

**Comment by 3mmarg97** [comment]
Oh thanks . Unfortunately its too late . I used Node.js with Socket.io to do this because . But I'll try using this soon in another project . thanks you any way this will be very useful for me for my next project
