### ISSUE TITLE
Upgrade dependencies to guzzlehttpd

### ISSUE THREAD

**Issue by innobrig** [ratchetphp/Ratchet#507]
Would it be possible to refactor the package to use guzzlehttp instead of guzzle? 

Composer reports the following: 
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by cboden** [comment]
It's a warning, not an error and is resolved in the 0.4 branch which is in RC stage. 

https://github.com/ratchetphp/Ratchet/issues?utf8=✓&q=abandoned
