### ISSUE TITLE
composer: Use guzzle/guzzle instead.

### ISSUE THREAD

**Issue by smellymoo** [ratchetphp/Ratchet#510]
using cboden/ratchet  v0.3.6

> Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
> Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
> Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
> Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

your website: http://socketo.me says install cboden/ratchet, but there is also ratchetphp/Ratchet on github, which is right?

**Comment by rbairwell** [comment]
The cboden/ratchet reference refers to the Composer Packagist package https://packagist.org/packages/cboden/ratchet - which is actually built from https://github.com/ratchetphp/Ratchet . So they are both correct.

I agree the guzzle code needs updating (hopefully to use the guzzlehttp library).

**Comment by cboden** [comment]
https://github.com/ratchetphp/Ratchet/issues?utf8=✓&q=is%3Aissue%20guzzle%20abandoned%20

It's not an error it's just a warning. Everything still works. The 0.4 branch addresses this.
