### ISSUE TITLE
Runtime check mbstring.func_overload

### ISSUE THREAD

**Issue by tom--** [ratchetphp/Ratchet#517]
Ratchet's mode of failure in the case that mbstring.func_overload is 7 (I only tested 7 and 0) on a run-time platform is inscrutable:

    HTTP/ 400 Invalid Sec-WebSocket-Key\r\n

#30 mentions checking mbstring.func_overload in unit tests but this isn't very useful for users of Ratchet. We don't usually run unit tests on dependencies in development and even less on platforms farther down the ops line. Each run-time environment has variables that even composer platform requirements cannot check.

Suggest adding a check for mbstring.func_overload != 0, perhaps in the WsServer constructor, and throw an exception, e.g. "Ratchet requires mbstring.func_overload=0"

**Comment by cboden** [comment]
There's a [check done](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/App.php#L69) in the optional `App` class. 

I completely agree with you, the check should probably go in `WsServer` instead as that's the component that requires proper UTF-8 encoding.

**Comment by tom--** [comment]
Great!

Btw the `3 !== strlen('✓')` check is a reliable test of the run-time platform only if you know the encoding of App.php is definitely correct. It's likely to be the case but isn't entirely safe to assume. `ini_get('mbstring.func_overload') !== "0"` has the virtue of being specific.

**Comment by cboden** [comment]
I believe in this case the implicit check is better. The size checks on WebSocket frames are in bytes and this check ensures that a known UTF-8 character that is to be 3 bytes is in fact so. Other than func_overload I don't *know* of another way to change that value but the implicit check would ensure the same.

**Comment by tom--** [comment]
> ...that a known UTF-8 character...

Once the file App.php is beyond your control this is an assumption, not a fact that the software knows. People can make mistakes that affect file encoding so the test multivalent.

You can resolve this by adding `bin2hex('✓') === 'e29c93'` to know that the string literal is U+2713 in UTF-8.
