### ISSUE TITLE
Awesome library but Documentation and Examples outdated.

### ISSUE THREAD

**Issue by infokani** [ratchetphp/Ratchet#519]

**Comment by cboden** [comment]
What specifically have you found that is outdated?

**Comment by infokani** [comment]
Sorry if i misunderstood. I saw in [github ](https://github.com/cboden/Ratchet-examples) that examples was updated 3 years ago.

**Comment by cboden** [comment]
yeah...I need to get around to updating that repository...the website http://socketo.me is the best place for documentation.
