### ISSUE TITLE
How to use Ratchet in Android 4.2.2 webview ?

### ISSUE THREAD

**Issue by kareti** [ratchetphp/Ratchet#522]
Hello,
My chat application using Ratchet is working in all modern browsers.
It is working very well in android 6.0 webview , android 5 webview etc...

In Android 4.2.2, it is working in browsers.
in Android 4.2.2 webview, Ratchet is not responding.
It don't show any output in javascript after 
var conn = new WebSocket('wss://website.com');
conn.onopen
conn.onerror
conn.onclose
There is no response.

Please suggest how to use Ratchet in in Android 4 webview.
Thanks

**Comment by samizdam** [comment]
As you can check on http://caniuse.com/#search=websocket android support websocket from version 4.4.
