### ISSUE TITLE
How can I limit the amount of incoming queries?

### ISSUE THREAD

**Issue by doctor911** [ratchetphp/Ratchet#523]
Greetings!

Is there any way to limit the amount of messages coming from connected users? 
I'd like to make a restriction for every user on 2-3 queries per second. 
I'm making an MMO browser game, and the users flooding the WebSocket server with queries might become a real problem (whether these are actual queries or fake ones, sent in order to cause lag). It would be nice if Ratchet could reject user requests if they are coming too frequently.

Thanks!

**Comment by hdogan** [comment]
You can implement your own rules with token buckets. See https://github.com/bandwidth-throttle/token-bucket

**Comment by cboden** [comment]
Utilizing an algorithm such as the one @hdogan provided inside a `MessageComponentInterface` decoration layer is a good solution. See [IpBlackList](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Server/IpBlackList.php) as an example of a basic security layer. For your use case though make sure you put it after the `WsServer` layer.
