### ISSUE TITLE
How to close a connection from javascript?

### ISSUE THREAD

**Issue by kareti** [ratchetphp/Ratchet#525]
Hello,
I am running a chat service.
most of my members use mobile.
Even after they move away from my application, their connection is still active in ratchet.

I have the following javascript code.
Please tell me what code should I place in chatclose(); 

 window.onblur = timelyExit;  
 function timelyExit()
  {
        refInterval = 1;

        // change this to trigger some kind of inactivity timer
        setTimeout(function() { 

		chatclose(); 

		}, 10000);

  }

Also, is this the right method ?
Please suggest.
Thanks

**Comment by kareti** [comment]
can I just place 

conn.close()

in the timer above.
Also, please suggest me if the above code works in all browsers.
Thanks.

**Comment by cboden** [comment]
Yup, `conn.close()` is correct.
