### ISSUE TITLE
how to know if a user is still connected or not?

### ISSUE THREAD

**Issue by kareti** [ratchetphp/Ratchet#526]
Hi,
I have a chat application using ratchet php.
it works well. 

However, connections are not being closed on mobile devices.
How to know if user is still connected?

I read words like ping-pong, heartbeat etc.

Please suggest a good way to implement any technique to find if user is still connected or not.

Thanks

**Comment by mtancoigne** [comment]
>  I read words like ping-pong, heartbeat etc.

You can set up a "ping-pong" test : the server sends a ping to the client and the client should answer "pong". if it takes too much time to answer, you can disconnect it.

Sadly, i'm new to websockets, so I don't have any example to provide.

**Comment by filipecoelho** [comment]
In branch 0.4 it has this implementation

**Comment by theborland** [comment]
In branch 0.4 (is that stable enough to use?) is this feature - to auto-close connections autoimplemented  or is that something I need to do?
Thanks

**Comment by pritammore** [comment]
Hi @filipecoelho @cboden 

I am getting the Handshake failed Error.
currently, lua-websockets is configured in openwrt OS and trying to connect Server done using Ratchet-Websockets 0.4 dev.

Below error is received.
Websocket Handshake failed: Invalid Sec-Websocket-Accept (expected N9CxZL/lcu6fXwp/V9XHv9kIX6w= got nil)


but while using Ratchet-Websocket master branch. It works fine but here I dont have keepAlive functionality.

Pritam

**Comment by cboden** [comment]
With the release of 0.4 use the [`enableKeepAlive`](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsServer.php#L198) method on WsServer or using the App helper class mentioned in the README will automatically enable this.
