### ISSUE TITLE
how to close connection associated with a $conn->resourceID ?

### ISSUE THREAD

**Issue by kareti** [ratchetphp/Ratchet#528]
Hi,
I have a one to one chat application.
When a member A sends chat message to another member B, I will check the last time B was active.
If B is inactive, I want to close the connection of B.
I have the  $conn->resourceID number of B.

How to close B  $conn

Please suggest.
Thanks

**Comment by doctor911** [comment]
You may create an array with ResourceIDs as keys and connections as values.

class Chat implements MessageComponentInterface {
    protected $clients;
    protected $id2conn;

    public function __construct() {
        $this->clients = new \SplObjectStorage;
        $this->id2conn = array();
        ...
    }

    public function onOpen(ConnectionInterface $conn) {
        $this->clients->attach($conn);
        $this->id2conn[$conn->resourceID] = $conn;
        ...
    }
    ...
}

So you can use this to close connection:
$this->id2conn[$id]->close();
where $id is known resourceID.
