### ISSUE TITLE
 Connection.js:7 WebSocket connection to 'ws://192.168.1.255:2000/' 

### ISSUE THREAD

**Issue by El-Hendawy** [ratchetphp/Ratchet#529]
Connection.js:7 WebSocket connection to 'ws://192.168.1.255:2000/' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE
Connection @ Connection.js:7
(anonymous) @ mainCtrl.js:11
e @ angular.min.js:39
Q.instance @ angular.min.js:80
N @ angular.min.js:61
g @ angular.min.js:54
(anonymous) @ angular.min.js:53
(anonymous) @ angular.min.js:19
$eval @ angular.min.js:134
$apply @ angular.min.js:135
(anonymous) @ angular.min.js:19
e @ angular.min.js:39
d @ angular.min.js:19
zc @ angular.min.js:20
Yd @ angular.min.js:18
(anonymous) @ angular.min.js:289
j @ jquery-2.1.1.js:2
fireWith @ jquery-2.1.1.js:2
ready @ jquery-2.1.1.js:2
J @ jquery-2.1.1.js:2
angular.min.js:108 Error: [$compile:tpload] http://errors.angularjs.org/1.4.1/$compile/tpload?p0=http%3A%2F%2Flocalhost%2Fapi%2FviewPost&p1=404&p2=Not%20Found
    at angular.min.js:6
    at angular.min.js:145
    at angular.min.js:120
    at m.$eval (angular.min.js:134)
    at m.$digest (angular.min.js:131)
    at m.$apply (angular.min.js:135)
    at l (angular.min.js:87)
    at N (angular.min.js:91)
    at XMLHttpRequest.x.onload (angular.min.js:92)
(anonymous) @ angular.min.js:108
(anonymous) @ angular.min.js:80
(anonymous) @ angular.min.js:120
$eval @ angular.min.js:134
$digest @ angular.min.js:131
$apply @ angular.min.js:135
l @ angular.min.js:87
N @ angular.min.js:91
x.onload @ angular.min.js:92

**Comment by Mecanik** [comment]
Make sure your "server" is listening on 192.168.1.255 because by default it will use 0.0.0.0

**Comment by cboden** [comment]
Please provide more information to help troubleshoot. Server code and client code would be required.
