### ISSUE TITLE
Child Process Blocks during onMessage

### ISSUE THREAD

**Issue by istvanskeri** [ratchetphp/Ratchet#534]
I'm using ReactPHP Child Process library to start a long running php task that sends percentage completed back to parent. The child process starts when a socket message is received from user.

The issue is that I am not seeing percentages come through on the client browser until the very end of the process. In the terminal i do see the percentages coming async from the child process as they are printed in the terminal with the echo $percent in the code below.

```php
public function onMessage(ConnectionInterface $from, $msg) {
        $numRecv = count($this->clients) - 1;
        echo sprintf('Connection %d sending message "%s" to %d other connection%s' . "\n"
            , $from->resourceId, $msg, $numRecv, $numRecv == 1 ? '' : 's');
                               
        $loop = Factory::create();
        $process = new Process('exec php pong2.php');
        $process->on('exit', function ($code) {
            echo 'EXIT with code ' . $code . PHP_EOL;
        });                    
        
        $process->start($loop);
        $process->stdout->on('data', function($percent) {
            echo $percent;      
            foreach ($this->clients as $client) {
                $client->send($percent);
            }
        });

        $process->stdin->write("start");
        $loop->run();
    }
```

**Comment by cboden** [comment]
1) Creating any subsequent event loops will block the first one. onMessage isn't blocking your script your second loop is. You should be injecting the existing loop that Ratchet is running on if you need access to it.

2) I would recommend spinning up a Child Process with the construction of your app. Setting up and tearing down a new process per message received will be taxing on your system. Use this initial child process to do blocking work as needed. 

@WyriHaximus may be able to chime in with a link to an example of this behaviour.

**Comment by WyriHaximus** [comment]
@cboden This is probably related to https://github.com/WyriHaximus/reactphp-child-process-messenger/issues/8 and if @istvanskeri is still using my package there is a loop running inside it so any blocking operations will also block that loop. Now once the operation reaches the end and marks it done or failed the child does nothing until it receives the next operation. Now that is the moment the loop fully starts spinning again and starts delivering the messages to the parent.

**Comment by istvanskeri** [comment]
@WyriHaximus 

I stopped using child-process-messenger and now I'm only using child process. 

Yes, onMessage is not blocked because I am able to get the percentages async in the terminal. the 'echo $percent' in stdout on data is working great.  What seems to be blocking though is  

$client->send($percent);

it only sends the percents when the child process is finished and it sends it all at once. 

```

$process->stdout->on('data', function($percent) {
            echo $percent;     
            $this->percent = $percent;      
            foreach ($this->clients as $client) {
                $client->send($percent);        
            }                  
        });       

```

**Comment by istvanskeri** [comment]
@cboden 

I see what you're saying, $process's loop is blocking the parent loop. Is there an example anywhere where i can see how to inject the parent loop into the child process? Thanks

**Comment by istvanskeri** [comment]
This is a major blocker for me, any chance either of you can offer some advice on how i can send percentages back to user async? I thought that the idea behind child process was to not block the parent, yet the parent is blocked at the moment

**Comment by WyriHaximus** [comment]
@istvanskeri Child processes won't block on the parent side a long as you use the same loop for everything. But if you use a separate loop your new loop will block the other loop making it look that child process.

Would it be possible to share more code so we can help you get the loop into `onMessage`?

**Comment by istvanskeri** [comment]
@WyriHaximus 

I got this working today, was able to pass in the loop to the Chat class and create the child process off of that loop. Thanks for all your help!

**Comment by WyriHaximus** [comment]
Glad to hear 🎉!

**Comment by mostafaahamidmanon** [comment]
Here are some non-blocking code with Ratchet
```
<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
namespace App;
use Ratchet\MessageComponentInterface;
use Ratchet\ConnectionInterface;
/**
 * Description of Socket
 *
 * @author Tasneem
 */
class Socket implements MessageComponentInterface{
    
    /**
     *
     * @var $clients array of each client
     */
    protected $clients;
    protected $loop;
    
    /**
     * constructor
     */
    public function __construct(\React\EventLoop\LoopInterface $loop) {
        $this->loop = $loop;
        $this->clients = new \SplObjectStorage;
    }
    
    /**
     * 
     * @param ConnectionInterface $conn attaches clients
     */
    public function onOpen(ConnectionInterface $conn) {
        echo "\nNew Client Connected...\n";
        $this->clients->attach($conn);
    }
    
    /**
     * 
     * @param ConnectionInterface $from
     * @param $msg
     */
    public function onMessage(ConnectionInterface $from, $msg) {
        
        
        echo "\nNew Message: " . $msg . "\n";
        foreach($this->clients as $clientSocket){
	    $this->loop->futureTick(function() use ($clientSocket){
		$clientSocket->send("\ndata data start\n");
	    });
	    $this->loop->futureTick(function() use ($clientSocket){
		$clientSocket->send("\ndata data two\n");
	    });
	    $stream = new \React\Stream\ReadableResourceStream(fopen(storage_path('logs/laravel.log'), 'r'), $this->loop);
  	    $loop = $this->loop;
            $stream->on('data', function($data) use ($clientSocket, $loop){
		$loop->futureTick(function() use ($clientSocket, $data){
			$returnValue = file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log'));
			$clientSocket->send($returnValue);
			$clientSocket->send($data);
		});
            });
            $stream->on('end', function() use ($clientSocket, $loop){
                $loop->futureTick(function() use ($clientSocket){
			$clientSocket->send('finished');
		});
            });
            $this->loop->run();
        }
    }
    
    /**
     * 
     * @param ConnectionInterface $conn
     */
    public function onClose(ConnectionInterface $conn) {
        echo "\nConnection Closed \n";
        $this->clients->detach($conn);
    }
    
    /**
     * 
     * @param ConnectionInterface $conn
     * @param \Exception $e
     */
    public function onError(ConnectionInterface $conn, \Exception $e) {
        echo "\nError on Connection: {$e->getMessage()} on line {$e->getLine()} in file {$e->getFile()} \n";
        $conn->close();
    }
}
```

**Comment by chintan13** [comment]
@istvanskeri would you please post your working example here!
