### ISSUE TITLE
RedisSessionHandler how I can use it

### ISSUE THREAD

**Issue by romanlex** [ratchetphp/Ratchet#536]
Hello. In page i see http://socketo.me/docs/sessions
```(in development) RedisSessionHandler```
Tell me please how I can use phpredis library for this? https://github.com/phpredis/phpredis

**Comment by cboden** [comment]
I haven't put any work into Session handling in a while. phpredis won't work properly as it's I/O is blocking. A good amount of work will need to be done with an async client to make this function.
