### ISSUE TITLE
 PHP Fatal error: Allowed memory size of exhausted - close connection?

### ISSUE THREAD

**Issue by theborland** [ratchetphp/Ratchet#537]
Im running ratchet 0.3 and over time, this error always pops up.  All my users are on mobile devices and Im wondering if the connections are not closing properly.  I saw other users with this issue and it sounds like maybe going to 0.4 could fix that - any ideas? Do I need to do anything so these users are really gone (ping/pong -> if so how - I couldnt find any info about this)? 
Thanks,
JB

**Comment by cboden** [comment]
Updating to 0.4 is certainly a good idea with the number of improvements to it. 

Running out of memory could be a number of things. If you have *a lot* of connections and your memory limit for PHP is really small you may need to increase the limit. 

Another problem could be a memory leak. React and Ratchet have been thoroughly tested so if it's a memory leak the most likely culprit would be your application built on top of it. If you're keeping lookups in your app class during the lifespan of a connection make sure you're cleaning up resources in your `onClose` method so garbage collection can take affect.

**Comment by kusnir** [comment]
I have the same problem. If there are only push clients, the memory usage of server is stable. But when I run one client, every message increase memory usage about 4576B. To simulate:
1. run server: php server.php
2. run push client: php client-push.php
3. run client (it can be also web browser connected to ws://localhost:8080): php client.php

In the server output you will see something like:
1 / 1917120 / 4194304 / 4576
<count of clients> / <memory usage> / <memory usage real> / <increase memory compared with previous run>

After while the server will finished with message: Fatal error: Allowed memory size of 4194304 bytes exhausted (tried to allocate 4096 bytes) in ...vendor\react\stream\src\WritableResourceStream.php on line 55

I am running it on Windows 7 Enterprise, PHP Version 7.2.5.

[client.txt](https://github.com/ratchetphp/Ratchet/files/1950945/client.txt)
[client-push.txt](https://github.com/ratchetphp/Ratchet/files/1950946/client-push.txt)
[server.txt](https://github.com/ratchetphp/Ratchet/files/1950947/server.txt)

**Comment by mbonneau** [comment]
There has been a new release of RFC6455 (https://github.com/ratchetphp/RFC6455/releases/tag/0.2.4) that includes @kusnir's fix. (Thanks @kusnir!)

@theborland - if there are further problems please open a new issue.
