### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by istvanskeri** [ratchetphp/Ratchet#538]
I'm getting a segmentation fault error from my ratchet server. 

Ubuntu 14.4
memory_limit = 128M
PHP 5.5.9

I'm using the following versions of ratchet:

"cboden/ratchet": "^0.3.6",     
"react/child-process": "^0.4.3"

**Comment by istvanskeri** [comment]
the seg fault is happening because of this line: 

$process->stdin->write(true);

I am sending a stdin to the child process.

**Comment by WyriHaximus** [comment]
Well you can't write a boolean to over a stream. Also have you tried updating to the latest 5.5 for bugfixes in PHP it self?

**Comment by istvanskeri** [comment]
I'm actually passing a json string.

$process->stdin->write($json);

 Do you mean updating PHP 5.5.9 with the latest patches?

**Comment by cboden** [comment]
Any update on this?
