### ISSUE TITLE
Ratchet + mbstring.func_overload

### ISSUE THREAD

**Issue by nkizza** [ratchetphp/Ratchet#539]
Hey! Just wanted to contact you to say, I was suffering from ratchet returning me 400 on connection request. The reason was, when HandshakeVerifier tries to verify the key, strlen returns weird values due to mbstring.func_overload value 2 or more. So maybe you make it clear for future users that mbstring.func_overload could be an issue?

Also, awesome library, and you sir are awesome. thank you!

**Comment by cboden** [comment]
Thank you for the kind words! There's a check in App.php about this but that doesn't cover all scenarios. 0.4 will have the check against this moved in WsServer so it will always be caught.
