### ISSUE TITLE
Reconnection feature or bug ?

### ISSUE THREAD

**Issue by Mecanik** [ratchetphp/Ratchet#541]
I noticed in my tests that if the server crashes or shuts down, "users" will reconnect automatically to the server. My question is, is this a feature? or is it a bug? If it's a feature, do we have control over it ?

Many thanks

**Comment by speekadievs** [comment]
how your users connecting to the server? the server can't automatically reconnect with the user, only the user itself can do it (javascript). Do you use some kind of a library for your user connections or do you use the native javascript WebSocket?

**Comment by Mecanik** [comment]
@speekadievs - I am using the native WebSocket, and my users get connected to the server once the page fully loaded ( think of it as a chat server ). What's amazing is that my server crashed a couple of times due to exceptions since I am still developing, and as soon as the server was restarted I did not even get to "reload" the page to connect again because it automatically reconnected o.O

This is a good thing, a very good thing but I need to know if it's stable otherwise I need to develop myself something to reconnect...

**Comment by speekadievs** [comment]
@Mecanik in my tests I've seen that if the sometimes when a server gets an exception, only one connection actually is dropped (the one who caused the exception) and all other connections aren't bothered. So maybe the same thing is happening to you, because the native js WebSocket doesn't have reconnecting built in and the server for sure can't start a connection with the client, the client must start the connection

**Comment by Mecanik** [comment]
@speekadievs I don't know what did you test, but in my case when there was an exception the server crashed. I am using: https://github.com/pmill/php-chat

**Comment by speekadievs** [comment]
@Mecanik still, I don't see any reconnection functionality. I probably wouldn't trust that the reconnection will always happen to you, so it's best to create the functionality yourself on the client side so you will always be sure what is happening

**Comment by Mecanik** [comment]
@speekadievs Indeed you are right, thanks for that. This is the least of the problems I have... I`m struggling to "bypass" the 1024 connections limit... https://github.com/ratchetphp/Ratchet/issues/300

Do you have any idea ? I would very much appreciate it....

**Comment by cboden** [comment]
1024 connections is a limitation of the default StreamSelectLoop and default configuration of most others. You need to install an extension, such as ExtEventLoop, and use its corresponding class. See https://reactphp.org/event-loop/#exteventloop for more details.
