### ISSUE TITLE
How to install 0.4

### ISSUE THREAD

**Issue by CyanoFresh** [ratchetphp/Ratchet#542]
Hello. I want to try 0.4 version, but I can't install it via composer. I've tried with `"dev-0.4"` version, tried adding to the `"repositories"` of composer.json but it can't install it. Is it possible to install 0.4 without hard-copying sources?

**Comment by samizdam** [comment]
Hm... Branch 0.4 exists: https://github.com/ratchetphp/Ratchet/tree/0.4
It is not Ratchet issue, but it is composer feature. Read this topic https://getcomposer.org/doc/articles/versions.md#branches in the composer docs.

Can you present composer.json fragment and error output from terminal?

**Comment by CyanoFresh** [comment]
```json

  "require": {
...
    "cboden/ratchet": "dev-0.4",
...
}
...
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/ratchetphp/Ratchet"
    }
  ],
...
```
```cmd
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package cboden/ratchet dev-0.4 exists as cboden/ratchet[0.1.1, 0.4.x-dev, dev-master, dev-wamp-sync-bug, v0.1, v0.1.2, v0.1.3, v0.1.4, v0.1.5, v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8, v0.3.0, v0.3.1, v0.3.2, v0.3.3, v0.3.4, v0.3.5, v0.3.6] but these are rejected by your constraint.

```

**Comment by samizdam** [comment]
It's strange... I reproduce this issue. May be it's composer bug. 
But you can get required version (revision 4ac1f914f3150c9b35d2f5bf794363561ac3bde9) with 
```
  "require": {
    "cboden/ratchet": "0.4.x-dev"
  }

```
without repository: this release exists on packagist: https://packagist.org/packages/cboden/ratchet#0.4.x-dev

**Comment by CyanoFresh** [comment]
thanks. Works with `"0.4.x-dev"`
