### ISSUE TITLE
Remove or modify the initial message

### ISSUE THREAD

**Issue by 00byte** [ratchetphp/Ratchet#545]
Hello,

When a new Socket connection is created, the server automatically sends a message like this one:
[0,"2104043690597efd5ceff74868485635",1,"Ratchet\/0.3.6"]

Is there a way to remove this initial message?

While searching for a solution (I don't remember where) I read that a first message is required because otherwise the client will not know if the connection has been created correctly. If that's true, is there a way of sending a custom message or at least removing the version?

Thanks!

**Comment by Mecanik** [comment]
I never seen such message in my setup, where do you get that ? I guess it can be changed eventually.

**Comment by cboden** [comment]
There is no public method to change this as it is required by the WAMP protocol. To do this without changing the source code you could wrap the WampService component with your own that would intercept the sent message and you could replace it with your own.
