### ISSUE TITLE
Could non-string data supplied to send() result in an exception?

### ISSUE THREAD

**Issue by halfer** [ratchetphp/Ratchet#547]
I am sending data to a browser JS SPA, and in one of my send calls, I had a bug. On a `ConnectionInterface` variable called `$conn`, I essentially did this:

```
$conn->send(['message' => 'Useful stuff', ]);
```

The error there of course is that an array was passed when I should have supplied a string. Could an `is_string()` test be supplied here, and an exception thrown if it is not a string? I agree the bug was entirely my doing, but a proper exception may have saved some dev time here.

As it stands it just raises notices and warnings:

```
[12-Aug-2017 11:34:47 UTC] PHP Warning:  strlen() expects parameter 1 to be string, array given in /var/www/controller/vendor/cboden/ratchet/src/Ratchet/WebSocket/Version/RFC6455/Frame.php on line 76
[12-Aug-2017 11:34:47 UTC] PHP Notice:  Array to string conversion in /var/www/controller/vendor/cboden/ratchet/src/Ratchet/WebSocket/Version/RFC6455/Frame.php on line 90
```

**Comment by cboden** [comment]
I'm not a fan of doing this type of check. As you said the API is clearly defined and to start putting type checks where a type is specified where is the line drawn? 

Given the API docs this is something an IDE should catch. 

This isn't helpful right now but I plan on updating Ratchet to PHP7 for 0.5 which will have strict type interfaces.

**Comment by halfer** [comment]
Fair enough. My use case was buried in a queue, where it was easy to ignore the generated warnings/notices. Probably need some more unit/functional tests.... :smile_cat:
