### ISSUE TITLE
Websocket data compression

### ISSUE THREAD

**Issue by akshay2193** [ratchetphp/Ratchet#548]
Hey,

I am using ratchet 0.3.6 and wanted to know if it supports permessage-deflate extension, I could find this only for 0.4?
If yes how do I  enable it?

**Comment by cboden** [comment]
This is currently open in a PR in the underlying library. It's not available at all in 0.3 but if you're using 0.4 you could pull in the branch of the PR to use it.

**Comment by akshay2193** [comment]
Hey just one more thing, what is the tentative timeline to  release a stable version of 0.4?

**Comment by cboden** [comment]
0.4 is considered stable, just not released yet. My day job has been tying me down but with 2 weeks of vacation coming up I plan on updating the website documentation and releasing 0.4

**Comment by akshay2193** [comment]
Cool. Thanks
