### ISSUE TITLE
Maximum concurrent connection on a digitalocean vps

### ISSUE THREAD

**Issue by manjok** [ratchetphp/Ratchet#549]
Hi, I have setup ratchet on digitalocean vps and its running. 
However I worry that the vps might not be able to handle large number of concurrent connection. 
Can anyone give me a rough number on how much can the vps handle? 

vps spec - 
1Gb memory 
1 Cpu

**Comment by halfer** [comment]
Why not use an on-server test script to find out? Use a WebSocket client library to create a large number of connections, and configure your app to send simple ack replies back. You'll know when there's an issue if you get problems creating a new connection.

I'd guess your first errors would come in at 1,000 simultaneous connections, but there's things you can tune to improve that. Try it!

**Comment by cboden** [comment]
Off the top of my head: several thousand. As Jon suggested, testing your own limits is the best way to find out.
