### ISSUE TITLE
Can Ratchet server send a message to client (for example, iPhone App)? 

### ISSUE THREAD

**Issue by aleksey-kozakov** [ratchetphp/Ratchet#55]
Hello, Chris. First of all I want to say 'thank you' for your work. 

I've found out that 'MessageComponentInterface' has 'onMessage' function that is called every time a client sent a massage. And the server can send an answer back to this client (and other connected clients).

But I need an ability to send a massage from server to client without client send a massage first.

For example. iPhone App has a feed of photos. And when a new photo is added by another iPhone App, this photo will be upload to the server, processed, and need to be shown on the first iPhone App immediately after processing. So, the Ratchet server has to check for new photos and send this photo to  iPhone App. Of course, Ratchet server has not to check for new photo, but it need to send a new data (photos) to iPhone Apps. 

How can I solve this problem? Thank you.

**Comment by harveyslash** [comment]
how can I use push messaging without using wampinterface(i.e. i want to use messagecomponentInterface) ? I want to use this for iOS , and there is no library that supports wamp v1 in iOS
