### ISSUE TITLE
getContents() returns weird characters

### ISSUE THREAD

**Issue by Tretiakoff** [ratchetphp/Ratchet#550]
Hi, 

I’m on Ubuntu, i have PHP 7.0.18 and I installed "cboden/ratchet":"0.4.x-dev". 

When I send this from client side : 

 var data = { "message" : "Hello" };

I get this on server side: 

b"ü\x13{"message":"Hello"}"

(i'm using getContents() method of MessageInterface) 

Is there any explication? How can I fix it?

Thanks

**Comment by cboden** [comment]
You want to call [`getPayload()`](https://github.com/ratchetphp/RFC6455/blob/master/src/Messaging/Message.php#L78) instead. `getContents()` returns the raw data of the message including the first two bites detailing metadata about the message.

**Comment by Tretiakoff** [comment]
Thank you :)
