### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by CyanoFresh** [ratchetphp/Ratchet#552]
Hello. I've been using Ratchet for a while but only now I am realizing doing something wrong. 
In the examples, Chat application's business logic located in the MessageComponentInterface. But if there will be more than just sending messages? Like calculating or game's logic? If store this in the server class - it will become whery big.
Can you please explain me how to organize my code with this library?
Sorry for English, hope you understand me

**Comment by samizdam** [comment]
If you want make monolithic application, you can put Domains classes and Business logic services separately and inject its into thin Ratchet controllers. 

Or, if your application are really big, look to micro services: your Web Socket Server can be only simple dispatcher between frontend and backend. Your "hard" logic can be processed in standalone services. WebSocket can be only gateway for web clients, and proxy all events and requests via some event bus (like AMQP) to backend. 

Sorry for my English too)

**Comment by cboden** [comment]
Well put @samizdam!

Take a look at the [socketo.me app](https://github.com/ratchetphp/socketo.me/blob/master/bin/run-all-the-things.php#L29) to see an example of layering some logic together in a single application.
