### ISSUE TITLE
cant establish connection to wamp with autobahn!

### ISSUE THREAD

**Issue by tsaritepe** [ratchetphp/Ratchet#555]
I want to use use RPC via autobahn to my ratchet wamp server. But i could not establish the connection.

My server side:

```php
$server = new \Ratchet\App('localhost',3000);
       $server->route('', new WebSocketController,['*']);
       $server->run();
```

My Class:
```php
use Ratchet\ConnectionInterface as Conn;
use Ratchet\Wamp\WampServerInterface;

class WebSocketController extends Controller implements WampServerInterface {
   public function onPublish(Conn $conn, $topic, $event, array $exclude, array $eligible) {
        $topic->broadcast($event);
    }

    public function onCall(Conn $conn, $id, $topic, array $params) {
        $conn->callError($id, $topic, 'RPC not supported on this demo');
    }

    // No need to anything, since WampServer adds and removes subscribers to Topics automatically
    public function onSubscribe(Conn $conn, $topic) {}
    public function onUnSubscribe(Conn $conn, $topic) {}

    public function onOpen(Conn $conn) {
        echo "opened";
    }
    public function onClose(Conn $conn) {
         echo "close";
    }
    public function onError(Conn $conn, \Exception $e) {
         echo $e;
    }
}
```

And the client side:
```javascript
 var autobahn = require('autobahn');
 var connection = new autobahn.Connection({url: 'ws://localhost:3000'});
 connection.onopen = function (session, details) {
   console.log(sessions);
};


connection.onclose = function (reason, details) {
   console.log(reason);
   console.log(details);
}
connection.open();

```

Here what i get from autobahn console.log:
unreachable
{ reason: null,
  message: null,
  retry_delay: 1.7760546390824472,
  retry_count: 1,
  will_retry: true }
unreachable

{ reason: null,
  message: null,
  retry_delay: 2.883934737974839,
  retry_count: 2,
  will_retry: true }

and what i get from serve side console output
opened close opened close

Anyone can help???

**Comment by cboden** [comment]
What does the Network tab in debug tools show? Try making a basic WebSocket connection, does that connect?

**Comment by tsaritepe** [comment]
According the search I did among issues, I should use autobahn 0.8.* since it doesnt support wamp v2. I could not install that version via npm. The problem was probably this. I solved it by using thruway. 

Thanks.

**Comment by alcalyn** [comment]
Yes it is, I do so. Autobahn 0.9+ implements wampv2, we have to use autobahn 0.8, and I also don't find it on npm. Instead I find [wamp1](https://www.npmjs.com/package/wamp1), but I haven't tested it yet.

**Comment by quickshiftin** [comment]
Hi - Might I suggest putting some sort of disclaimer on the bottom of the [push demo page](http://socketo.me/docs/push)? One's natural tendency when working with Javascript these days is to reach for libraries via npm. I personally wasted a good two hours trying to figure this out yesterday...

**Comment by topproto** [comment]
Hi, I have seriously been trying for days to get this stuff working, using different autobahns and ratchet php and thruway. Does anyone have a complete example of this? :)

**Comment by WyriHaximus** [comment]
@topproto If you use Thruway, use https://github.com/voryx/Thruway.js/ with it. Ratchet, when used with autobahn expects a version that supports WAMPv1, IIRC the current versions only support WAMPv2 at this point.

**Comment by hayden-t** [comment]
https://github.com/ratchetphp/Ratchet/issues/655#issuecomment-404176983
