### ISSUE TITLE
How do you pass query string onOpen?

### ISSUE THREAD

**Issue by totszwai** [ratchetphp/Ratchet#558]
Following your MyChat example:

	public function onOpen(ConnectionInterface $conn) {
		//$query = $conn->WebSocket->request->getQuery();
		//echo $query;
		//echo $query->get('hello');
		print_r($conn);

		$this->clients->attach($conn);
	}

Printing the $conn->WebSocket only gives:

    Class Object
    (
        [closing] =>
    )

On my Java side I'm connecting with this url:

    WebSocketContainer container = ContainerProvider.getWebSocketContainer();
    container.connectToServer(this, new URI("ws://localhost:8080/chat?hello=dsfdsf"));

What am I missing? This is with the latest version of Ratchet.

**Comment by totszwai** [comment]
Damn, looking around other places, saw this page: http://socketo.me/docs/router
Then instead of implementing the `Ratchet\MessageComponentInterface` like in the Chat example, I changed it to implement `Ratchet\Http\HttpServerInterface`.

Updated the `onOpen` signature to `onOpen(ConnectionInterface $conn, RequestInterface $request = null)`, I'm now able to get the `$request`.


Perhaps you could update the example to use the `HttpServerInterface` instead? I don't see the point of using MessageComponentInterface which hides the $request? Or add a snippet on showing how to access the query string too?

**Comment by cboden** [comment]
Apologies, the documentation could use some love. On the [WsServer](http://socketo.me/docs/websocket) page it shows the PSR Request object is set on the Connection via `$httpRequest`.

**Comment by alcalyn** [comment]
I do it here: https://github.com/eole-io/sandstone/blob/ed7f6a003431374658f1095aa4358b93960ae095/src/Websocket/Application.php#L54

to retrieve `access_token` in url, i.e `ws://localhost:8080/?access_token=xxx`

**Comment by alcalyn** [comment]
In fact, for the Ratchet 0.4, with the ReqeustInterface, I do this: https://github.com/eole-io/sandstone/blob/feature/wss/src/Websocket/Application.php#L48-L55
