### ISSUE TITLE
WAMP v2 supporting

### ISSUE THREAD

**Issue by idubinets** [ratchetphp/Ratchet#559]
Hi Guys, 

do you have a plan to support WAMP v2?

**Comment by alcalyn** [comment]
https://github.com/ratchetphp/Ratchet/issues/168

**Comment by cboden** [comment]
[This comment](https://github.com/ratchetphp/Ratchet/issues/168#issuecomment-55339203) gives information about v2 and Ratchet. 

[Thruway](https://github.com/voryx/Thruway) is v2 support with Ratchet.
