### ISSUE TITLE
socketo.me DNS address not found

### ISSUE THREAD

**Issue by chrisf121** [ratchetphp/Ratchet#561]
Error is:
`socketo.me’s server DNS address could not be found.`
`ERR_NAME_NOT_RESOLVED`

**Comment by WyriHaximus** [comment]
Just tried it and works without issues for me. Maybe there was a glitch, could you try again?

**Comment by cboden** [comment]
Also tested and was able to access the site. Can you confirm if you're still not able to reach it?

**Comment by chrisf121** [comment]
It's now accessible. Not sure what happened.
I'll close this now.
