### ISSUE TITLE
[React/Socket/Server]: Can not create socket server

### ISSUE THREAD

**Issue by karborator** [ratchetphp/Ratchet#564]
I'm using Fedora 26 with turned off selinux

When I try to create new instance of
new \React\Socket\Server( "127.0.0.1:5555", $loop);

[RuntimeException]
Failed to listen on "tcp://127.0.0.1:5555": Address already in use

$ sudo lsof -i tcp:5555
$

**Comment by cboden** [comment]
reactphp/socket#119
