### ISSUE TITLE
WAMP2 2017

### ISSUE THREAD

**Issue by dartkinselok** [ratchetphp/Ratchet#566]
Hello! We are using your awesome project for our high-load service and and would like to know if you are planning to implement the WAMP2 protocol in Ratchet? I was very interested in this question, since the repository again became active and new commits are appearing now. Thanks in advance!

**Comment by cboden** [comment]
Ratchet is not going to support WAMPv2. [Thruway](https://github.com/voryx/Thruway) solves this.

**Comment by dartkinselok** [comment]
Thank you for your answer! Another question. If I correctly understand, Thruway based on Ratchet. Is there any migration from Ratchet to Thruway walkthrough or how to migrate painless? Thanks :)

**Comment by cboden** [comment]
Yes, Thurway is built on top of Ratchet.

As for migration, I'm not sure...ping @mbonneau  😀
