### ISSUE TITLE
Unable to connect to my websocket when i moved it from localhost to my online host

### ISSUE THREAD

**Issue by Deewai** [ratchetphp/Ratchet#567]
The websocket was working perfectly when on localhost but when i moved it to an online host, i couldn't connect to it again. Please i'm lost i dont know what is wrong and i'cve spent a lot of time trying to fix this. I've been on this for over a month now. Please help

**Comment by cboden** [comment]
Please provide some source code so I can help troubleshoot.

**Comment by Deewai** [comment]
`<?php
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Chat;
use Ratchet;

    require dirname(__DIR__) . '/vendor/autoload.php';
    $app = new Ratchet\App('160.153.16.37', 3128,'0.0.0.0');
    $app->route('/chat', new Chat);
    $app->route('/echo', new Ratchet\Server\EchoServer, array('*'));
    $app->run();

`


Thats the code i used in my chat-server.php

**Comment by cboden** [comment]
I get a connection timeout when trying to connect. Who's your host? Have you enabled access port 3128 to in your hosts security settings?

**Comment by Deewai** [comment]
i'm using a shared hosting on godaddy

**Comment by Deewai** [comment]
u can try it again. i mistakenly stopped the websocket but its up now

**Comment by cboden** [comment]
What's the output when you run your script?

I don't know GoDaddy but I'm fairly confident they're not going to allow you to open ports to the outside world.

**Comment by Deewai** [comment]
timeout

**Comment by Deewai** [comment]
if they wont allow me open port what should i do then?

**Comment by cboden** [comment]
Your best bet is to use a virtual private hosting service such as AWS, Google Compute, Linode, Digital Ocean, Microsoft Azure, etc. 

A quick google for "WebSockets on GoDaddy" reveals that they don't allow this kind of behaviour; they only allow PHP to run through CGI.

**Comment by Deewai** [comment]
wow... thank you very much.
But just want to confirm there is nothing wrong with my code

**Comment by cboden** [comment]
Nope, code looks good 👍

**Comment by Deewai** [comment]
Okay. Thank you very much. I really appreciate your help
