### ISSUE TITLE
Right way to share session between website and socket server when using PdoSessionHandler

### ISSUE THREAD

**Issue by wp-src** [ratchetphp/Ratchet#570]
Hi, im new to ratchet and i don't know how to work with symfony libraries. Also my project is in codeigniter.
I want share a session between website and websocket server.
Here is my code for Website side:
```php
    public static function start()
    {
        $ci = &get_instance();
        $db = $ci->load->database();

        $dbOptions = array(
            'db_table'          =>'sessions',
            'db_id_col'         =>'sess_id',
            'db_data_col'       =>'sess_data',
            'db_time_col'       => 'sess_time',
            'db_lifetime_col'   => 'sess_lifetime'
        );

        $sess = new Session(
            new PhpBridgeSessionStorage(
                new PdoSessionHandler($db, $dbOptions)
            )
        );

        return $sess;
    }
```

The problem with this code is that it stores sessions behind other data in normal php sessions. 
And here is my code for websocket side:
```php
        $db = $this->load->database();

	    $sess = new Ratchet\Session\SessionProvider( new WsServer(
            new Login()
        ), new PdoSessionHandler($db, array(
                'db_table'=>'sessions',
                'db_id_col'=>'sess_id',
                'db_data_col'=>'sess_data',
                'db_time_col' => 'sess_time',
                'db_lifetime_col' => 'sess_lifetime'
            ))
        );

        $server = IoServer::factory(
            new HttpServer(
                $sess
            ),
            8080
        );

        $server->run();
```
Problem in websocket side code is its Session object not contains my stored properties. As i said i think the problem is that in website side it stores data in the files instead of saving them in database.
Can someone help me to find what is wrong in this?
I must mention that i don't want run any other servers. or force user to install libraries and etc..

**Comment by alcalyn** [comment]
> Problem in websocket side code is its Session object not contains my stored properties

When you run your websocket server, you should do something like `php bin/websocket-server.php`.
If so, at this time, there is no session as you do run from cli.

Your website side seems to be ok, the usual way. But websocket side, you should authenticate your user when he opens a websocket connection.
To do that, I could send an authentication token as websocket url parameter, i.e:

`ws://localhost:8080?token=xxxxx`

I can retrieve the token websocket server side with:

``` php
# For Ratchet 0.3
$conn->WebSocket->request->getQuery()->get('token');

# For Ratchet 0.4
parse_str($conn->httpRequest->getUri()->getQuery(), $queryParameters);
$queryParameters['token']
```

I don't know about your implementation, but if you're trying to get a session at ws server start, you're wrong as you can authenticate users only when they open a ws connection.

**Comment by wp-src** [comment]
@alcalyn Thanks for response and the snippet, but after receiving the token from user in websocket side what you do with it ?
I used PdoSessionHandler to store the session in database so i could access it for example by its token (Or ratchet do it for me), is this wrong ? If so then for what we use PdoSessionHandler ?
I have read on the web, when websocket server opens the session it is no longer accessible in webserver side. Then i want PdoSessionHandler to store it in database, so i could authenticate with database instead of using php sessions, which is not doing so, and it is being stored in php sessions(files).
Thanks.

**Comment by alcalyn** [comment]
> after receiving the token from user in websocket side what you do with it ?

I'm using OAuth2, so it's in fact an access token the user must create from the RestApi (my website side). So I'm not using PHP sessions.

If you're using `PdoSessionHandler`, you should find a way to load a session from a `session_id` manually. I see in your second snippet (websocket side) that you're not providing any `session_id`, so it seems to try to retrieve it from `$_SESSION`, which is wrong.

Instead, I don't know very well `PdoSessionHandler`, but try to send the `session_id` through the websocket connection when an user opens a new one, then load the session manually using something like `PdoSessionHandler::read` (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L275) to load the session.

But I think PHP `session_id` is not intended to be sent manually, so you may use OAuth2 instead.

This is the method I implemented in Sandstone: https://eole-io.github.io/sandstone/authentication.html

**Comment by wp-src** [comment]
@alcalyn Thanks. I want first try using Pdo... way if possible.
Because if we use library that is not supported by ratchet then we must control everything in our way..

> If you're using PdoSessionHandler, you should find a way to load a session from a session_id manually. I see in your second snippet (websocket side) that you're not providing any session_id, so it seems to try to retrieve it from $_SESSION, which is wrong.
I don't think it need session_id.  Because it receives db credentials from us.

**Comment by alcalyn** [comment]
> why session in website side is not being saved in database

I just given a try with this code:

``` php
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage;
use Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler;

$pdo = new PDO('mysql:host=database;dbname=ratchet', 'root', 'root');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$dbOptions = [
    'db_table'          => 'sessions',
    'db_id_col'         => 'sess_id',
    'db_data_col'       => 'sess_data',
    'db_time_col'       => 'sess_time',
    'db_lifetime_col'   => 'sess_lifetime',
];

$storage = new NativeSessionStorage([], new PdoSessionHandler($pdo, $dbOptions));
$session = new Session($storage);

$session->set('foo', 'bar');
```

When I hit this code webserver side, it adds a new entry in database **only when I set a variable in session** with the `$session->set('foo', 'bar');`. If I remove the `set`, nothing in database, but you should try to set something and it should work.

Here is my exemple: https://github.com/alcalyn/ratchet-session-pdo

*You can run it with docker by cloning it, running `make`, then hit `http://0.0.0.0:8480` in your browser, and access PHPMyAdmin at `http://0.0.0.0:8481`.*

**Comment by wp-src** [comment]
Thank you i resolved the issue, there was two problems in my configuration. First one is codeigniter loads the db connection in a way that is not usable in ratchet and throws errors. Second one is i must unload codeigniter sessions library in codeigniter config.
