### ISSUE TITLE
how to trigger onMessage function from server-side ?

### ISSUE THREAD

**Issue by salehmosleh** [ratchetphp/Ratchet#571]
in my project , i want to send data to some clients automatically , without receiving any request from clients.but i cant access to clients from out side of `MessageComponentInterface` class object. i prefer to tell to `MessageComponentInterface` class ; send to alive clients a message. so i need to trigger onMessage function from server-side , how can i do it ?
here is my WebSocketCon class :
```php
<?php 
use Ratchet\MessageComponentInterface;
use Ratchet\ConnectionInterface;

class WebSocketCon implements MessageComponentInterface {
    protected $clients;
    public $users;
	
    public function __construct() {
        $this->clients = new \SplObjectStorage; 
        $this->users = [];
    }

    public function onOpen(ConnectionInterface $conn) {
        $this->clients->attach($conn);
        echo "New connection! ({$conn->resourceId})\n";
    }

    public function onMessage(ConnectionInterface $from, $msg) {
        $data = json_decode($msg);
        if($data->command=="subscribe"){
            $this->users[(int)$data->uid] = $from;
            echo "New subscribe! ({$data->uid})\n";
        }
    }

    public function sendMessageToAll($msg){
        foreach ($this->clients as $client) {
            if ($from !== $client) {
                $client->send($msg);
            }
        }
    }
	
    public function sendMessageTo($idusers,$msg){
        foreach ($idusers as $idu) {
            $idu = (int) $idu;
            if(array_key_exists($idu,$this->users)){
                $this->users[$idu]->send($msg);
            }
        }
    }
	
    public function onClose(ConnectionInterface $conn) {
        $this->clients->detach($conn); 
            if (($key = array_search($conn, $this->users)) !== false) {
                unset($this->users[$key]);
            }
        echo "Connection {$conn->resourceId} has disconnected\n";
    }

    public function onError(ConnectionInterface $conn, \Exception $e) {
        echo "An error has occurred: {$e->getMessage()}\n";

        $conn->close();
    }
}
```
and here is my cmd.php :

```php
<?php
require 'vendor/autoload.php';

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer; 
require 'classes/WebSocketCon.php';

$server = IoServer::factory(
    new HttpServer(
        new WsServer(
            new WebSocketCon()
        )
    ),
    8081
);

$server->run();
?>
```

**Comment by dartkinselok** [comment]
Hello! You should to look at the ZMQ (Push integration) module. It described on socketo.me in the "Push integration" tab. :)

**Comment by halfer** [comment]
Are you just looking for a Web Socket client you can use programmatically? I use [textalk/websocket](https://github.com/Textalk/websocket-php) for this.

**Comment by cboden** [comment]
Update your cmd.php to give access to yourWebSocketCon class:
```php
<?php
require 'vendor/autoload.php';

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer; 
require 'classes/WebSocketCon.php';

$app = new WebSocketCon();

$server = IoServer::factory(
    new HttpServer(
        new WsServer(
            $app
        )
    ),
    8081
);

// Somewhere else:
$app->sendMessageToAll('Hi everyone!');

$server->run();
```

---

If you're looking for a full blown WebSocket client see Ratchet's [Pawl](https://github.com/ratchetphp/Pawl).

**Comment by salehmosleh** [comment]
hi gays , thank you for your answers. im trying to push a notification to some clients, so i use  ZMQ (Push integration) module( @dartkinselok ). everything is ok but `onBlogEntry` does not run. it seems `tcp://127.0.0.1:5555` does not work fine. i use wampserver , PHP5.5 and Apache 2.4 on windows 10. Thanks in advance for your help. ( @cboden , @halfer )
here are my server codes( receiver ):
```
<?php
require 'vendor/autoload.php';
require 'classes/WebSocketCon.php';
$loop   = React\EventLoop\Factory::create();
$pusher = new WebSocketCon;

// Listen for the web server to make a ZeroMQ push after an ajax request
$context = new React\ZMQ\Context($loop);
$pull = $context->getSocket(ZMQ::SOCKET_PULL);
$pull->bind('tcp://127.0.0.1:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself
$pull->on('message', array($pusher, 'onBlogEntry'));

// Set up our WebSocket server for clients wanting real-time updates
$webSock = new React\Socket\Server($loop);
$webSock->listen(8081, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect
$webServer = new Ratchet\Server\IoServer(
	new Ratchet\Http\HttpServer(
		new Ratchet\WebSocket\WsServer(
			new Ratchet\Wamp\WampServer(
				$pusher
			)
		)
	),
	$webSock
);
$loop->run();
```
here are sender codes : 
```
	require_once("vendor/autoload.php");
	$context = new ZMQContext();
	$socket = $context->getSocket(ZMQ::SOCKET_PUSH,"pusher");
	$socket->connect("tcp://127.0.0.1:5555");
	$entryData = array(
		'category' => "sm"
	  , 'title'    => "saleh"
	  , 'when'     => time()
	);
	$socket->send(json_encode($entryData)); 
```
here are javascripts : 
```
		var conn = new ab.Session('ws://localhost:8081',
			function() {
				conn.subscribe('sm', function(topic, data) {
					// This is where you would add the new article to the DOM (beyond the scope of this tutorial)
					console.log(data);
					alert('New article published to category "' + topic + '" : ' + data.title);
				});
			},
			function() {
				console.warn('WebSocket connection closed');
			},
			{'skipSubprotocolCheck': true}
		);
```

**Comment by cboden** [comment]
Are you receiving any errors on either the server or client side?

**Comment by alcalyn** [comment]
Also, which Ratchet version are you using ? `0.3.x` or `0.4.x` ?
If you're using `0.4.x`,

``` php
$webSock = new React\Socket\Server($loop);
$webSock->listen(8081, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect
```

has to be changed to something like

``` php
$webSock = new React\Socket\Server('127.0.0.1:5555', $loop);
```

**Comment by salehmosleh** [comment]
@cboden , no , it does not display any error.

**Comment by salehmosleh** [comment]
@alcalyn here is my composer.json file ; 
```
{
    "name": "smprogram/taskdan",
    "description": "this is a task manager",
    "type": "project",
    "require": {
        "cboden/ratchet": "^0.3.6",
        "react/zmq": "^0.3.0"
    }
}

```

**Comment by alcalyn** [comment]
I tested it, Push message it well sent and received by the push server:

Arguments received by `onBlogEntry` method:
```
array(1) {
  [0]=>
  string(51) "{"category":"sm","title":"saleh","when":1508784615}"
}
```

It looks like the problem is after, when broadcasting this message to websocket clients.

**Comment by salehmosleh** [comment]
@cboden @alcalyn  , i think TCP connection does not work on my local PC. i test below example but it does not work.I'm confused , help me please...
here is my pull.php : 
```
<?php

require 'vendor/autoload.php';

$loop = React\EventLoop\Factory::create();

$context = new React\ZMQ\Context($loop);

$pull = $context->getSocket(ZMQ::SOCKET_PULL);
$pull->bind('tcp://127.0.0.1:5050');

$pull->on('error', function ($e) {
    var_dump($e->getMessage());
});

$pull->on('message', function ($msg) {
    echo "Received: $msg\n";
});

$loop->run();

```
and here is my push.php : 
```
<?php

require 'vendor/autoload.php';

$loop = React\EventLoop\Factory::create();

$context = new React\ZMQ\Context($loop);

$push = $context->getSocket(ZMQ::SOCKET_PUSH);
$push->connect('tcp://127.0.0.1:5050');

$push->on('error', function ($e) {
    var_dump($e->getMessage());
});

$i = 0;
$loop->addPeriodicTimer(1, function () use (&$i, $push) {
    $i++;
    echo "sending $i\n";
    $push->send($i);
	
});
$loop->run();
```
also i disabled my firewall , but it still does not work.
![test pull push](https://user-images.githubusercontent.com/3959998/32010518-eaf4f136-b9be-11e7-9697-6d3280f3fd73.jpg)

**Comment by alcalyn** [comment]
The same code works on my Ubuntu 17.10
Try running admin mode or something like that, or having an error message

**Comment by rfrancois** [comment]
I have the exact same problem. Did you find a solution ?
I didn't try yet, it seems this guy found something : [https://stackoverflow.com/questions/34018599/zeromq-not-working-when-sending-request-over-http](https://stackoverflow.com/questions/34018599/zeromq-not-working-when-sending-request-over-http). But I don't so like the idea to desactivate enforcing mode.

**Comment by rfrancois** [comment]
@halfer Yes sure.

I am following this tutorial : [http://socketo.me/docs/push](http://socketo.me/docs/push). I didn't change anything in the code except port number 8080 to 9000, and I added a var_dump("test"); at the begining of [onBlogEntry function](http://socketo.me/docs/push#zeromq_messages).

When I launch my file new_post.php which contains code of the section [Editing your blog submission](http://socketo.me/docs/push#edit_blog_submission), nothing displays in my console. As weel as nothing displays in client's console.

If I add a var_dump("test2") in the onSubscribe function, when client connects, it displays "test2" client's console when he opens [the page ("Client side")](http://socketo.me/docs/push#client).

I'm using RedHat with PHP 5.4. Maybe this doesn't help. I plan to try this code on an Ubuntu with the latest features to see if it works better. Anyway I need this to work on my PHP 5.4, then I hope someone has a solution.

**Comment by halfer** [comment]
@rfrancois: hmm, OK. For web sockets I just use the raw JS class on the browser side, and `textalk/websocket` on the PHP side (the latter should not cause any different behaviour, all WS libraries should work about the same).

In the client code in that tutorial, I can't see any acknowledgement of the browser to server connection. I do this:

```
    var
        isSecure = window.location.protocol === 'https:',
        protocol = isSecure ? 'wss://' : 'ws://',
        address = protocol + window.location.host;

    console.log("Attempting a WebSocket connection on `" + address + "`");
    ws = new WebSocket(address);

    ws.onopen = function () {
        console.log('WS connection opened');
    };

    ws.onmessage = function (e) {
        // Handle an incoming message here
    };

    ws.onclose = function (e) {
    }
```

Try that and see if you get a browser to server connection?

**Comment by rfrancois** [comment]
Just to say that it was a problem with SELinux which blocked requests. I can't tell you how to solve this problem because administrator of my area did it for me and didn't tell me what he has done.
Thanks for your help !

**Comment by Silverviql** [comment]
And there is a solution for windows ?
https://github.com/Silverviql/crm_2.3/blob/master/console/controllers/PusherController.php
https://github.com/Silverviql/crm_2.3/blob/master/console/components/BasePusher.php
https://github.com/Silverviql/crm_2.3/blob/master/console/components/Pusher.php
PHP5.6-x64 and Apache 2.4-x64 on windows 7.
"react/zmq": "v0.4.0", "cboden/ratchet": "v0.4.1"

create a new event

` public function get () {
        $data = [
        'topic_id' => 'onNewData',
        'data'  => 'eventData' . rand(1,100)
    ];
    \console\components\Pusher::sentDataToServer($data);
    var_dump($data);`
``client
`$this->registerJsFile('/frontend/web/js/autobahn.min.js');

$script = <<<JS

        var conn = new ab.connect('ws://localhost:8080',
                function(session) {
                    // eventMonitoring идентификатор, который мы передаём в push класс.
                   session.subscribe('onNewData', function(topic, data) {
                        // Сюда будут прилетать данные от вашего веб приложения.
                        console.info('New data: topic_id: "' + topic + '"');
                        console.log(data);
                    });
                },
                function(code, reason, detail) {
			console.warn('WebSocket connection closed: code=' + code + '; reason=' + reason + '; detail=' + detail);
		},
		{
			'maxRetries': 60,
			'retryDelay': 4000,
			'skipSubprotocolCheck': true
		}
        );
   
JS;
$this->registerJs($script);`

**Comment by halfer** [comment]
@Silverviql is that a question or an answer? :smile_cat:

**Comment by Silverviql** [comment]
@halfer This is a question). I tried the usual this example https://github.com/friends-of-reactphp/zmq 

On the version 

> "react/zmq": "v0.4.0",

> "cboden/ratchet":"v0.4.1

there was an error Fatal error: Uncaught exception 'ZMQSocketException' with message 'Failed to bind the ZMQ: Address in use' in C:\OpenServer\domains\crmas\vendor\react\zmq\src\SocketWrapper.php on l ine 171

> "cboden/ratchet": "v0.3.4",
>         "react/zmq": "v0.3.0"
![2018-07-19_10-21-22](https://user-images.githubusercontent.com/23103415/42927797-3773809e-8b3e-11e8-85c6-bf575b7989a4.png)  
nothing comes

**Comment by Silverviql** [comment]
@halfer  
I solved the problem, never deploy the sockets to windows. My solution is to install ubuntu 16.04 and configure and work and forget about the window

**Comment by tafelnl** [comment]
I seem to have problems that are similar to the ones mentioned in this thread.

I followed the [push tutorial](http://socketo.me/docs/push) and changed nothing to the code.

The client side is working fine (thus subscribing and unsubscribing etc works) but whenever I try to execute the file from the step [Editing your blog submission](http://socketo.me/docs/push#edit_blog_submission) it keeps loading for a long while and eventually gives me the following error message (in Chrome) `ERR_CONNECTION_RESET`

When I do the following `var_dump`:
```
$context = new ZMQContext();

$socket = $context->getSocket(ZMQ::SOCKET_PUSH, 'my pusher');
$socket->connect("tcp://localhost:5555");

var_dump($socket); exit;

$socket->send(json_encode($entryData));
```

It returns the following:
`object(ZMQSocket)#2 (0) { }`

(but after the first time it will return the same error as above `ERR_CONNECTION_RESET`)

I tried disabling the firewall. But that did not make any difference.

Everything else seems to work just fine. But just broadcasting from the server does not work.

It might be important to note that this is all done on a xampp server running on Windows

**Comment by tafelnl** [comment]
Hmm, whenever I execute the script from the command line it seems to work. But the problem is that in the production version, it also needs to work from the browser.

But I have no idea why it would work from the command line but not when the file is executed by the browser.

Any ideas?

**Comment by tafelnl** [comment]
@mbonneau Yes it is :)

**Comment by carlo-fontanos** [comment]
I am having the same issues described by @tafelnl. Any solution?
