### ISSUE TITLE
Организация работы с Ratchet

### ISSUE THREAD

**Issue by motokraft** [ratchetphp/Ratchet#572]
Здравствуйте! Я только начинаю работать с данной библиотекой и есть несколько вопросов...

1. Как правильно организовать работу библиотеки...
2. На каждой странице есть свой функционал (к примеру на странице интернет аукциона надо обновить актуальную цену если кто то сделал ставку и сделать ставку так что бы после ее обновилась информация на странице) как правильно растасовать этот функционал....

Может у кого есть небольшие примеры проектов? Поделитесь пожалуйста....

**Comment by samizdam** [comment]
Добрый день. 
1. Вопрос риторический. Можете конкретизировать, что значит правильно? Чем примеры из документации для начала не подходят? Что пробовали и что именно не получается?
2. Тоже очень общий вопрос, похоже не на вопрос а просьбу решить вашу проблему. Что и как сделали, что именно не получается? 

Попробуйте декомпозировать свою задачу на минимальные кусочки и двигайтесь шаг за шагом. Если на конкретном шаге что-то не ясно, спрашивайте - со ссылкой на конкретный код, с которым испытываете затруднения. 

Примеры здесь же, на гитхабе пробовали искать, или вообще в Гугл, неужели ничего не находится?

**Comment by motokraft** [comment]
Предположим есть код

> define('JPATH_BASE', '/var/www/html');
> define('DS', DIRECTORY_SEPARATOR);
> 
> use Ratchet\Server\IoServer;
> use Ratchet\Http\HttpServer;
> use Ratchet\WebSocket\WsServer;
> use Components\ComK2;
> 
> require_once JPATH_BASE.DS.'ratchet'.DS.'vendor'.DS.'autoload.php';
> $server = IoServer::factory(new HttpServer(new WsServer(new ComK2())), 8080);
> $server->run();

который запускает websocket server.
На странице списка материалов есть фильтр в котором при изменении одного выпадающего списка должен появится второй....

Вот пример класса который будет работать с websocket-ами
> namespace Components;
> use Ratchet\MessageComponentInterface;
> use Ratchet\ConnectionInterface;
> 
> class ComK2 implements MessageComponentInterface
> {
>     protected $clients;
> 
>     public function __construct()
> 	{
>         $this->clients = new \SplObjectStorage;
>     }
> 
>     public function onOpen(ConnectionInterface $conn)
> 	{
>         $this->clients->attach($conn);
>         echo "New connection! ({$conn->resourceId})\n";
>     }
> 
>     public function onMessage(ConnectionInterface $from, $msg)
> 	{
>         print_r(json_decode($msg));
>     }
> 
>     public function onClose(ConnectionInterface $conn)
> 	{
>         $this->clients->detach($conn);
>         echo "Connection {$conn->resourceId} has disconnected\n";
>     }
> 
>     public function onError(ConnectionInterface $conn, \Exception $e)
> 	{
>         echo "An error has occurred: {$e->getMessage()}\n";
>         $conn->close();
>     }
> }

При получении каких то данных я их просто вывожу...
Ну так как мне сделать обработчик который будет отвечать только за то что я выберу из первого выпадающего списка...

Проблема в том что я не могу понять как правильно этим пользоваться...

**Comment by samizdam** [comment]
Код который вы привели - просто пример базового использования Ratchet. 
Не понял о каких выпадающих списках идёт речь. 
Пока проблема сформулирована очень туманно. 

Попробуйте точнее сформулировать: какую именно конкретную техническую задачу вы хотите решить, какие шаги для этого предприняты, в чём именно состоит препятствие.
