### ISSUE TITLE
Non-blocking code with message queue

### ISSUE THREAD

**Issue by CyanoFresh** [ratchetphp/Ratchet#574]
Hello. 
I have MessageComponent application. Current flow:
1. onMessage is triggered, send message to the queue (RabbitMQ, using https://github.com/yiisoft/yii2-queue ).
2. Worker receives message, starts executing (working with db, long-running, etc.)
3. Worker executed the job, connects to the server by https://github.com/ratchetphp/Pawl and sends message with job descriptions

Is this a right way? But now I have a problem: worker receives a message only after 600ms after message was created (P.S.: problem with yii2-queue).

**Comment by cboden** [comment]
600ms is *way* longer than it should take. Two things off the top of my head:
1. You're using a blocking Redis client inside a non-blocking Ratchet environment. There are 2 async Redis clients available built on top of ReactPHP I'd suggest you switch to.
2. Communicating back via Pawl is a good solution, however it sounds like you're opening a new connection on every job? Establishing a connection takes time (including the socket setup). A faster workflow would be to have a long-established connection and sending a message per job completed.

**Comment by CyanoFresh** [comment]
Thanks for reply, problem was with yii2-queue. Moved to RabbitMQ. With examples from rabbitmq all is ok (1ms).
Please show me examples how to run 2 libraries on single react loop, I can't realize how to send message to RabbitMQ (this lib https://github.com/jakubkulhan/bunny/blob/master/tutorial/1-hello-world/send-async.php ) from Ratchet's onMessage callback. Or how to keep connection alive in Pawl and send message only if I receive message from RabbitMQ ( https://github.com/jakubkulhan/bunny/blob/master/tutorial/1-hello-world/receive-async.php )

**Comment by mostafaahamidmanon** [comment]
<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
namespace App;
use Ratchet\MessageComponentInterface;
use Ratchet\ConnectionInterface;
/**
 * Description of Socket
 *
 * @author Tasneem
 */
class Socket implements MessageComponentInterface{
    
    /**
     *
     * @var $clients array of each client
     */
    protected $clients;
    protected $loop;
    
    /**
     * constructor
     */
    public function __construct(\React\EventLoop\LoopInterface $loop) {
        $this->loop = $loop;
        $this->clients = new \SplObjectStorage;
    }
    
    /**
     * 
     * @param ConnectionInterface $conn attaches clients
     */
    public function onOpen(ConnectionInterface $conn) {
        echo "\nNew Client Connected...\n";
        $this->clients->attach($conn);
    }
    
    /**
     * 
     * @param ConnectionInterface $from
     * @param $msg
     */
    public function onMessage(ConnectionInterface $from, $msg) {
        
        
        echo "\nNew Message: " . $msg . "\n";
        foreach($this->clients as $clientSocket){
	    $this->loop->futureTick(function() use ($clientSocket){
		$clientSocket->send("\ndata data start\n");
	    });
	    $this->loop->futureTick(function() use ($clientSocket){
		$clientSocket->send("\ndata data two\n");
	    });
	    $stream = new \React\Stream\ReadableResourceStream(fopen(storage_path('logs/laravel.log'), 'r'), $this->loop);
  	    $loop = $this->loop;
            $stream->on('data', function($data) use ($clientSocket, $loop){
		$loop->futureTick(function() use ($clientSocket, $data){
			$returnValue = file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log')) . 
					file_get_contents(storage_path('logs/laravel.log'));
			$clientSocket->send($returnValue);
			$clientSocket->send($data);
		});
            });
            $stream->on('end', function() use ($clientSocket, $loop){
                $loop->futureTick(function() use ($clientSocket){
			$clientSocket->send('finished');
		});
            });
            $this->loop->run();
        }
    }
    
    /**
     * 
     * @param ConnectionInterface $conn
     */
    public function onClose(ConnectionInterface $conn) {
        echo "\nConnection Closed \n";
        $this->clients->detach($conn);
    }
    
    /**
     * 
     * @param ConnectionInterface $conn
     * @param \Exception $e
     */
    public function onError(ConnectionInterface $conn, \Exception $e) {
        echo "\nError on Connection: {$e->getMessage()} on line {$e->getLine()} in file {$e->getFile()} \n";
        $conn->close();
    }
}
