### ISSUE TITLE
Chat example not working

### ISSUE THREAD

**Issue by TomAshley303** [ratchetphp/Ratchet#575]
I pasted the example code and ran it from CLI. I can connect to the echo route and it works but I can't connect to the /chat route. Ratchet doesn't give any error.

**Comment by TomAshley303** [comment]
I had to pass it `array('*')`

**Comment by cboden** [comment]
The app does a host check with default origin policy. Without the `[*]` Ratchet would have failed your connection if it didn't come from the same host as the first parameter of the App class. You would have received a 403 HTTP status code on your client when attempting to connect.
