### ISSUE TITLE
Option to Disable xdebug Warning

### ISSUE THREAD

**Issue by samizdam** [ratchetphp/Ratchet#576]
I want write integration test, that create and configure instance of Ratchet\App. 
And I want get code coverage from my tests, but I get error because:  https://github.com/ratchetphp/Ratchet/blob/e3e223066c0403f3081783755858ad942cd69e0c/src/Ratchet/App.php#L66

I think it should be optional, like is done in composer: https://github.com/composer/composer/issues/4622

**Comment by str** [comment]
The flag to disable the warnining is:

```php
putenv('RATCHET_DISABLE_XDEBUG_WARN=true');
```
