### ISSUE TITLE
Reconnecting a user to its socket

### ISSUE THREAD

**Issue by daatysonz** [ratchetphp/Ratchet#577]
At the moment i am building a facebook like chat. Currently on facebook the user is always on the same page and the content is reloaded allowing a socket to stay open, much like iframe. But in my custom built chat everytime the user changes page everything refreshes ending that connection and creating a new one.

1- Anyway to reconnect the user to the same socket without closing the connection when changing page?

2- I've also read that currently there is a limit on the socket of 1024 connections, is there anyway to get over this limit?

**Comment by dartkinselok** [comment]
Hello, @daatysonz! 

1. No. Maybe you’ve replaced JS code that have opened WS connection. Move it outside of your AJAX replacement block.

2. It’s very important and highly-problematic issue. You have to increase file limit in your system and (VERY IMPORTNANT!!!) install `ev` or `event` module in PHP. Note that this extension will work only if you’ve installed libevent in your system. More details you can find on http://socketo.me/docs/deploy . Read carefully! Don’t miss any details. And don’t repeat my mistakes:) Good luck!

**Comment by daatysonz** [comment]
Thank you for the active, fast and precise response.
