### ISSUE TITLE
Hey I am new to websockets so I need your help. I want to  Create a ratchet server on a dedicated server and use it on client hosted on shared hosting.  

### ISSUE THREAD

**Issue by xarvagya** [ratchetphp/Ratchet#581]
I have configured and started ratchet on the dedicated server it works fine when i use this on the same machine but when I am using it on another web server with the same url wss://chat.example.com/wss2/chat
it is giving the error 
Error during WebSocket handshake: Unexpected response code: 403

Hope you understand my problem

Please Help me Thanks in advance

**Comment by cboden** [comment]
Sounds like the third q/a from the [troubleshooting page](http://socketo.me/docs/troubleshooting)

**Comment by xarvagya** [comment]
thank you so so so much for the instant answer ! I think i would solve my issue can you please tell me a little briefly about
 "allow another Origin the third parameter of App::route() accepts an array of allowed origins"

  which file should I change in order to allow an array of my urls ...

sorry may be this is a very childish question ... but I m just a beginner .. Plese Help

**Comment by xarvagya** [comment]
Well I have this line in the end where array is  array("*")

 $app->route('/echo', new Ratchet\Server\EchoServer, array('*'));

Should I change This Line

**Comment by cboden** [comment]
A WebSocket request looks something like this:
```
GET / HTTP/1.1                    
Host: echo.socketo.me:9000        
Connection: Upgrade               
Upgrade: websocket                
Sec-WebSocket-Version: 13         
Sec-WebSocket-Key: MG02dFdQUE1USkRNSDRLeg==                          
User-Agent: Ratchet-Pawl/0.3      
Origin: http://echo.socketo.me
```

The `Origin` HTTP header is the URL of the website the WebSocket request is made from. A default security measure Ratchet makes by default is that the Origin domain has to match the Host domain. By adding the second array in to route of `['*']` you're telling the server that that route can be accepted from any Origin/website wanting to make a WebSocket request.

**Comment by xarvagya** [comment]
thank you so much this thing solved my issue ... I am so grateful to you and this ratchet Library ....
thank you so so much . 💯 🥇
