### ISSUE TITLE
Websocket Not working 

### ISSUE THREAD

**Issue by shayanali995** [ratchetphp/Ratchet#583]
Hello,

When i was not using SSL and cloudfare my websocket was working on my server IP now its not working i have done everything even reverse proxy and other things to sort out this issue please help me ! 

PHP version is 7
Ubuntu Apache 16.04

Thanks,

**Comment by mariapaulinar** [comment]
It was temporarily disabled 
 :( https://github.com/ratchetphp/Ratchet/commit/680b2ae45c539b676e2c1a5ea2b59da52298c67f

**Comment by cboden** [comment]
@shayanali995 Can you provide more information please? Logs would be helpful. 

@mariapaulinar `App` had this API removed temporarily, but you can still use TLS by piecing together a React Connector with TLS enabled. Also, this issue is about proxying TLS, not enabling it in user land.
