### ISSUE TITLE
class/interface naming confuse a lot

### ISSUE THREAD

**Issue by clor09** [ratchetphp/Ratchet#587]
oh, this is not a bug, but really     the class/interface naming confuse me a lot, e.g. HttpServer & HttpServerInterface, MessageInterface & ConnectionInterface(may called this name??), but they seems not do things like what they were named...

**Comment by cboden** [comment]
Can you elaborate at all? A MessageInterface defines the functions of a Message object, which contains the data sent to/from a server and client. A Connection is a representation of a client connected which the server can send a Message to or disconnect from (close).
