### ISSUE TITLE
$conn->WebSocket returns "closing"??

### ISSUE THREAD

**Issue by maxisme** [ratchetphp/Ratchet#589]
For some reason this `var_dump`:
```
class Sock implements MessageComponentInterface {
    ...
    public function onOpen(ConnectionInterface $conn) {
        $this->clients->attach($conn);
        var_dump($conn->WebSocket);
    }
```

returns:
```
object(stdClass)#51 (1) {
  ["closing"]=>
  bool(false)
}
```

____
I setup the remote socket like:

```
// setup remote server
$remote_server = new Sock();
$ws = new WsServer($remote_server);
//$ws->disableVersion(0);
$server = IoServer::factory( 
	new HttpServer($ws),
    34648
); 

//local socket for on curl requests to Ratchet socket
$context = new React\ZMQ\Context($server->loop);
$pull = $context->getSocket(ZMQ::SOCKET_PULL);
$pull->bind('tcp://127.0.0.1:5555');
$pull->on('message', array($remote_server, 'onLocal'));

$server->run();
```

for some reason `$ws->disableVersion(0)` is dead too.

My composer:
```
{
    "require": {
        "cboden/ratchet": "^0.4.1",
        "ext-zmq": "*",
        "evenement/evenement": "^2.0",
        "react/zmq": "^0.3.0"
    }
}
```

**Comment by cboden** [comment]
The `disableVersion` was removed in 0.4. That version of the WebSocket protocol is no longer supported. 

`closing` is a parameter on connections that will be set to `true` once the close handshake has begun.

**Comment by psadaic** [comment]
I believe his question was, and what I would like to know aswell, why `$conn->WebSocket` object contains only `closing` property.

Or to rephrase myself, why I can not access `$conn->WebSocket->request` anymore?

**Comment by maxisme** [comment]
I needed `request` to get a header did you? If so this is the solution to get the forwarded real IP:
```
$from->httpRequest->getHeader('X-Real-IP')[0]
```

**Comment by psadaic** [comment]
Already tried that but it is not working when using SSL.

**Comment by maxisme** [comment]
are you using `nginx`?

**Comment by psadaic** [comment]
Of course.

**Comment by maxisme** [comment]
what is your config?

**Comment by psadaic** [comment]
Nginx config is fine. Problem is that `httpRequest` object is non-existent.

**Comment by maxisme** [comment]
I want to see how you proxy forward...?

**Comment by psadaic** [comment]
```
location / {
                proxy_http_version 1.1;

                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto https;
                proxy_set_header        Host $http_host;
                proxy_set_header        X-NginX-Proxy true;

                proxy_set_header        Upgrade $http_upgrade;
                proxy_set_header        Connection $connection_upgrade;

                proxy_pass              http://websocket;

                proxy_redirect off;
        }

```

**Comment by maxisme** [comment]
what is your `websocket` upstream?

I just have this:
```
location / {
        proxy_pass http://sock;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400;
    }
```
and the upstream:

```
upstream sock {
    server 127.0.0.1:12345 fail_timeout=20s;
}
```

then I setup the ratchet socket like this:

```
$remote_server = new Sock();
$ws = new WsServer($remote_server);
$server = IoServer::factory( 
	new HttpServer($ws),
    12345
); 
$server->run();
```

**Comment by psadaic** [comment]
Thanks but there is nothing wrong with my nginx config.

**Comment by maxisme** [comment]
Yeah, just wondering what you are doing differently to me so that:

> Problem is that httpRequest object is non-existent when using ssl

?

**Comment by maxisme** [comment]
the way I found out what to do was `var_dump($con)` and spent ages working out the format

**Comment by cboden** [comment]
What version of Ratchet are you using @psadaic? The `httpRequest` object only gets attached to a connection (and forwarded to your app) if the handshake was successful.
