### ISSUE TITLE
WSS using React\Socket\SecureServer results in SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by BrainFeeder** [ratchetphp/Ratchet#592]
Hi!

We're trying to get this TLS websocket running since last week. Everything worked fine without certificate. We've got a trusted certificate from letsencrypt.org and are trying to implement the secure connection with React\Socket\SecureServer (as suggested by @cboden at #500 [in this comment](https://github.com/ratchetphp/Ratchet/pull/500#issuecomment-329460941)). 

I know time is scarce, but can someone please help us out here?

Using cboden/ratchet v0.3.5, react/zmq v0.3.*
[server.php](https://pastebin.com/VEc9qMgU) (our setup is different as in #590 )

Connection at client with AutobahnJS v0.8.2
```javascript
	var conn = new ab.Session(wss://xxxx:8080,
		function() {
			console.info('Listening');
			
			// Listen for events.
			conn.subscribe('someThing', function(topic, data) {
			
			});
			
		},
		function() {
			console.log('Closed');
		}
	);
```
In console it shows 'Firefox can not connect with server at wss://xxxx:8080/'. And 'Closed'. At the netwerk tab we get the SSL_ERROR_NO_CYPHER_OVERLAP error.

**Comment by BrainFeeder** [comment]
Okay, it works :| 

It might be interesting for others to add this in the documentation somewhere.. at least until 0.4.1 is stable enough.

	$loop   = React\EventLoop\Factory::create();
	$pusher = new Beheren\Pusher;

	// ZMQ binding
	$context = new React\ZMQ\Context($loop);
	$pull = $context->getSocket(ZMQ::SOCKET_PULL);
	$pull->bind('tcp://0.0.0.0:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself (127.0.0.1 || 0.0.0.0)
	$pull->on('error', array($pusher, 'onError'));
	$pull->on('message', array($pusher, 'onLogIn'));

	// Set up secure React server
	$webSock = new React\Socket\SecureServer(
		new React\Socket\Server($loop),
		$loop,
		array(
			'local_cert' => 'xxxx/combined.pem',
			//'allow_self_signed' => true,
			'verify_peer' => false
		)
	);
	$webSock->listen(8080, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect (127.0.0.1 || 0.0.0.0)

	// Ratchet magic
	$webServer = new Ratchet\Server\IoServer(
		new Ratchet\Http\HttpServer(
			new Ratchet\WebSocket\WsServer(
				new Ratchet\Wamp\WampServer(
					$pusher
				)
			)
		),
		$webSock
	);

	$loop->run();

**Comment by newmediacrew** [comment]
Hi BrainFeeder,

We are also trying to get WSS to work. Did you manually install Beheren\Pusher and React\ZMQ\Context with composer ?

Regards

**Comment by BrainFeeder** [comment]
@newmediacrew Beheren\Pusher is a script we wrote but is almost the same as the [pusher at the Ratchet docs](http://socketo.me/docs/push). All other requirements are installed with composer.
We needed to install [ZeroMQ](http://zeromq.org/) on the server (PHP: libzmq PECL extension) in order to work with ZMQ\Context though.

**Comment by mbonneau** [comment]
Closed due to inactivity.
