### ISSUE TITLE
Firefox : "connection interrupted while the page was loading"

### ISSUE THREAD

**Issue by sebinator** [ratchetphp/Ratchet#593]
hello everyone,
i having an issue since a while now, it was on 0.3 and and on the 0.4 as well,
the issue is happening Only on firefox, 
i am getting a connection as expected, but at some point the connection just drop.
and i am getiing that error :

connection to wss://mydomain.com/wss2/NNN/?myIdUser=1 was interrupted while the page was loading.

**Comment by cboden** [comment]
Can you provide the request/response from the Network debug tab?

**Comment by sebinator** [comment]
![error](https://user-images.githubusercontent.com/5305248/34909683-8ce55c0e-f85a-11e7-95ee-027db891d3eb.JPG)

**Comment by sebinator** [comment]
i didn't noticed this on google chrome, but only firefox currently

**Comment by sebinator** [comment]
sorry i sent the wrong screenshot, here is what you asked
![error](https://user-images.githubusercontent.com/5305248/34915463-f784ef86-f92f-11e7-9d4e-aa045e7a96d9.JPG)

![error2](https://user-images.githubusercontent.com/5305248/34915484-4112d9e2-f930-11e7-8d2d-0540491de9f1.JPG)


it seems the issue does not occur on Chrome, but only firefox. 
It happens after couple seconds/minutes ... the connection is just lost,
so my script make a new one.

**Comment by sebinator** [comment]
anyone can help? :)

**Comment by cboden** [comment]
Possibly this bug? https://bugzilla.mozilla.org/show_bug.cgi?id=712329

**Comment by sebinator** [comment]
yes it seems to be it, is there a solution?

**Comment by cboden** [comment]
https://stackoverflow.com/a/23784296/753926

**Comment by sebinator** [comment]
thanks, i will try this :)

**Comment by sebinator** [comment]
it didn't helped :/
![nope](https://user-images.githubusercontent.com/5305248/44112272-53354acc-a00d-11e8-8370-2224e695cfb5.JPG)

**Comment by mbonneau** [comment]
Closed for inactivity.
