### ISSUE TITLE
Ratchet closes Socket without Code 1000

### ISSUE THREAD

**Issue by Kapsonfire** [ratchetphp/Ratchet#596]
```php
      public function onOpen(ConnectionInterface $FROM)
      {
                 $this->clients->attach($FROM);
                 $FROM->send($this->buildPacket('noLogin', 'No UserID found'));
                 $FROM->close();
                 return;
       }
```

using this Code, ratches closes the Socket (websocket) abnormally - Client gets event.code == 1006
its also impossible to define a code in the ConnectionInterface and 1006 is a reserved error code
Ratchet should close with Code 1000

**Comment by cboden** [comment]
Can you provide the code for your `buildPacket` method?

**Comment by Kapsonfire** [comment]
nothing special
public static function buildPacket(string $packetName, $packetData = null)
    {
        $packet = new stdClass();
        $packet->type = $packetName;
        $packet->data = $packetData;
        return json_encode($packet);
    }

**Comment by Kapsonfire** [comment]
It doesnt matter where/when you call .close()

Client always gets event.code == 1006


It would be much better if we can send a custom CloseCode

**Comment by cboden** [comment]
Ratchet never issues status code [1006 (abnormal close)](https://tools.ietf.org/html/rfc6455#section-7.4.1). This code is considered if the underlying connection is closed without a closing frame negotiation. What's likely happening is there is an error in your server which is causing the stream to immediately close and the client is reporting this. 

The [WsConnection close method](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsConnection.php#L30) accepts a close code or close frame. You can find all the acceptable codes in the [Frame class](https://github.com/ratchetphp/RFC6455/blob/master/src/Messaging/Frame.php#L12-L23).

**Comment by Kapsonfire** [comment]
In Client  (Chrome Latest Stable)
 _socket.onclose = function(event) {
        console.log(event.code);
 };

In Server
 public function onOpen(ConnectionInterface $FROM)
{
        $FROM->close(); return;
}


event.code is 1006


reproducable


How to use the WsConnection Close Method, if I have to implement the ConnectionInterface ?

**Comment by cboden** [comment]
I just tested this with a brand new Ratchet server (v0.4.1) on Chrome (63.0.3239.132) and received `1000` in the console.

**Comment by Kapsonfire** [comment]
It can be closed then - just last Question:
How to use the WsConnection Close Method, if I have to implement the ConnectionInterface ?

**Comment by cboden** [comment]
`WsConnection` implements `ConnectionInterface`. It overload the `close` method. While `ConnectionInterface`'s `close` method has no parameters `WsConnection` has an optional parameter with a default value allowing you to pass a close code while maintaining the original interface.
