### ISSUE TITLE
Fail on install with composer

### ISSUE THREAD

**Issue by tranquilodf** [ratchetphp/Ratchet#601]
Hello! I am trying to install by composer, however, it has the following message:

`Problem 1
    - The requested package lavarel/lavarel could not be found in any version, there may be a typo in the
package name.
`
Could you help me?

**Comment by PenguinArts** [comment]
Maybe it should be "laravel" instead of "lavarel"

**Comment by tranquilodf** [comment]
Works. 
composer.json was with wrong data.
Tks
