### ISSUE TITLE
Failed to listen on...

### ISSUE THREAD

**Issue by martinstepanek** [ratchetphp/Ratchet#610]
This is my error, when i run index: 
`PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://85.255.4.82:8080":  in /var/www/teachat/server/vendor/react/socket/src/TcpServer.php:164`

index.php: 
```
$server = IoServer::factory(new HttpServer(new WsServer(new Chat())), 8080, '85.255.4.82');
$server->run();
```

My public IP: 85.255.4.82 (127.0.0.1 doesnt work too)

My configuration for folder with PHP script:
```
<VirtualHost *:8080>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/teachat/server
	<Directory /var/www/teachat/server/>
		Require all granted
		AllowOverride All
		Options Indexes FollowSymLinks
	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

On my localhost it works, but not in production. Do you know how can i fix it?

**Comment by mbonneau** [comment]
@martinstepanek It appears that you are trying to run Ratchet in a php cgi context using Apache. Ratchet should be run as a stand-alone process.

**Comment by ramashankar-cloudnix** [comment]
Can you please explain it  how to configure it for non SSL websites running on apache /php
