### ISSUE TITLE
Connection Refused/ Connection Timeout

### ISSUE THREAD

**Issue by TaimurTTS** [ratchetphp/Ratchet#611]
Hi, I have used sockets from this tutorial: https://github.com/kishor10d/CodeIgniter-Ratchet-Websocket

Everything is working fine on localhost, But when i uploaded files on server it gave error. I was told that port which is 2000 might be blocked I contacted support they told me it is now open and now, firewall is also not blocking the port. 

I was told by hosting support to use 127.0.0.1 instead of domain name or server ip.

i am getting this error : **WebSocket connection to 'ws://127.0.0.1:2000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED**

if I change ip to Server IP or Doamin Name i get: **failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT**

**Comment by TaimurTTS** [comment]
according to hosting support there is no service listing to port 2000, so it is not responding

**Comment by mbonneau** [comment]
@TaimurTTS I am not exactly sure what you are saying the problem is. Perhaps you need to use the address `0.0.0.0` instead of `127.0.0.1` so that you are listening on all interfaces?

**Comment by TaimurTTS** [comment]
Thanks for your reply. I changed **ws://127.0.0.1:2000/** to **ws://DomainName/**. 
I Found the problem, the port 2000 was open but it was getting blocked by firewall. 
Thanks
