### ISSUE TITLE
Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by sebinator** [ratchetphp/Ratchet#612]
Hi, 
i having this error, i have no idea what may cause this issue
**WebSocket connection to 'wss://mydomain.com/wss2/:8888/?myIdUser=16' failed: Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID**

--- JAVASCRIPT ----
websocket = new WebSocket("wss://mydomain.com/wss2/:8888/?myIdUser=1");

---- PHP -----
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use ChatApp\Chat;

require dirname(__FILE__).'/../vendor/autoload.php';
    
$server = IoServer::factory(
    new HttpServer(
    	new WsServer(
    		new Chat()
    	)
    ),
    8888
);

$server->run();

**Comment by skorunka** [comment]
I think this happens when your SSL certificate is unsigned and you are in Chrome?

**Comment by sebinator** [comment]
no my ssl is fine, and i don't have that issue in chrome , it occur on firefox
