### ISSUE TITLE
Bench Ratchet WampServer

### ISSUE THREAD

**Issue by andreybolonin** [ratchetphp/Ratchet#614]
https://github.com/observing/thor

<img width="621" alt="screen shot 2018-02-17 at 2 42 55 pm" src="https://user-images.githubusercontent.com/2576509/36341045-dc703954-13f0-11e8-9877-3569f8782993.png">

any ideas how to bench WampServer (Ratchet)?

**Comment by WyriHaximus** [comment]
No clue, can't seem to install that tool, and does it support WAMP v1?:
![image](https://user-images.githubusercontent.com/147145/36343427-7121ddc6-140c-11e8-803a-5bb3ad1904f1.png)

**Comment by mbonneau** [comment]
I am not aware of benchmarking tools for the WAMPv1 protocol. The project does keep an eye on the WebSocket side with the autobahn testsuite.

**Comment by andreybolonin** [comment]
wrk -t4 -c400 -d10s ws://127.0.0.1:8000
