### ISSUE TITLE
Connection closed immediately

### ISSUE THREAD

**Issue by romain83000** [ratchetphp/Ratchet#617]
Hi, 
First, Thanks for your amazing job. Really helpfull ! 
I have an issue with a device pre configured to connect to the websocket server.  The connection is closed immediately after it s opened. The device is trying to reconnect all the time.
```
 public function onOpen(ConnectionInterface $conn)
    {
      echo "on open\r\n";
      $this->repository->addClient($conn);
    }

    public function onClose(ConnectionInterface $conn)
    {
      echo "on close \r\n";
      $this->repository->removeClient($conn);
    }
```

my logs are : 
on open
on close
on open
on close
on open
on close

I had an other web socket server and the connection worked fine. Maybe i missed something with your websocket server.
Do you have an idea ?

**Comment by johankitelman** [comment]
Hey! Can you show logs from client’s console?

**Comment by romain83000** [comment]
Hello ! 
I can't show you logs from client's console because I can't access to the software code client. it's a preconfigured device so i can't modify it. 
The only things I can do are to dump packets with wireshark. 
I did it and after the message " swithing protocol " from the server, the device is disconnected.

**Comment by johankitelman** [comment]
Please make sure your software works with WAMP1.

**Comment by romain83000** [comment]
I dont really know if it works with WAMP1 ( to be honnest i dont know this protocol by the way ). Is there any way to check it ? I can just configure IP, port and path to connect to the websocket server. 
Thanks a lot trying helping me  :)

**Comment by mbonneau** [comment]
Closed due to inactivity.
