### ISSUE TITLE
Can the xdebug trigger_error be disableable? (local dev)

### ISSUE THREAD

**Issue by jraubswitch** [ratchetphp/Ratchet#621]
First off, I am only using xdebug during local development. When deployed xdebug is never loaded.

So during development, within Ratchet\App::__construct there is a check for xdebug being loaded:

```php
        if (extension_loaded('xdebug')) {
            trigger_error('XDebug extension detected. Remember to disable this if performance testing or going live!', E_USER_WARNING);
        }
```

When I'm using this library within a Symfony Command and I've configured my services in my services.yaml, this is the only way to squelch the error:

```php
<?php
declare(strict_types=1);

namespace App\Broadcast;

use Ratchet\App;
use React\EventLoop\LoopInterface;

class RatchetApp extends App
{
    /**
     * RatchetApp constructor.
     * @param string $httpHost
     * @param int $port
     * @param string $address
     * @param LoopInterface $loop
     */
    public function __construct(
        string $httpHost = 'localhost',
        int $port = 8080,
        string $address = '127.0.0.1',
        LoopInterface $loop = null
    )
    {
        @parent::__construct(
            $httpHost,
            $port,
            $address,
            $loop
        );
    }
}
```

Can there be a configurable way to override the check, so that I don't have to use this shim?

**Comment by jraubswitch** [comment]
Note: when the error happens Symfony turns it into an exception so that the command cannot be registered.

**Comment by samizdam** [comment]
I am already open similar issue #576

**Comment by str** [comment]
The flag to disable the warnining is:

```php
putenv('RATCHET_DISABLE_XDEBUG_WARN=true');
```
