### ISSUE TITLE
Send binary data

### ISSUE THREAD

**Issue by SilverDeath32** [ratchetphp/Ratchet#627]
Hi,
first a big thank you for developing and maintaining this library.

quick question:
how would i send binary data, e.g. a file.
i saw by digging around in old issues that there was once a support with an optional flag $isBinary in send method. however you removed that in https://github.com/ratchetphp/Ratchet/commit/237615890d6eb84abc14cc8182c0ccd66fd02b76 with the comment "(should pass message object instead)"

do i understand right, that ive now to manually do something like the following to send binary data:

```php
use Ratchet\RFC6455\Messaging\Frame;
$bin = file_get_contents('file.bin');
$binaryMsg = new Frame($bin, true, Frame::OP_BINARY);
$client->send($binaryMsg);
```

if yes, why is this not documented? in http://socketo.me/docs/migration-3 its only explained how to receive binary messages, not sending them and i found no other source besides that.

Many thanks,
Silver

**Comment by Jawan81** [comment]
For general binary data your approach probably won't work, because in Frame's constructor the length of the payload is determined using strlen(), which stops at the first occurrence of a '\0' character, but this might not be the last byte of the binary payload. So for binary data there should be a different method (that I don't see either).

**Comment by SilverDeath32** [comment]
oh, no, thats totally fine, in php strlen actually "knows" if its handles binary data or a string (probably because its loose typed and probably saves size+type and data seperately) and then returns the actual byte size.
e.g.
```
$hexString = '1200003456';
$bin = hex2bin($hexString);
echo 'Len is: ' . strlen($bin);
$hex = bin2hex($bin);
echo 'Hex is: ' . $hex;```
will actually output
```Len is: 5 
Hex is: 1200003456```
i also tested it with some bigger binary files with a C++ client and ratched as server and it works well.
i just wondered if its actually the "right" way to do it, cause i couldnt find any doc for it and it seemed a little bit complicated if it was a matter of setting a flag in an earlier version.

**Comment by Mecanik** [comment]
@SilverDeath32 I never seen anyone send binary data through websocket honestly, at least not as binary maybe some other form ( compressed ? ). 

From what I know, websocket is not designed for this purpose and you would be better of using something else that is documented and supported for binary data.

**Comment by SilverDeath32** [comment]
it is:
https://tools.ietf.org/html/rfc6455
it even was implemented for easy access in ratchetphp:
https://github.com/ratchetphp/Ratchet/issues/18
https://github.com/ratchetphp/Ratchet/pull/404
question is why it was removed in
https://github.com/ratchetphp/Ratchet/commit/237615890d6eb84abc14cc8182c0ccd66fd02b76

**Comment by mbonneau** [comment]
@SilverDeath32 Yes you must pass a message object if you would like to send a binary message. It was changed a while back and I can't recall the reason at the moment. It is possible that we wanted the API between the client and server to be the same for sending.

**Comment by SilverDeath32** [comment]
okay, thank you.
maybe document that somewhere (e.g. http://socketo.me/docs/migration-3 ), or add an extended api set which allows this in a more easy way.

**Comment by ryancwalsh** [comment]
@SilverDeath32 I'm wondering if you ever figured out how to put an audio file into:

```
$binaryMsg = new \Ratchet\RFC6455\Messaging\Message();
$conn->send($binaryMsg);
```

(http://socketo.me/docs/migration-3 didn't show how to do this.)

[IBM Watson Speech-to-text](https://console.bluemix.net/docs/services/speech-to-text/websockets.html#WSaudio) requires that I send an audio file as binary.

Thanks so much for any help!

**Comment by ryancwalsh** [comment]
Never mind. Here is what worked for me. Install via `composer require ratchet/pawl`.

```
\Ratchet\Client\connect($url)->then(function(\Ratchet\Client\WebSocket $conn) use($contentType, $fullFileName) {
    $conn->on('message', function($msg) use ($conn) {
        Log::debug("Received: {$msg}");
    });
    $conn->on('close', function($code = null, $reason = null) {
        Log::debug("Connection closed ({$code} - {$reason})");
    });
    $conn->send(json_encode([
        'content-type' => $contentType,
        'timestamps' => true,
        'speaker_labels' => true,
        'smart_formatting' => true,
        'inactivity_timeout' => 60 * 5,
        'x-watson-learning-opt-out' => true,
        'action' => 'start'
    ]));

    $frame = new \Ratchet\RFC6455\Messaging\Frame(file_get_contents($fullFileName), true, \Ratchet\RFC6455\Messaging\Frame::OP_BINARY);
    $binaryMsg = new \Ratchet\RFC6455\Messaging\Message();
    $binaryMsg->addFrame($frame);
    $conn->send($binaryMsg);
    $conn->send(json_encode([
        'action' => 'stop'
    ]));
}, function ($e) {
    echo "Could not connect: {$e->getMessage()}\n";
});
```
