### ISSUE TITLE
Problem send message error after 8 - 12 hours

### ISSUE THREAD

**Issue by vanht** [ratchetphp/Ratchet#628]
Afters 8 - 12 hours, When i try to connect to WebSocket server from the client, after connect success, client send message but the server respond with the following error Error during WebSocket handshake.

I'm using autobahn js from client side, but i tested the connection from Simple Websocket Client and websocket and same thing appened.

My server code:
```
        $port = 8080;
        $server = IoServer::factory(
            new HttpServer(
                new WsServer(
                    new WampServer(
                        new Wamp
                    )
                )
            )
          , $port
        );
        $server->run();
```

I run 8PM yesterday, and tested 9AM today. Two day, i don't have any solution. 
Thanks all.

**Comment by Gemorroj** [comment]
plz, add `Waml` class code

**Comment by vanht** [comment]
@Gemorroj I get code from link https://github.com/ratchetphp/socketo.me/blob/master/src/Ratchet/Website/Chat/ChatRoom.php

**Comment by vanht** [comment]
sr, I found error.
New day, wamp class can't connect mysql.
Code error: 2006
Message code: MySQL server has gone away ..

**Comment by Gemorroj** [comment]
Keep in mind that when working with a database, you should use an asynchronous model.
https://github.com/amphp/mysql for example

**Comment by vanht** [comment]
@Gemorroj Thank you.
I will confirm it.
