### ISSUE TITLE
$from->send("tx"); do not work onMessage

### ISSUE THREAD

**Issue by klys** [ratchetphp/Ratchet#632]
Hi, im using ratchet to make a TCP server for a real time server using php.

on the onMessage event i have a `$from->send("text to send to client who is triggeting the onMessage");`
 and in the client it is never received.

Also im using only ioServer component like follow:
```php
$server = IoServer::factory(
			new Chat(),
			8080	
	);
```
what im doing wrong here?

Not any error is being displayed.

Thank you for reading.

**Comment by Mecanik** [comment]
You cannot just send back a message like that, you need a **ConnectionInterface** to get the connection handle and then:

`$client->getConnection()->send("WHATEVER MESSAGE");`

But my example is just basic, I myself setup a "protocol", and send/recv messages in JSON format.

Use the example in the documentation...

**Comment by mbonneau** [comment]
@klys Can you post more information about the problem? It looks like that should generally work to me, but maybe there is something else going on.

**Comment by klys** [comment]
I follow the example on te socketo.me website about websockets, first i was using this source for websockets, but later o decided to implement a TCP only solution, which start working, i was able to connect to the server using my TCP client, i received messages to the client when another client send a message to the server, but i cant manage to get a message back when is the same client sending a message alone. Its like if is the only user connected the message is never handled...

This is my code on onMessage:

`$params = explode( "|", trim($msg));

		switch ($params[0]) {
			case '1': // message to my self
				echo "cod 1 de {$from->resourceId} \n";
				$from->send("Message");
				break;
			
			case '2': // message to all
				echo "cod 2 of {$from->resourceId} \n";
				foreach($this->clients as $client) {
					
						$client->send($params[1]); // even to my self
					
				}		
				break;
		}
`

**Comment by klys** [comment]
I solved the problem, it was created by a old dll socket implementation.

Im using a new one whitout issue.

Thank you guys for trying help!
