### ISSUE TITLE
How to deal with MySQL server has gone away error

### ISSUE THREAD

**Issue by PenguinArts** [ratchetphp/Ratchet#634]
Hi,

I am using ratchet in my application and after a certain time the server stops with this error:
"string(87) "An error has occurred: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away"

I made some research and I have increased the waiting time. I did not use the maximum time, because I am not sure if this is a good practive.
Is there another method to solve this problem ?

Thank you!

**Comment by bartnodots** [comment]
It is better to check if the connection is still alive and reconnect if it is not. Check for example http://php.net/manual/en/mysqli.ping.php

**Comment by PenguinArts** [comment]
Thank you! I will try this solution.

**Comment by PenguinArts** [comment]
I tried to figured out how to solve this issue, but I don't know where this problem starts. Where should I check if the connection is still alive and reconnect if it is not? In push-server? Where I do the connection to database? Thank you!

**Comment by cboden** [comment]
The service that is going to use the database is the service that should check if the connection is established and make a connection if it's not.

**Comment by benjaminrau** [comment]
@PenguinArts This is how i check if the mysql connection was dropped and reconnect if needed
`/**
     * @return \Doctrine\ORM\EntityManager
     */
    protected function getEntityManager()
    {
        $entityManager = $this->container->get('doctrine.orm.entity_manager');

        if (false === $entityManager->getConnection()->ping()) {
            $entityManager->getConnection()->close();
            $entityManager->getConnection()->connect();
        }

        return $entityManager;
    }`

**Comment by CPHgroup** [comment]
There is a problem with ratchet and mysql ping where ratchet custom error handler is blocking ping from working.
