### ISSUE TITLE
Chat slows down after 350+ active chat users

### ISSUE THREAD

**Issue by josephmiller2000** [ratchetphp/Ratchet#635]
When we reach 300-350+ users at a time in chat room. It slows down and takes few sec for new users to connect to socket.

Server Configuration : 
CentOS 7.4.1708
32GB RAM
Intel  Xeon E3-1270v6 - 4c/8t - 3.8GHz /4.2GHz
Nginx Latest Version.

Server Usage When we reach 350+ users is : 0.7/100
memory usage :  4%/100

Help me to sort this issue. Thanks

**Comment by mbonneau** [comment]
@josephmiller2000 Are you making any blocking function calls in your Ratchet process (sleep, blocking database calls, blocking file i/o)?

**Comment by josephmiller2000** [comment]
I'm not sure, i have to take this to my developer and see what he gonna say. 
Basically what makes the chat? to get overload when we reach 350+ active real time users?

**Comment by PenguinArts** [comment]
What your developer said? I am curios what the reason was for slowing down.

**Comment by cboden** [comment]
350 users is not be a problem for Ratchet to handle for a tiny EC2 instance, let along the behemoth of a server you're running 😀. As Matt suggested, blocking network calls are most likely preventing operations such as new connections and sending messages. Any network connections, such as database queries, that need to be done in the same running application as Ratchet need to utilize [React's](https://reactphp.org) EventLoop and be done asynchronously.
