### ISSUE TITLE
Chat bot/Advertising 

### ISSUE THREAD

**Issue by josephmiller2000** [ratchetphp/Ratchet#637]
Is it possible to create a chatbot ( automatic predefined messages should send on specific time interval ).

Can we able to do this in ratchet?

**Comment by johankitelman** [comment]
I think it's easier, faster and more logical to use JavaScript for this:)


вт, 24 апр. 2018 г. в 18:01, josephmiller2000 <notifications@github.com>:

**Comment by mbonneau** [comment]
Yes, you can use Ratchet for this.

@johankitelman - I deleted this comment because it was not answering the question.

**Comment by josephmiller2000** [comment]
@mbonneau is there any demo or GitHub project? How it is done?  Some help needed.

**Comment by mbonneau** [comment]
https://github.com/ratchetphp/socketo.me/blob/master/src/Ratchet/Website/Chat/Bot.php
