### ISSUE TITLE
[documentation] warn against using TLS with Ratchet via php-based means for users of php versions less than 7

### ISSUE THREAD

**Issue by dkrieger** [ratchetphp/Ratchet#639]
Prior to https://github.com/php/php-src/commit/17e9fc9 (landed in php v7.0.18 and v7.1.4), [fwrite() on non-blocking SSL sockets didn't work](https://bugs.php.net/bug.php?id=72333). This issue becomes more pronounced above 8kb writes, but it can happen with smaller writes. It might be helpful to warn somewhere in the documentation that versions of php prior to the aforementioned commit cannot handle TLS (as used by Ratchet, anyway) gracefully -- you already steer users towards using stunnel, and this is a pretty convincing reason.

Note: I had been calling React\Socket\Server constructor explicitly instead of using IoServer::factory() to use TLS with Ratchet -- switching (back) to stunnel now in light of this php bug.

**Comment by mbonneau** [comment]
@dkrieger Thanks for the suggestion. In future versions of Ratchet, we will be dropping support for unsupported PHP versions. PHP 7.0 is [past end-of-life already](http://php.net/eol.php), so if people are using versions earlier than 7.1, they are pretty much on their own right now anyway.
