### ISSUE TITLE
Large sends can cause memory issues

### ISSUE THREAD

**Issue by dkrieger** [ratchetphp/Ratchet#640]
To stress test my websocket server, I wrote a debug endpoint that puts a file full of an arbitrary amount of zeros -- 5MiB at time of writing -- into a string using file_get_contents(), calculates the string length using strlen(), and sends the data and the length metadata to the connection. If I fire off 5 such requests in rapid succession, I notice my ws server memory and cpu usage spike severely, and the memory remains locked up long afterward the connection is closed, requiring the server to be reset. I'm even explicitly calling unset() on the string full of zeros immediately after sending the response, but the memory remains locked up. Is it possible that buffers used for a given connection aren't getting cleaned up on connection close, and if so, is there a known solution to this?

**Comment by mbonneau** [comment]
The design of Ratchet is geared more towards smaller messages.

When you have a string that puts a large amount of data in the buffer, that causes PHP to copy the buffer 2-3 times (once for the copy into the frame, and again for encoding the raw frame from the payload, and possibly more).

You may be able to break this up yourself depending on how your application is set up by using multiple frames per message.
