### ISSUE TITLE
Closing connection doesn't stop execution

### ISSUE THREAD

**Issue by citadelnetworks** [ratchetphp/Ratchet#641]
Closing a connection using  something like the example below doesn't stop the execution of the code. 
Right now we're putting everything in if and else statements and stopping further execution like that. 
Is there a better way or proper way to do this?

Function to kill connection:
```php
public function forceClose(ConnectionInterface $conn, $reason) {
        // Close connection to client, violated security
        $conn->close();
        $this->clients->detach($conn);
        echo "PeerId: {$this->peerID}'s connection has been terminated for security reasons\n";
        echo "Reason: {$reason}\n";
    }
```

Example of calling said function:
```php
$this->forceClose($conn, 'onMessage parameter check failed');
```

**Comment by mbonneau** [comment]
@citadelnetworks If there are any open connections, listening connections, or timers open, the loop will not exit.

Are you trying to shut down the server or a single connection?

**Comment by citadelnetworks** [comment]
Well I have an option connection and that function above will close the connection if it fails a security check point. But the code execution will  continue for the connection even if the connection is closed. 

I couldn't figure out how to really stop the execution, I'm thinking a while loop but that didn't really work for some reason.

Any ideas? Sorry it's my first time using Ratchet. 

Also this is a single connection.

**Comment by mbonneau** [comment]
I am not sure what you mean that "code execution will continue for the connection even if the connection is closed".

Are you still receiving messages after you call close?

**Comment by citadelnetworks** [comment]
No the client side closes, but the code execution on the server doesn't stop.

So when the user enters, I have a function run. In the middle of the function, if the forceClose is called, the function doesn't stop executing. It'll kill the client connection and run the rest of the function outputting stuff.

**Comment by mbonneau** [comment]
@citadelnetworks The server is supposed to continue running. If you would like the server to shutdown, you will need to stop listening for connections.

**Comment by mbonneau** [comment]
@citadelnetworks The code will continue to run. It is up to the developer to prevent that code from running.

You may want to look into some reactphp tutorials that can explain better than I can how the event loop and connections work.

https://reactphp.org/#articles

**Comment by Tofandel** [comment]
You just need to return from the function.. Basic php
