### ISSUE TITLE
Call to a member function getHeader() on null

### ISSUE THREAD

**Issue by graschik** [ratchetphp/Ratchet#643]
Hi, I have some problems (

> This is my run command:
> ```php
>         try {
>             $dbHost = 'localhost';
>             $dbName = 'sessions';
>             $dbUser = 'mysql';
>             $dbPassword = 'mysql';
>             $pdo = new PDO("mysql:host=$dbHost;dbname=$dbName", $dbUser, $dbPassword);
>             $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
>         } catch (PDOException $exception) {
>             echo $exception->getMessage();
>             die;
>         }
> 
>         $dbOptions = [
>             'db_table' => 'sessions',
>             'db_id_col' => 'sess_id',
>             'db_data_col' => 'sess_data',
>             'db_time_col' => 'sess_time',
>             'db_lifetime_col' => 'sess_lifetime',
>             'lock_mode' => 0,
>         ];
> 
>         $server = IoServer::factory(
>             new HttpServer(
>                 new WsServer(
>                     new SessionProvider(
>                         new ChatServer(),
>                         new PdoSessionHandler($pdo, $dbOptions)
>                     )
>                 )
>             ),
>             8080
>         );
> 
>         $server->run();
>         //$loop->run();
>     }
> ```

>My Chat:
>```php
>     public function __construct()
>     {
>         $this->clients = new \SplObjectStorage;
>     }
> 
>     public function onOpen(ConnectionInterface $conn, RequestInterface $request=null)
>     {
>         print("new conection (". $conn->Session->get('current_user_id').")");
>         // Store the new connection to send messages to later
>         $this->clients->attach($conn);
> 
>         echo "New connection! ({$conn->resourceId})\n";
>     }
> 
>     public function onMessage(ConnectionInterface $from, $msg)
>     {
>         $numRecv = count($this->clients) - 1;
>         echo sprintf('Connection %d sending message "%s" to %d other connection%s' . "\n"
>             , $from->resourceId, $msg, $numRecv, $numRecv == 1 ? '' : 's');
> 
>         foreach ($this->clients as $client) {
>             if ($from !== $client) {
>                 // The sender is not the receiver, send to each client connected
>                 $client->send($msg);
>             }
>         }
>     }
> 
>     public function onClose(ConnectionInterface $conn)
>     {
>         // The connection is closed, remove it, as we can no longer send it messages
>         $this->clients->detach($conn);
> 
>         echo "Connection {$conn->resourceId} has disconnected\n";
>     }
> 
>     public function onError(ConnectionInterface $conn, \Exception $e)
>     {
>         echo "An error has occurred: {$e->getMessage()}\n";
> 
>         $conn->close();
>     }
>```

> My JS
>```javascript 
>         var conn = new WebSocket('ws://127.0.0.1:8080');
> 
>         conn.onopen = function(e) {
>             console.info("Connection established succesfully");
>         };
> 
>         conn.onmessage = function(e) {
>             var data = JSON.parse(e.data);
>             Chat.appendMessage(data.username, data.message);
> 
>             console.log(data);
>         };
> 
>         conn.onerror = function(e){
>             alert("Error: something went wrong with the socket.");
>             console.error(e);
>         };
>```

When I run server and go to the page, I get error "In SessionProvider.php line 77: Call to a member function getHeader() on null".
How to resolve this? 
Why my RequestInterface is null?

**Comment by mbonneau** [comment]
@graschik It looks like you are decorating the components in the wrong order. I think the `SessionProvider` needs to be passed into the `HttpServer` as `WsServer` does not pass the request into `onOpen`.

**Comment by Schneider95** [comment]
Yep, that's it.

`
$memcached = new \Memcached();
$memcached->addServer('memcached', 11211);
$memcachedSessionHandler = new MemcachedSessionHandler($memcached);

$notificationServer = new NotificationServer();

$wsServer = new WsServer($notificationServer);

$sessionProvider = new SessionProvider(
    $wsServer,
    $memcachedSessionHandler
);

$httpServer = new HttpServer($sessionProvider);

$server = IoServer::factory($httpServer, 8080);

$server->run();
 `
