### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by ben7244** [ratchetphp/Ratchet#646]
I tryed to install ratchet but It failed. 

root@7b04a4433847:/var/www/html# php composer.phar require cboden/ratchet
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^0.4.1 for cboden/ratchet
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 17 installs, 0 updates, 0 removals
    Failed to download symfony/routing from dist: The zip extension and unzip command are both missing, skipping.
The php.ini used by your command-line PHP is: /usr/local/etc/php/php.ini
    Now trying to download from source
  - Installing symfony/routing (v3.4.9): Cloning 9deb375986

  [RuntimeException]
  Failed to clone https://github.com/symfony/routing.git, git was not found, che
  ck that it is installed and in your PATH env.

  sh: 1: git: not found

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

Ps:I try an update but, it's the last version. 
The folder vendor is created but autoload.php is not present....

**Comment by mbonneau** [comment]
It looks like your OS is missing a few tools (git, unzip). Install the missing tools and try installing again.

This is not an issue with the library so I am closing this issue.
