### ISSUE TITLE
Ratchet with running php server

### ISSUE THREAD

**Issue by bassimr** [ratchetphp/Ratchet#648]
Hi,

how can I use Ratchet web socket using the default ports 80 & 443 to pass the firewall taking into consideration that php server using XAMPP is already running and using these ports

**Comment by mbonneau** [comment]
I would recommend using nginx.

**Comment by bassimr** [comment]
thank you for the reply, but can you explain how can it work with nginx ?

**Comment by mbonneau** [comment]
@bassimr - Check out these issues: https://github.com/ratchetphp/Ratchet/issues/75 https://github.com/ratchetphp/Ratchet/issues/551

Those have some tips for setting it up.
