### ISSUE TITLE
How to run server script without cmd?

### ISSUE THREAD

**Issue by zerolimitss** [ratchetphp/Ratchet#649]
I have a simple hosting without command line, ftp only.
Am I right, I should add chat_server.php file to CRON and set launching every minute? 
I did it, but it doesn't work. Does ratchet have any requirements to hosting?
I got the next error on my hosting:
`Fatal error: Uncaught RuntimeException: Failed to listen on "tcp://127.0.0.1:8080": Address already in use in `But everything works fine at the local machine.

**Comment by mbonneau** [comment]
Running it every minute will not have the desired results. You may want to look into getting a VPS or some other service that will allow you to have long-running php processes.
