### ISSUE TITLE
Tutorial App won't work

### ISSUE THREAD

**Issue by mfairchild365** [ratchetphp/Ratchet#65]
I recently tried to set up the tutorial application (http://socketo.me/docs/hello-world) on a fresh install of linux MINT 14.

However, the client JS was unable to establish a connection with the server. After some debugging, I discovered that the server was seeing the connection and attempting to send a message. However, the client never finished connecting. It is like the handshake failed somewhere.

I turned on error reporting and did not receive any errors. I tried it in both FireFox and Chrome.

I was able to install and get other php web socket servers to work (Wrench, PHPws, etc). This one was the exception.

I am not sure how to proceeded without spending an entire day debugging the system. This seems like a bug to me, and I wish I could pin point it. Has anyone else had problems like this?

**Comment by andresrivas1506** [comment]
Hi, I'm following Hello World tutorial and the first step works for me, but next step does not (work in a web browser)

**my chat-server.php**
```php
<?php
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Chat;

    require dirname(__DIR__) . '/vendor/autoload.php';

    $server = IoServer::factory(
        new HttpServer(
            new WsServer(
                new Chat()
            )
        ),
        8080
    );

    $server->run();
```

**my structure files:**
> bin/chat-server.php
> src/MyApp/Chat.php
> vendor/*

When I try to run the shell script, it don't run..

Please tell me what I'm doing bad

**Comment by cboden** [comment]
@andresrivas1506 Do you get any errors? Make sure to turn on/up error reporting:
```php
ini_set('display_errors', 1);
error_reporting(E_ALL);
```

**Comment by andresrivas1506** [comment]
Thanks for your quick answer, I was getting no errors, but I closed the terminal, ran the shell script again and now it works
