### ISSUE TITLE
how to share and manage session in socket

### ISSUE THREAD

**Issue by SunilParashar** [ratchetphp/Ratchet#651]
HI,
I am new to socket programming. I have developed a portal using MySQL and PHP. Now I want to show online status of friends/users and also chat in case he/she is online. Also I will have to use session data in socket as well as I have destroy the session on user disconnect/browser close.

How can I do this, please help me

Thanks,
Sunil

**Comment by cboden** [comment]
See the docs on http://socketo.me to being learning about socket programming, specially the [Sessions](http://socketo.me/docs/sessions) and page.
