### ISSUE TITLE
Object of class Ratchet\Wamp\WampConnection could not be converted to string

### ISSUE THREAD

**Issue by ZnarKhalil** [ratchetphp/Ratchet#652]
hi everyone, i am trying to make a command for ratchet push-server in laravel.
 i run the command and everything works fine but when i try to run client javascript this error is being display on the cmd 
**An Error has occurred: Object of class Ratchet\Wamp\WampConnection could not be converted to string**
any help please?
my laravel code 
```
<?php

namespace App\Console\Commands;

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;

use App\Socket\Pusher;
use Illuminate\Console\Command;
use React\EventLoop\Factory as ReactLoop;
use React\ZMQ\Context as ReactContext;
use React\Socket\Server as ReactServer;
use Ratchet\Wamp\WampServer;


class PushServer extends Command
{
    protected $signature = 'pushServer:serve';

    protected $description = 'Command description';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        $loop = ReactLoop::create();

        $pusher = new Pusher();
        $context = new ReactContext($loop);

        $pull = $context->getSocket(\ZMQ::SOCKET_PULL);
        $pull->bind('tcp://127.0.0.1:5555');

        $pull->on('message' ,[$pusher , 'broadcast']);

        $webSocket = new ReactServer('0.0.0.0:8080', $loop);
        $webServer = new IoServer(
            new HttpServer(
                new WsServer(
                    new WampServer(
                        $pusher
                    )
                )
            ),
            $webSocket
        );
        $this->info('Run Handle');
        $loop->run();
    }
}
```
my javascript code
```
var conn = new ab.Session('ws://localhost:8080',
            function() {
                conn.subscribe('onNewData', function(topic, data) {
                    console.log('New article published to category "' + topic + '" : ' + data.data);
                });
            },
            function() {
                console.warn('WebSocket connection closed');
            },
            {'skipSubprotocolCheck': true}
        );
```

**Comment by ZnarKhalil** [comment]
PushServer Class and javascript had no error, the error was in **onOpen function** in the base class which extends WampServerInterface

**Comment by roman-briazgalov** [comment]
ZnarKhalil, could you please say how did you resolve this problem?

**Comment by ZnarKhalil** [comment]
Hi Roman,
please make sure that your class which implements WampServerInterface is like similar code:
`<?php

namespace App\Socket\Base;


use Ratchet\ConnectionInterface;
use Ratchet\Wamp\WampServerInterface;

class BasePusher implements WampServerInterface
{
    protected $subscribedTopics = [];

    public function getSubscribedTopics(){
        return $this->subscribedTopics;
    }

    public function addSubscribedTopics($topic){
        $this->subscribedTopics[$topic->getId()] = $topic;
    }

    public function onSubscribe(ConnectionInterface $conn, $topic) {
        $this->addSubscribedTopics($topic);
    }

    public function onUnSubscribe(ConnectionInterface $conn, $topic) {
    }
    public function onOpen(ConnectionInterface $conn) {
        echo "New Connection \n";
    }
    public function onClose(ConnectionInterface $conn) {
        echo "Connection  has disconnected\n";
    }
    public function onCall(ConnectionInterface $conn, $id, $topic, array $params) {
        // In this application if clients send data it's because the user hacked around in console
        $conn->callError($id, $topic, 'You are not allowed to make calls')->close();
    }
    public function onPublish(ConnectionInterface $conn, $topic, $event, array $exclude, array $eligible) {
        // In this application if clients send data it's because the user hacked around in console
        $conn->close();
    }
    public function onError(ConnectionInterface $conn, \Exception $e) {
        echo "An Error has occurred: {$e->getMessage()}\n";
        $conn->close();
    }

}`

as for me, I had a mistake in onCall Function but I really don't remember the exact mistake.
I hope this code will help you.

**Comment by roman-briazgalov** [comment]
Hi @ZnarKhalil !
Thanks for reply!
I have checked the code and unfortunatelly i have the same code in this class. So i will try to resolve it or will make a new issue. If i find the solution i will post it here.
Thanks!
