### ISSUE TITLE
Push integration doesnt work, an example with new release?

### ISSUE THREAD

**Issue by birneos** [ratchetphp/Ratchet#655]
Hi,

my ratchet chat-server is on and the communication with clients is fantastic. Now i am want integrate the zmq functionality. Your example with push notification, i cannot get up and running. My first problem is the integration with autobahn.js. 

Do you have an example, either with a recent release of autobahn.js or an alternative to autobahn.js? I tried to integrate autobahn.ws, but that does not work either.

Thank you so much.

Marco

**Comment by mikealmond** [comment]
You need to use the older version of autobahn in order for it to work. Unfortunately you can't get that from their website anymore. There is a fork on GitHub here https://github.com/sergeyvolkov/autobahn-old
