### ISSUE TITLE
socket  connection get down issue

### ISSUE THREAD

**Issue by deepak9889** [ratchetphp/Ratchet#657]
socket  connection get down after some time....
once the socket connection is created working fine but after some time connection is get down . and stop receiving data from server.
but when i restart server(httpd) and execute server.php and start working fine again

**Comment by mbonneau** [comment]
Closed for inactivity.

@deepak9889 It sounds like you are running inside an apache process which is not the way to run the server.  It needs to be run as a standalone process.
