### ISSUE TITLE
Ratchet WebSocket Server + Apache on same Port 80 via Slim?

### ISSUE THREAD

**Issue by moonlight81** [ratchetphp/Ratchet#663]
Is it possible?

**Comment by samizdam** [comment]
It is not a Ratchet issue. 

In common case you can not run 2 application on same port on host. 
But you can proxy (with apache, nginx or another) requests to virtual hosts with same port, like this:
```
wss.example.com:80 -> Slim (as mod_php)
web.example.com:80 -> Ratchet:8080 (as socket server)
```

**Comment by moonlight81** [comment]
So if I understand you corrrctly: I can use apache as a proxy and this can get requests for ratchet connections and http requests at the same time. So it doesn't matter if I use slim for example for rooting for both services?

**Comment by moonlight81** [comment]
I solved the problem by configuring apache as a proxy
