### ISSUE TITLE
explore/support Swoole

### ISSUE THREAD

**Issue by yehosef** [ratchetphp/Ratchet#667]
I recently came across a new event lib like ReactPHP called Swoole (https://www.swoole.com/) with very impressive benchmarks:
https://gist.github.com/nkt/e49289321c744155484c
Basically, ReactPHP was getting about 1/2 the performance of NodeJS and Swoole was about 10x greater than NodeJS (20x better than ReactPHP).

I would be great if it was possible for Ratchet to support Swoole where it's available.

Why would I not just use Swoole natively?  I would prefer to use Ratchet so I can have a common interface where Swoole is not installed.  

There is a similar discussion in php-pm (https://github.com/php-pm/php-pm/issues/389) but I think with Ratchet the benefit is even greater because it's easier to reach a bottleneck with networking/concurrency (c10k).

**Comment by cboden** [comment]
"Hello World" benchmarks are to be taken with a grain of salt. 

---

I personally haven't looked into Swoole at all though. To go about doing this, one would make a replacement for the [IoServer](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Server/IoServer.php) class (and its [IoConnection class](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Server/IoConnection.php) that is bubbled through an app). I would prefer this to be a stand-alone library as, I mentioned above, I'm not familiar with Swoole, and would not want to have to officially support something I'm not familiar with.
