### ISSUE TITLE
Update phpUnit to phpUnit7

### ISSUE THREAD

**Issue by elovin** [ratchetphp/Ratchet#670]
Is there a reason to keep phpUnit < Version 5 ?

Are the tests outdated ?

**Comment by cboden** [comment]
> Is there a reason to keep phpUnit < Version 5 ?

No reason in particular. That was the latest version at the time. We'd consider merging a PR if there's no breaks. 

> Are the tests outdated?

No. The tests assert the library functions as it should.

**Comment by elovin** [comment]
okay thanks for the information
