### ISSUE TITLE
Custom sessionName parameter instead of php's one

### ISSUE THREAD

**Issue by proArtex** [ratchetphp/Ratchet#671]
Add ability to provide custom session name to VirtualSessionStorage.
Hardcoded session_name() doesn't work with Symfony framrwork for example: [WebSocketBundle issue](https://github.com/GeniusesOfSymfony/WebSocketBundle/issues/89). We can pass optional $sessionName to VirtualSessionStorage's constructor and so on.

You can read more about [Symfony sessions](https://symfony.com/doc/current/components/http_foundation/sessions.html).

**Comment by mbonneau** [comment]
Closed because the associated PR was closed.
