### ISSUE TITLE
[Q] How can I get clients real IP?

### ISSUE THREAD

**Issue by andrewgorpenko** [ratchetphp/Ratchet#673]
Good day. I am wondering if I can get clients real IP address. I’d like to get this IP in onMessage method. I tried using remoteAddress, but it always returns 127.0.0.1. Can you please help? Thanks!

**Comment by andrewgorpenko** [comment]
Mr @cboden told someone to use 
`$conn->WebSocket->request->getHeaders()`
but I receive this message from onError method: 
`Undefined property: stdClass::$request.`
 Then I found this piece of code:
`$conn->httpRequest->request->getHeaders()`
and I get this error:
`Undefined property: GuzzleHttp\Psr7\Request::$request`

Basicly what I want to do is to get real client IP with x-real-ip header or something similar to that. But this methods do not exist.

**Comment by cboden** [comment]
`$conn->WebSocket->request` is 0.3. 

`$conn->httpRequest->getHeaders()` is the method to call in 0.4.

**Comment by andrewgorpenko** [comment]
What a heck? Tried the same thing today and it showed me httpRequest is undefined and now it is working as it should be. Thanks a lot for your fast response!
