### ISSUE TITLE
how to set response headers?

### ISSUE THREAD

**Issue by moonlight81** [ratchetphp/Ratchet#674]
is it possible to set these Headers on myself and send it?

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
Sec-WebSocket-Protocol: somesubprotocols

I know that I can read the Reqeust header with $conn->httpRequest->getHeaders(), but don't know the vice versa way?

**Comment by cboden** [comment]
If you're looking to support custom sub-protocols have your component implement the [WsServerInterface](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsServerInterface.php) and return `['somesubprotocols']`;

If you're looking for other customization you'll need to create another set of decorator component/connection to handle your custom HTTP response.
