### ISSUE TITLE
WSS for Ratchet in windows IIS?

### ISSUE THREAD

**Issue by chv17** [ratchetphp/Ratchet#679]
I'm having same problem as #100 #489 and others.

But my host is in windows IIS.
Can anyone help me make an wss connection?

I tried to change directly from ws:// to wss:// but no result.

Thank you.

**Comment by beri75** [comment]
Here a useful answer about IIS configuration: https://stackoverflow.com/a/46906425/2532443
I hope can be helpful for you...

**Comment by mbonneau** [comment]
Closed for inactivity.
