### ISSUE TITLE
Ping/Pong?

### ISSUE THREAD

**Issue by hongkongkiwi** [ratchetphp/Ratchet#68]
Does Ratchet include support for Ping/Pong?

I'm using this on the client to determine if the server has disappeared. The protocal specifies this and it's pretty transparently handled on most server implementations. I'm wondering if Rachet has support for this?

**Comment by Itach1Uchixa** [comment]
Please check: Ratchet/src/Ratchet/WebSocket/Version/RFC6455.php:164
