### ISSUE TITLE
what is the format of timeStamp in onmessage callback?

### ISSUE THREAD

**Issue by engdev-trey** [ratchetphp/Ratchet#681]
Hey,

Trying to display timestamp of sent message in basic chat app.

Doing:

```
conn.onmessage = function(e)
{
    console.log(e)
}
```
displays a timeStamp property, however I've no idea of what format it's in.

Doing one message at:

> Thursday 6th September 2018 14:03 returns 123384

and another at:

> Thursday 6th September 2018 14:19 returns 2195683

They're so different (aside from two columns if we prefix the first number with a 0) that I can't tell how they're being generated. They can't be UNIX timestamp as doing a conversion returns 1 Jan 1970... what format is timeStamp in?

**Comment by engdev-trey** [comment]
Answer is:

miliseconds from server start - not from 1 Jan 1970 - which is why I got such weird results. Something that's definitely worth mentioning in the docs that you use timeago and it should be used in the project for timestamping - however, is it pos to go from 1 Jan 1970 to do a D/M/Y H:i:s format?

**Comment by cboden** [comment]
What variable are you pulling this from? I don't see Ratchet passing a date/time string anywhere. 

My recommendation is to pass your date/time string in your own payload to the client.

**Comment by mbonneau** [comment]
@engdev-trey Looks like this is talked about here: https://stackoverflow.com/questions/52204565/what-format-is-a-5-6-digit-timestamp-and-how-do-i-convert-it

This is not part of the API though.
