### ISSUE TITLE
$conn->WebSocket always return  ["closing"]=>   bool(false)

### ISSUE THREAD

**Issue by gitmasta** [ratchetphp/Ratchet#684]
i'm trying to use Ratchet with laravel but when i do a var_dump to $conn->WebSocket in onOpen or in onMessage it always return me 

> object(stdClass)#670 (1) {
  ["closing"]=>
  bool(false)
}

this is the code i use
```php
    namespace App\Http\Controllers;
    use Ratchet\MessageComponentInterface;
    use Ratchet\ConnectionInterface;
    use App;
    use Auth;
    use Config;
    use Crypt;
    use App\User;
    use Illuminate\Session\SessionManager;

    class WebSocketController extends Controller implements MessageComponentInterface{
    function onOpen(ConnectionInterface $conn){
    $session = (new SessionManager(App::getInstance()))->driver();
    var_dump($conn->WebSocket);
    }

    function onClose(ConnectionInterface $conn){
    }

    function onError(ConnectionInterface $conn, \Exception $e){
    $conn->close();
    }

    function onMessage(ConnectionInterface $conn, $msg){
    var_dump($conn->WebSocket);
    }
    }   
```

**Comment by cboden** [comment]
Can you show more code? This is only part of your setup. 

I don't think Laravel's SessionManager is going to work like this though.

**Comment by gitmasta** [comment]
what part of my code you want me to show you

**Comment by mbonneau** [comment]
@gitmasta If you could post the server code (where you put the `App` and stuff together), that would be helpful.

For now I am going to close this issue, if you are still having an issue I will reopen it.
