### ISSUE TITLE
Ratchet 0.3.6 with PHP 7

### ISSUE THREAD

**Issue by aks2193** [ratchetphp/Ratchet#685]
@cboden Hey, I was trying to setup ratchet 0.3.6 with PHP 7.0 and saw that eventlib is not supported for PHP 7.0 
I was wondering how the event driven part of react will work without event-lib?
Will it be able to handle concurrent request properly?
I am using ZeroMQ to do asynchronous jobs and all this socket level operations will come under I/O so how will the  performance get affected?

**Comment by cboden** [comment]
`stream_select` (default) will handle up to 1024 connections. After that you will require an extension. See [React's documentation](https://reactphp.org/event-loop/#loop-implementations) on loop implementations.

**Comment by aks2193** [comment]
Thanks @cboden 
@Mecanik -> Thanks for the info just had one question, I was going through some blogs and official release page and have read that  libevent-beta  has been failing with segmentation fault on PHP 7.
What's the difference between the above git link and that beta version?

**Comment by Mecanik** [comment]
There is no difference in what I posted is just how to compile and add it. I’m aware of the segmentation fault and this is why I added the second instructions for php 7.1, however the segmentation fault is in their recent commits because I was using libevent for 1+ year and had no issues.

Regardless of this, I really recommend using the “ev” extension.

**Comment by aks2193** [comment]
I tried to install libevent and get the following error when I run the "./configure" command
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for libevent support... yes, shared
checking for libevent headers in default path... not found
configure: error: Cannot find libevent headers

**Comment by Mecanik** [comment]
Where do you run "./configure" ?

**Comment by aks2193** [comment]
cd pecl-event-libevent
Inside the pecl-event-libevent folder

**Comment by aks2193** [comment]
Closing the issue for now, I am using event library instead of libevent.
Thanks for all the help.
