### ISSUE TITLE
Using event library with ratchet

### ISSUE THREAD

**Issue by aks2193** [ratchetphp/Ratchet#693]
@cboden -> Hey, so I am actually using ratchet 0.3.6 and php 7.0 on centos box.
Since libevent doesn't work with php 7.0 I have tried to install the event lib using the below mentioned commands

wget "https://bitbucket.org/osmanov/pecl-event/get/c0f1f1060100.zip"
unzip -xvf c0f1f1060100.zip 
cd osmanov-pecl-event-c0f1f1060100
phpize
yum install libevent-devel
./configure --with-event-core --with-event-extra --enable-event-debug
make
make install
added extension=event.so to /etc/php.ini file

and restarted the ratchet servers. 
How do I make sure that the event library is being used by ratchet?
Do I need to make some changes from ratchet?

**Comment by WyriHaximus** [comment]
The ReactPHP event loop factory takes care of that. (Assuming you use it to create your event loop instance.)

**Comment by aks2193** [comment]
Yep I am using the factory. Thanks for the info.
