### ISSUE TITLE
App works only in one subnet that devices use (not server subnet)

### ISSUE THREAD

**Issue by xTermy** [ratchetphp/Ratchet#695]
I have created a server and app that allows me to use voice chat and text chat, but when i tried to use it with my friend that was in his house and me in mine, but when i am in one subnet on one ip address everything is okey, You can check everything on https://projectex.pl/coowork/voice_chat/comm.html?room=5575498
Is there any solution for this problem?

--
Edit #1 I want to add that i am using WSS protocol

**Comment by mbonneau** [comment]
Closed for inactivity. Also, needs more detail/explanation of what diagnostic steps have already been taken.
