### ISSUE TITLE
bytes of buffered data lost during stream conversion

### ISSUE THREAD

**Issue by lazychaser** [ratchetphp/Ratchet#699]
Hello.

I'm using latest version of your package and reactphp with libevent for loop.

Sometimes after writing to socket, it stops responding and when I'm trying to close the connection, it throws an error:

```
Event::__construct(): 2690 bytes of buffered data lost during stream conversion! {"exception":"[object] (ErrorException(code: 0): Event::__construct(): 2690 bytes of buffered data lost during stream conversion! at /var/www/avito-messenger/vendor/react/event-loop/src/ExtEventLoop.php:84)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Event::__constr...', '/var/www/avito-...', 84, Array)
#1 /var/www/avito-messenger/vendor/react/event-loop/src/ExtEventLoop.php(84): Event->__construct(Object(EventBase), Resource id #609, 20, Object(Closure))
#2 /var/www/avito-messenger/vendor/react/stream/src/WritableResourceStream.php(60): React\\EventLoop\\ExtEventLoop->addWriteStream(Resource id #609, Array)
#3 /var/www/avito-messenger/vendor/react/stream/src/DuplexResourceStream.php(124): React\\Stream\\WritableResourceStream->write('\\x88\\x82#+vE \\xC3')
```

Also, in some cases, the whole script stops responding to timers and pcntl signals, takes 100% of CPU.

FD limit is set to 1024. I checked such stalled processess and they used less.

Can you help me?

**Comment by mbonneau** [comment]
@lazychaser This error is at a lower level than Ratchet. I don't have a lot of experience with libevent. Are you able to try this with `StreamSelectLoop` to see if libevent is the issue?

**Comment by mbonneau** [comment]
@lazychaser I am closing this now. If you are still having issues, you should open an issue over with the reactphp folks.

**Comment by blogdaren** [comment]
got the same issue, so what happened？why keep it closed?
