### ISSUE TITLE
Detection of client leaving

### ISSUE THREAD

**Issue by wpottier** [ratchetphp/Ratchet#70]
Hi,
I've an issue while using Ratchet for one of my project. It seems that sometimes the server doesn't detect the client leaving (ex: when i switch of the network on the client).
Moreover when i try to send data to that ghost connection with the server there is no error or exception thrown.

**Comment by Brade** [comment]
How do you handle sending a message that expects an immediate response? Seems like you'd have to program both sides (server and client) to send messages, and on the server side keep an array of connection ID's with most recent timestamp of heartbeat received. 

Or is there a way within the "send" function to know right away whether the client you tried to send to exists or not?

**Comment by cboden** [comment]
@Brade You're correct in theorizing both sides need to send messages. Send can not know if the client "exists" or not.

**Comment by rmoni3000** [comment]
Does Ratchet has any loop method for me to periodically check non-closed connection or should I start ping-pong on the client side and check non-closed connection on any class method? For example: onClose.

**Comment by doubleOrt** [comment]
So, no fixes as of now ? Only workarounds ?

**Comment by doubleOrt** [comment]
> @wpottier haha, indeed! I was able to replicate this issue quite easily.
>
>I did find a relatively decent workaround: Put your Ratchet application behind HAProxy (as per Ratchet's Deployment doc) setting the timeout tunnel option relatively low and have your client or server periodically send data to the other before the timeout occurs. This will ensure your timeouts will trigger Ratchet's onClose as well as keep your true long lived connections open.
>
>While the above will work for you, I'll leave this issue open and try to tackle this problem either in React, as @igorw pointed out, or perhaps at the Ratchet level by doing something like using WebSocket ping/pong frames as a heartbeat to detect timeouts.

What is the role of HAProxy in your proposed solution ? Shouldn't i be able to do just fine if i go the ping-pong way ?

**Comment by cboden** [comment]
This should be resolved in 0.4 with [`enableKeepAlive`](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsServer.php#L198) utilizing WebSocket ping/pong frames.

**Comment by sargearmstrong** [comment]
Sorry to reopen this, but can somebody kindly confirm..

1- Should OnClose within ratchet be triggered by a client's internet dropping? I've tested this before and it seemed like yes, but.. I have long running/stable ratchet instance with many connections where randomly this one client dropped (for many hours) without OnClose firing server side - so odd.

2- Does OnClose fire if a connection encounters OnError? What about if calling $conn->close(); from inside OnError?

Thanks for whatever comments!
