### ISSUE TITLE
> Are WordPress and your Ratchet application being hosted on the same server?

### ISSUE THREAD

**Issue by AnthonySaunders** [ratchetphp/Ratchet#701]
Does this mean that if they are both running on the same server that the $pull->on('message') will not execute?

_Originally posted by @AnthonySaunders in https://github.com/ratchetphp/Ratchet/issues/533#issuecomment-440389035_

**Comment by mbonneau** [comment]
No - he was just asking to verify that the addresses were correct. It works fine either way (as long as your network/firewall/etc. is setup to work that way).
