### ISSUE TITLE
Update ratchet document for session

### ISSUE THREAD

**Issue by mshamaseen** [ratchetphp/Ratchet#703]
In ratchet document for  [http://socketo.me/docs/sessions#wrapped](sessionProvider) it says wrapped by WsServer, whereas it's actually **Wrap** the WsServer not wrapped by it.

the wraps should be like this:

`IoServer::factory(
            new HttpServer(
                new SessionProvider(
                    new WsServer(
                        new Chat()
                    ),
                    new Handler\MemcachedSessionHandler($memcached)
                )
            ),
            6502
        );`

please update the document as it take me a hole week to figure this out ..

**Comment by mbonneau** [comment]
Moved to socketo.me
