### ISSUE TITLE
Routing in Ratchet and using route as variable

### ISSUE THREAD

**Issue by TechOverflow** [ratchetphp/Ratchet#704]
I have a server set up as so

```
    $server = IoServer::factory(
    new HttpServer(
        new WsServer(
            new Person()
        )
    ),
    8080
    );

    $server->run();
```

This works if the client uses `ws://localhost:8080`.

What I would like to do is set a route like `ws://localhost:8080/chat/{name}` ie. `ws://localhost:8080/chat/Bob` and then be able to use `Bob` as a variable in the `onMessage()` function, ie. 

```
    $name = $route->name;

    echo 'Welcome, ' . $name . '!'; // Welcome, Bob!
```

I have found examples like 

```
    $app = new Ratchet\App("localhost", 8080, '0.0.0.0', $loop);
    $app->route('/chat', new Chat, array('*'));

    $app->run();
```

but none mention a using a variable in the route.
How can this be accomplished? 

I have also asked this question on Stack, but noone seems to be familiar with it [link](https://stackoverflow.com/questions/53427217/routing-in-ratchet-and-using-route-as-variable).

**Comment by mbonneau** [comment]
@Jciel - Thanks for the answer.
