### ISSUE TITLE
established connection for reload page, wamp

### ISSUE THREAD

**Issue by lykich99** [ratchetphp/Ratchet#711]
Hi.
I use ratchet, autobahn, wamp pub/sub, ssl, It work.
But If the **message was sent when the page was reloaded, it will not be delivered**(now page loading), but if the page has already loaded and send the message, it will be delivered.
In chrome network wamp tub I see

Request URL: wss://aa.bbb.com:8080/
Request Method: GET
Status Code: 101 Switching Protocols
Connection: Upgrade
Sec-WebSocket-Accept: 6JkvWshQEaMc/QRxedqjn6BzxAg=
Sec-WebSocket-Protocol: wamp
Upgrade: websocket
X-Powered-By: Ratchet/0.4.1
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6
Cache-Control: no-cache
Connection: Upgrade
Cookie: PHPSESSID=ccdjog1pittbttnv0b3bus07ca
Host: aa.bbb.com:8080
Origin: https://aa.bbb.com
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: rRaDQ6PL/xe499jnxy9kKg==
Sec-WebSocket-Protocol: wamp
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

On chrome console I see Cookie: `PHPSESSID=ccdjog1pittbttnv0b3bus07ca` not change
On console websocket I see the message have been sent when page loading, but after load page this message not delivered.

```php
$pdo = new \PDO(\'mysql:host=localhost;dbname=pdo\', $dbUser, $dbPass );
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

      $dbOptions = array(
                  'db_table'    => 'sessions',
                  'db_id_col'   => 'sess_id',
                  'db_data_col' => 'sess_data',
                  'db_time_col' => 'sess_time',
				  );		
				
	$loop   = \React\EventLoop\Factory::create();
	$context = new \React\ZMQ\Context($loop);
	  //$context =  new \ZMQContext();
        $pull = $context->getSocket(\ZMQ::SOCKET_PULL);
        $pull->bind('tcp://127.0.0.1:5555');
	$pusher = new \App\Sockets\Pusher;
	$pull->on('message', array($pusher, 'onSmsEntry'));			
	$webSock = new \React\Socket\Server('0.0.0.0:8080', $loop); // Binding to 0.0.0.0 means remotes can connect
	
	$webSock = new \React\Socket\SecureServer($webSock, $loop, [
            'local_cert'        => '/etc/ssl/sms/aaa.bb_com.crt', // path to your cert
            'local_pk'          => '/etc/ssl/sms/server.key', // path to your server private key
            'allow_self_signed' => TRUE, // Allow self signed certs (should be false in production)
            'verify_peer' => FALSE
        ]);
		
	$webServer = new \Ratchet\Server\IoServer(
			new \Ratchet\Http\HttpServer(
			   new SessionProvider(	
				new \Ratchet\WebSocket\WsServer(
					new \Ratchet\Wamp\WampServer(
						$pusher
					)
				),
			     //new Handler\MemcachedSessionHandler($memcache)
				new Handler\PdoSessionHandler($pdo,$dbOptions)
			  )	
			),     
			$webSock
		);
		
	$loop->run();
```

In browser

```js
ab._debugws = true;
    var conn = new ab.Session('wss://'+ host +':8080',
        function(session) {
		    
			console.log('subscribe!!!');
			console.log('session',session);
            
		 conn.subscribe( app_user_id, function(topic, data) {
		  //session.subscribe( app_user_id, function(topic, data) {
                console.log('New message for userId = "' + topic + '" : ' + data.message);
				console.log('data',data);
				var directionTxt = '';
				if( data.direction == 'IN' ){
					directionTxt = 'Incoming message !!!';
				}
				else {
					directionTxt = 'Outgoing message !!!';
				}
				
				swal( directionTxt, "From:"+ data.from +"\n To:" + data.to + "\nState: " + data.state +"\nMessage:" + data.message );
				beep();	
                blinkTab(directionTxt);
            });
		
        },
        function( code, reason) {
            //console.warn('WebSocket connection closed');
			console.warn('WebSocket code', code);
			console.warn('WebSocket reason', reason);
        },
        {
		 'skipSubprotocolCheck': true,
		 // 'maxRetries': 60,
                 //'retryDelay': 4000,
		
		}
    );
```

If I open different pages of the site I see on console websocket

New connection! (782)                                                                                                                                      
subscribe                           
Connection Subsribe 782           
9               
 onClose      
Connection 782 has disconnected           
New connection! (787)         
subscribe                 
Connection Subsribe 787           
9New connection! (790)            
subscribe
Connection Subsribe 790 
9
 onClose
Connection 790 has disconnected
New connection! (795) 
 subscribe
Connection Subsribe 795

**Do I have the opportunity of avoid losing messages, when refreshing the page?**
Thanks for response.

**Comment by mbonneau** [comment]
@lykich99 Ratchet does not come with a built-in mechanism to allow subscriptions that will avoid losing messages when the page is refreshed.
