### ISSUE TITLE
Origin Issue

### ISSUE THREAD

**Issue by josephmiller2000** [ratchetphp/Ratchet#721]
http://socketo.me/docs/origin

I followed this method to setup, origin check and works fine. But now spam bot ( spammer ) can set >>

host and origin by getting that information from domain headers and add those information to their spam bot header to connect to the websocket.

Is there anyway to avoid users settings fake header and stop them from connecting to socket .

**Comment by cboden** [comment]
Unfortunately not. If you break down what's happening, a client is opening a socket and sending text through it, so a bad actor can send what ever text they want, including a specific origin header.

Origin check is a guard used to enforce browsers. All browsers set Origin and Host themselves and do not allow clients to overwrite it.

**Comment by josephmiller2000** [comment]
Yes i get that part 👍 

But, we are getting chat bots, spammers who can directly connect to chat socket externally to send spammy links or messages in users ( private or main rooms ).

We need some kind of 24hrs once generating key, which only should allow users connect to the socket if the key is valid and then the socket handshake happens.

In a chat.php function >> we can call they key from function where the auto key generates and we can apply it in socket connection.

But, people who does the direct connection , have to set this key manually every day to start the spam or abuse the chatters in the room.

- Because there is no filter option to check the direct socket message

- there is no any option or method to validate the socket connection is a proxy or vpn.

Im just stating this because, this will be a one step harder for spammers and it is a security feature for us.

If you have any better idea about the direct socket connection let me know.

**Comment by WyriHaximus** [comment]
> But, we are getting chat bots, spammers who can directly connect to chat socket externally to send spammy links or messages in users ( private or main rooms ).

That's the unfortunate and inconvenient truth of running a chat site.

Some random thoughts on this:
* Require users to login
* Require those users to fetch a one-time token from the server with their session to keep their chat session alive and validate that over the websocket
* Start banning IP's from spammer, both on an application level and on server level (blackholing their connection attempts on the firewall)
* You can determine which cloud provider your spammers use and black hole them, the downside of this is that legit users might have a VPN there (you could do account flags to resolve this but that means you can't blackhole on a firewall level)
* Autobanning and filtering based on patterns expressed by those bots, like link spamming on chat entry

**Comment by josephmiller2000** [comment]
@WyriHaximus yes thats right, requires user login, not everyone like to register in a chat site.

- The token thing is needed.

- Yes, blocking proxy and vpn will solve most of the issue from chat spam bots. But, need to find a 24*7 good up-time api to detect proxy and vpn ip.

- Yes chat pattern will work, sending same or repeated messages will get a auto ban. ( what is a real user who sends hai to 3 different user in a private message? ). He will get a ban right?
