### ISSUE TITLE
mutiple ports on one instance

### ISSUE THREAD

**Issue by jupitern** [ratchetphp/Ratchet#730]
Hi,
two questions:
Is the code bellow the best to handle mutiple ports on one instance?
In windows 10 / IIS, PHP 7.3.2 I cannot pass 254 connections and on Debian / Apache / PHP 7.3.2 cannot pass 1019 connections.  Any ideia why and how can I increase these numbers?

```php
use Lib\Chat\ChatServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use React\Socket\Server;
use Ratchet\Server\IoServer;
use React\EventLoop\Factory as EventLoopFactory;

require __DIR__ .DIRECTORY_SEPARATOR. 'bootstrap.php';

$chatServer = new ChatServer;

$loop = EventLoopFactory::create();
$ports = [8081, 8082];
foreach ($ports as $port) {
    $sock = new Server("0.0.0.0:{$port}", $loop);
    $server = new IoServer(new HttpServer(new WsServer($chatServer)), $sock, $loop);
}

$loop->run();

**Comment by cboden** [comment]
Yes, that is the correct way to host a multiple servers on the same running instance. 

To increase the concurrency limit you need to use a loop implantation that is not StreamSelect. See [React's documentation](https://reactphp.org/event-loop/#loop-implementations) on this.
