### ISSUE TITLE
php chat-server.php stuck

### ISSUE THREAD

**Issue by mohhamedion** [ratchetphp/Ratchet#732]
i have already do ALL the steps in ratchet tutorial 
and when i run php chat-server.php
the cmd stuck and show nothing until the CMD close by it self 

![2019-04-29_02-06-09](https://user-images.githubusercontent.com/41584933/56871222-73c1ef80-6a23-11e9-88b9-f0eddbe9b066.png)

**Comment by WyriHaximus** [comment]
Well that's the nature of writing services, they keep running endlessly and wait for something to do. In this case for websocket connections.
