### ISSUE TITLE
2 websocket servers

### ISSUE THREAD

**Issue by Dev1lDragon** [ratchetphp/Ratchet#733]
Hi my problem that i need 2 diferent websocket server for dewelop and production and when i try run first is all going wel but when i try run second i have:

Fatal error: Uncaught RuntimeException: Failed to listen on "tcp://127.0.0.1:8843": Address already in use in /beta_html/composer/websocket/vendor/react/socket/src/TcpServer.ph
p:164
Stack trace:
#0 /beta_html/composer/websocket/vendor/react/socket/src/Server.php(36): React\Socket\TcpServer->__construct('tcp://127.0.0.1...', Object(React\EventLoop\StreamSelectLoop), Arr
ay)
#1 /beta_html/composer/websocket/vendor/cboden/ratchet/src/Ratchet/App.php(90): React\Socket\Server->__construct(8843, Object(React\EventLoop\StreamSelectLoop))
#2 /beta_html/websocket/php_server.php(8): Ratchet\App->__construct('localhost', 9000)
#3 {main}
  thrown in /beta_html/composer/websocket/vendor/react/socket/src/TcpServer.php on line 164

**Comment by cboden** [comment]
Only one socket can bind to a port at a time. Your best bet will probably to run them on different ports.

**Comment by Dev1lDragon** [comment]
websocket port is diferent. first is open in port 9001 an that i try to open in port 9000

**Comment by cboden** [comment]
Your logs show you trying to connect to port `8843` which is already in use. It may or may not be PHP that has already bound to the port.

**Comment by Dev1lDragon** [comment]
port is used but i dont know whi because i define 9000 and 9001

**Comment by Dev1lDragon** [comment]
php is:
`
<?php
include '_config.php';

$connection = @fsockopen('localhost', $GLOBALS['_DW_CONF']['websocket']['port']);

if (!is_resource($connection)) {
    $app = new Ratchet\App('localhost', $GLOBALS['_DW_CONF']['websocket']['port']);
    $app->route('/app', new Doctusware\WebSocket\App, array('*'));
    $app->route('/echo', new Ratchet\Server\EchoServer, array('*'));
    $app->run();
} else {
    echo "socket is already runing";
    exit;
}
`

**Comment by cboden** [comment]
[App](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/App.php#L88) binds to port `8843` when used in order to serve Flash policy.

**Comment by Dev1lDragon** [comment]
how to bind to other port?

**Comment by cboden** [comment]
You can't. App is a "helper" class designed to take some pain away from piecing all the components together yourself. You can't run App.php on two applications on the same server at the same time.

**Comment by Dev1lDragon** [comment]
what work around for that?

**Comment by cboden** [comment]
Build your app with Ratchet's components as seen in the [documentation](http://socketo.me/docs/hello-world#next_steps).

**Comment by Dev1lDragon** [comment]
tnx

**Comment by Dev1lDragon** [comment]
1 question not related wit that how to do routes?

**Comment by Dev1lDragon** [comment]
Find sulution and that consist in duplicate your class(App.php) and change line $flashUri = 10000+$port;//8843;

**Comment by wblessen** [comment]
@cboden 

Since we are using two or more applications with websockets on the same server, 
and changing or extending the App.php from /vendor has some negative impact:

Would it be ok, to extend Ratchet, so that your flashUri Port 8843 can be changed in the constructor of App.php?

**Comment by Marre-86** [comment]
Also hit this trap.
It's quite easier actually:
```
        $loop = \React\EventLoop\Factory::create();

        $dashboard = new DashboardWebSocketServer($loop);
        $terminal = new TerminalWebSocketServer($loop);

        $server = new \Ratchet\App($host, $port, $address, $loop);
        $server->route('/dashboard', $dashboard);
        $server->route('/terminal', $terminal);

        $server->run();
```
