### ISSUE TITLE
Connection closed before receiving handshake response

### ISSUE THREAD

**Issue by mpjraaij** [ratchetphp/Ratchet#738]
Hi there,

I have integrated Ratchet with ReactPHP and when I call the endpoints from PHP with Pawl, it's resolving beautifully.

However, when I'm calling the websocket client-side I get:
```
WebSocket connection to 'ws://localhost:8687/secure/users/5mhSxnWY52XcqarFIi8wMrkwqEP2/messages/82f039fe5e424a3aac2b/events?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NTgwMDEzNTcsImV4cCI6MTU1ODAwMTk1NywianRpIjoiMVprN2l5SUVPeVozSVpNcmNLbUozcSIsImRhdGEiOnsidXNlcklkIjoiNW1oU3huV1k1MlhjcWFyRklpOHdNcmt3cUVQMiJ9fQ.cimDqbhCXoczg54ecGVGcm0Sd-t-No34BNYrbDZkPyw' failed: Connection closed before receiving a handshake response
```

This is the simple code I'm using:
```
let socket = new WebSocket(`${process.env.WS_BASE_URL}/secure/users/${uid}/messages/${cid}/events?token=${token}`)
```

I'm running it all in a docker containered environment. The port is definitely shared, it just closes the connection instantly. How do I solve this?

**Comment by mbonneau** [comment]
@mpjraaij - Could you share the server code at all or perhaps a small example that has the same behavior?
