### ISSUE TITLE
Can't seem to get Ratchet Working with Telnet

### ISSUE THREAD

**Issue by killrawr** [ratchetphp/Ratchet#739]
I have a class called [TypeWriterPhpSocketUsers](https://pastebin.com/RnnShfNA) with a file [socket.php](https://pastebin.com/ukJUT9iA)

When I run the command `php socket.php` the port 8181 for php.exe comes up as Active inside Netstat

![Net Stat](https://i.ibb.co/c2Q6CkM/rachet-netstat.png)

But my telnet is stuck on

**Microsoft Telnet> open localhost 8181
Connecting To localhost...**

What am I doing wrong??

**Comment by killrawr** [comment]
https://pastebin.com/4HbmpABg is my phpinfo

**Comment by killrawr** [comment]
bump

**Comment by cboden** [comment]
The pastebin links no longer work. It could be possible "localhost" isn't mapped for some reason? Try `telnet 127.0.0.1 8181`
