### ISSUE TITLE
Interface 'Ratchet\MessageComponentInterface' not found

### ISSUE THREAD

**Issue by parths267** [ratchetphp/Ratchet#740]
Hello,

I've referred [http://socketo.me/docs/hello-world](http://socketo.me/docs/hello-world) example,
directory structure > bin/chat-server.php, src/MyApp/Chat.php still shows 'Ratchet\MessageComponentInterface' not found

Note: - Tried composer update, as well ` "autoload": {
        "psr-4": {
            "MyApp\\": "src"
        }
    }`

**Comment by dozymoe** [comment]
Probably related to my pull request https://github.com/ratchetphp/Ratchet/pull/785

**Comment by cboden** [comment]
Try running a `composer update` before running the bin file. Composer needs to update its autoload file with reference to your directory.
