### ISSUE TITLE
How can we know the status of sent message is Read or not

### ISSUE THREAD

**Issue by sheeraz308** [ratchetphp/Ratchet#741]
Hello,

Is there any way that can give us the status of sent message . So we can show that the message is read by receiver or not.

Any help is greatly appreciated.

Thanks.

**Comment by newmediacrew** [comment]
Hello sheeraz308,

You can translate the message been seen by the receiver as a separate event.  Create something like handleMessageRead event. When the receiver is opening his application ( on focus  for example )you can send the event

Hope this helps

Regards Jerome
