### ISSUE TITLE
WsServer expecting a ComponentInterface argument

### ISSUE THREAD

**Issue by dchorel** [ratchetphp/Ratchet#748]
I followed the Hello world guide and all went well until I got to the end where we configure the server so it display what we want on a web page.
In the guide, we do it like this: 

```
$server = IoServer::factory(
    new HttpServer(
        new WsServer(
            new Chat()
        )
    ),
    8080
);
```

I'm getting an error on "new Chat()" saying that WsServer wants a ComponentInterface argument. Is the guide up-to-date? If not, how can I do it? If it is, what am I doing wrong?

**Comment by cboden** [comment]
did you remember to include `implements MessageComponentInterface` when you created the Chat class from the tutorial?
