### ISSUE TITLE
Can Ratchet work with Nginx's websocket proxying?

### ISSUE THREAD

**Issue by Rinum** [ratchetphp/Ratchet#75]
Nginx 1.3.13 has websocket support. Is it possible to use it with Ratchet? I tried it and didn't have any luck.

This is part of my .conf file with ratchet running on port 8080

<pre><code>
upstream websocket{
         server 127.0.0.1:8080;
}

server {
        location /websocket {
                 proxy_next_upstream error timeout http_502;
                 proxy_pass http://websocket;

                 proxy_http_version 1.1;

                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                 proxy_set_header Host $http_host;
                 proxy_set_header X-NginX-Proxy true;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection "Upgrade";

                 proxy_redirect off;
        }
}
</code></pre>

**Comment by Mecanik** [comment]
Well in my case, I cannot get the real_ip to pass it to the websocket....

**Comment by dartkinselok** [comment]
@Mecanik you have to pass `proxy_set_header X-Real-IP $remote_addr;` header to your location section.
