### ISSUE TITLE
Opacache + Ratchet

### ISSUE THREAD

**Issue by titansoftime** [ratchetphp/Ratchet#750]
I was just wondering if I should bother enabling php opcache in cli mode. I have a web based mmo which uses ratchet to handle user input as well as a periodic game loop that updates the user state every 0.5 seconds.

Anyone have any input on this?

**Comment by mbonneau** [comment]
I would say opcache is of no value here. There is no reason to cache the compilation of a long-running script as the compilation only happens when files are loaded - it does not effect performance once the script is up and running.

**Comment by titansoftime** [comment]
Gotcha. Thank you.
