### ISSUE TITLE
Testing Websocket server with PHPUnit

### ISSUE THREAD

**Issue by Cypaubr** [ratchetphp/Ratchet#751]
Hi is it possible to test my WS server with PHPUnit (mocking Connections etc.)?

**Comment by nhovratov** [comment]
You can use the mocks provided by ratchets own test. For connections it would be: `Ratchet\Mock\Connection`.
Just make sure to include the autoloader in your phpunit bootstrap file: `$autoloader->addPsr4('Ratchet\\', dirname(__DIR__) . '/vendor/cboden/ratchet/tests/helpers/Ratchet');`
