### ISSUE TITLE
Multiples sends on the same onMessage

### ISSUE THREAD

**Issue by wederfabricio** [ratchetphp/Ratchet#755]
Hello guys! I would like to do make someting like this:

onMessage:

        foreach ($this->clients as $client) {
            if ($from === $client) {
                $client->send($msg);
                sleep(10);
                $client->send('Anything');
            }
        }

And in my client browser: 

[20/09/2019 15:49:10]: Response of message1
//20s after...
[20/09/2019 15:49:20]: Response of message1

But I get:

[20/09/2019 15:49:20]: Response of message1
[20/09/2019 15:49:20]: Response of message1

It's possible?

**Comment by WyriHaximus** [comment]
You're using sleep so you're blocking the actual sending of messages so both arrive at the same time for the client

**Comment by wederfabricio** [comment]
Hello @WyriHaximus , thanks for your comment.

I was using **sleep** for simulate other requests, doing a manually delay between them. So, using sleep I caused this?

I need send multiple responses to client, and I wish they were sent instantly, without wait all messages as I mentioned above.

**Comment by WyriHaximus** [comment]
Using sleep in a event loop will block the loop and everything in it. As soon as you `$client->send` the event loop will start working to schedule sending the data for you, but it's not happening immaterially

**Comment by wederfabricio** [comment]
Thanks @WyriHaximus for your attention.

**Comment by murnieza** [comment]
I am having the same issue. I need to send out multiple messages back to client before I am done processing received message. 

I also added sleep but just for the sake of debugging the process. 

Is it possible to send response messages immediately?
