### ISSUE TITLE
Symfony + Ratchet loosing EntityManager Object in OnMessage function

### ISSUE THREAD

**Issue by DanielTecza** [ratchetphp/Ratchet#757]
Hi, i have a problem with objects in OnMessage function.

```php
$entity = $this->getUserQuestionById($data->UserQuestionId);

protected function getUserQuestionById($id)
   {
        $em = $this->container->get('doctrine')->getEntityManager();
        if ($em->getConnection()->ping() === false) {
            $em->getConnection()->close();
            $em->getConnection()->connect();
        }
        $entity = $em->getRepository('XXXBundle:XxxxXxxx')->find($id);
        return $entity ? $entity : false;
    }
```
i passed ContainerInterface to the constructor 

after about 1 week ratchet cant see my entity manager.
where I made a mistake?

**Comment by cboden** [comment]
Can you post more of your code please? This code looks ok, but there's a lot of context missing.

**Comment by DanielTecza** [comment]
Sory for the late of course i can here is my problem

<?php

namespace QuizBundle\WebSocket;

use Ratchet\ConnectionInterface;
use Ratchet\MessageComponentInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Doctrine\ORM\EntityManager;

class Notification implements MessageComponentInterface
{
    protected $clients;
    protected $container;
    protected $logger;

    public function __construct(ContainerInterface $container, $logger)
    {
        $this->clients = new \SplObjectStorage;
        $this->container = $container;
        $this->logger = $logger;
    }

    public function onOpen(ConnectionInterface $conn)
    {
        // Store the new connection to send messages to later
        $this->logger->info('New Connection');

        $this->clients->attach($conn);

        echo "New connection! ({$conn->resourceId})\n";
    }

    public function onMessage(ConnectionInterface $from, $msg)
    {
        try {
            $this->logger->info('Reciver Message, Body:' . $msg);
            $data = json_decode($msg);
            $dt = new \DateTime('@' . $data->startTime);
            $dt->modify('+30000 seconds');

            $entity = $this->getUserQuestionById($data->UserQuestionId);
            if (!$entity) {
                exec(getcwd() . '/restartWebSocket.sh');
            } else {
                if ($entity->getUniquHash() == $data->UniqueHash) {
                    $this->setUserQuestionDeadline($entity, $dt);
                    $from->send(30);
                    echo sprintf(
'Użytkownik o sesji: %s Wysyła prośbę o aktualizację pytania o Id "%s" ' . "
\n"
                        , $from->resourceId, $data->UserQuestionId);
                } else {
                    echo sprintf('Napotkano błąd!!' . "\n");
                    $from->send('Error');
                }
            }
        } catch (\Exception $e) {
            echo sprintf('Error:' . $e->getMessage());
            $from->send('Error' . $e);
        }
    }

    public function onClose(ConnectionInterface $conn)
    {

// The connection is closed, remove it, as we can no longer send it messages
        $this->clients->detach($conn);

        echo "Connection {$conn->resourceId} has disconnected\n";
        $this->logger->info('Disconected: ' . $conn->resourceId);
    }

    public function onError(ConnectionInterface $conn, \Exception $e)
    {
        $this->logger->error('Error:' . $e->getMessage());
        echo "An error has occurred: {$e->getMessage()}\n";

        $conn->close();
    }

    /**
     * Get UserQuestion by Id
     *
     * @param [type] $id
     * @return void
     */
    protected function getUserQuestionById($id)
    {
        $em = $this->container->get('doctrine')->getEntityManager();
        if ($em->getConnection()->ping() === false) {
            $em->getConnection()->close();
            $em->getConnection()->connect();
        }
        $entity = $em->getRepository('xxx:xxx')->find($id);

        return $entity ? $entity : false;
    }

    /**
     * Set new deadline
     *
     * @param UserQuestion $entity
     * @param DateTime $dateTime
     * @return void
     */
    protected function setUserQuestionDeadline($entity, $dateTime)
    {
        $dt = new \DateTime();
        $dt->modify('+31 seconds');
        $em = $this->container->get('doctrine')->getEntityManager();
        if ($em->getConnection()->ping() === false) {
            $em->getConnection()->close();
            $em->getConnection()->connect();
        }
        $entity->setDeadlineTimestamp($dateTime->getTimestamp());
        $entity->setDeadline($dt);
        $em->persist($entity);
        $em->flush();

        return true;
    }
}
Okey where is problem when i pass ContainerInterface and i get My Doctrine
Manager  after 2 weeks i dont get reponse from my entity Manager why?
conenction is not lost becuase i can ping echo to my database but update or
select query can not be done? this is very strange situation for me because
i must reload my WebSocket connection kill port and restart WS server every
week. any idea what i done wrong ?

wt., 5 lis 2019 o 16:26 Chris Boden <notifications@github.com> napisał(a):

**Comment by BrandonGillis** [comment]
Hello, I have exactly the same issue when using symfony4 + Ratchet. After some times I get the message "the entity manager is closed." and so I can't request the Db with doctrine anymore.

**Comment by pjcarly** [comment]
I had similar issues in the past, although not directly with Symfony (but with Drupal, which is built upon Symfony), and what turned out was causing the issue. Was that MySQL/MariaDB automatically closes the Database connection, when it has been unused for a long time (iirc 12 hours).

So if your application hasn't done any database interaction for over 12 hours, the connection would be closed from the MySQL side. We were able to solve the issue, by adding a task on the event loop, that would do a simple query once every few hours, to keep the database connection open (although the timeout can also be configured from the database side).

You never run into this issue when doing PHP applications for simple Request/Response applications, but for long running processes like Ratchet this is most definitely an issue.

I'm not sure if this will fix your issues, but decided to answer in case it might help you.

**Comment by cboden** [comment]
I believe @pjcarly advise is correct. Closing issue for now, you can reopen if this does not solve it.
