### ISSUE TITLE
How do I make it run in nginx php fpm ? 

### ISSUE THREAD

**Issue by qiulang** [ratchetphp/Ratchet#760]
Hi, this is a question.

I have a laravel app that I want to introduce websocket feature so I am thinking about using Ratchet.  My laravel app runs nginx+ php fpm , so how do I make it work with Ratchet ?

So far the only solution I can think of is to start a Ratchet process and let it communicate with my php fpm (thru redis)

Is there a better way ? Thanks!

**Comment by mostafaahamidmanon** [comment]
The best way is to employ Supervisord and make the proper configuration for it to hold the command that you have created.
Supervisord is designed to work with it.
Here is the documentation: [http://socketo.me/docs/deploy](http://socketo.me/docs/deploy)

Also, there are other different solutions that can be like Systemd but it not totally designed for application tier and more applicable to operating system processes and it also not recommended to to use it specially if Systemd is managing the operating system processes, then it is insecure to use it within the application tier and keep it exposed to external TCP connections, and it is better to use Supervisord separately as a process manager only for application tier.

**Comment by qiulang** [comment]
Hi thanks for reply. 
But your answer is more about deployment of Ratchet but my question is about any recommended way to make Ratchet server communicate with php fpm

**Comment by mbonneau** [comment]
Here is another idea: https://github.com/mbonneau/RatchetHttpPusher

**Comment by qiulang** [comment]
@mbonneau I haven't check your code but if you use http, how does Ratchet sent message to web server ?

**Comment by mbonneau** [comment]
@qiulang - It sets up its own server (react/http) just for the push notification - there is also an example script that shows how to post using it.
