### ISSUE TITLE
Could not open input file

### ISSUE THREAD

**Issue by swapnilbambal** [ratchetphp/Ratchet#762]
Hello,

I am facing following problem during installation

F:\xampp\htdocs\RatchatApplication>php ~/composer.phar require cboden/ratchet
Could not open input file: ~/composer.phar

**Comment by cboden** [comment]
That instruction is assuming you installed composer.phar in your home directory on a *nix based system. 

Please follow [composer's installation instructions for Windows](https://getcomposer.org/doc/00-intro.md#installation-windows) and adjust your command to your composer path accordingly.
