### ISSUE TITLE
Cant connect to database in ratchet

### ISSUE THREAD

**Issue by loginpoint** [ratchetphp/Ratchet#763]
i am using ratchet to make live messenger  so  i am trying to use mysql database to add online user and remove them when they close the problem is when i am trying to connect to database by mysql or pdo i got this error Class 'MyApp\mysql' not found in C:\xampp\htdocs\Athena\access\websocket\src\chat.php:8 or Class 'MyApp\PDO' not found in C:\xampp\htdocs\Athena\access\websocket\src\chat.php:8 in case of using pdo

and this is my code :
`<?php
namespace MyApp;
use Ratchet\MessageComponentInterface;
use Ratchet\ConnectionInterface;
use MyApp\conn;
class Chat implements MessageComponentInterface {
    public function __construct() {
        $conn = new mysql('localhost','user','','athena');
        $this->clients = new \SplObjectStorage;
    }
    public function onOpen(ConnectionInterface $conn) {
        $conn->query('INSERT INTO athena VALUES(id,1,1)');
        $this->clients->attach($conn);
        $data['type'] = 'id';
        $data['id'] = $conn->resourceId;
        $conn->send(json_encode($data));
        echo count($this->clients) - 1;
        echo "New connection! ({$conn->resourceId})\n";
    }

    public function onMessage(ConnectionInterface $from, $msg) {
        $numRecv = count($this->clients) - 1;
        echo sprintf('Connection %d sending message "%s" to %d other connection%s' . "\n"
            , $from->resourceId, $msg, $numRecv, $numRecv == 1 ? '' : 's');
        foreach ($this->clients as $client) {
            $data = json_decode($msg,true);
            $port = $data['port'];
            $code = json_encode($from);
            if ($port == $client->resourceId) {
                $client->send($msg);
            }
        }
    }

    public function onClose(ConnectionInterface $conn) {
        $this->clients->detach($conn);

        echo "Connection {$conn->resourceId} has disconnected\6";
    }

    public function onError(ConnectionInterface $conn, \Exception $e) {
        echo "An error has occurred: {$e->getMessage()}\n";

        $conn->close();
    }
}`

**Comment by WyriHaximus** [comment]
Looks like you don't have the PDO extension installed. There is a problem with using PDO tho, it blocks the event loop. Take a look at https://github.com/voryx/PgAsync/ (PostGreSQL) or https://github.com/friends-of-reactphp/mysql (MySQL) for your database needs.

**Comment by loginpoint** [comment]
> 
> 
> Looks like you don't have the PDO extension installed. There is a problem with using PDO tho, it blocks the event loop. Take a look at https://github.com/voryx/PgAsync/ (PostGreSQL) or https://github.com/friends-of-reactphp/mysql (MySQL) for your database needs

i am using xampp i think it contain pdo extenstion because i am using pdo in another projects and it work fine

**Comment by WyriHaximus** [comment]
Are they also ran from the cli or through fpm? And what's the difference environment configuration wise between those projects?

**Comment by erlangp** [comment]
@loginpoint
```
C:\xampp\htdocs\Athena\access\websocket\src\chat.php:8 or Class 'MyApp\PDO' not found in
```

i think u need to import the PDO class.

try to add `use PDO;` in your file

**Comment by webtinax** [comment]
your config file (database connect configs database name & ...) in http request has defined 
load file config in websocket process

**Comment by cboden** [comment]
It's possible your xampp and cli are reading different php.ini files. The web one may be loading PDO while the CLI is not.

**Comment by i4kelly** [comment]
> It's possible your xampp and cli are reading different php.ini files. The web one may be loading PDO while the CLI is not.

this this worked for me...
