### ISSUE TITLE
Weboscket with notification

### ISSUE THREAD

**Issue by nomopo** [ratchetphp/Ratchet#765]
Hello, can you help me? One client have a server that send me a JSON in random time, and i like to create a "script" or "app" that when i recive this i have a popup in my desktop. I think that best option is Websockets, Is it? Can you help me? thanks
The problem is that i don't know how can send this json to websocket-server.

**Comment by mcunha98** [comment]
The best sample you can follow and implement is http://socketo.me/docs/push
Is easy to understand the code, hard to setup environment...
