### ISSUE TITLE
Is there any spam protection option available to avoid BURP suite websocket spam

### ISSUE THREAD

**Issue by josephmiller2000** [ratchetphp/Ratchet#767]
There is a new option in burp suite, we can send the particular socket message to repeater or intruder to send multiple spam message using socket connection.

Is there anyway to avoid this kind of socket spam?. If i use some php check on the backend, it will eat all my server resources. Becoz, it should check each message of hundreds of chatters.

So, give me a solution to avoid this issue and fix the websocket spam.

**Comment by cboden** [comment]
Checkout the [IpBlackList](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Server/IpBlackList.php) class for some inspiration. You could increment a counter for every message sent by a single connection and if that surpasses a given threshold disconnect them.
