### ISSUE TITLE
How to use enableKeepAlive with the code from the "Push Integration" tutorial?

### ISSUE THREAD

**Issue by digitalpenguin** [ratchetphp/Ratchet#780]
Hi, 
I have built an integration following the Push Integration tutorial.
http://socketo.me/docs/push#tying_it_together

On my staging server the websocket connections are timing out after about a minute.
I saw in another issue I should be using `enableKeepAlive`:
https://github.com/ratchetphp/Ratchet/issues/728

My question is, how can I use that with the code from the tutorial:
```
<?php
    require dirname(__DIR__) . '/vendor/autoload.php';

    $loop   = React\EventLoop\Factory::create();
    $pusher = new MyApp\Pusher;

    // Listen for the web server to make a ZeroMQ push after an ajax request
    $context = new React\ZMQ\Context($loop);
    $pull = $context->getSocket(ZMQ::SOCKET_PULL);
    $pull->bind('tcp://127.0.0.1:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself
    $pull->on('message', array($pusher, 'onBlogEntry'));

    // Set up our WebSocket server for clients wanting real-time updates
    $webSock = new React\Socket\Server('0.0.0.0:8080', $loop); // Binding to 0.0.0.0 means remotes can connect
    $webServer = new Ratchet\Server\IoServer(
        new Ratchet\Http\HttpServer(
            new Ratchet\WebSocket\WsServer(
                new Ratchet\Wamp\WampServer(
                    $pusher
                )
            )
        ),
        $webSock
    );

    $loop->run();
```

Adding `$pusher->enableKeepAlive($webServer->loop, 30);` just before `$loop->run();` causes it to crash.

**Comment by cboden** [comment]
`$pusher` is an instance of `MyApp\Pusher` which, from the tutorial, does not have the `enableKeepAlive` method. This method is part of the `WsServer` class. When instantiating `WsServer` you'll need to assign it to a variable instead of creating is anonymously, then call the `enableKeepAlive` method on it before running the EventLoop.
