### ISSUE TITLE
Binary messages when using the App class

### ISSUE THREAD

**Issue by matheusb-comp** [ratchetphp/Ratchet#786]
In the [docs](http://socketo.me/docs/migration-3) about supporting binary messages, it is stated that the controller should implement `Ratchet\WebSocket\MessageComponentInterface`.

However, if using [`Ratchet\App`](http://socketo.me/api/class-Ratchet.App.html), when adding a new route with this controller, the `WsServer` is not created, since the [`$controller instanceof MessageComponentInterface`](https://github.com/ratchetphp/Ratchet/blob/57721e1f184f9e29378fc5363867c47ddda743fd/src/Ratchet/App.php#L108) test fails.

Is the `App` class expected to only be used with `Ratchet\MessageComponentInterface` controllers?

**Comment by cboden** [comment]
> \Ratchet\WebSocket\MessageComponentInterface used to extend \Ratchet\MessageComponentInterface but that was broken up into smaller and different interfaces in order to support binary messages. I forgot to update App accordingly.
