### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'MyApp\Socket' not found in 

### ISSUE THREAD

**Issue by pedropaulowski** [ratchetphp/Ratchet#791]
The error I received is this: "PHP Fatal error: Uncaught Error: Class 'Socket \ Socket' not found in /home/damas.ml/public/app.php:16 ". The error is in production, in localhost does not give this problem. Here are some files:
Sorry if i can't do this here

socket.php
```

<?php

namespace Socket;

use Ratchet\MessageComponentInterface;
use Ratchet\ConnectionInterface;
use Jogo\Jogo;
```
app.php

```
<?php

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Socket;




require dirname( __FILE__ ) . '/vendor/autoload.php';

$server = IoServer::factory(
    new HttpServer(
        new WsServer(
            new Socket()
        )
    ),
    8080
);

$server->run();
```
e o composer.json
```

{
    "autoload": {
        "psr-4": {
            "MyApp\\": "app",
            "Jogo\\": "jogo"
        }
    },
    "require": {
        "cboden/ratchet": "^0.4"
    } }
```

**Comment by darkworks** [comment]
try but including your socket.php

`require dirname( __FILE__ ) . '/MyApp/socket.php';`

**Comment by diaz3801** [comment]
your file name ./app/socket.php should be ./app/Socket.php for autoloader to load class properly
