### ISSUE TITLE
Apache mod_proxy_wstunnel SSL not working

### ISSUE THREAD

**Issue by Blaztix** [ratchetphp/Ratchet#796]
First of all, I know there is many issues and others in internet about this, but a read a lot, I think I am understanding but I can't get it work.

I'm working on a VPS with WHM (cPanel) and apache.
I installed
```apacheconf 
mod_proxy
mod_proxy_wstunnel
```

As I am working with WHM I cant modify httpd.conf directly, but I a create includes files.

```
/usr/local/apache/conf/userdata/ssl/2_4/{myUser}/{myDomain}/socket.conf
/usr/local/apache/conf/userdata/std/2_4/{myUser}/{myDomain}/socket.conf
```

In both files a write this

```apacheconf 
SSLProxyEngine on
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

ProxyPass /ws2/  ws://localhost:8081/
ProxyPass /wss2/ wss://localhost:8081/
```

Rebuilt apache httpd.conf and restart

```bash
/usr/local/cpanel/scripts/rebuildhttpdconf
/usr/local/cpanel/scripts/restartsrv_httpd
```

my PHP code

```php
<?php
require dirname(__DIR__,2) . '/vendor/autoload.php';

use App\Config;

use Ratchet\Server\IoServer;

use Ratchet\Http\HttpServer;
use Ratchet\Http\OriginCheck;
use Ratchet\WebSocket\WsServer;

use App\Socket\Ins;

$checkedApp = new OriginCheck(new WsServer(new Ins()), array(Config::URL)); #This work OK


$server = IoServer::factory(
            new HttpServer(
              $checkedApp
            ),
          8081
         );
$server->run();
```

I do many test and I got to many different errors ( 200, 404, 500, 503, 524, timeout)

1) This works good under `ws://` but no under `wss://`
2) I think `ProxyPass` is working fine, becuase without this I need use `ws://vps123.myhostingprovider.com:8081` and now `ws://myDomain.com/ws2/` its working.

Now, if I try
`conn = new WebSocket('wss://myDomain.com/wss2/');`

```
WebSocket connection to 'wss://myDomain.com/wss2/' failed: WebSocket opening handshake timed out
```

And detect this in apache log
`tail -f /usr/local/apache/logs/error_log`

```
[Sat Apr 11 02:17:28.832059 2020] [proxy:error] [pid 6235:tid 47412102215424] (20014)Internal error (specific information not available): [client {myIP}:50620] AH01084: passrequest body failed to 127.0.0.1:8081 (localhost)
[Sat Apr 11 02:17:28.832121 2020] [proxy:error] [pid 6235:tid 47412102215424] [client {myIP}:50620] AH00898: Error during SSL Handshake with remote server returned by /wss2/
```

**Comment by TechOverflow** [comment]
Did you specify the route to the cert files?
Here's my setup

```
$MyServer = new MyServer();

$app = new Ratchet\Http\HttpServer(
    new Ratchet\WebSocket\WsServer(
        $MyServer
    )
);

$loop = React\EventLoop\Factory::create();

$secure_websockets = new React\Socket\Server('0.0.0.0:8081', $loop);
$secure_websockets = new React\Socket\SecureServer($secure_websockets, $loop, [
    'local_cert' => '/path/to/cert/cert.pem',
    'local_pk' => '/path/to/cert/privkey.pem',
    'verify_peer' => false
]);

$secure_websockets_server = new Ratchet\Server\IoServer($app, $secure_websockets, $loop);

$secure_websockets_server->run();
```

**Comment by Blaztix** [comment]
I change this to
```php
<?php
require dirname(__DIR__,2) . '/vendor/autoload.php';

use App\Config;

use Ratchet\Server\IoServer;

use Ratchet\Http\HttpServer;
use Ratchet\Http\OriginCheck;
use Ratchet\WebSocket\WsServer;

use App\Socket\Ins;


$checkedApp = new OriginCheck(
       new WsServer(
            new Ins()
        ),
        array(Config::URL,'testdomain.com')
);

$app = new Ratchet\Http\HttpServer(
    $checkedApp
);   
    
$loop = React\EventLoop\Factory::create();

$secure_websockets = new React\Socket\Server('0.0.0.0:8081', $loop);
$secure_websockets = new React\Socket\SecureServer($secure_websockets, $loop, [
	'local_cert' => '/var/cpanel/ssl/apache_tls/{myDomain}/combined',
	'allow_self_signed' => true,
	'verify_peer' => false
]);
$secure_websockets_server = new Ratchet\Server\IoServer($app, $secure_websockets, $loop);

$secure_websockets_server->run();
```

Now when I try connect **sometime** say `New connection! ( {number} )`  
But client never recive 101 response.

Apache log
```
[Sat Apr 11 12:14:08.485726 2020] [proxy:error] [pid 11856:tid 47412091709184] (111)Connection refused: AH00957: WSS: attempt to connect to 127.0.0.1:8081 (localhost) failed
[Sat Apr 11 12:14:08.485764 2020] [proxy_wstunnel:error] [pid 11856:tid 47412091709184] [client {myIp}:51416] AH02452: failed to make connection to backend: localhost
```

**Comment by Blaztix** [comment]
I don't why, but now its working. I think the server was restarted and the socket start working without any problem.

**Comment by zhiyong80** [comment]
@Blaztix Could you update how your server has been running since Apr 2020? I too had some weird problem with socket, most likely because I tried to connect two pushing clients to the same socket, problems remained after I corrected the socket port but disappeared after system reboot.

**Comment by Fyod** [comment]
You need to restart the service in order for changes in (for example) server.php to happen. 
Server.php (or whatever file has the basic `run()` setup is basically an infinite loop, so you need to check `ps aux | grep php` and kill the process. Then just start the php script again.
This is why a full server restart applies any changes you make.

**Comment by zhiyong80** [comment]
@Fyod Thanks for the explanation. I did abort all the scripts with Ctrl + C, I guess that's not enough to reset some state at system level. After struggling with weird issues like messages being pushed to socket that I once accidentally bind to but not intended no more for 2 hours, I just restarted the system, and problem solved.
