### ISSUE TITLE
I can't get  websocket connection. 

### ISSUE THREAD

**Issue by Brian1111** [ratchetphp/Ratchet#798]
On Chrome console, I receive the following message:  "chatroom.php:72 WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 302";  "Connection Closed!"

And on Windows command prompt, I receive the following message:  "Fatal error: Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8080": An attempt was made to access a socke
t in a way forbidden by its access permissions."

**Comment by nineff** [comment]
sounds like that port is blocked by something else, did you try a different port?

**Comment by Brian1111** [comment]
Yes, I tried several different ports.  Also, I turned off the firewall and antivirus.  Nothing helps.  It did work on the beginning tutorial, Hello World.  Then suddenly stopped.  What could have blocked the port?

**Comment by Brian1111** [comment]
Sometimes I get the following message.   I removed ratchet package and reinstalled it on the first instruction, Hello World, code.  Now I am getting the following error on Windows command prompt, which states `class 'MyApp\Chat' not found`:

`PHP Fatal error:  Uncaught Error: Class 'MyApp\Chat' not found in C:\xampp\htdocs\rachet_websocket\bin\server.php:12`

**Comment by Brian1111** [comment]
I removed composer ratchet package from the code of Hello World, i.e., original tutorial, and reinstalled it.  Now on Windows command prompt, it says Server is connected, so I  am not getting error message.  But when I copy and paste the JavaScript code in Chrome console, I get the following error message:

`VM11:1 WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 302`

**Comment by Brian1111** [comment]
I could fix part of the problem, so now I can connect to XAMPP server.   I configured XAMPP to listen only to the IP Address of the localhost, i.e., `Listen 127.0.0.1:8080`.   However, still I get the following error at Chrome console:  

`WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 302
(anonymous) @ chatroom.php:68
j @ jquery.min.js:2
k @ jquery.min.js:2
chatroom.php:82 Connection Closed!`

Chrome console indicates that the problem is in the `chatroom.php` file in the following jquery code:

`var conn = new WebSocket('ws://localhost:8080');`

**Comment by Brian1111** [comment]
The problem apparently is with the Ratchet server library code because when I user another server, e.g.,  `echo.websocket.org`, the HTML5 websocket JavaScript code establishes a connection.   I have been using the same Ratchet code that has been posted by Ratchet.    However, I wonder why I am the only one who has gotten this problem?

**Comment by nineff** [comment]
sounds like a local issue on your machine then, as echo.websocket.org is a remote one.

**Comment by Brian1111** [comment]
Yes it is.   However, I have no problem using XAMPP localhost:8080 on other websites.  Probably I should try other PHP websocket server libraries or uninstall XAMPP and install WAMP instead.

**Comment by Brian1111** [comment]
I uninstalled XAMPP and installed WAMP instead.  Now I am getting 200 error message instead of 320 error message on Chrome console.
`WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 200`

**Comment by cboden** [comment]
You need to run the Ratchet script from a shell terminal. You don't access it through standard CGI.

**Comment by Brian1111** [comment]
Do you mean to run it from GIT Bash instead of Windows Command Prompt?   I did run it from GIT Bash; still I am getting the same error.

**Comment by Brian1111** [comment]
What do you mean by run the Ratchet script from a shell terminal?    I can get server connection both from GIT Bash and Windows Command Prompt.  However, on Chrome console I get error 200 message when I run it on WAMP server and I got error 320 message when I ran it on XAMPP server, as I stated above.

**Comment by Brian1111** [comment]
I am getting the same error message when haven't started Ratchet server as when I start Ratchet server: ` WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: Unexpected response code: 200`.   So starting Ratchet server doesn't make any difference to websocket connection.

**Comment by Brian1111** [comment]
I want to run this program on my website on GoDaddy to see if it works on their computer.  How can I create a CRON job on GoDaddy shared hosting site?   Should it be as follows?
`php public_html/ratchet_hello_world/bin/server.php`,  or  `php /usr/local/bin/ea-php56 /home/myusername/public_html/ratchet_hello_world3/bin/server.php`, or should I write it differently?
Also what should I put for port number on `bin/server.php` file instead of `8080`?

**Comment by Brian1111** [comment]
Here is more info.   I can get Telnet connection to the Ratchet server localhost.  However, after connection the blinking cursor doesn't move and I can't type anything into it.  After  I type something to it, e.g., ("Hello") and click return, I get  an error message, as attached images.

![1  Server Connection](https://user-images.githubusercontent.com/12651236/80410924-2ec3d980-8880-11ea-9616-fb00b83246ec.jpg)
![2  Telnet Connection](https://user-images.githubusercontent.com/12651236/80410932-32576080-8880-11ea-864c-9d739e16e7f2.jpg)
![3  Telnet Connection Error](https://user-images.githubusercontent.com/12651236/80410945-38e5d800-8880-11ea-8472-65c51c03c53b.jpg)

**Comment by cboden** [comment]
Your screen shots are missing the initial telnet command and the HTTP request you typed. However, based on the response it looks like you hit your Apache server, not the Ratchet server.

**Comment by Brian1111** [comment]
What do you mean by the screen shot missing the HTTP request that I typed?  I didn't type any HTTP request inside the command prompt.   However, I did type `$ telnet localhost 8080`.   What is the reason that it hit the Apache server and not the Ratchet server?    I suspect that Ratchet doesn't work on Windows 10.   I switched from WAMP to XAMPP, and tried running it on port 80.   It  didn't  help.  Now I am trying to run it on Ubuntu inside Virtualbox.     Should I make more changes inside the Apache server so Telnet connects to the Ratchet server instead of Apache server?

**Comment by cboden** [comment]
You don't need WAMP or XAMPP or anything like that for a Ratchet server. You especially should't run Ratchet inside one of those. 

> What is the reason that it hit the Apache server and not the Ratchet server?

You requested the port that Apache is listening on. If 8080 is both the port Apache and Ratchet are listening on, that's the problem. Either shut down Apache, change its port, or change Ratchet's port and re-start your Ratchet process.

**Comment by Brian1111** [comment]
I could connect to Ratchet server without XAMPP.  Do I need Apache server then?   I could connect telnet to Ratchet; however, again I could not type anything into telnet after the connection.  After that I copied and pasted the JavasScript code into Chrome console, and after entering `conn.send('Hello World!');`  I was able to see Hello World! on Chrome console in another browser.   But I could not make the JavaScript code work on index.php file,  so I had to paste it in Chrome console to make it work.

Attached is the screenshot of the command prompt that shows it is connected.   

![ratchet_server_connection](https://user-images.githubusercontent.com/12651236/81001824-27ab4700-8dfd-11ea-9c6a-9694e09ed426.jpg)

**Comment by Brian1111** [comment]
What should I write in the URL after localhost:8080 to make index.php work?   The following URL doesn't work:  `localhost:8080/ratchet_hello_world/index.php`

**Comment by Brian1111** [comment]
I ran Apache server on port 8081, and I ran Ratchet server on port 8080.    I could make it work finally.  So I close this comment.   However on the next lesson, I have problem installing ZeroMQ extension.

**Comment by nineff** [comment]
you don't nessesarily need apache, but you need some kind of webserver (like apache, nginx, iis, ...) which will be responsible for to serve the HTML generated by your index.php script.
The (pure php) script using reatchet is then another server (not a webserver but a web_socket_server) which has nothing to do with your index.php

**Comment by Brian1111** [comment]
Yes, there are two server running side by side.  Chris Boden instructions says that the standard practice is to use nginx as a proxy.   So do I need nginx as a third server, so three servers running side by side?
