### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by rukavina** [ratchetphp/Ratchet#801]
Hello,
Are there plans for version 1.0, and if yes what's expected to change comparing current 0.4.

Thanks!

**Comment by cboden** [comment]
We've been considering this lately:

* Replace connection magic getters/setters with explicit functions. See [containers branch](https://github.com/ratchetphp/Ratchet/tree/container/src/Ratchet)
* PHP 7.?
* Compression

Ratchet currently functions very well and has for a very very long time. "1.0" is just a number.

**Comment by rukavina** [comment]
Thanks for the quick answer!
I agree that it's very stable for a long time. IMHO 0.3.x could have been 1.x, 0.4.x 2.x.
But from the semantic versioning point of view, it's not just a number. Unlike 0.x, 1.x should guarantee stable API and compatibility. And I think composer rules behave differently for stable releases.
All in all, I think the project is ready for 1.x and that would provide more confidence from other projects depending on it.

**Comment by cboden** [comment]
You're right, we could (probably should) have tagged 0.3 as 1.0. 

Matt and I are working to get that list of 3 features complete to push a new version though. Stay tuned.

**Comment by cboden** [comment]
v0.5 milestone has been updated with our goals. 

v0.5 will be a candidate for v1.0
