### ISSUE TITLE
I connected Ratchet server on hosting site, but when I paste JavaScript code I get an error.

### ISSUE THREAD

**Issue by Brian1111** [ratchetphp/Ratchet#803]
I could run Ratchet server on my shared hosting site on GoDaddy terminal.  Attached is the screenshot:

![cPanel_server_started](https://user-images.githubusercontent.com/12651236/81245512-08154980-8fca-11ea-95e0-d9f0ec2b3997.jpg)

But when I paste the JavaScript code to Chrome console, I get an error message.  Attached are the screenshots:

![Chrome_console_error](https://user-images.githubusercontent.com/12651236/81245431-cc7a7f80-8fc9-11ea-92bd-d761466c9313.jpg)
![Chrome_console_error2](https://user-images.githubusercontent.com/12651236/81245434-cedcd980-8fc9-11ea-9faf-417935f72401.jpg)

You can check it for yourself at the following link:  

http://pika4.com/ratchet_hello_world2/

**Comment by cboden** [comment]
Have you configured your hosting's security to allow port 8000 to be open? Most hosting providers block everything except port 80 and 443 by default.

**Comment by Brian1111** [comment]
It runs on port 8080.  Apparently GoDaddy hasn't blocked port 8080 because it says server connected and I am not getting any error message.  What is your opinion?  

I tried to run it on a subdomain on port 80, but it didn't work.  Please clarify if I run it on port 80 do I need two servers or one server is enough?  Also, if I run it on port 80, should I run it on a subdomain?   Can I run it on main domain?

**Comment by Brian1111** [comment]
Here is more info:  When I don't run Ratchet server on GoDaddy Chrome console shows an error message and network status shows nothing.  However, when I run Ratchet server on GoDaddy terminal, the error on Chrome console disappears and network status becomes 200.

**Comment by Brian1111** [comment]
I ran several port scanners.  Apparently the only port that is open is port 80.  And port 8080 is closed.  So can I run my program on port 80 only on one server?   Or is the only option to upload my program to a cloud hosting such as Digital Ocean or AWS?

**Comment by Brian1111** [comment]
The only way to run Ratchet server is by deploying it to a cloud hosting.  So I close this issue.
