### ISSUE TITLE
Class 'MyApp\Chat' not found

### ISSUE THREAD

**Issue by wpmanoj** [ratchetphp/Ratchet#804]
Hi, this is seems like regular problem but still lack of solutions. tried lot to solve but couldn't with any solution. this will help lot of people who is trying to use ratchet.

using - ratchet hello world example (exact same source code on web) 

this example works in windows perfectly. but in google cloud platform Ubuntu 16.4 gave this error.

error message is -
PHP Fatal error:  Uncaught Error: Class 'MyApp\Chat' not found in /home/wpman/ws/bin/server.php:12
Stack trace:
#0 {main}
  thrown in /home/wpman/ws/bin/server.php on line 12

project directory
~/ws/bin/server.php
~/ws/src/chat.php
~/ws/vendor/
~/ws/composer.json
~/ws/composer.lock
~/ws/composer.phar

**Comment by nineff** [comment]
did you simply copy your files from a windows machine to a linux server? in that case all include paths are likely wrong. run composer update to fix them.

**Comment by wpmanoj** [comment]
No i din't copy files from window
I followed installation document. used composer.

almost 10 days, i still couldn't find a solution.

thank you for replying.

**Comment by cboden** [comment]
Try running `composer update` again before running server.php

**Comment by anatmart** [comment]
websocket folder

bin\chat-server.php
src\MyApp\Chat.php
composer.json
{    
	"autoload": {
        "psr-4": {
            "MyApp\\": "**src/MyApp**"
        }
    },
    "require": {
        "cboden/ratchet": "^0.4.4"
    }
}

**Comment by JoseGonzalez84** [comment]
@anatmart hit the bullseye! this works for me. Thanks.
