### ISSUE TITLE
Help needed based on your experience 

### ISSUE THREAD

**Issue by K12AZ** [ratchetphp/Ratchet#821]
Hi Guys, 

Good day, I have a few confusing things about Ratchet. If will be great if anyone can help me understand the floor.

I have already created a room based chat application for testing. That is very basic I have created as a hello world project.

##############################
Story
##############################

Basically what I want to create a school-based chat application.

**for example**, in school, there are 1 to 5 grades. in each grade, there will be 30 or 40 students. (this can be different to each class) and for each class time-based teachers will join. 

**example** Math teacher 8 am to 8.45.  English teacher 8.45 to 9.30

First version teachers can share word files, pdfs, and photos. but later we are planning to take video or screen share to students. 

##############################
Questions
##############################
 

1. When we connect Ratchet where its best to keep data? Memcache or database MYSQL?
2. let's think if the student registered to the system. so after Ratchet Initialized, we will have a resource ID, 

> is this resource ID permanent? I mean, can I use this id later to send messages. 
> or what is the best way. example one to one chat 

3. What is the best way to keep chat history,

4. teacher can disable chat when needed. how to do such an activity 

Thank you, Looking forward to hearing suggestions and recommendations.

**Comment by nineff** [comment]
First of all, did you have a look at the existing open source solutions for your usecase? [Big Blue Button](https://github.com/bigbluebutton/bigbluebutton) comes directly to mind.
But to answer your questions: 
1. To keep data permanently, use a database. For short-term storage it really depends, both options have their pros and cons, memcache might be slightly faster.
2. the resource ID stays the same as long as the web-socket connection persists, but it is not permanent in the sense you're talking about. You have to authenticate your users in a different way and correlate this other method with your websocket connections. This can be done using sessions. See The tutorial on the website and #816.
3. probably writing it to a database
4. you could define roles for specific users and have them execute "server commands" which govern the behavior of your application. You might also set up a REST API or have a dedicated control panel for those users. Also the Pub/Sub pattern of the WAMP Subprotocoll might be useable.

**Comment by K12AZ** [comment]
@nineff  Thank you for your time and answers. I will have a look at Big Blue Button.
