### ISSUE TITLE
Integer before json string?

### ISSUE THREAD

**Issue by great9** [ratchetphp/Ratchet#826]
I'm getting:
`0{"sid":"616e62f6-1c51-4b73-987c-8b0d5cff03d4","upgrades":["websocket"],"pingInterval":5000,"pingTimeout":20000}`

Is there a problem with the way I'm opening the messageInterface?
`$Socket->on('message', function (\Ratchet\RFC6455\Messaging\MessageInterface $wsdata) use ($var1,$var) {`

**Comment by nineff** [comment]
This is very little code to guess on, but my feeling says there is probably another function returning false (cast to string and therefore displayed as 0) somewhere before.

**Comment by great9** [comment]
Well, before that we only have `$connector= new Ratchet\Client\Connector($loop);

$connector($ws_url)->then(function (Ratchet\Client\WebSocket $socket) use 
	($var1, $var2...) {

**Comment by cboden** [comment]
I've had this issue pop up a few times in personal projects...I can't remember specifics but it was something silly I was doing. Like I was accidentally echo'ing the output of an assignment.

**Comment by great9** [comment]
socket url: wss://wbs.mxc.com/socket.io/?EIO=3&transport=websocket
here's just the first message (all messages have the integer in front.
`0{"sid":"4900b5c6-114b-4836-916a-b1158a5f0c10","upgrades":["websocket"],"pingInterval":5000,"pingTimeout":20000}`

Am I crazy?

**Comment by cboden** [comment]
Can you show more of your server side code please? There's not enough context to get an understanding of what's going on.

**Comment by great9** [comment]
it's client side...
`$connection($ws_url)->then(function` (Ratchet\Client\WebSocket $exchangeSocket) use ($var){
echo "Connected\n";
//subscribe to some channels....
 $exchangeSocket->on('message', function (\Ratchet\RFC6455\Messaging\MessageInterface $wsdata) use () {
echo $wsdata."\n";
`

spits those values out

**Comment by cboden** [comment]
Do you get the same result when using a web browser from the same server?

**Comment by great9** [comment]
No I don't experience the same output using browser-native websocket
library. But the ws messaging does contain the integer in front of the json
response from the server afair.

**Comment by cboden** [comment]
What language/library is the server side in?

**Comment by great9** [comment]
I have no idea

**Comment by cboden** [comment]
Is the URL public?

**Comment by cboden** [comment]
> But the ws messaging does contain the integer in front of the json response from the server

If the server is sending a `0`, this is a server issue, not a client parsing issue.

**Comment by great9** [comment]
but the native browser libraries don't have a problem with this, and they are basically clients parsing that data.

**Comment by WyriHaximus** [comment]
Could it be chunked encoding?
