### ISSUE TITLE
Ratchet Slowing Down

### ISSUE THREAD

**Issue by areebmajeed** [ratchetphp/Ratchet#827]
**Server Specifications:**

Intel(R) Xeon(R) CPU E5-2670 @ 2.60GHz x 32 Cores
32 GB RAM
Ubuntu

Using ExtEventLoop

```
    [soft core] => 0
    [hard core] => unlimited
    [soft data] => unlimited
    [hard data] => unlimited
    [soft stack] => 8388608
    [hard stack] => unlimited
    [soft totalmem] => unlimited
    [hard totalmem] => unlimited
    [soft rss] => unlimited
    [hard rss] => unlimited
    [soft maxproc] => 2097152
    [hard maxproc] => 2097152
    [soft memlock] => 67108864
    [hard memlock] => 67108864
    [soft cpu] => unlimited
    [hard cpu] => unlimited
    [soft filesize] => unlimited
    [hard filesize] => unlimited
    [soft openfiles] => 65535
    [hard openfiles] => 65535
```

After every restart of the WS server, it runs fine for 2-3 days, after which it occasionally slows down. The load on the server remains the same, more or less. The average number of connected users is 500, and that usually ranges between 400 to 700, nothing unusual here. The WS server processes over 1,000 to 3,000 messages per second.

This is a statistics server. Every second, there are over 2,000 messages and they are sent to the connected clients (around ~500). As far as I know, there is no blocking code on the server.

Do you have any idea what could be happening and how would be I able to debug this issue?

**Comment by areebmajeed** [comment]
The average RAM usage is around 400 MB and the average CPU load is 65%, but it also peaks to 100%+, sometimes, I believe.

**Comment by cboden** [comment]
The CPU spikes are probably when it loops the 2000 x 500 msgs/clients, which is fine. Technically, that looping is blocking but it will be so fast it should be negligible. 

If it begins to slow down after several days that would lead me to first look for a memory leak. If you're building any state with connections ensure they're being cleaned up/removed upon disconnecting. Same with any data incoming/outgoing. Sounds like you've done this already though; that 400MB is the whole process even after the slow down?

My next step would be to enable XDebug and run a Cachegrind profile. This will tell you how long each function call takes to run and should point you to a slow culprit. Beware though, enabling XDebug itself will slow your process down on its own, so if this is production you should monitor performance and disable it once you have a Cachegrind profile to work with.

**Comment by areebmajeed** [comment]
I'll wait till the WS server slows down again and then I will post up some diagnostic information here. After that, I would be moving forward with the debugging tool you've suggested. Thank you so much

**Comment by areebmajeed** [comment]
Okay, the server has started glitching now.

RAM Usage: 587 MB
CPU Usage: 100% (Fixed)

WebSocket connection to 'wss://xxx.xxx.xx/xxx/' failed: Error during WebSocket handshake: Unexpected response code: 502

The WS server is up and printing to the terminal every second as I had intended it to.

**Comment by areebmajeed** [comment]
Unable to run Profiler on this because it ends up with the following error(s):

PHP Warning:  EventBase::loop(): Failed to invoke event callback in /root/.wss-server/Ratchet/react/event-loop/src/ExtEventLoop.php on line 204

PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting!

**Comment by WyriHaximus** [comment]
@areebmajeed do you have xdebug or anything enabled on the server?

**Comment by areebmajeed** [comment]
> @areebmajeed do you have xdebug or anything enabled on the server?

Yes, that's what I am trying to use, atm. However, it is causing the process to crash with the errors given above.

**Comment by WyriHaximus** [comment]
> > @areebmajeed do you have xdebug or anything enabled on the server?
> 
> Yes, that's what I am trying to use, atm. However, it is causing the process to crash with the errors given above.

@areebmajeed Do you have the stack trace?

**Comment by areebmajeed** [comment]
> > > @areebmajeed do you have xdebug or anything enabled on the server?
> > 
> > 
> > Yes, that's what I am trying to use, atm. However, it is causing the process to crash with the errors given above.
> 
> @areebmajeed Do you have the stack trace?

Ah, I didn't copy that. I will try running it again.

**Comment by vfuse** [comment]
I am having the same issue, we are using this for a live stream of logging data. Once starting the server it's able to handle 1000 messages/s easily but after a few hours it's limited to about 10 messages/sec. The only option is to restart the websocket server.

**Comment by cboden** [comment]
@vfuse please set `xdebug.profiler_enable` to `1` and provide a KCacheGrind file.

**Comment by areebmajeed** [comment]
I fixed this issue a few days back. One of the arrays containing specific users (who were listening to the logs) wasn't being cleared on disconnect.

One line fix and since then, no slowdowns! 👍
