### ISSUE TITLE
How to verify if end to end connection compression is happening

### ISSUE THREAD

**Issue by aks2193** [ratchetphp/Ratchet#829]
Hey @cboden ,
Firstly thanks for maintaining and developing this library.

I am using ratchet 0.4.1 and was wondering how do I determine if the connection coming to the server is compressed or not?

Below is a small part of my code based on what I could find from documentation 

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use Ratchet\WebSocket\MessageComponentInterface;
use Ratchet\ConnectionInterface;
use React\EventLoop\Timer\Timer;
use GuzzleHttp\Message\Request;
use Guzzle\Parser\ParserRegistry;
use Guzzle\Http\Message\RequestInterface;
use Ratchet\RFC6455\Messaging\MessageInterface;
use Ratchet\RFC6455\Messaging\Frame;
use Dflydev\FigCookies\FigRequestCookies;
use Dflydev\FigCookies\Cookies;

class ServerApplication implements MessageComponentInterface {
   
    public function onOpen(ConnectionInterface $conn) {
        // Store the new connection to send messages to later
        $this->id[$conn->resourceId] = $conn;
    }
 
    public function onMessage(ConnectionInterface $from, MessageInterface $msg) {
            $binaryMsg = new Frame($msg, true, Frame::OP_BINARY);
            $from->send($binaryMsg);
    }

Any help will be highly helpful here, trying to understand the workings here.

**Comment by cboden** [comment]
If you're asking if data sent/received is gzipped using deflate, the code is in the library but isn't being utilized yet. 

Binary messages are meant for non-plain text; images for example. 

I'm not quite sure what you're asking/trying to do.

**Comment by aks2193** [comment]
Hey so yeah I am asking related to data sent/received is gzipped using deflate. So basically I wanted to send a complete compressed format data. Can you guide me as to starting point of how do I use that feature and any specific reason why its not being used yet?

Also if I do binary for normal text messages then will it provide any improvement over sending normal text data?

Really sorry if the questions are novice.
Thanks for all the help

**Comment by cboden** [comment]
> Also if I do binary for normal text messages then will it provide any improvement over sending normal text data?

No, using text in binary frames will just make your life unnecessarily complicated. 😀

> Can you guide me as to starting point of how do I use that feature and any specific reason why its not being used yet?

At a high level we need to replicate code used in the [RFC lib test server](https://github.com/ratchetphp/RFC6455/blob/master/tests/ab/startServer.php) into [WsServer](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsServer.php) to support deflate along with coming up with an interface that allows optional user configuration with sensible defaults if omitted. If I remember correctly it hasn't been turned on yet as we had a bit of a cyclic dependency issue that needs to be solved. @mbonneau and I are going to take a look at it this week.
