### ISSUE TITLE
How to monitor performance of server?

### ISSUE THREAD

**Issue by zhiyong80** [ratchetphp/Ratchet#830]
Hi,

I am trying to monitor the performance of Ratchet server. At the minimum, the total number of connections, then latency, message count etc. of each connection. What are the proper ways to do this?

I can think of either store connections data onto disk then share that file, or store connections data into database, or add a separate end point to beam out those numbers upon all open/close/message events. The later seems a more proper way. But then there is authentication, which doesn't seem to be easy/out of box in Ratchet.

Please advise. Thanks.

**Comment by nineff** [comment]
I imagine you'd basically have to create your own testsuite for this. You could useeither client-side measurements or server-side measurements (or a combination of both) for latency. (You might want to look at #823 for an implementation regarding server side measurements)

Number of connections and message count can only really be measured on the server, a database seems to be the logical step here. Authentication can then be handled by this database as well.

**Comment by zhiyong80** [comment]
I just went through beyondcode/laravel-websockets, the package that wraps around Ratchet for Laravel, it seems monitoring of cocurrent connections , message counts of each connection is done by periodically updating entries in database.
