### ISSUE TITLE
verifyUpgradeRequest will always return false

### ISSUE THREAD

**Issue by alexandersamson** [ratchetphp/Ratchet#831]
![image](https://user-images.githubusercontent.com/32638530/92667508-6ea9cb80-f30c-11ea-8219-0627d66e63f8.png)
`verifyUpgradeRequest` will always return false, because of a capital 'W'. In effect it always returns a 426 on handshake (HTTP Server)
Using: `"cboden/ratchet": "^0.4.3"`

**Comment by cboden** [comment]
I'm not sure where this code is coming from? The [line you're referring to](https://github.com/ratchetphp/RFC6455/blob/master/src/Handshake/RequestVerifier.php#L86) is located in the RFC6455 lib and git blame shows that logic hasn't changed in 5 years.

**Comment by alexandersamson** [comment]
`vendor/ratchet/rfc6455/src/Handshake/RequestVerifier.php`
That's the file. Really weird. It took me over an hour to pinpoint the 426 on that 'W'. Of course, the `var_dump`s are mine. Any clue on how this could end up differently on my side?
I could still backtrace the composer command i've used:
`C:\Users\xxx\mafiaPhpApi>composer require cboden/ratchet`
Could that have reeled in a wrong/older version of the files? But then still, the version looks proper to me in the `composer.json`, sitting at `0.4.3`.

**Comment by WyriHaximus** [comment]
Bitrot?

**Comment by cboden** [comment]
If you're able to provide a reproducible repo, please feel free to re-open the issue, but as I don't see how this is possible I'm closing this for now.
