### ISSUE TITLE
Looking for a Senior Ratchet+PHP developer

### ISSUE THREAD

**Issue by expo1998** [ratchetphp/Ratchet#838]
Hi,
first of all **apologies** if this is not the right forum or way to reach out to the Ratchet community. If that is the case please point me in the right direction.

We're looking for a senior PHP+Ratchet developer to work on a back end project we need to develop.
It's basically a relatively simple Async Websocket server with connections to a MySQL database. 
We can disclose the details and discuss terms with interested developers.

Much appreciated

Regards
Expo98

**Comment by cboden** [comment]
Hi 👋. 

I have some availability coming up for part-time contract work. Feel free to reach me by email if interested in opening a dialog.

**Comment by expo1998** [comment]
Hi, thank you
I am definitely interested in discussing the project with you.
How may I reach you?

Sent from ProtonMail mobile

-------- Original Message --------
