### ISSUE TITLE
not working with ssl enabled on the server

### ISSUE THREAD

**Issue by akramg478** [ratchetphp/Ratchet#839]
Hi,

Thanks for the awesome work, but all my efforts going waste so far as I even bought vps server now to run this library. But as soon as ssl is enabled it throws error and does not work. Played a lot and well checked Google but unable to solve. Can you please guide how to run it on ssl ... ?

My code is:

`use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
    require dirname(__DIR__) . '/vendor/autoload.php';

    $server = IoServer::factory(
        new HttpServer(
            new WsServer(
                new Chat()
            )
        ),
        8080
    );

    $server->run();

and my js calling code is`

`var conn = new WebSocket('ws://162.214.163.112:8080'); `

even tried with wss but does not work .. any one knows here please ???

**Comment by arrudatr** [comment]
if you are using https frontend, you cant use "ws" without proxypass...

**Comment by cboden** [comment]
How did you enable SSL? That is not shown in your details. Also, if you're attempting to connect via SSL the protocol on the front end should be `wss://`

**Comment by LuizCarlos-Success** [comment]
Good morning people.
I had been looking for this solution for some time.
And I managed to make it work on my VPS server.
Without having to adapt the code in the Ratchet library.
Following the suggestion of **arrudatr**, using the proxypass.

**Proxypass configuration. (In my case the support made it for me)**
ProxyPass "/ws/" "ws://yourdomain:8081/"
ProxyPass "/wss/" "wss://yourdomain: 8081/"

**Adaptation of the script.js file:**
// WebSocket

  var conn = new WebSocket ('wss: // yourdomain / ws /');
// or
  var conn = new WebSocket ('wss: // yourdomain / wss /');
     conn.onopen = function (e) {
         console.log ("Connection established!");
     };

conn.onmessage = function (e) {
// console.log (e.data);
     showMessages ('other', e.data);
};
That's it guys.
Luiz Carlos Teixeira

**Comment by david-marweblous** [comment]
Hey everyone.

I have been searching everywhere to find a solution to this problem and still come out empty handed..
I have a VPS with plesk obsidian installed. Have implemnted proxy pass in apache and still nothing.
My app works fine on localhost but as soon as i put it on the server and run it nothing. error could not establish connection with the server on wss://mydomain.com/8080

If anybody could help i would much appreciate it as i have been at this for about a month now with no soloction :'(

**Comment by cboden** [comment]
Check out this tweet: https://twitter.com/PhippsyTech/status/1368355232032329733

**Comment by david-marweblous** [comment]
Thanks for the quick reply :D

Have modfied the server.php like in the post added the route to my keys and still nothing.. don't know what im missing
Server.php
```
<?php
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Chat;

use React\EventLoop\Factory as LoopFactory;
use React\Socket\SecureServer;
use React\Socket\Server;

require dirname(__DIR__) . '/vendor/autoload.php';

$loop = LoopFactory::create();

$server = new IoServer(
    new HttpServer(
        new WsServer(
            new Chat()
        )
        ),
        new SecureServer(
            new Server(
                '0.0.0.0:8091', $loop
            ),
            $loop, [
                'local_cert' => '/opt/psa/var/modules/letsencrypt/etc/live/www.mydomain.com/fullchain.pem',
                'local_pk' => '/opt/psa/var/modules/letsencrypt/etc/live/www.mydomwin.com/privkey.pem',
                'allow_self_signed' => FALSE,
                'verify_peer' => FALSE
            ]
        )
);
$loop->run();

js code
 var conn = new WebSocket('wss://mydomain.com:8091');
```
Apart from this i have tried changing the app.php file as suguested in troubleshoot.

`public function __construct($httpHost = 'mydomain', $port = 8091, $address = 'ipadress of server', LoopInterface $loop = null) {`

if i add proxy pass to apache i get a 500 error.

Again any help is much appreciate.

**Comment by david-marweblous** [comment]
Thanks for the quick response :D

implemented this and found an error with the proxy_path (bloody plesk)

all working now.
Thanks for your help :D
