### ISSUE TITLE
Plan for v0.5 milestone

### ISSUE THREAD

**Issue by simPod** [ratchetphp/Ratchet#841]
Hello is there any plan for releasing v0.5 or anything that could be done to move it forward? Thanks!

**Comment by cboden** [comment]
I have a rough roadmap written down on a piece of paper...which is not at all useful or transparent for collaboration (shame on me 🔔). The [0.5 milestone](https://github.com/ratchetphp/Ratchet/milestone/16) also includes a rough outline. 

I will commit to creating issues for a full v0.5 roadmap in the next couple of weeks so we can move forward with getting a new release out.

**Comment by cboden** [comment]
Thanks for the nudge @simPod, here we go! #850
