### ISSUE TITLE
How to send data of another class to ratchet after send to client?

### ISSUE THREAD

**Issue by miladfathi021** [ratchetphp/Ratchet#845]
I want to send data to ratchet via class in php to send it to client

send data through JavaScript

        var conn = new WebSocket('ws://localhost:6001/');
        conn.onmessage = function(e) { console.log(e.data); };
        conn.onopen = function(e) { conn.send('Hi'); };
But I want to send data to ratchet via php for send notification

How do I do this?

**Comment by cboden** [comment]
Have you checked out https://github.com/ratchetphp/Pawl?

**Comment by miladfathi021** [comment]
Thank you bro
