### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by titansoftime** [ratchetphp/Ratchet#853]
I'm sorry I know this is probably not the place for this but has anyone had any issues with Ratchet after upgrading to PHP8? Their list of breaking changes is pretty large and I am a little hesitant to upgrade even though 5.4 -> 7.0 worked very well minus one easy to fix issue (granted was easy since someone posted the solution online).

**Comment by WyriHaximus** [comment]
Test it out locally. All the underlying @reactphp libraries have been updated to support PHP 8.

**Comment by nineff** [comment]
a very quick test from my side worked, but sessions did not. As I previously had problems with that I'll have to investigate further.

**Comment by ahmeteminkocal** [comment]
It works great for me except there is a problem with ev and event libraries. I couldn't build them using pecl. And because of that my current open connection limit is about 1024.

**Comment by titansoftime** [comment]
So far I have had no issues with Ratchet! Can't say the same for my own code but that was all my own fault =]

Going to close as this appears to be a non-issue.
