### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by nathnat** [ratchetphp/Ratchet#858]
Salutations,

I'm running a WebSocket server using Ratchet but I am having issues connecting in JavaScript.

### The issue
I get the following error:
`WebSocket connection to 'ws://my-domain.com:8080/' failed: Error during WebSocket handshake: Unexpected response code: 200`

### My code
Server:
```
$app = new Ratchet\App('my-domain.com', 8080);
$app->route('/', new ServerImpl, array('*'));
$app->run();
```

Browser:
```
let connexion = new WebSocket('ws://my-domain.com:8080');
```
### Sidenotes
I am using Apache 2.4.41 (Ubuntu) and PHP 7.4.3.

**Comment by cboden** [comment]
Is Apache configured to listen on port 8080? Ratchet does not return 200 status codes.

**Comment by nathnat** [comment]
I close it because I don't get any response.
