### ISSUE TITLE
Memory leaks when a client with a low internet speed connects

### ISSUE THREAD

**Issue by kraven99** [ratchetphp/Ratchet#861]
Hi. I'm just looking for solution to such problem: when a client with a low internet speed connects, the message queue overflows causing a memory leak in ram. 
I would be so glad for any advice.

**Comment by WyriHaximus** [comment]
Increase your service's memory limit. Or put your message queue in an external service

**Comment by kraven99** [comment]
> Increase your service's memory limit. Or put your message queue in an external service

Thank you for your advice, it may be useful for my production.
And could you suggest, where does messege queue store (specific location/variable).
