### ISSUE TITLE
concurrency model question

### ISSUE THREAD

**Issue by wmerfalen** [ratchetphp/Ratchet#868]
Hello. I'm using the Ratchet I/O demo used on this page: http://socketo.me/docs/hello-world
I am using the full example that includes:
```    
$server = IoServer::factory(
        new HttpServer(
            new WsServer(
                new Chat()
            )
        ),
        8080
    );
```
My question is: is this setup single threaded? I'd like for my class to maintain the same member variable as state and the sole reason for using Ratchet is that I do not have multiple requests being processed at the same time.

To elaborate further, all I'm doing is storing an array of integers. A web socket client can reserve an int. Once it's reserved, no other client can reserve that int until it's released.

**Comment by WyriHaximus** [comment]
Yes, if you only start one instance of it, it will be single threaded. When you need to scale up you could Redis or Memcached as state store.

**Comment by wmerfalen** [comment]
> Yes, if you only start one instance of it, it will be single threaded. When you need to scale up you could Redis or Memcached as state store.

what a prompt response! thank you so much! :)
