### ISSUE TITLE
After connecting the server not closing the server .

### ISSUE THREAD

**Issue by mukundbharti** [ratchetphp/Ratchet#871]
implemented this library but the problem is how to kill the server not any specific method for that

**Comment by WyriHaximus** [comment]
Have a look at setting up signal handling: https://reactphp.org/event-loop/#addsignal

**Comment by mukundbharti** [comment]
still im facing same issue  , on stop and start .

**Comment by cboden** [comment]
If you're running it from the CLI hold control key and press the c key. ctrl+c

**Comment by mukundbharti** [comment]
No im running it on server by php ... im starting server perfectly but thaier is problem with stop

**Comment by cboden** [comment]
I don't understand what you're doing. Please provide clear step-by-step instructions on what you're doing so someone can reproduce the problem you're having.

**Comment by mukundbharti** [comment]
can you help me how to integrate stop and start with php method

**Comment by mukundbharti** [comment]
simply tell me how to run and close this server by php

**Comment by mukundbharti** [comment]
Hi there , 
I have used this for the WebSocket handshake please look into this how-to close and start this ratchet server using php .

Thanks

**Comment by cboden** [comment]
Run `php bin/server.php` from a terminal. 

ctrl+c to stop the process.
