### ISSUE TITLE
There is Issue with Starting and closing with php 

### ISSUE THREAD

**Issue by mukundbharti** [ratchetphp/Ratchet#872]

**Comment by WyriHaximus** [comment]
Which is? Any errors you can share?

**Comment by mukundbharti** [comment]
![Screenshot from 2021-03-26 15-11-34](https://user-images.githubusercontent.com/73641199/112612975-96462880-8e45-11eb-85c4-06b01e71b61a.png)

**Comment by mukundbharti** [comment]
this issue showing on close and start

**Comment by cboden** [comment]
Change the port you're running Ratchet on. Another server is already bound to port 8015, you can't have two services listening on the same port.

**Comment by mukundbharti** [comment]
how to close this port by php ... i know Its started i need to stop by php method

**Comment by cboden** [comment]
As @WyriHaximus [said](https://github.com/ratchetphp/Ratchet/issues/871#issuecomment-803356872) in #871 look into signal handling.
