### ISSUE TITLE
not an issue but request

### ISSUE THREAD

**Issue by softwareJ** [ratchetphp/Ratchet#876]
can you please just add regular session if you can instead of symphony? Just a thought for consideration.

**Comment by cboden** [comment]
If it were possible I would have done that instead of needing Symphony 😉

**Comment by WyriHaximus** [comment]
Note that using `$_SESSION` isn't possible due to it being a global variable and the same process is handling countless different requests at the same time. And using a global then means all those requests access the same global sessions, leaking everything everywhere to everyone.
