### ISSUE TITLE
Error on Client and Server script

### ISSUE THREAD

**Issue by alexolliveira** [ratchetphp/Ratchet#882]
Server: Fatal error: Uncaught Error: Interface 'MessageComponentInterface' not found in
Client: WebSocket connection to 'ws://127.0.0.1:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by WyriHaximus** [comment]
> Server: Fatal error: Uncaught Error: Interface 'MessageComponentInterface' not found in

Looks like autoloading isn't used. Having the following at your PHP entry point should resolve that:

```php
require 'vendor/autoload.php`;
```

> Client: WebSocket connection to 'ws://127.0.0.1:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

If your server won't start, the client can't connect to it

**Comment by alexolliveira** [comment]
Issue solved! Thanks!
