### ISSUE TITLE
Run Server

### ISSUE THREAD

**Issue by alexolliveira** [ratchetphp/Ratchet#883]
How to start the server without using CMD or access server.php directly. I would like the websocket server get started together with apache

**Comment by WyriHaximus** [comment]
Not. You need a way to run the command to start the server somehow, so either your way of hosting provides that or you need to find one that does.

**Comment by omegaalfa** [comment]
> Not. You need a way to run the command to start the server somehow, so either your way of hosting provides that or you need to find one that does.

Please one example

**Comment by WyriHaximus** [comment]
> Please one example

Well personally I used to have a VPS at DigitalOcean so I had command line access. But these days I use their Kubernetes offering to run my code in containers.
