### ISSUE TITLE
Multiple topics

### ISSUE THREAD

**Issue by alexolliveira** [ratchetphp/Ratchet#885]
How do I subscribe to two or more topics? I'm using autobahn.js in client-side

Is there client-side for php?

**Comment by WyriHaximus** [comment]
https://github.com/ratchetphp/Pawl is a PHP client and yes you can subscribe to multiple topics just like you subscribed to the first topic. That's one of the powers of websockets

**Comment by alexolliveira** [comment]
Ok man! Thanks you!  ;)

**Comment by WyriHaximus** [comment]
Also no need to open multiple websocket connections, it all goes over a single connection <3

**Comment by alexolliveira** [comment]
@WyriHaximus 🤔 How do I implement CORS using Ratchet(pusher)?🤔
