### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by alexolliveira** [ratchetphp/Ratchet#886]
🤔 How do I implement CORS using Ratchet(pusher)?🤔
Any suggestion will be welcome. ;)

**Comment by WyriHaximus** [comment]
Are you running into any issues, and if so, which?

**Comment by alexolliveira** [comment]
I wanna protect my websocket from external accesses!

**Comment by WyriHaximus** [comment]
Handle that inside the websocket connection itself, you can put the authentication there. AFAIK websockets don't even support CORS
