### ISSUE TITLE
How to close websocket with specific close code?

### ISSUE THREAD

**Issue by seb303** [ratchetphp/Ratchet#890]
I'm probably missing something obvious here, but have been trying to figure this out for hours with no joy, so would be very grateful for a pointer...

In my application I need to close a websocket with a specific code (e.g. 1011) if an error occurs.  However, I can't see how to get access to the "close" function which accepts a code parameter.

Here's the bare bones of what I'm doing:

```
use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;

$loop = React\EventLoop\Factory::create();
$MyServer= new MyServer($loop);

$webSock = new React\Socket\Server('0.0.0.0:8010', $loop);
$server = new IoServer(
	new HttpServer(
		new WsServer(
			$MyServer
		)
	),
	$webSock
);
$loop->run();
```

And:

```
use Ratchet\MessageComponentInterface;
use Ratchet\ConnectionInterface;

class MyServer implements MessageComponentInterface {
	...
	public function onError(ConnectionInterface $conn, \Exception $e) {
		// ($conn instanceof WsConnection) is FALSE
		$conn->close(1011); // Closes with code 1000
	}
}
```

**Comment by gregant** [comment]
Use `Ratchet\Http\CloseResponseTrait` that provides close method with http status code.

**Comment by cboden** [comment]
The `CloseResponseTrait` closes a connection during the HTTP handshake, before a WebSocket connection is handled. One the HTTP connection has been upgraded and the WebSocket connection established, you'll want to use a WebSocket close Frame to initiate a connection shutdown. 

@seb303 You're right with the logic you had initially in that you pass `1011` to the [close function](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsConnection.php#L30). The most likely reason you didn't see 1011 in the close is that a close was already initiated with a different code.

**Comment by seb303** [comment]
@cboden Thanks for your reply.

You are correct: now I am testing it again, I can see the socket is being closed with the code specified (regardless of using the Trait mentioned).  I can't now repeat what I was seeing before, but I think you are right that something must have closing the connection prior to the onError function being called.
