### ISSUE TITLE
Connection Failed after 4 months of working fine

### ISSUE THREAD

**Issue by david-marweblous** [ratchetphp/Ratchet#913]
I had the websocket work perfectly on my server for a live chat on my site.
Accedently changed the name of the folder the websocket was in. Realized my problem and changed it back exactly the way it was but now still can't connect to it. Nothing else has changed... websocket runs no problem just can't connect :S
Running over SSL

Linux server: 20.04.2
Plesk 18.0.35
php 8.0.7
apache/nginx
server.php:

use Ratchet\Server\IoServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use MyApp\Chat;

use React\EventLoop\Factory as LoopFactory;
use React\Socket\SecureServer;
use React\Socket\Server;

require dirname(__DIR__) . '/vendor/autoload.php';

$loop = LoopFactory::create();

$server = new IoServer(
    new HttpServer(
        new WsServer(
            new Chat()
        )
        ),
        new SecureServer(
            new Server(
                '0.0.0.0:8080', $loop
            ),
            $loop, [
                'local_cert' => '/opt/psa/var/modules/letsencrypt/etc/live/www.yourdomain.com/fullchain.pem',
                'local_pk' => '/opt/psa/var/modules/letsencrypt/etc/live/www.yourdomain.com/privkey.pem',
                'allow_self_signed' => FALSE,
                'verify_peer' => FALSE
            ]
        )
);
$loop->run();

App.php:

public function __construct($httpHost = 'yourdomain.com', $port = 8080, $address = 'SERVERS_IP', LoopInterface $loop = null) {
        if (extension_loaded('xdebug') && getenv('RATCHET_DISABLE_XDEBUG_WARN') === false) {
            trigger_error('XDebug extension detected. Remember to disable this if performance testing or going live!', E_USER_WARNING);
        }

        if (null === $loop) {
            $loop = LoopFactory::create();
        }

        $this->httpHost = $httpHost;
        $this->port = $port;

        $socket = new Reactor($address . ':' . $port, $loop);

        $this->routes  = new RouteCollection;
        $this->_server = new IoServer(new HttpServer(new Router(new UrlMatcher($this->routes, new RequestContext))), $socket, $loop);

        $policy = new FlashPolicy;
        $policy->addAllowedAccess($httpHost, 80);
        $policy->addAllowedAccess($httpHost, $port);

        if (80 == $port) {
            $flashUri = '0.0.0.0:843';
        } else {
            $flashUri = 8843;
        }
        $flashSock = new Reactor($flashUri, $loop);
        $this->flashServer = new IoServer($policy, $flashSock);
    }

apache2/sites-available/000-default.conf :

ProxyPass /chat wss://127.0.0.1:8080/
ProxyPassReverse /chat wss://127.0.0.1:8080/

Any help would be much appriciated.

**Comment by zhiyong80** [comment]
@david-marweblous if possible, could share the cause/fix? even just on a superficial level. I am planning put a system into production, would like to avoid common pitfalls. Thanks.
