### ISSUE TITLE
The onSubscribe not firing

### ISSUE THREAD

**Issue by ran23** [ratchetphp/Ratchet#92]
Hi. 

First of all, I want to say thank you for sharing this library. I have successfully installed Ratchet/Push Integration and ZMQ, and the connection is working. The problem I'm currently facing is delay firing of onSubscribe and onPublish( I just used onPublish to check if the connection really works ).  Actually the onSubscribe is not firing when the page load unless manually confirm the connection using  'conn.publish('http://fakesite.com/data', 'hi' );' on client side, using Chrome Console. After I confirmed the connection, I'm using 'conn.subscribe('http://fakesite.com/data', onEvent );, in Chrome Console, to fire server onSubscribe.  

I guess the problem is on my Windows server, but not sure. This is related to the problem I'm facing with manual coding of PHP socket.  The PHP socket_select is not firing with the single ws.send("stmt"), so I used Time Interval Loop on my JS send function. 

Any idea why it wont work perfectly with my server. 

Sorry for my poor English.

**Comment by mbonneau** [comment]
Closed due to inactivity.
