### ISSUE TITLE
Where are the implementation of functions of ConnectionInterface?

### ISSUE THREAD

**Issue by zhiyong80** [ratchetphp/Ratchet#924]
Hi,

First please forgive my ignorance. I am going through the source code and trying to understand the package better.  Two functions of ConnectionInterface are widely used.

```
    /**
     * Send data to the connection
     * @param  string $data
     * @return \Ratchet\ConnectionInterface
     */
    function send($data);

    /**
     * Close the connection
     */
    function close();
```

But I cannot find how these two functions are implemented anywhere under /cboden/ratchet. There is also the isBinary() function of MessageInterface that I am interested but cannot find implementation.

Where did I miss?

Thanks.

**Comment by zhiyong80** [comment]
Just noticed ConnectionInterface is mentioned as Magic Accessor in 0.5 roadmap. This does seem like a magic too me. But still there must be actual implementation. Can anyone point me to it? Thanks.

**Comment by cboden** [comment]
Ratchet is built in layers using the decorator pattern with [Components](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/ComponentInterface.php). Standard is IO > HTTP > WebSocket. Each layer has its own implementation of `ConnectionInterface` which, typically, on connection, decorates the previous layer's `ConnectionInterface`. 

So, when you `->send("hello")` at the WebSocket layer it transforms your message and passes it up the decorator chain eventually making it to the IO layer that sends the data over the socket.

**Comment by zhiyong80** [comment]
Thanks for the explanation. I didn't realize this was a decorator pattern.
