### ISSUE TITLE
Add support for Symfony 6

### ISSUE THREAD

**Issue by frank9999** [ratchetphp/Ratchet#925]
Hi,

Ratchet doesn't support Symfony 6 yet, which was released a week ago.

> Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - Root composer.json requires cboden/ratchet ^0.4.3 -> satisfiable by cboden/ratchet[v0.4.3].
>    - cboden/ratchet v0.4.3 requires symfony/http-foundation ^2.6|^3.0|^4.0|^5.0 -> found symfony/http-foundation[v2.6.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.34, v5.0.0, ..., v5.4.0] but these were not loaded, likely because it conflicts with another require.

**Comment by frank9999** [comment]
Added PR #926 to add Symfony 6 support. I didn't test the PR, let me know if you have feedback or need help with anything else :)

**Comment by cboden** [comment]
fixed in #926
