### ISSUE TITLE
Can't connect to stats server wss.analyticacdn.com try to disable adblock and refresh page - Help

### ISSUE THREAD

**Issue by lise12333** [ratchetphp/Ratchet#931]
It goes like this, a while ago, I installed an AdBlock because the ads got on my nerves. After some time, I searched for a movie online, 
I wanted to watch it. But look, when I turned on the movie and wanted to click play on the movie - this appearded ( can't connect to stats server wss.analyticacdn.com try to disable adblock and refresh page ), I disabled the AdBlock right away, I disabled it, but it was showing it again, I deleted and uninstalled the AdBlock, but it was showing it again.. After few tries, I even formated my laptop, got everything deleted, I installed again and it showed me again. If anybody knows a way I can get rid of this problem please.

- Can't connect to stats server wss.analyticacdn.com try to disable adblock and refresh page
- Can't connect to stats server wss.analyticacdn.com try to disable adblock and refresh page
- Can't connect to stats server wss.analyticacdn.com try to disable adblock and refresh page
- Here is a photo
- 
![image](https://user-images.githubusercontent.com/96210908/146277216-570fbafa-7e08-40fd-9aff-41c976323e32.png)

**Comment by lise12333** [comment]
PS: I did everything that I red on google etc, but it didn't help.. Help me please.

**Comment by cboden** [comment]
Sir, this is a Wendy's
