### ISSUE TITLE
Removing the X-Powered-By header

### ISSUE THREAD

**Issue by quakemmo** [ratchetphp/Ratchet#932]
Is there any way to remove or at least change the X-Powered-By: header sent by Ratchet upon handshake?

Thank you.

I'd like to at least conceal the version.

**Comment by cboden** [comment]
Yes, it's possible. I'll leave it up to you as an exercise to understand Ratchet's architecture. Hint: Ratchet heavily utilizes the decorator pattern.

**Comment by BrokenSourceCode** [comment]
> Yes, it's possible. I'll leave it up to you as an exercise to understand Ratchet's architecture. Hint: Ratchet heavily utilizes the decorator pattern.

@cboden Is it possible while using the `Ratchet\App` class?

**Comment by cboden** [comment]
Yes

**Comment by BrokenSourceCode** [comment]
@cboden I tried to access the response generated by `Ratchet\WebSocket\WsServer` but i can't. The handshake negotiator is implicitly called inside the class and i can't modify the response that is directly sent. Any tips please?

https://github.com/ratchetphp/Ratchet/blob/5012dc954541b40c5599d286fd40653f5716a38f/src/Ratchet/WebSocket/WsServer.php#L117-L119

@quakemmo Were you able to solve this problem? If so, in what way? I've spent several hours on this but I can't figure out how I can use the decorators for this case.

**Comment by quakemmo** [comment]
It is a security issue and you have several options:

1. Spend inordinate amounts of your time to dig through the mountains of Ratchet's code to find a way to fix it, without knowing whether or not that fix will work in future versions of Ratchet. Good if your time and mental energy isn't very valuable to yourself.

2. Use a WAF to strip it. Probably the best option.

3. Ditch Ratchet and use something different - probably a decent option as well. Getting the condescending "leave that as an exercise" reply to a security concern probably means at least one thing - Ratchet is not future-proof and committing your project to it may mean technical debt. There are other solutions, even in PHP (check out Swoole).

**Comment by BrokenSourceCode** [comment]
> It is a security issue and you have several options:
> 
> 1. Spend inordinate amounts of your time to dig through the mountains of Ratchet's code to find a way to fix it, without knowing whether or not that fix will work in future versions of Ratchet. Good if your time and mental energy isn't very valuable to yourself, and you don't mind having another burden - making sure your hack works every time you "composer update".
> 2. Use a WAF to strip it. Probably the best option.
> 3. Ditch Ratchet and use something different - probably a decent option as well. Getting the condescending "leave that as an exercise" reply to a security concern in server software probably means at least one thing - Ratchet is not future-proof and committing your project to it may mean technical debt. There are other solutions, even in PHP (check out Swoole).

@quakemmo Thanks for your honest answer. I agree with you, **this is a real security issue**. That's why I've reopened an issue with the same subject...

It's true that I don't really understand the answer of the repository author, since apparently (unless I'm wrong) we are unable to use decorators to solve this issue. 

I'll think about your suggestion and see if it's not too complex to migrate my actual Ratchet code to a similar library like Swoole. I need high performance (at least like Ratchet) and a good security for my app. I'll try to see if Swoole can fit my needs!
