### ISSUE TITLE
How to send a binary message to ratchet WebSocket server?

### ISSUE THREAD

**Issue by zhiyong80** [ratchetphp/Ratchet#933]
Hi,

I am trying to build a gateway server for my IoT devices. I noticed from[ this page](http://socketo.me/docs/migration-3) that Ratchet V0.4+ supports receiving binary messages from client. I suppose I can call member function isBinary() like the following.
```
    public function onMessage(ConnectionInterface $from, MessageInterface  $msg) {
        if($msg->isBinary()) {
            echo "received binary message\r\n";
        } else {
            echo "received non-binary message\r\n";
        }
    }
```
My question is, how does a client let Ratchet server know that messages being sent are binary? We are writing our own embedded websocket client.

Please advise, and thanks.

**Comment by cboden** [comment]
See the [WebSocket.send](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send) function. The send methods accepts a number of different objects. The underlying connection will signal if it's binary.

**Comment by zhiyong80** [comment]
@cboden Thanks for such quick response. I guess we will need to go through the code of some open source websocket client.
