### ISSUE TITLE
Fibers

### ISSUE THREAD

**Issue by ziaratban** [ratchetphp/Ratchet#940]
Do you have a schedule for using [fibers](https://www.php.net/releases/8.1/en.php#fibers)?

#850

**Comment by clue** [comment]
@ziaratban Excellent question!

Fibers are in fact supported in ReactPHP by using the new async package: https://github.com/reactphp/async. Because Ratchet builds on top of ReactPHP, this means it also supports fibers just fine 🚀

I hope this helps :+1:
