### ISSUE TITLE
Deployment: ev vs. event, what happens when both are installed?

### ISSUE THREAD

**Issue by zhiyong80** [ratchetphp/Ratchet#941]
In [this page](http://socketo.me/docs/deploy), Mr. Boden states that 

> No further setup is necessary; if either of these extensions is present, the evented I/O loop toolkit used by Ratchet will automatically utilize them, which will drastically improve concurrency.

My questions are:
1) What happens when both ev and event extension are installed? Does Ratchet randomly pick one or it has a preferred extension?
2) How do I know that either ev or event is being used by Ratchet? There are a few Gist on how to install ev/event, usually both. They seem right, but it will be great if there is a way to make sure the extension is successfully installed.

Thanks.

**Comment by WyriHaximus** [comment]
If that happens ev will be used: https://github.com/reactphp/event-loop/blob/master/src/Factory.php#L50-L72

**Comment by zhiyong80** [comment]
@WyriHaximus thanks for the pointer. I guess I can stick an echo line in that function to check if either ev or event extension is used as well.
