### ISSUE TITLE
Websocket dies after 2 days

### ISSUE THREAD

**Issue by david-marweblous** [ratchetphp/Ratchet#951]
Hi everyone,

Ive had the websocket running for last 7 months with little problems.
I have just changed servers and passed everything over to the new server and for some reason my websocket dies after two days.
Have tried to find an error log or something to give me a reason why this is happening but i have not found anything.

Is there any where that logs the exeception/errors? Or a possible reason to why this is happening?

Thanks in advance.

**Comment by Fyod** [comment]
If it was a major php fault, you should have something in the site's error log. I would also check uptimes of the server and apache to see if they crashed.
Error/exceptions to connections and messaging is not automatically logged, afaik.
