### ISSUE TITLE
onMessage on HttpServer is called, but onOpen is not

### ISSUE THREAD

**Issue by szado** [ratchetphp/Ratchet#959]
I am using `HttpServer` to receive requests. I have a problem: it looks like `onMessage` on my` HttpServerInterface` is being called with the request payload, but before that the `onOpen` method is not called. 
Does anyone have an idea why? Can it be something related to http2/multiplexing requests or just malformed request?

**Comment by cboden** [comment]
Looking at the [logic in HttpServer.onMessage](https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/Http/HttpServer.php#L39) I don't see how this would be possible. 

Please provide a reproducible example so others can test.

**Comment by szado** [comment]
It was problem with my implementation.
