### ISSUE TITLE
Help needed with connections per second

### ISSUE THREAD

**Issue by BBrey** [ratchetphp/Ratchet#965]
I think we are doing something wrong. Currently we have a running ratchetphp websocket over SSL and it can only handle around 15 connections per second and starts to have (more) problems when reaching 9000 concurrent users

The code works like this:

- on construct we enable logging (syslog) and create an SplObjectStorage to store the users
- onconnect we 
  - validate the token via an **external** api (using a guzzle client)
  - add the result to a SplObjectStorage object

Should we move the validation somewhere else? Since it is an api call won't be superfast.
Messages are sent pretty quickly even on times we have a lot of load the cpu/memory isn't the problem.

**Comment by WyriHaximus** [comment]
Try replacing Guzzle with https://reactphp.org/http/#client-usage as I'm somewhat assuming you are using Guzzle with their build in async implementation.

**Comment by WyriHaximus** [comment]
Looks like you're using Guzzle in blocking mode, and as such it will block the event loop for the duration of that `GET` call

**Comment by BBrey** [comment]
> Looks like you're using Guzzle in blocking mode, and as such it will block the event loop for the duration of that `GET` call

Ok and that will block other users from connecting to our websocket?

**Comment by WyriHaximus** [comment]
Yes, that will block everything going on inside the event loop and that includes everyone connecting with the websocket.

**Comment by BBrey** [comment]
Thank you for the info, we now use JWT tokens to authenticate so the API call can be removed. We think that is the best solution.

**Comment by WyriHaximus** [comment]
Once you've removed the call. Can you let us know if it met the expected outcome?

**Comment by BBrey** [comment]
The first results look promising, at peak hours users can connect without any problems now. We need to keep an eye on this the next week when the peak is a bit higher.

**Comment by BBrey** [comment]
Unfortunately the first school day we still have problems at peak times. The next problem we face is that the PHP process reaches 100% CPU at peak times.

**Comment by BBrey** [comment]
> Hah great! If possible, launch a replica. Or try to offload work from that process into others.

I think that would be best indeed but we don't have a way to do that yet in the frontend though.

**Comment by WyriHaximus** [comment]
Yes, or you have to move those channels to something like redis or postgresql.
