### ISSUE TITLE
Would this be suitable for operational transformation?

### ISSUE THREAD

**Issue by bjorno43** [ratchetphp/Ratchet#982]
**Explanation**
Operational transformation is used for collaborative editing of a document. The idea is that multiple clients can simultaneously edit a single document (textfield for example), where the intentions of each client remain intact as much as possible.

**Visualization example**
[http://operational-transformation.github.io/index.html](http://operational-transformation.github.io/index.html)

**Question**
Would Ratchet be suitable for this? In order to make something like this functional, each client must run fully asynchronous / non-blocking. NodeJS would probably be more suitable for that and it's probably the reason why no one ever seems to have bothered trying to make it in PHP. I've attempted to do it with Ratchet once before, but it was too slow imho. However, I believe this was due to me not properly developing it and not because of Ratchet. Hence I'd like your input on this before I make another attempt at it.

**Comment by clue** [comment]
@bjorno43 Good question, operational transformation is certainly interesting!

I haven't personally benchmarked Ratchet (input welcome!), but it builds on top of ReactPHP to employ blocking I/O. ReactPHP can easily handle tens or hundreds of thousands operations per second(!), so I have no reason to believe Ratchet wouldn't be suited to build this.

It's my understanding you would want to implement server side with Ratchet and the clients would most likely run in your browser environment? You might as well implement the client side in PHP with Ratchet/Pawl, but I would be curious to learn more about your use case.

Also, make sure to share your results if this is something you're working on, I'm sure this is something more people would be interested in (me included)! I hope this helps!

**Comment by bjorno43** [comment]
> 

My use case would be the ability to create projects online and have people collaborate on it. Someone could create a new project and invite collaborators to work on it. Projects can easily be managed through a unique ID so they'll remain private from other eyes. Once in a project, the manager(s) can create new files / directories in a filetree somewhere on the side. Those in turn can be opened to initiate some editor like CodeMirror or AceEditor who will load the correct syntax highlighting based on the file extension. Tabs can be used like any other IDE to keep track of multiple files at once. Projects can obviously be downloaded or uploaded just as well at any given time.

As for the client side, that can just be pure html / css / js. I mean, PHP could work if creating accounts is desired with it, but whatever you wish to use in the front end doesn't really matter as long as it can communicate with the back end. My idea was to use ot.js ([https://github.com/Operational-Transformation/ot.js/](https://github.com/Operational-Transformation/ot.js/)). It's made for Node, but it should be possible to adept it to use Ratchet instead.

Of course I'll release my work in a repo on my account when I get to that point. I'm strong believer of Open Source and what can achieved with contributors. Thanks for the info you've given me so far. I was just a bit worried because if you think about it, some people can easily reach 300 keystrokes per minute. If you have 100 or even just 10 people typing at that speed, you can imagine how many operations will be going through the websocket per second.

**Comment by clue** [comment]
300 keystrokes per minute per user * 100 users => 30000 keystroke events per minute = 500 keystroke events per second

(In any real world scenario you would most likely batch adjacent keystrokes to a single event to reduce overhead and the number of network roundtrips)

Last time I checked, ReactPHP could handle ~50k HTTP requests per second on my laptop on a single CPU core, so even if we're using a different transport protocol, I don't expect this to be a bottleneck any time soon.

Looking forward to checking out your project 👍
