### ISSUE TITLE
ratchet 0.2.6 encryption problem?

### ISSUE THREAD

**Issue by zedel** [ratchetphp/Ratchet#99]
After updating from Ratchet 0.2.5 to 0.2.6 (with composer update) my Symfony2.2/Websocket program isn't working any more. I'm using autobahn.js on clientside.
My websocket server starts fine, and I'm seeing a connect request on the server side, but in the next moment the client disconnects:
uncaught exception: server does not speak WAMP (but '' !)
Autobahn could not connect to ws://192.168.1.104:8080 (code 1000, reason 'server does not speak WAMP', wasClean true).

sniffing the network traffic it looks like some kind of encryption problem?

GET / HTTP/1.1
Host: 192.168.1.104:8080
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:21.0) Gecko/20100101 Firefox/21.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: de-de,de;q=0.8,en-us;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Sec-WebSocket-Version: 13
Origin: http://192.168.1.104
Sec-WebSocket-Protocol: wamp
Sec-WebSocket-Key: pxDU+2dsBNEWUqaU8lmv2w==
Cookie: PHPSESSID=cmkrvl9jf35g9fojcg194qijn1
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: PTSAf6r2IbpkxzjquCnuoLq0jy4=
X-Powered-By: Ratchet/0.2.6

.&[0,"51af00e2affe8",1,"Ratchet\/0.2.6"]
..?...<..vM..a...vL..|K..cZ..3h..C
..?...<..vM..a...vL..|K..cZ..3h..C

**Comment by yehudahkay** [comment]
Does this problem still exist? I had this problem trying to use autobahn but I seem to be able to connect without autobahn
