### ISSUE TITLE
socketo.me is down :( 

### ISSUE THREAD

**Issue by dakman** [ratchetphp/Ratchet#994]
![image](https://user-images.githubusercontent.com/2136346/212618933-389ec23b-53b2-402c-b446-275b7461fa54.png)

**Comment by cboden** [comment]
Indeed...I switched the hosting to GCP recently; that seems to have been a mistake. I restarted the compute instance but it's failing to bring up the containers properly. I'll take another look after work this evening.

**Comment by cboden** [comment]
It's back up now. Thanks for the heads up!
