### ISSUE TITLE
new link for documentation

### ISSUE THREAD

**Issue by GJVothel** [ratchetphp/Ratchet#995]
in the documentation example 'hello world' you linked to the SplObjectStorage class but the link is not working anymore. Here is the new link: https://www.php.net/manual/en/class.splobjectstorage.php if you want to update it :)

Edit: Incorporated clues comment

**Comment by clue** [comment]
PRs welcome! :+1: 

(nit: should probably link to English documentation here: https://www.php.net/manual/en/class.splobjectstorage.php)

**Comment by GJVothel** [comment]
Someone already did a request, nearly 2 years ago ;)
https://github.com/ratchetphp/socketo.me/pull/44
